pimcore/static/js/pimcore/document/tags/textarea.js

When pasting HTML code with double quotes they are encoded to ```&quot;```. This doesn't happen with single quotes. This pull request leaves quotes as they are after pasting.

Don't html encode double quotes on paste

---

pimcore/models/Object/ClassDefinition/CustomLayout/Resource.php

Set classId during INSERT to avoid cluttering the database with
classId=0, as the next UPDATE may fail for some reason (like race
condition)

Prevent integrity violation in CustomLayout create()

---

pimcore/models/Webservice/Service.php

Reports missing ID instead of pointless error:
PHP Fatal error:  Call to a member function setUserModification() on a non-object

Improve error handling in API update methods

---

pimcore/models/Asset/Resource.php
pimcore/models/Object/AbstractObject/Resource.php

Rights for folders for Objects and Assets granted in a role's workspace are now additive if a user has more than one role.

Rights in roles for workspaces are additive now

---

pimcore/models/Object/ClassDefinition.php
pimcore/models/Object/ClassDefinition/Data.php

- @method tag in Listings for the Iterator Interface. This enables type hinting e.g. for foreach
- @method tag in Class for methods provided by the resource. This enables type hinting for getByXXXX() methods

Added PHPDoc to improve type hinting in user defined Objects.

---

pimcore/lib/Logger.php

Added public static method getPriorities() in Pimcore\Logger. This can be used if you want to create a seperate logger but don't want to extent on the Pimcore logger.
The logger has the priorities already mapped from the system config to Zend_Log constants.

Added getPriorities() on Pimcore\Logger

---

pimcore/models/Tool/Targeting/Rule/Actions.php

Global targeting rules couldn't save because of this.
Error:
```
Warning: include_once(Pimcore/Model/Tool/Targeting/Rule/Document.php): failed to open stream: No such file or directory in
```

Targeting FIX - targets didn't save

---

pimcore/lib/Pimcore/Model/Cache.php

Added a static function test() on Pimcore\Model\Cache as a wrapper function around Zend_Cache_Core::test().
Returns the last modified time of a cache entry. We use this so our cache warmer would see when a cache is about to expire and needs refreshing.

Model\Cache::test() added that returns the last modified time of a cache entry

---

pimcore/static/css/editmode.css
pimcore/static/js/pimcore/document/tags/input.js

Usage: $this->input('field', ['placeholder' => 'placeholder text']);
Before I forget, is /static5/.../input.js in use?

PIMCORE 2688 - Placeholder option for input editable

---

pimcore/config/texts/en.csv
pimcore/lib/Pimcore/Tool.php
pimcore/modules/admin/controllers/SettingsController.php
pimcore/static/js/pimcore/settings/system.js

Reordering is still not possible but each language-container has a "mark as default" option

PIMCORE-2466 Change order of the system language

---

pimcore/lib/Pimcore/Update.php

https://www.pimcore.org/board/viewtopic.php?f=19&t=2220
Prevent warnings from unlink function when for some reason file/dir is
already deleted.

Improve stability of the updater

---

pimcore/cli/reset-password.php

In case you're interested. This might be useful to other users and to e.g. automate installation under certain use-cases. 
Usage:
```bash
php pimcore/cli/reset-password.php id/username
```
The utility will prompt for the new password and update the record in the database automatically.

Added CLI utility to reset password

---

pimcore/modules/admin/views/scripts/login/index.php

Opera >= 15 uses WebKit (Blink). Tested on Opera and the Pimcore admin works like a charm

Add Opera support for admin

---

pimcore/models/WebsiteSetting/Resource.php

Not all variables were set when calling WebsiteSetting\Resource::getByName()

Bugfix: Assign all variables to the model when getting a WebsiteSetting by name

---

pimcore/models/Asset.php
pimcore/models/Object/AbstractObject/Resource.php

Fixed a bug that prevented creating Objects, Assets and Folders with a name consisting of the single character "0"

Bugfix: creating Objects, Assets and Folders with "0" as name

---

pimcore/modules/admin/controllers/MiscController.php
pimcore/static/js/pimcore/document/pages/settings.js
pimcore/static/js/pimcore/settings/staticroutes.js

Submodules, if present, can now be selected in document settings and static routes with a selectbox instead of entering the name by hand, additionally the controller select boxes are updated accordingly.

Improvement: Make submodules selectable in document settings and static routes

---

pimcore/lib/Pimcore/Image/Adapter/Imagick.php

Force the locale to use with ImagickDraw to "en" to ensure the corret formatting of floats.
Just using "" won't fix this, see http://php.net/manual/en/function.setlocale.php
"If locale is NULL or the empty string "", the locale names will be set from the values of environment variables with the same names as the above categories, or from "LANG"."
If your system is set to "de" this thus will still result in komma decimal seperator.

Bugfix: ImagickDraw error "non-conforming drawing primitive definition `,'"

---

pimcore/models/Webservice/Service.php

REST Service use class mapping only in update mode with Object::getById() method.
Now, with this fix, also in add mode.

REST Service: use class mapping in object creation

---

pimcore/models/Object/ClassDefinition/Data/StructuredTable.php
pimcore/static/js/pimcore/object/classes/data/structuredTable.js

Added a field "length" for columns in StructuredTables to override the length of 255 for VARCHARS for text fields

Improvement: added length field for columns in StructuredTables

---

pimcore/lib/Pimcore/Tool/Mime.php

for autocad dxf files the mimetype from fileinfo gets text/plain and this makes it unable to open that asset in backend.

added autocad file mime

---

pimcore/static6/js/lib/ext-plugins/portlet/Portlet.js

This is very minor. The padding here is producing a gap inside each portlet. Is there a reason why its set as 8 8 0 0? Removing it appears to remove the gap.
Sorry for the aweful branch name :-( I'm never editing directly in github again!
Thanks,

Removed padding from portlet base class

---

pimcore/static6/js/pimcore/object/importer.js

I've fixed combobox using displayfield as value in mapping fieldname(type_ was being sent instead of the fieldname.
Also improved the layout of mapping grid & prevented displayfields from being submitted in every request in the import process.

bugfix: importer mapping + minor improvements

---

pimcore/modules/admin/controllers/ObjectController.php

Related to: https://github.com/pimcore/pimcore/issues/286
For competeness, I saw that  
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/object/object.js#L38
checks for options but doesn't check for null. I have left this line unedited for future 'option' considerations.

setting layoutid to null if it is specified as an empty parameter

---

pimcore/lib/Pimcore/View/Helper/PimcoreNavigation.php

When searching page by ```uri```, site request should be taken into account.
Page uri is set as ```fullPath``` [here](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/View/Helper/PimcoreNavigation.php#L297) and [here](https://github.com/pimcore/pimcore/blob/master/pimcore/models/Document/Link.php#L130).

Fix active page for site request in navigation helper.

---

pimcore/static6/js/pimcore/object/preview.js

One line that fixes Object preview functionality in Pimcore 4

Fixing object preview for ExtJS 6

---

build/travis/php.ini

php.ini comments starting with ``#`` are deprecated since PHP 5.3 (https://secure.php.net/manual/en/migration53.deprecated.php)
This patch prevents deprecation warnings like
```
PHP Deprecated:  Comments starting with '#' are deprecated in /home/travis/.phpenv/versions/5.5.21/etc/conf.d/php.ini on line 2 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /home/travis/.phpenv/versions/5.5.21/etc/conf.d/php.ini on line 3 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /home/travis/.phpenv/versions/5.5.21/etc/conf.d/php.ini on line 4 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /home/travis/.phpenv/versions/5.5.21/etc/conf.d/php.ini on line 5 in Unknown on line 0
PHP Deprecated:  Comments …
```

replace deprecated php.ini # comments

---

pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php

Locks should be released as soon as possible - in this case, when somehow libreoffice failed to convert file, the lock wasn't released at all - exception was thrown without releasing lock. It caused next php processes to hang. In worst case scenario - it can deplete server's php processes pool.

Fixing problem with hanging soffice locks

---

.gitignore

NetBeans creates a ``nbproject`` directory in the project's root directory. For not having to exclude that in every commit, I added a .gitignore entry for that folder.

ignore NetBean's 'nbproject' directory

---

pimcore/lib/Csv/Reader/String.php

PHP 7 writes this warning when trying to import objects using CSV Import:
`Declaration of Csv_Reader_String::initStream($string) should be compatible with Csv_Reader::initStream() in [...]\pimcore\lib\Csv\Reader\String.php on line 13`
This ist just a warning by PHP 7; however, pimcore just closes the import window.
The solution to this is actually quite simple, see my proposed changes.

Make CSV Import compatible with PHP 7

---

pimcore/static6/css/editmode.css
pimcore/static6/js/pimcore/document/tags/input.js
pimcore/static6/js/pimcore/document/tags/textarea.js
pimcore/static6/js/pimcore/document/tags/wysiwyg.js

Re-introduce the placeholder functionality for input, textarea and wysiwyg editables, as it used to exist in ExtJS 3,4.

placeholder-extjs6

---

pimcore/models/Document/Tag/Area.php

This may be potencially problematic fix as it may change block ID's. However without this fix everytime we enable or disable brick it changes other blocks ID's and page content disapear. Problem is in order when condition test for enabled brick was made after "pimcore_tag_block_current" in Zend registry has been modified and if brick doesn't exist or is disabled it finishes without removing changes already made to "pimcore_tag_block_current" I have just moved the test if brick is enabled to happen before any changes to "pimcore_tag_block_current" is made.

Fixes bug when block names are modified by non-existing or disabled brick

---

pimcore/lib/Pimcore/Composer.php

otherwise the rename function in postCreateProject will throw an error.

check if plugin or website dir already exists. 

---

pimcore/static6/css/ext-modifications.css
pimcore/static6/js/pimcore/startup.js

I've added collapseMode to the west/east region panels as this was causing a rendering issue as can be seen here in Chrome

Viewport tree expand/collapse fix

---

pimcore/static6/js/pimcore/object/folder/search.js

Both the search grid and outer panel had scroll enabled, which led to a double scroll. I have removed autoScroll from the outer panel.

Fixed double scroll on object search grid

---

pimcore/models/Object/KeyValue/KeyConfig.php

once set, then unset, this function would return `"0"`, which is true as it's a string

cast mandatory to bool in KeyConfig

---

pimcore/static6/js/pimcore/object/objectbricks/field.js

when adding a class definition in object bricks ext will throw an error: `this.classDefinitionsItems.get is not a function`

Class definition js fix

---

pimcore/models/Asset.php

map potx, ppsx, pptx, xlsx, xltx, docx, dotx mime types as asset/document, not asset/text

---

pimcore/models/Document/Tag/Multihref.php
pimcore/models/Object/ClassDefinition/Data/Multihref.php
pimcore/static6/js/pimcore/document/tags/multihref.js
pimcore/static6/js/pimcore/object/tags/multihref.js

Example: When adding a document with ID 5 and then an object with ID 5, the object replaces the document in multihref field.
The "id" is used as an unique identifier in Ext.js store, thus the elements get overwritten when having the same id. This pull request changes the field name to "elementId" which resolves the problem.

Multihref fix: multiple elements of different type with the same ID couldn't be added to the multihref field

---

pimcore/static6/css/ext-modifications.css

I like the new design and icons. But this one thing has bothered me from the beginning. The tabs are very hard to discern. It is difficult to see which tab is active and on some monitors this is actually completely impossible - all tabs seem to be the same shade of grey.
To some people it also wasn't immediately obvious that tabs are actually tabs, they thought those were just buttons on the top. Hopefully the small inset shadow on the bottom of inactive tabs should improve that. 
It is just a suggestion, but IMO it improves the UX of new UI.

STYLING SUGGESTION: styling of tabs to improve contrast of UI

---

pimcore/models/Object/ClassDefinition/Data/Password.php
pimcore/modules/admin/controllers/SettingsController.php

Enhances password field with support for [`password_hash`](http://php.net/manual/de/function.password-hash.php). Salt and salt location params will be ignored when in `password_hash` mode (maybe there's a way to disable/hide them when `password_hash` is selected?) and `password_hash` will be called with PHP's defaults for algorithm, parameters (e.g. cost) and salt handling.
In addition, a verify method on the password definition takes care of validating a password: 
```php
<?php
/* @var Pimcore\Model\Object\ClassDefinition\Data\Password $passwordField */
$passwordField = $customer->getClass()->getFieldDefinition('password');
// verify password against value stored in object, optionally take care of updating the hash if it is outdated
$result = $passwordField->verifyPassword($password, …
```

Password field password_hash

---

pimcore/modules/admin/controllers/ObjectController.php

The icon for variants was not displayed in object tree. This pull request breaks the icon for the Ext.js 3.4 (a placeholder icon is still displayed). But I guess the focus is on ExtJs 6, right?

FIX: Icon for variants not displayed in the object tree

---

pimcore/static6/js/pimcore/document/tags/renderlet.js

Added restrictions for renderlet.
Need to add 2 new lines into "Configuration" table: https://www.pimcore.org/wiki/display/PIMCORE4/Renderlet 
| Name | Type | Description | Mandatory |
| --- | --- | --- | --- |
| type | string | The type of the element assigned to the renderlet (document, asset ,object) |  |
| className | string | Specify class name (if type "object" chosen) |  |

Restrictions for renderlet

---

pimcore/static6/js/pimcore/asset/tree.js
pimcore/static6/js/pimcore/object/tree.js

Corrects the reference to the asset and object id in the tree so that the user cannot edit the filename of the home folders

bugfix, prevent rename of home folders

---

pimcore/modules/install/controllers/IndexController.php

Corrects a typo and case in installer error messages.

installer: fixed typo and case spelling

---

pimcore/static6/css/icons.css

This PR makes Pimcore display text.svg as icon for RTF-files in the asset tree view instead of none.

ExtJS 6 icons: using text icon for rtf files

---

pimcore/static6/js/pimcore/settings/httpErrorLog.js

Fixes HttpErrorLog in the pimcore admin panel for static 6, maintains legacy static compatibility.

Fixed grid display of HTTP Errors

---

pimcore/lib/Pimcore/Controller/Action/Frontend.php

This PR adds the httpResponseCode into the cacheKey of an error document. I noticed that the error document is cached and therefore if you were to have a site which used an error document to return both 404 and server 500 errors it would not be possible to customise the response per error code.
Example of a document that could now be created (assuming you set the $code in the controller action)
```
<?php if ($this->editmode || $this->code == 404) : ?>
<h1><?= $this->input('error_code_404_h1', [ 'placeholder' => 'Not Found' ]); ?></h1>
<p><?= $this->wysiwyg('error_code_404'); ?></p>
<p><?= $this->getSuggestedContent(); ?></p>
<?php endif; ?>
<?php if ($this->editmode || $this->code >= 500) : ?>
<h1><?= …
```

Added HTTPResponseCode to error document cachekey

---

pimcore/static6/js/pimcore/element/selector/abstract.js
pimcore/static6/js/pimcore/element/selector/object.js

Fixes two problems:
- initially only 20 elements are loaded although 50 is preselected in combo box
- changing the value in "Elemente pro Seite" combo box doesn't work as expected - only 20 elements were loaded always

Bugfix for itemselector - elements per page

---

pimcore/static6/css/icons.css

Missing icon for SQL query button in object grid view. Not sure if I chose the best icon, but it's better than empty button :)

Missing icon for SQL query button

---

pimcore/lib/Pimcore/Image/Optimizer.php

For me, jpegoptim set the file mode of optimized images to 0600 which made them unreadable for our webserver process. I've added chmods in the same way it is done for "regular" thumbnails to prevent this from happening. Though i have not tested the other optimizers i suspect the same problem might occur, so i added chmods for them as wenn, just in case.

Explicitly set file mode for optimized images

---

pimcore/lib/Pimcore/Console/Command/Definition/Import/AbstractStructureImportCommand.php
pimcore/lib/Pimcore/Console/Command/Definition/Import/ClassCommand.php
pimcore/lib/Pimcore/Console/Command/Definition/Import/FieldCollectionCommand.php
pimcore/lib/Pimcore/Console/Command/Definition/Import/ObjectBrickCommand.php
pimcore/lib/Pimcore/Console/Traits/DryRun.php

Adds CLI commands to import JSON export files for classes, objectbricks and fieldcollections
```
$ php pimcore/cli/console.php definition:import:class class_Customer_export.json
$ php pimcore/cli/console.php definition:import:objectbrick objectbrick_FooBar_export.json
$ php pimcore/cli/console.php definition:import:fieldcollection fieldcollection_Bazinga_export.json
```

CLI commands for definition imports

---

pimcore/static6/js/pimcore/helpers.js

A simple fix for the bug which allows to save a document with Alt+S key combination (occurs only on Windows for some reason). In the Polish keyboard layout "Alt+s" is used to type "ś" character so the bug makes entering text by my fellows a little problematic.

Ignore alt+s combination for saving

---

pimcore/static6/js/pimcore/document/pages/settings.js

I found that it's not possible to use controllers from plugin's `controllers` dir in the document's settings. Controller for listing all possible values is already there `/admin/misc/get-available-modules` so I just have created JS code that uses it.

Add module's selector in document's setting tab.

---

pimcore/config/texts/en.json
pimcore/models/Object/ClassDefinition/Layout/Fieldcontainer.php
pimcore/models/Object/ClassDefinition/Layout/Splitter.php
pimcore/modules/admin/views/scripts/index/index6.php
pimcore/static6/css/icons.css
pimcore/static6/js/pimcore/object/classes/class.js
pimcore/static6/js/pimcore/object/classes/layout/fieldcontainer.js
pimcore/static6/js/pimcore/object/classes/layout/splitter.js
pimcore/static6/js/pimcore/object/helpers/customLayoutEditor.js
pimcore/static6/js/pimcore/object/helpers/edit.js

Our goal was to build better looking, more complex forms to increase the editors user experience.
Basic implementation of ExtJS FieldContainer (http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.form.FieldContainer) and Splitter (http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.resizer.Splitter) as Pimcore ClassDefinition layout elements.
We've tested the implementation against import, export and the rest api.
- hbox/vbox layout for fieldcontainer
- custom fieldcontainer label (to allow single labled form rows/fieldcontainers – see examples address row)
- splitter to add additional spacing between form field and the ability to allow user resizable inputs
Dummy ClassDefinition Export:
https://gist.github.com/joramhoefs/cb68f8f480635d87e787
ClassDefinition:
Object usage:

Add ExtJs "fieldcontainer" and "splitter" to pimcore ClassDefinition

---

pimcore/static6/js/pimcore/object/tags/calculatedValue.js

Hi, the Calculated value icon is too big on objects. This should fix it.
Current style:
New style:

Calculated Value object field icon style

---

pimcore/models/Document/Tag/Video.php

- add video to a target (in a snippet for example)
- delete video from assets.
- try to add a vide in snippet again: the target video is gone.
this pr should fix this.

fix missing video target when deleting video link

---

pimcore/static6/js/pimcore/layout/portal.js

Hi, dashboard layout serialization fails on portlet reordering because of missing dashboard key in the request. This should fix it.

Dashboard portlets reordering

---

.gitignore
pimcore/models/Object/ClassDefinition/Data/Nonownerobjects.php

In the documentation of the Nonowner objects is a example code:
`
$def = $object->getClass()->getFieldDefinition("myNonOwnerObjectField");
$refKey = $def->getOwnerFieldName();
$refId = $def->getOwnerClassId();
$nonOwnerRelations = $object->getRelationData($refKey,false,$refId);`
[https://www.pimcore.org/wiki/display/PIMCORE3/Non-Owner+Objects](url)
But $def->getOwnerClassId(); dosn't exists. 
Fixes # 
Added getOwnerClassId function to Nonownerobjects.php

Added getOwnerClassId function to Nonownerobjects.php

---

pimcore/static6/js/pimcore/object/tags/checkbox.js

FIX - checked checkbox was always dirty - calling setValue made it dirty. The value is now set in the checkbox's constructor instead

FIX - checked checkbox was always dirty

---

pimcore/models/Object/Fieldcollection/Definition/Dao.php
pimcore/models/Object/Objectbrick/Definition/Dao.php

Import all classes via bulk import
Bulk import throws and exception with MySQL version 5.7
```
2016-04-06T15:48:41+02:00 EMERG (0):   7 MB | () [23]: [Exception] with message: Mysqli statement execute error : All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
In file: /var/www/pimcore/lib/Zend/Db/Statement/Mysqli.php on line 214
#0 /var/www/pimcore/lib/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/pimcore/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...')
#3 /var/www/pimcore/lib/Pimcore/Resource/Wrapper.php(263): call_user_func_array(Array, Array)
#4 /var/www/pimcore/lib/Pimcore/Resource/Wrapper.php(233): …
```

models MySQL 5.7 fixes

---

pimcore/static/js/frontend/pdfViewer/viewer.js
pimcore/static6/js/frontend/pdfViewer/viewer.js

This PR fixes problem with removing pdfFullscreen class on Internet Explorer, which makes PDF Viewer unusable in fullscreen:
I've changed wrong names of Fullscreen API functions to correct ones

Resolved Fullscreen problem on Internet Explorer

---

pimcore/models/Search/Backend/Data.php

The Pimcore\Document\Adapter throws an Exception in getPdf() if something's wrong, which is caught e.g. in Pimcore\Models\Asset\Document::readPageCount(), but not in this class.
If you, for example, in a plugin create a xls and store it in an asset, the error creating the thumbnail is correctly caught, but the exception that then is thrown when generating the search data is uncaught.
For your convenience here's the stacktrace:
[stacktrace.txt](https://github.com/pimcore/pimcore/files/214688/stacktrace.txt)

Added a try/catch to catch exceptions from document adapters

---

pimcore/static6/js/pimcore/document/tags/areablock.js

Sometimes the position of the toolbar can be very annoying. 
especially when the toolbar has been repositioned and after a reload the position is the initial again. this PR will take care about that.
**what it does**
- Check if toolbar position exists in localstorage. If so, use that information.
- If the window size has been changed so that the toolbar would be out of view, update the toolbar position.
- Also checks and stores the toggle state.

save toolbar position in localstorage

---

pimcore/static6/js/pimcore/object/versions.js

With the exctjs6 config enabled, clicking on an object version throw an JS error and does not open the preview
```js
ReferenceError: event is not defined
this.showVersionPreview(grid, rowIndex, event)
```
pimcore/static6/js/pimcore/object/versions.js
```js
onRowClick: function(grid, record, tr, rowIndex, e, eOpts ) {
var selModel = grid.getSelectionModel();
if (selModel.getCount() > 2) {
selModel.select(record);
}
if (selModel.getCount() > 1) {
this.compareVersions(grid, rowIndex, event);
}
else {
this.showVersionPreview(grid, rowIndex, event);
}
},
```
either change function variable name
```js
onRowClick: function(grid, record, tr, rowIndex, e, eOpts ) {
```
in pimcore/static6/js/pimcore/asset/versions.js
and pimcore/static6/js/pimcore/object/versions.js
or change variable name like in …

fix preview of object versions

---

pimcore/static6/js/pimcore/helpers.js

The same bug like here: https://github.com/pimcore/pimcore/pull/511
This is a fix for capital Polish special characters (Ś and Ó) because I forgot about them last time :)

Fix for text input with alt + shift

---

pimcore/static6/js/pimcore/object/tree.js

Hi,
I found a small bug in the object publish/unpublish function when called from a customview. See animation for details:
This PR should fix it. I also checked the documents customview and it seems fine.
Regards,
Martin

customviews tree publish/unpublish fix

---

pimcore/lib/Pimcore/Cache/Backend/MysqlTable.php

The API allowes the value `null` for `$specificLifetime` in the `save()` method, which is specified as infinite lifetime.
"expire" is stored in the database as `time() + $lifetime`, which in case of `null` results in immediate expiration instead of none at all.
Setting the expiration date to "1 year" in case of `null` should fix this.
I borrowed this piece of code from https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Cache/Backend/Mongodb.php method `set()`

Fixed a bug with immediate expiration in MySQL table cache

---

pimcore/lib/Pimcore/Cache/Backend/Mongodb.php

otherwise the check "fails" (for example with MongoDB extension v1.1.6)

Additional check if extension "mongodb" is loaded

---

pimcore/models/Object/Localizedfield.php

For now it returns the latest localized version from fallback list regardless of value.
Example: For now, if I have object with localized field "text", and three locales specified in System Settings: en_US, de_DE and en_150. Fallback specified for de_DE is en_150, en_US.
$obj->text:en_US = "Some text for US"
$obj->text:en_150 = "Some text for EU"
$obj->text:de_DE = ""
$obj->localizedfields->getLocalizedValue('text', 'de_DE') will always return "Some text for US" if de_DE value not specified.
After fix it will return first not empty value from fallback list.

Fix language fallback for localized field value.

---

pimcore/models/Object/ClassDefinition.php
pimcore/models/Object/Concrete.php

Allow to call static getByLocalizedfields($fieldName, $value, $locale, $limit | array("limit", "offset")) on Objects.
- Change static method "getByLocalizedfields" to accept new parameters in PHPDoc
- Add feature to allow getByLocalizedfields

allow getByLocalizedField on Objects.

---

pimcore/models/Document/Tag/Video.php

This change will display youtube videos using the URL youtube-nocookie.com which does not set cookies for visitors to comply with EU cookie guidelines.
A setting in ACP might be useful for this feature in case somebody does like youtube cookies.

Use youtube-nocookie.com to comply with EU cookie guidelines

---

pimcore/static6/js/pimcore/object/tags/multiselect.js

Admin translations for multiselect fields in object were not available as this call to the translation function seemed to be missing.

Added call to admin translation function for labels in multiselect fields

---

pimcore/lib/Pimcore/Console/Application.php

Hi,
this fixes console commands autoloading on windows. There is a problem with different directory separator trimming which results in a fatal error when trying to use the console.
Regards,
Martin

console: commands autoload on windows fix

---

pimcore/models/Object/ClassDefinition/Data/Classificationstore.php

With b0053fa "new datatype - calculated values" this PHPDoc type was set. However, for this classname there's no data class for the classification store.

Classification store: Fixed PHPDoc type in class definition

---

pimcore/models/Document/Tag/Area.php

The Area load the action.php file but can't find the right classname.
There is no $this->currentIndex() so replace it with $options["type"]
Maybe a copy/paste error from the changes on May 21 :)

Area can't load action.php BUG

---

pimcore/static6/js/pimcore/settings/system.js

instead of `click` its now the `change` event we need to trigger.

fix save default language event when change radio button

---

pimcore/models/Asset.php

Fixes: warnings in IDEs
Changed: added variable types to @param phpDoc

Fixed phpDoc to prevent warnings in IDEs

---

pimcore/lib/Pimcore/Model/Listing/AbstractListing.php

Fixes # 
After addConditionParam in listing, the origin params were overwritten by the new ConditionParams, resulting addConditionParam is unusable. 
The proposed change will solve this problem by adding the initial params as base params.
More information can be found on this post.
https://groups.google.com/forum/#!topic/pimcore/XoVjsffszmU

Resolve overwrite origin params in object listing

---

pimcore/config/texts/en.json
pimcore/models/User.php
pimcore/static6/js/pimcore/element/abstract.js
pimcore/static6/js/pimcore/settings/user/user/settings.js

Extension to #397  
Opens confirmation dialog when closing dirty elements (Document, Asset, Object). Can be enabled and disabled in the user settings as suggested in #397 .
For this extension to work a small update script for the database is needed.
`ALTER TABLE users ADD COLUMN allowDirtyClose TINYINT(1) UNSIGNED NOT NULL DEFAULT 0`

Decision dialog on closing dirty elements

---

pimcore/models/Object/AbstractObject/Dao.php

If rename an object which has variant-childs, their o_path does not change, because the object only updates if it has either at least a folder or an object child. This makes the database inconsistent as the variant childs have a path which does not exist. The solution is the check for variant childs in the updateChildPaths method of the Dao.

update child paths also if parent has only variants as childs

---

pimcore/lib/Pimcore/WorkflowManagement/Workflow/Decorator.php

Sicking with convention, the note_title and note_type configs which are used for customising the type and title of the notes created during an action have been updated to camelCase

Workflowmanagement - Updated References in Decorator for notes

---

pimcore/lib/Pimcore/Update.php

Fixes # 
If is_file is not true, you will get an e_notice in line 341, because $outputMessage is not set.
E_NOTICE: Undefined variable: outputMessage in /.../pimcore/lib/Pimcore/Update.php:334

Fixed PHP warning in Pimcore/Update

---

pimcore/modules/admin/controllers/ClassificationstoreController.php

Fixes # 
Pimcore throws an exception when adding multiple groups at once to a group. 
The problem is, that extjs sends an multi-dimension array to the server. When adding one item, it only sends an "key-value" array.

fix classificationstore add multiple groups at once to a collection

---

pimcore/static6/js/pimcore/object/classes/class.js

The input field for traits in the new Extjs6 surface of class definitions was gone missing.
This fix adds it again.

Bugfix: Inputfield for traits was missing

---

pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php

Since moving the state / status out of the fields within a classdefinition, State/Status should be saved after the object version was saved, allowing the workflowmanagement.action.before event and object saving to prevent the transition.

Moved setElementState/Status

---

docs/Development_Documentation/05_Objects/01_Object_Classes/03_Structured_Data_Fields/08_Classification_Store.md

Minor documentation fix for Classification store example code.

docs: Fix for example code in "Accessing Classification Store through code"

---

pimcore/models/Object/ClassDefinition/Data/Objectbricks.php

Webservice Import for Object-Bricks when corresponding class has not been created yet. This happens when a Class has a brickfield but no Objectbricks are configured for it.

fix webservice import for object-bricks without corresponding class

---

pimcore/models/Object/Concrete.php
pimcore/models/Object/Service.php

This change removed duplicate code for determining whether an object has an inheritable parent object.
I noticed this duplication while trying to override `Object\Concrete::getNextParentForInheritance()` but having not the desired effect as `Object\Service::hasInheritableParentObject()` implemented it again.

Removed duplicate code for determining inheritable parent object

---

pimcore/models/Object/Data/QuantityValue.php

Fixes an issue where the type of $this->getUnit() is a string, but its expecting to be Unit.

check instanceof type of quantity value

---

pimcore/modules/admin/controllers/EmailController.php

Hi,
this is a small fix for the dynamic parameters popup in sent e-mails log. Any asset/document/object parameter is now always marked as deleted. This PR should fix that and also ads a check for classmapping when determinig the pimcore element type.
Before PR:
After PR:
M.

Sent email enhanced log fix

---

pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php

This small adjustment should make it possible to change the formData entirely within the preAction event. I came across this requirement when migrating a client. We have scenarios where we need to override the state / status of an action based on certain element information.

Workflowmanagement - Refresh of formData after the preAction event

---

pimcore/models/Object/Classificationstore.php

Value "0" evaluated to false in condition if($value) and thus not allow setting/saving this ordinary value.

Classification store: Allow setting value zero ("0")

---

pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php
pimcore/static6/js/pimcore/workflowmanagement/actionPanel.js

example action configuration:
```
[
"name" => "create_task",
"label" => "Create Task",
"additionalFields"=>[
[
"name" => "assignee",
"fieldType"=> "user"
]
],
"notes" => [
"required" => false
]
],
```

Workflowmanagement - Added support for "user" fieldType in actions

---

pimcore/static6/js/pimcore/object/tags/quantityValue.js

This allows for quantity values to be empty. This is important for inheritance - in case the user changes the value in an inherited object or variant, the user can't revert back to inherited state since he cannot set the unit to empty, which is required in order for inheritance to kick back in.
I tested it and didn't notice any unwanted behaviour caused by this change.

Allow empty units in quantity value field

---

pimcore/lib/Pimcore/Controller/Router/Route/Frontend.php

Chaining 301 redirects is bad for user experience (more delay), for SEO, and for performance. We should clean the URL once, instead of redirecting the user at every step of the process.
- Creating a `$finalUrl` variable in Frontend router used along the url cleaning process ;
- Remove 3 identical blocks of code and run this code only at the end of the cleaning process, only if the `$finalUrl` is different than the `$originalPath`.

Refactor the URL cleanup logic to avoid chained redirects

---

pimcore/models/Document/Tag/Video.php
pimcore/static/js/pimcore/helpers.js
pimcore/static/js/pimcore/object/tags/video.js
pimcore/static6/js/pimcore/helpers.js
pimcore/static6/js/pimcore/object/tags/video.js

This is a pull request for https://github.com/pimcore/pimcore/issues/696
It adds Dailymotion for video element. Now the 3 main video providers can be choose (YouTube, Vimeo and Dailymotion).
_Side note:
When making this pull request i find some incoherence betweens extjs4 and extjs6 in the videos.js tags. For extjs6 it seems to miss the URL converter to ID but not sure... So i touched nothing : )
Actually if copying youtube/vimeo URL (not ID), it seems to not work (video doesn't preview in the backend). So **I relabeled "ID" instead "URL" or "URL / ID" the input field**, as directly pasting URL seems broken. Maybe it could be abandonned (code to be cleaned) or corrected in another issue ?_

Add dailymotion as video source (like youtube or vimeo)

---

pimcore/models/Object/ClassDefinition/Data/Multiselect.php
pimcore/static/js/pimcore/object/classes/data/multiselect.js
pimcore/static/js/pimcore/object/tags/multiselect.js
pimcore/static6/js/pimcore/object/classes/data/multiselect.js
pimcore/static6/js/pimcore/object/tags/multiselect.js

This is a pull request for https://github.com/pimcore/pimcore/issues/734
This add max. items options for "multiselect" field data type object, like multihref for instance (same position and name in GUI). Like multihref, validation is only done at GUI level (not in checkValidity php method, so direct API call can bypass this).
As a side use case, now multiselect can be used as color selector (as it accept HTML value) for choosing a single color by limit it to 1 max. items (like you did on the e-commerce Pimcore demo but for multiple color choice).
_Side note:
Validating the max items limit was a bit tricky. First i try using combination of "maxSelections", "validateOnChange: true" and "validitychange (combo, isValid, eOpts)" event, but it is not possible to restore previous value or abort …

Add a maximum selected items for multiselect object field

---

pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php

If setTimeout isn't called, video transcoding runs into the (new) default timeout of 60 seconds. Therefore, increased the timeout to infinity

setTimout of symfony process

---

pimcore/lib/Pimcore/Helper/Mail.php

When Pimcore sends an email with non-ASCII characters in the subject, \Pimcore\Helper\Mail::logEmail() doesn't decode the UTF-8 mime encoded subject line, so a string like `=?UTF-8?Q?Hello=20=C3=B6=C3=A4=C3=BC=C3=9F?=` show up in the "Sent Email" grid in Pimcore's admin GUI.
This fix uses `mb_decode_mimeheader()` to decode an encoded subject header before storing the log entry in table `email_log`.
```
$template = \Pimcore\Model\Document\Email::getByPath('/path/to/email/template');
$email = new \Pimcore\Mail('UTF-8'); // tested with encodings UTF-8 and ISO-8859-1
$email->setDocument($template);
$email->clearSubject()->setSubject('Hello – 你好');
$email->send();
```
Result in db table `email_log` and "Sent Email" grid without fix:
`=?UTF-8?Q?Hello=20world=20=E2=80=93=20=E4=BD=A0=E5=A5=BD?=`` …

Converts mime encoded email subject before storing in database

---

pimcore/models/Asset/Image.php

This change prevents a warning if `iptcparse` should fail and return `false`.
I encountered a JPEG image with the value `Photoshop 3.0 8BIM%                     ` in the IPTC field "APP13". The special characters are an EOT (0x04) and a DLE (0x10).
For some reason this lets iptcparse return `false` and PHP throws a `Warning: Invalid argument supplied for foreach()`.

Prevents warning it iptcparse fails

---

pimcore/models/Element/Tag.php
pimcore/models/Element/Tag/Dao.php

This change adds a method to retrieve elements (documents, assets, objects) that have a specific tag assigned.
Usage example:
```
$tag = \Pimcore\Model\Element\Tag::getById(1);
// retrieve all documents
$el = \Pimcore\Model\Element\Tag::getElementsForTag($tag, 'document');
// retrieve images from assets
$el = \Pimcore\Model\Element\Tag::getElementsForTag($tag, 'asset', ['image']);
// retrieve objects of class 'Test' and include child tags
$el = \Pimcore\Model\Element\Tag::getElementsForTag($tag, 'object', ['object'], ['Test'], true);
```

Adds a method to retrieve elements that have a specific tag assigned

---

pimcore/modules/admin/controllers/ObjectController.php

Fixes always true condition in check path `\Admin_ObjectController::addAction`.
I don't see case when it should be always true.

Fixes always true condition

---

pimcore/static6/js/pimcore/object/helpers/gridTabAbstract.js

The filter condition was shown incorrectly when using the Greater-than-operator. Only ExtJS 6 (static6) is affected.

Grid: Fix for displaying filter condition with operator ">"

---

pimcore/static6/js/pimcore/document/tags/href.js

Currently reload document works only when you drag&drop object into field, but when you change field by search widget (context menu > search) it won't work.

Fix reload document behaviour - href tag

---

pimcore/lib/Pimcore/Controller/Router/Route/Frontend.php

Hi, imho it's a bit annoying that the frontend http authentication configurable in system settings pops also on documents in backend (editmode and preview). So maybe we could suppress it on frontend requests by admin? Here is a PR if you agree :).

do not show frontend http auth in backend

---

pimcore/static6/js/pimcore/helpers.js

I think is safer to use POST instead of default GET because if we have the scenario that an object is linked to many objects inside multi-object field then the request can exceed the maximum of ~ 2000 character url limit 
In my test scenario i got a url with +40000 characters

Nice path request via post

---

pimcore/static6/js/pimcore/element/selector/object.js

This code will fix the issue that when changing the class backend search functionality will ignore query parameter, user needs to click on search button in order to actually filter the result based on query

Add query params to store when changing class in search box

---

docs/Development_Documentation/10_Extending_Pimcore/11_Event_API_and_Event_Manager.md
pimcore/lib/Pimcore/Web2Print/Processor.php
pimcore/lib/Pimcore/Web2Print/Processor/WkHtmlToPdf.php

This pull-request is to add an event before the pdf generation of web2print documents.
Puporse is to be able to inject dynamicaly options to wkhtml/pdfreactor depending of the document.
**One good usage may be the following one.**
Actually for wkhtml2pdf, you can only set page-size globaly. But some document could be A4 but other have another format (visit cards, small flyer, etc.).
So we could set an heritable property on document container like a property name "page-size" for instance.
Using this event hook, developper could grab the document properties and modify pdf generation option by setting $this->option on the "processor" object passed as argument in the event, and modify options as they want before rendering the PDF.
This way, we could have different format for instance without …

web2print - prePdfGeneration event to be able to add config options

---

pimcore/modules/admin/controllers/AssetController.php
pimcore/modules/admin/controllers/DocumentController.php
pimcore/modules/admin/controllers/ObjectController.php
pimcore/static6/js/pimcore/elementservice.js

This pull request is for https://github.com/pimcore/pimcore/issues/844
It add the key of the element (document/asset/object) in the popin when clic on delete in the main element tree. So enduser can be more confident when he delete element without asking himself if he has done the right click on the right element ; )
Here is an example of the result:

Delete dialog: show key of element

---

pimcore/static6/css/icons.css
pimcore/static6/js/pimcore/helpers.js

Notifications except "success" type wont' show icon because in ext6 css there's no icon_notification_* classes, so I added pimcore_icon_success also set window max width and made it closable.

ExtJS6 Fix notification icons & window width behaviour

---

pimcore/lib/Pimcore/Cache.php

Fixes # 
This code fixes a nasty bug that corrupts pimcore cached objects.
To reproduce the bug:
- Create class with DateTime field (startdate).
- Clear the cache
- In code do this:
- $object = Object::getById(666);  // just an example
- $dt = $object->getStartdate();  // get get a REFERENCE to the startdate here
- $dt->add(new \DateInterval('P1D'));  // we change the startdate of the object because we chage the reference
- // we never save the changed object
- Now the object with the altered (but not saved!) start date gets cached!

Fixes bug that corrupts cache

---

pimcore/models/Document/Tag/Date.php
pimcore/models/Element/Note/Dao.php
pimcore/models/Object/ClassDefinition/Data/Date.php
pimcore/models/Object/ClassDefinition/Data/Datetime.php
pimcore/models/Tool/Email/Log/Dao.php
pimcore/models/Webservice/Data/Mapper.php
tests/lib/Test/Tool.php

In PHP we can use DateTime or DateTimeImmutable, both use the same
interface so can be used interchangeably as DateTime objects.
To make sure DateTimeImmutable and DateTime can be used the instanceof
checks must check for DateTimeInterface instead of only DateTime.
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

Check for DateTimeInterface instead of just DateTime

---

pimcore/models/Tool/Email/Log.php

See here: https://3v4l.org/hrFVT
This causes errors resending mail when CC and Bcc are not set

EmailLog / buildArray returns invalid recipients when $data is NULL

---

pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php

Right now behaviour is like Multihref (objects, document or assets), but it should return 
```
\Pimcore\Model\Object\Data\ElemenentMetadata[]
```

Fixes MultihrefMetadata phpdoc (return type) generation.

---

pimcore/lib/Pimcore/Controller/Router/Route/Frontend.php

- Removed a not needed if condition in Frontend Router
In Line 94 $matchFound is set to false and until line 148 it can't be set to another value. checkForRedirect will be always executed. So the if condition is not necessarily.

Removed unnecessary if-condition in Frontend Router

---

pimcore/models/Object/ClassDefinition/Data/Datetime.php

When not using the compat-layer (useZendDate) Date and DateTime hold an instance of Carbon. The auto-generated class files for DateTime still used the PHPdoc for \Pimcore\Date.

ClassDefinition DateTime: Use Carbon for PHPdoc as well

---

pimcore/lib/Pimcore/Controller/Action/Admin/Printpage.php

The workflow component uses the "admin.document.get.preSendData" event to add data about the workflow. Currently the Printpage overrides the getDataByIdAction action and does not add this event.
This PR adds that functionality. It is already tested and worklow component does work on print pages after this change.

Add event admin.document.get.preSendData to PrintPages

---

pimcore/lib/Pimcore/Image/Adapter/Imagick.php

Fixes #1095
Check if there is an AlphaChannel before trying to remove it. Using `Imagick::getImageAlphaChannel()` which returns (int) 0 in PHP, if the Image has no AlphaChannel. 
This is needed for the Tree-Preview Thumbnails, which use `pimcore/static6/img/tree-preview-transparent-background.png` as Base/Background. 
And this image has no AlphaChannel, which can be checked in the Shell with this command:
`convert pimcore/static6/img/tree-preview-transparent-background.png -verbose info:`

Only try to remove AlphaChannel, if Image has an AlphaChannel

---

pimcore/lib/Pimcore/Cache/Tool/Warming.php

This commit fixes a fatal error during cache warming:
```
Fatal error: Call to protected method Pimcore\Cache::storeToCache() from context 'Pimcore\Cache\Tool\Warming' in /pimcore/lib/Pimcore/Cache/Tool/Warming.php
```
This fix uses Cache::save instead of Cache::saveToCache

Use Cache::save() instead of protected method Cache::storeToCache()

---

pimcore/lib/Pimcore/Controller/Plugin/Targeting.php

Fixes # 
Fix the problem of missed location when Personas or List of Targets use Country as condition

[fix] load geoip.js if Personas use Country as condition

---

pimcore/static6/js/pimcore/object/tags/video.js

Fixes #1121 
`this.getBody().update(content);`
seemed to mess up the dom. It removed the inner div's of the classes 'x-autocontainer-outerCt' and 'x-autocontainer-innerCt', which caused Ext.js to crash.
If you update the html of the video panel component like this:
`this.component.update(content);`
It will keep the dom elements in place.
I am not sure if this.getBody() returns the right object, but it is certainly related.

Call update video panel in another way - see #1121

---

pimcore/models/Object/ClassDefinition/Dao.php

Wildcards in MySQL LIKE Statements must be escaped. Otherwise wrong classes will be deleted. Unfortunately happened in our PROD environment today.
Eg:
- Delete the class with object Id 6
- The previous LIKE Statement object_collection_%_" . $this->model->getId() . " will also delete the following collection: object_collection_whatever_26
- The _ matches exactly one character in MySQL LIKE Statements. So the _ in the example above will be matched with the %, the non-escaped _ will match the value 2 and the model-Id is 6

Escaped wildcards in MySQL LIKE Statements.

---

pimcore/static/js/pimcore/document/tags/link.js
pimcore/static6/js/pimcore/document/tags/link.js

Sometimes i use the link editable to be more flexible for links, for example if the target has to be a document or also an external link. But the text part has to be more flexible (for example an wysiwyg or even more). So i don't use the text field of the link. In this case it shows the "Not set" message in the editmode, altough the link is actually set. This is a bit confusing, therefore is suggest to show the path of the link if it is set.

show path of link if no linktext is set instead of not_set message

---

pimcore/lib/Pimcore/Mail.php
tests/AllTests.php
tests/TestSuite/Pimcore/AllTests.php
tests/TestSuite/Pimcore/MailTest.php

Applies https://framework.zend.com/security/advisory/ZF2016-04 fix to `Pimcore\Mail`
Fixes #1165

Backport ZF2+ pwnscriptum handling to Pimcore\Mail #1165

---

pimcore/lib/Pimcore/WorkflowManagement/Workflow/Service.php

When configuring an action you can now configure the date of the note
e.g.
```
"log_telephone_call" => [
"label" => "Log Telephone Call",
"transitionTo" => null,
"notes" => [
"required" => true,
],
"additionalFields" => [
[
"name"=> "noteDate",
"fieldType" => "datetime",
"title" => "Date of Conversation",
"required" => true
]
]
],
```
The note will automatically look for noteDate as a field in the actions additional fields

Workflowmanagement - Allow actions to dictate the date of notes

---

pimcore/lib/Pimcore.php

* Split up `Pimcore::run()` into multiple, smaller methods
* Accept `returnResponse` parameter in `Pimcore::run()` and return the response object instead of sending it to the client
* Accept optional request and response objects in `Pimcore::run()` which are passed to dispatcher

Split up initialization logic and accept optional request/response objects in Pimcore::run()

---

docs/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/01_Text_Types.md
pimcore/static/js/pimcore/document/tags/wysiwyg.js
pimcore/static6/js/pimcore/document/tags/wysiwyg.js

This is the pull request for issue https://github.com/pimcore/pimcore/issues/1160.
With this, it is now possible to globally change in just one place document editable wysiwyg configuration.
Thanks!

added defaultEditorConfig for documents and documentation is updated

---

pimcore/lib/Pimcore/Console/Command/InternalNewsletterDocumentSendCommand.php

Fixes hostUrl argument in internal-newsletter-document-send command. This argument was ignored until now.
Problem when not using hostUrl: 
1. Multi-Site Newsletter would never be able to display images cause the HostUrl is unknown.
2. When no Main-Domain is configured, images would also not be able to be displayed.

fixes hostUrl for newsletter send command

---

pimcore/models/Object/AbstractObject.php

Fall back to parent object ID if parentId is not set but we have a parent object

---

pimcore/lib/Pimcore/Controller/Action/Frontend.php
pimcore/models/Document/Tag/Area.php
pimcore/models/Document/Tag/Areablock.php
pimcore/models/Document/Tag/Block.php

Before using pimcore_tag_block_current we must check if it is set in the
registry. Also made the variable consistent to an array since at some
places there is a check if the content is not an array and chages it to
an array.
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

checks if pimcore_tag_block_current is in registry

---

pimcore/modules/admin/controllers/MiscController.php

Fixes #1139 
This commit uses PHPs built-in ReflectionClass to more reliably list a controllers available actions including inherited methods. Example:
```
// file /lib/Website/Controller/Action.php
namespace Website\Controller;
use Pimcore\Controller\Action\Frontend;
class Action extends Frontend {
public function init() {}
}
// file /lib/Website/Controller/ContentController.php
namespace Website\Controller;
use Website\Controller\Action;
class ContentController extends Action {
public function init() { parent::init(); }
public function fooAction() {}
}
// file /website/controllers/ContentController.php
class ContentController extends Website\Controller\ContentController {
// some comment: function doesntExistAction is shown if using regex
public function barAction()
}
```
Current method …

#1139 Use ReflectionClass to list available actions

---

pimcore/modules/admin/controllers/TranslationController.php

Fixes sorting on Admin Translations.
Admin Translations allows to edit more languages then configured languages, therefor the controller needs to check against all admin languages instead of just user languages.
If we don't do this, we get following error:
```
Server threw exception - could not perform action. Please reload the admin interface and try again.
Status: 500 | Internal Server Error
URL: /admin/translation/translations?admin=1&xaction=read&_dc=1484672406598
Params:
( ! ) Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translations_admin.es' in 'order clause' in vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
( ! ) Zend_Db_Statement_Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column …
```

fixes admin translations join on valid-language table

---

pimcore/modules/admin/controllers/LogController.php

Once the filter component has been set it couldn't be unset anymore (besides button "reset").

Application logger: Fix for unsetting filter "Component"

---

pimcore/models/Document/Tag/Areablock.php

When importing from webservice, the $data variable is a stdClass object, not an array. This throws an error.

Fix areablock import from webservice

---

docs/Development_Documentation/10_Extending_Pimcore/11_Event_API_and_Event_Manager.md
pimcore/models/Object/ClassDefinition.php
pimcore/models/User/AbstractUser.php

This is the pull request for https://github.com/pimcore/pimcore/issues/974
I made it like asset, document, object, classe, ... : separate save into add and update events.
I add delete event for object class as it was missing.
Documentation has been updated and reorganized too (order: add/update/delete for all events).
Thanks!

User events and object class delete event

---

pimcore/modules/admin/controllers/SettingsController.php

This fix prevents PHP from warning 'strpos() expects parameter 1 to be string, array given' when filtering. Site ids are stored as an array in config/staticroutes.php since bac7b39

Minor fix: staticroutes filter function uses only scalar values

---

pimcore/models/Element/Tag/Dao.php

A variable assignment was missing in the getTagsForElement function which can lead to an exception in the compare function.

Fixed potential issue with loading tags for an element

---

pimcore/lib/Pimcore/Document/Newsletter/AddressSourceAdapter/ReportAdapter.php

Fix: Sending Newsletter through Report Adapter didn't work due to wrong handling of offset and limit.

Fix handling of offset and limit

---

pimcore/models/Object/ClassDefinition/Dao.php
pimcore/models/Object/Localizedfield/Dao.php
pimcore/modules/install/controllers/CheckController.php

This greatly simplifies moving Pimcore Databases around, without (in this case) reducing security, since there's no need anymore to keep the Users in sync - which is even impossible, when IP's/Hostnames change and requires to recreate all VIEWS after a database transfer (or patch the export SQL-file).
Drawback: This is a extension to the SQL Standard.
See [MySQL Docs](https://dev.mysql.com/doc/refman/5.7/en/stored-programs-security.html)

Set SQL SECURITY INVOKER on VIEWs

---

pimcore/modules/admin/controllers/ElementController.php

This pull request is for: https://github.com/pimcore/pimcore/issues/1244
As there is already a global filter for type, title and description, I just added support for this global search for user and date.
I think it is more simple than adding filter grid wich will be make things complicated because of the generic actual common filter.
User can search a specific user or specific date even a month (searching for "2017-01" for instance).

notes user and date search

---

pimcore/config/texts/en.json
pimcore/models/Object/ClassDefinition/Data/Objectbricks.php
pimcore/static6/js/pimcore/object/classes/data/objectbricks.js
pimcore/static6/js/pimcore/object/tags/objectbricks.js

This is pull request for : https://github.com/pimcore/pimcore/issues/999
Objectbricks can be limit to one, so only a single objectbrick could be added for the related field in an object.
Purpose of this is for instance, sometimes you model a generic object and want to add some specific fields depending the object type. Object brick is great for it but user could not be limited to the number of them he can add. This PR give the option to prevent the user to be able to add several objectbrick.
A use case could be modeling a generic "product" classe having an objectbrick field called "Type of product".
The generic classe will have price, name, weight, ...
The objectbricks could be: tv, bycicle, book... which will bring additionnal specific field to the product. Only one of those must be …

Option to limit the number of objectbricks which could be added

---

pimcore/models/Tool/Setup/Dao.php

I think is better to use the sql variable, since we apply trim on $m and we append ';'

Unused variable $sql

---

pimcore/models/Object/ClassDefinition.php

phpdoc for magic Listing methods is generated with static keyword
However the phpdoc standard doesn't allow this.
Syntax for @method from phpdoc:
@method [return type] [name]([[type] [parameter]<, ...>]) [<description>]
reference:
https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html
I experienced problems in NetBeans as magic methods generated by Pimcore like
`* @method static \Pimcore\Model\Object\Account\Listing getByAccount_type ($value, $limit = 0)`
annoy the code indexer. The indexer takes `static` as type and `Listing` as method name which appears as many times as we have magic methods. Thus it displays "duplicate method" errors.

phpdoc of magic method mustn't contain static keyword

---

pimcore/modules/install/mysql/install.sql

- Make sure to drop tmp_store
- Drop keyvalue_keys before keyvalue_groups to work around foreign key constraints
- Drop classificationstore_relations and
classificationstore_collectionrelations before
classificationstore_stores and classificationstore_keys to work around
foreign key constraints
Fixes #1277

Fix MySQL errors during reinstall

---

pimcore/models/User/UserRole.php

Added [] to new variables to prevent an error in pimcore/models/User.php getMergedWebsiteTranslationLanguagesEdit() function.
getWebsiteTranslationLanguagesEdit() will return null without empty array initialization, which will cause:
$this->mergedWebsiteTranslationLanguagesEdit = array_values($this->mergedWebsiteTranslationLanguagesEdit);
to crash.

Added default empty arrays to new variables in UserRole.php

---

pimcore/modules/admin/controllers/TranslationController.php

The "on" filter for creation and modification date was not working for shared translations due to comparison of timestamps instead of just dates.

fixed on date filter for creation and modification date in shared translations

---

pimcore/static/js/pimcore/object/classes/data/data.js

Adding a href data type with name children will break the object class completely on Pimcore 4.

Add children as forbidden name

---

pimcore/lib/Pimcore/Console/Command/ClassesRebuildCommand.php
pimcore/models/Object/ClassDefinition.php

During the `php pimcore/cli/console.php deployment:classes-rebuild` always are generated new timestamps in `definition_*` files, in my opinion it a bug, because it first load definition file saves it(why?) and then create/update models and database.

Fixed unnecessary class definition file rebuild during class rebuild command

---

pimcore/models/Object/ClassDefinition/Data/QuantityValue.php

The quantity value fields were displayed like this in the grid: 123 [object Object]
This pull request fixes the issue by implementing the getDataForGrid method.

Quantity value grid display

---

pimcore/lib/Pimcore/Web2Print/Processor/PdfReactor8.php

We need this option accessible in our print document for further processing.

Pass the colorspace option to the print document

---

pimcore/lib/Pimcore/Log/Handler/ApplicationLoggerDb.php

When making a simple log send:
```
$logger = \Pimcore\Log\ApplicationLogger::getInstance("My component", true);
$logger->log("info", "Test message");
```
A notice error is send (undefined index).
This pull request prevent this notice error when using ApplicationLoggerDb.
Thanks.

Notice error ApplicationLoggerDb

---

pimcore/lib/Pimcore/Log/Maintenance.php

This pull request is for: https://github.com/pimcore/pimcore/issues/1128
Instead deleting it directly, the usagelog  is archived for 30 days, so administrator don't loose datas the day the limit size was reached. It will be keep 30 days in case of.
And this way, it is more working like the other logs.

Archiving usagelog.log

---

pimcore/models/Asset.php

If you try to static create an asset from a non-local stream it will just create an empty file. That's because the $tmpFile is unlinked (line 326) right after stream_copy_to_stream in line 321. Later in the getStream method of the Asset class $this->stream is set to null, because a non-local stream is (always) not rewindable.
Fixes # 
1) getStream just sets the stream to null if a LOCAL stream is not rewindable. So the remote stream can be copied to local filesystem in the update method in line 624.
2) Line 307 - 333 is unnecessary, because all these I/O Actions like line 311 are performed twice in the setData method.
- Removed line 307 - 333
- Don't set a non-local stream to null if it's not rewindable
- Changed some array_key_exists calls to isset
`$imgUrl = …

static create asset fix (remote stream)

---

pimcore/models/Version.php

The current maintenance script will wait 5 seconds each iteration regardless of the need for version gzipping. In this case we'll just wait 1 sec after gzipping to reduce total load. Currently the script always sleeps about 50 seconds on many of our sites even if nothing has to be done.

Wait 1 sec after gziping

---

pimcore/modules/admin/controllers/TranslationController.php

Extra-check on the tag name to handle self-closing tags (do not use `<bpt>`/`<ept>` logic but the `<ph>` instead).
About the `<ph>` element :
> The <ph> element is used to delimit a sequence of native standalone codes in the translation unit
> http://www.maxprograms.com/articles/xliff.html#Table2
This case happens on WYSIWYG inputs with the `enterMode` parameter to 2.
The modifications handle the following cases:
- `<br>` (HTML 5)
- `<br />` (XHTML syntax, valid in HTML5 as well)
- `<br></br>` (XHTML syntax)

XLIFF export: Handle selfclosing tags

---

pimcore/modules/admin/controllers/TranslationController.php

Export of WYSIWYG content in XLIFF is inconsistent: Text preceding the very first html tag is stripped.
e.g.: `My<strong>Test</strong>String` => `<strong>Test</strong>String`
Preserve plain text before the first html tag by checking position of the first `<` character
I chose not to modify the regex, since we are handling a fairly special case, that will happen only for the very first iteration of the loop. Let me know if you find a more sensible way to solve this issue!

XLIFF export: plain text / html 

---

pimcore/lib/Pimcore/Db.php
pimcore/lib/Pimcore/Db/Connection.php
pimcore/lib/Pimcore/Db/ZendCompatibility/QueryBuilder.php
pimcore/models/Asset/Listing/Dao.php
pimcore/models/Document/Dao.php
pimcore/models/Document/Listing/Dao.php
pimcore/models/Object/Listing/Dao.php

Fixes #1385. The following usage is now recommended as it passes parameters to Doctrine`s `executeQuery()` (internally building a prepared statement instead of quoting values into the query):
```php
/** @var Connection $db */
$db = $this->get('database_connection');
$qb = $db->select();
$qb
->from(['o' => 'objects'])
->where('o.o_id < :o_id')
->order('o.o_id ASC')
->setParameter('o_id', 10, \PDO::PARAM_INT);
$results = $qb->execute()->fetchAll();
```
Passing a QueryBuilder to `fetch*` also works. The QB will be transformed to a string and its parameters will be prepended to the list of passed params. The following calls are equal:
```php
/** @var Connection $db */
$db = $this->get('database_connection');
$qb1 = $db->select();
$qb1
->from(['o' => 'objects'])
->where('o.o_id < :o_id') …
```

[DB] Update Zend Compatibility Query Builder

---

pimcore/models/Site.php
pimcore/models/Staticroute.php

I installed a fresh copy of the pimcore 5 demo website version.
For example at the portal page of the demo website I noticed in the symfony sql console that some unnecessary/multiple queries regarding sites were fired.
I've not installed a cache backend so the mysql cache is used.
The following query was executed 5 times:
This happens because the Site::getByDomain() method is called multiple times with the same domain. Therefore I think it makes sense to store the result of Site::getByDomain() in the runtime cache in order to avoid multiple calls to the backend cache.
Additionally I noticed multiple completely useless calls like this:
I added a check to avoid this too into the Staticroutes model.

Site handling performance improvement

---

pimcore/config/startup.php
pimcore/models/User.php

Define the `user-image` directory once at startup. It allows to override this path (to move it to S3 for example)

Move the user-image path to a constant

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/SettingsController.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Tool/AssetsInstaller.php
web/pimcore/static6/js/pimcore/extensionmanager/admin.js

Fixes Issue #1388 
* Runs `assets:install` command after enabling a bundle
* Shows a `Clear cache and reload` button on the extension grid
* Shows the "Please reload..." message only after changing an extension state

Run assets:install command after enabling bundle

---

pimcore/models/Object/ClassDefinition/Data/QuantityValue.php

The getFromWebserviceImport method of the QuantityValue data type should not throw an exception if only parts of the field (only value or only unit) are filled. 
It should be a valid counterpart to the getForWebserviceImport method in order to make it possible to transfer the data from one pimcore instance to another one correctly via the REST webservice.
This pull request applies to Pimcore 5 - should I create the same one for Pimcore 4? It should be fixed there too!

QuantityValue getFromWebserviceImport bugfix

---

pimcore/lib/Pimcore/Tool.php

This avoids notices when run from tests without request.
I experienced a notice with a test that loads `\Pimcore\Config::getWebsiteConfig()` in a utility class.
`\Pimcore\Config::getWebsiteConfig()` calls `\Pimcore\Tool::isFrontentRequestByAdmin()` which produces the notice by accessing `$_SERVER["REQUEST_URI"]` without checking if it is set.
My fix avoids this.

check REQUEST_URI if set before matching

---

web/pimcore/static6/js/pimcore/object/helpers/grid.js

Object grid cell editing didn't work anymore because the routing/url structure changed in pimcore 5.

make object grid cell editing work again in pimcore 5

---

app/AppKernel.php
doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Extension/Bundle/Config/StateConfig.php
pimcore/lib/Pimcore/Extension/Bundle/PimcoreBundleManager.php
pimcore/lib/Pimcore/Extension/Config.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/BundleCollection.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/Item.php
pimcore/lib/Pimcore/Kernel.php
pimcore/tests/unit/HttpKernel/BundleCollection/BundleCollectionTest.php
pimcore/tests/unit/HttpKernel/BundleCollection/ItemTest.php
web/pimcore/static6/js/pimcore/extensionmanager/admin.js

Fixes Issue #1455
* Bundles are registered on the `AppKernel` via `registerBundlesToCollection`. A `BundleCollection` handles bundle priority and filters by environment
* Bundle state (enabled, priority, environments) is written to config file in a normalized manner, supporting both boolean and array entries through a `StateConfig` class
* Extension manager exposes priority and environments in editable grid cells

Bundle initialization priority

---

web/pimcore/static6/js/pimcore/helpers.js

Grid layout needs to be refreshed after an update of the grid content occured otherwise strange things will happen if the new content's height is bigger then the original row height.

MultiRelation path formatter layout bugfix

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/WorkflowController.php

WorkflowController::submitWorkflowTransitionAction has a second parameter to $this->json, which is a boolean, but json expects it to be a http-header-code, therefore it throws an error with invalid http-code 1. this pr fixes that

fix WorkflowController::submitWorkflowTransitionAction json return

---

web/pimcore/static6/js/pimcore/object/tags/nonownerobjects.js

Drag&Drop of non owner fields did not work reliably, because find() method did not determine the class name exactly. For instance if there existed "ShopProduct" and "ShopProductMaterial" classes then "ShopProductMaterial" was matching incorrectly.

pimcore5 | Nonowner fields | bug | extjs

---

pimcore/static6/js/pimcore/object/tags/nonownerobjects.js

Drag&Drop of non owner fields did not work reliably, because find() method did not determine the class name exactly. For instance if there existed "ShopProduct" and "ShopProductMaterial" classes then "ShopProductMaterial" was matching incorrectly.

Nonowner fields | bug | extjs

---

pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php

I created a class with to fieldcollection fields, both allowing the same fieldcollection. That fieldcollection contains a "Multihref with metadata" attribute. After adding the fieldcollections and filling in some data for additional columns in the metadata field, only the metadata for one field will be saved.
From what i can tell, the problem lies in the `delete` and `save` methods of `pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php`
There, the owner name is not included in the delete-statement (for unlocalized fields at least) when the old metadata is removed. This means that all metadata gets deleted, regardless of the fieldcollection they belong to. If multiple metadata fields with the same name are present in the fieldcollections ob an object, only the values from …

Fixed error with fieldcollections containing metadata fields

---

web/pimcore/static6/js/pimcore/helpers.js
web/pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
web/pimcore/static6/js/pimcore/object/tags/objectsMetadata.js

This pull request fixes the inheritance indicator when a multirelation path formatter is used in objects with metadata or multihref with metadata (other relation types are not effected).
We tried several different solutions but unfortunately it's not possible to solve it differently without doing some refactorings.

MultiRelation path formatter bugfix: inheritance indicator didn't work when a path formatter was used

---

pimcore/static6/js/pimcore/helpers.js
pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
pimcore/static6/js/pimcore/object/tags/objectsMetadata.js

MultiRelation path formatter bugfix: inheritance indicator didn't work when a path formatter was used (pimcore 4)

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/TranslationController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/ElementListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Service/Context/PimcoreContextGuesser.php
pimcore/lib/Pimcore/Service/Request/PimcoreContextResolver.php
pimcore/lib/Pimcore/Templating/Renderer/ActionRenderer.php
pimcore/models/Document/Service.php

Fixes issue #1441
Pimcore context needs to be resolved for every request, not globally as otherwise Documents rendered from admin (e.g. `DocumentRenderer::render()` will end up without a document).

Fix document render errors from admin context

---

pimcore/models/Object/ClassDefinition/Data/Classificationstore.php

In admin mode, when editing an object, the classificationstore groups are not sorted correctly.
The sorter field is used, but there is a bug in the sort function.
The variables AND the comparaison sign are inverted at the same time.

Classificationstore groups not sorted

---

pimcore/static6/js/pimcore/element/notes.js

Details panel in Notes & Events view isn't resizable which makes it hardly usable for one of our use-cases. This pull requst keeps the same default size, but allows for resizing.
I will provide additional Pull Request for Pimcore 5 if this one gets accepted.

Allow for resizing of details panel in Notes & Events view.

---

pimcore/lib/Pimcore/Translate.php

Trimmed $messageId's that return empty string translations appear to be saved.

[BugFix] Don't create translations for empty strings

---

pimcore/models/Object/Fieldcollection/Dao.php

When using object relation field in localized block in field collection, updating data relation in field-collection removes the field-collection object relation data for all other objects of same type.
How to reproduce
- Create a field-collection(fields1) with localized block and add object relation field to localized block
- Create a class e.g. Test and add field collection-field with allowed types = fields1
- Create object(object1) of class Test
- In object1, relate object in localized field collection and save it
- Create object(object2) of class Test
- In object2, relate object in localized field collection and save it
- object1 field-collection data will get lost on object2 field-collection data update

bugfix: localized object relation data lost in field collection

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php

Asset controller has an undefined method setParam.
You can easily reproduce this problem by doing the following:
- Create a class with an asset datafield with a default upload path.
- Create a new object of this class and upload a file in the asset field.
parentId of the new asset is tracked in a seperate variable instead of in an undefined method
UndefinedMethodException HTTP 500 Internal Server Error Attempted to call an undefined method named "setParam" of class "Pimcore\Bundle\AdminBundle\Controller\Admin\AssetController"

Bugfix: Replace undefined setParam method calls

---

pimcore/models/Schedule/Manager/Procedural.php

Skip maintenance jobs that have a lock at execution time, unless we are running in a forced mode.
In cluster environment, where the database and the `var` folder are shared across instances, running the jobs in parallel on several machines might lead to several issues. 
The current lock process check the state of jobs at initialization time, but assumes this state won't change before actually start processing the job. We should check whether the job is currently locked or not just before executing it.

Skip locked jobs at execution time

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/MiscController.php

When selecting the template for a document, currently only templates in `app/Resources` are taken into consideration. This adds support for bundle templates.

Add templates defined in bundles to list of selectable templates

---

doc/Development_Documentation/03_Documents/03_Navigation.md
doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/04_Migrate_to_Symfony_Stack.md
doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
install-profiles/demo-cms/app/Resources/views/layout.html.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/NavigationRendererPass.php
pimcore/lib/Pimcore/Bundle/CoreBundle/PimcoreCoreBundle.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_php.yml
pimcore/lib/Pimcore/Navigation/Builder.php
pimcore/lib/Pimcore/Navigation/Renderer/AbstractRenderer.php
pimcore/lib/Pimcore/Navigation/Renderer/Breadcrumbs.php
pimcore/lib/Pimcore/Navigation/Renderer/Menu.php
pimcore/lib/Pimcore/Navigation/Renderer/RendererInterface.php
pimcore/lib/Pimcore/Templating/Helper/Navigation.php
pimcore/lib/Pimcore/Templating/Helper/Navigation/Exception/InvalidRendererException.php
pimcore/lib/Pimcore/Templating/Helper/Navigation/Exception/RendererNotFoundException.php
pimcore/lib/Pimcore/Templating/PhpEngine.php
pimcore/models/Object/ClassDefinition.php
pimcore/models/Object/ClassDefinition/Data/Block.php
pimcore/models/Object/ClassDefinition/Data/Localizedfields.php
pimcore/models/Object/Fieldcollection/Definition.php
update-scripts/60/postupdate.php

Renderers have no connection to the Helper anymore and require the navigation container as mandatory argument in all `render*` methods. They now hold an instance of the delegating rendering engine, effectively supporting any kind of template. Additional helpers can be added to the helper by tagging them with the `pimcore.navigation.renderer` DI tag.
The helper itself does not have any state anymore but just exposes methods to build and render navigations. This has 2 main advantages:
* Navigation state is predictable as every call requires the container. No nav containers will be cached on the helper level (helper is stateless)
* The navigation can be rendered from everywhere (Twig, PHP, ...) and the helper reused from other templating engines (as preparation for Twig support)
The …

[NAVIGATION][TEMPLATING] Refactor navigation to be independent from navigation helper

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/AdminBundle/Session/Handler/AbstractAdminSessionHandler.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Session/Handler/AdminSessionHandler.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Session/Handler/AdminSessionHandlerInterface.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Session/Handler/SimpleAdminSessionHandler.php
pimcore/lib/Pimcore/Tool/Session.php

As preparation for #1525: in certain cases (e.g. the naming migration or testing) it's necessary to set the admin session to a dummy/in-memory session which does not open/close foreign session and which does not rely on a real session storage. This change defines a common interface an `AdminSessionHandler` needs to implement and allows to set a custom admin session handler on `Pimcore\Tool\Session` if needed.

[SESSION][ADMIN] Add support for a mockable admin session

---

.travis/system.template.php
install-profiles/demo-cms-twig/var/config/system.template.php
install-profiles/demo-cms/var/config/system.template.php
pimcore/lib/Pimcore/Http/RequestHelper.php
pimcore/lib/Pimcore/Tool.php

As preparation for #1525: Updates `Pimcore\Tool` to make use of the current request object instead of `$_SERVER` and `$_REQUEST` globals. This is needed when handling multiple master requests in a single process (e.g. testing or the migration script running through the whole dispatching process multiple times).

Use Request instead of $_SERVER and $_REQUEST globals in Pimcore\Tool

---

pimcore/modules/admin/views/scripts/index/index6.php
pimcore/modules/admin/views/scripts/login/index.php

When a customer has in there company has a compatibility rule (All websites) in IE, force the browser to take the latest render version. This to prevent that the admin of Pimcore be rendered with old IE render engine.
Changes in the admin layout and the login page

[Pimcore4] Problems with IE company wide compatibly settings

---

pimcore/lib/Pimcore/Document/Tag/TagHandler.php
pimcore/lib/Pimcore/Templating/HelperBroker/DocumentTag.php
pimcore/lib/Pimcore/Templating/Renderer/TagRenderer.php

Follow up to #1598. Further normalizes/fixes areabrick edit template markup and fixes editmode not being handled properly in edit templates as the editmode parameter was not honored while rendering document tags.

Fixes to Areabrick edit templates

---

web/pimcore/static6/js/pimcore/settings/staticroutes.js

Static Routes service controllers are only working with AppBundle services without this pr. This PR appends the moduleName param in the Static Routes grid.

in addition to pr #1560 fix staticroutes to append moduleName param

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/MiscController.php
pimcore/lib/Pimcore/Controller/Config/ControllerDataProvider.php
web/pimcore/static6/js/pimcore/settings/staticroutes.js

* Add module AJAX select to static routes editor
* Changes to bundle selection logic in document/static route
- If no bundle is selected, all controllers defined as service will be returned.
Additionally, all controllers which are no service and which are defined in the
defaultBundle (AppBundle) will be included. This allows us to leave
the module select empty while still getting results which make sense
in most cases.
- If a bundle is selected both controllers which are services and normal
controllers will be filtered to those which are defined in the bundle.

Refinements to bundle/controller selection

---

pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/AdminExceptionListener.php
pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/BruteforceProtectionListener.php
pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/HttpCacheListener.php
pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/UsageStatisticsListener.php
pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/UserPerspectiveListener.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/config/event_listeners.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/AbstractContextAwareListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/BlockStateListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/ContentTemplateListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/MaintenancePageListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/ResponseExceptionListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml

* Add a `profiler` context to make sure context specific event handlers to not run on profiler requests
* Refine event handler definitions (user context resolver interface everywhere)
* Make sure BlockState, ContentTemplate and FullPageCache listeners run only in frontend context

Event handler optimizations

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/AdminBundle/Security/User/TokenStorageUserResolver.php

Is it really necessary to have a Container dependency inside the TokenResolver? Shouldn't this (PR) be enough? I mean, if the security.token_storage service is missing (eg. SecurityBundle is missing as well), something is wrong anyway.

[Admin] refactor TokenStorageUserResolver to get rid of Container dependency

---

web/pimcore/static6/js/pimcore/object/helpers/edit.js

newConfig's properties have to overwrite xTypeLayoutMapping's properties to take in account the configuration of class layouts. (web/pimcore/static6/js/pimcore/object/helpers/edit.js)

CSS Styles of class layout component are ignored.

---

pimcore/models/Object/ClassDefinition/Data/Password.php
web/pimcore/static6/js/pimcore/object/classes/data/password.js

`password_hash` was already implemented in #471, but the default is still `md5`.

Make password_hash the default algorithm for password fields

---

pimcore/config/bootstrap.php
pimcore/lib/Pimcore/Tool.php
web/app.php

Tool::getClientIp() does not have access to a request at the time the kernel is built. Now the request is set as static property on Tool until the kernel is built. To make this possbile, initialization logic needs to be split up into bootstrapping (autoloader, constants) and building the kernel.

Fix Pimcore::inDebugMode() returning false if debug mode is configured to IP

---

pimcore/models/Document/Tag/Image.php

I experienced a weird behaviour with DI on Images and Thumbnails: when defining custom classes in my `di.php` file, the custom Thumbnail class was being used only when a specific thumbnail config was defined in the Tag.
It apparently lies on both image thumbnails not being retrieved the same way. Getting a thumbnail with `new Asset\Image\Thumbnail($image);` seems to ignore the defined overwrite rules (I am not so sure to understand why though).
- Why is the DI class not being called in this case?
- Deferred option: I let it to its default value, not so sure what would be the best option here

Homogenize the way we retrieve thumbnails in Image Tag

---

pimcore/models/Asset.php
pimcore/models/Asset/Image/Thumbnail.php

When you want to get checksum other than md5 or sha1 instead of exception sha1 checksum is returned.

Fix getChecksum bug in if logic

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/External/AdminerController.php

Adminer behaves quite weird on first request. It loads all available database but flushes the output (https://github.com/vrana/adminer/blob/master/adminer/drivers/mysql.inc.php#L336 + https://github.com/vrana/adminer/blob/master/adminer/include/functions.inc.php#L1227). Not sure what the idea behind this is. This PR solves the issue and Adminer gets displayed properly.

[#1627] Adminer Integration: Styling Issues

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Command/UpdateCommand.php

Update puts the system into maintenance mode, so the internal:update-process command should ignore maintenance mode when being run
Adds --ignore-maintenance-mode flag to the call

Fix for the update command: --ignore-maintenance-mode

---

pimcore/models/Element/Tag/Dao.php

When saving a tag, only attempt to get idPath of existing tag when tag has an ID (i.e. when the tag already exists). 
To reproduce bug (before fix):
Try creating a new tag, either through "Tag Configuration" or via the Tags tab on an asset.

save tag: fix exception when tag does not yet exist

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Routing/Staticroute/Router.php

Many older projects use parameters like `language` to define a language in the URL. As this is now handled by Symfony's default `_locale` parameter, all existing static routes and code relying on their params needs to be updated. This PR adds a mapping to resolve existing params like `language` to the `_locale` attribute. The mapping is only used if no explicit `_locale` parameter is set. 
Valid params can be set via config:
```yaml
pimcore:
routing:
static:
locale_params:
- language
```

[ROUTING] Add a list of parameters which are mapped to _locale attribute if not set

---

web/pimcore/static6/js/pimcore/object/tags/objectbricks.js

How to reproduce this bug?
1. Add objectbricks field in some class, set limit e.g. to 1.
2. Create new object.
3. Press green (+) button in object brick field.
4. After new element is added, press red (x) button to remove it.
5. Try go to step 3, but you'll get error message "Limited reached".

Fix "Limit reached" bug in objectbricks.js

---

pimcore/models/Object/ClassDefinition/Data/QuantityValue.php

Wrong phpdoc types for QuantityValue
Fix the namespace in the classdefinition of QuantityValue

add proper namespace in QuantityValue phpdocType

---

website_demo/config/customviews.example.php

Unclear instruction how to use the "classes" attribute
Extended description so it's clear it expects a comma-separated list of class ids (not class names)

Better description of "classes" attribute in customviews sample

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php

* wirecardSeamless not converting Decimal to number before rounding
* agent not creating a reproducible fingerprint as string and float representations are mixed when loading from order object/from cart

[ECOMMERCE] Fix payment issues with Decimal

---

pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
pimcore/lib/Pimcore/Routing/Staticroute/Router.php

When loading a static route inside a site, the nearest document isn't properly resolved as it does not take the site into account.

Static routes inside a site do not resolve nearest document properly

---

pimcore/models/Tool/Setup.php

We use a deployment system where we checkout the project (including parameters.yml) and then run Pimcore Installation and load data from Fixtures. This PR makes sure that the parameters.yml doesn't get overwritten or recreated with different 'secret' parameter which would stage a VCS change on the server after deployment.

Generate parameters.yml file only if it doesn't exist.

---

composer.json

the "myclabs/deep-copy" package only gets installed in dev mode since the only dependency is in "phpunit/phpunit" - which is not available in `--no-dev` mode.

add myclabs/deep-copy to composer.json

---

pimcore/config/constants.php
pimcore/lib/Pimcore/Update.php

- `composerUpdate()`: only update the real pimcore `composer.json`
- `installData()`: move `composer.json` to the real pimcore directory
- `composerDumpAutoload()`: `dump-autoload` only in real pimcore directory
This PR will force pimcore to use the real pimcore `composer.json` file, since the `PIMCORE_PROJECT_ROOT` could lead to a different path and a thereby to a different `composer.json`.

Composer file path

---

pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php

case-insensitive preg_match patterns for file extensions since upper case extensions are valid in most/all file systems

case-insensitive preg_match patterns

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/TranslationController.php

Content-Type is set with a ending ':', therefore fastcgi reports duplicate-header exception.

[AdminBundle] fix translations export Content-Type

---

pimcore/models/Object/ClassDefinition.php

1. IDEs aren't able to autocomplete static getBy-calls on an object. 
2. If you extend a class and a getBy method call should be overridden, the IDE will throw an error like 'Cannot make non-static method ... static"
- marked non-static method calls in doc-block as static methods.
All 'getBy' calls are realized by "__callStatic" in Pimcore\Model\Object\Concrete. So methods should be marked as static.

Mark non-static methods as static

---

pimcore/lib/Pimcore/Event/DocumentEvents.php
pimcore/lib/Pimcore/Event/Model/PrintConfigEvent.php
pimcore/lib/Pimcore/Web2Print/Processor/PdfReactor8.php
pimcore/lib/Pimcore/Web2Print/Processor/WkHtmlToPdf.php

Added events:
- pimcore.document.print.processor.modifyProcessingOptions
- pimcore.document.print.processor.modifyConfig
to modify the processing behaviour of the Web2Print adapters.
Usage Example: 
Listener definition:
app.event_listener.test:
class: AppBundle\EventListener\TestListener
tags:
- { name: kernel.event_listener, event: pimcore.document.print.processor.modifyProcessingOptions, method: modifyProcessingOptions }
- { name: kernel.event_listener, event: pimcore.document.print.processor.modifyConfig, method: modifyConfig }
Listener: 
<?php
namespace AppBundle\EventListener;
use Pimcore\Event\Model\ObjectEvent;
class TestListener
{
public function modifyProcessingOptions(\Pimcore\Event\Model\PrintConfigEvent $event){
$arguments = $event->getArguments();
$options = …

Web2Print Events - Add events to configure the processing options and the configuration for the adapters

---

pimcore/config/texts/en.json
pimcore/models/Asset.php
pimcore/modules/admin/controllers/AssetController.php
pimcore/static6/js/pimcore/asset/asset.js

The upload function currently has a little bit strange behaviour:
Currently it just replaces the binary content of the asset.
This pull requests improves the behaviour as following:
- If the uploaded asset has the same type (for example Asset\Image) as the existing asset the filename and mime type will be updated (for example if a jpg gets replaced by a png).
- If the uploaded asset would change the type of the original asset an error message will be shown and the upload will be declined as such type changes could be quite dangerous when the asset is already used somewhere.
If the pull request gets accepted I will create one for Pimcore 5 too. Please let me know if I should update anything in the behaviour.

Asset replace function: handle change of file types correctly

---

web/pimcore/static6/js/pimcore/document/tags/table.js
web/pimcore/static6/js/pimcore/object/tags/table.js

**Bug description:**
When using a cellediting plugin, the celleditor is always attached in DOM to the latest cell it was used in. If the row with that cell gets removed, the editor DOM node gets orphaned and removed by ExtJSs garbage collector (after 0-30s).
**Steps to reproduce:**
* add a table field to the object (or table editable to the document)
* add 2 additional rows to the table (there will be 3 rows now)
* put 'a', 'b' and 'c' into each of the rows respectively
* delete rows with 'c' and 'b'
* wait 30 seconds (default interval of the garbage collector)
* try editing the row by doubleclicking - it won't work and you will get errors in console
To make testing faster, you can change the garbage collector interval by issuing this command in console:
``` …
```

Prevent garbage collection of cell editors - bug of Ext.Js.

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php
pimcore/lib/Pimcore/Extension/Bundle/PimcoreBundleManager.php
pimcore/lib/Pimcore/Extension/Bundle/Traits/StateHelperTrait.php

After uninstalling or disabling the ecommerce framework, the Fieldcollections extending from `IndexFieldSelectionCombo` which are not deleted on uninstall still try to fetch the installer which is not available anymore. This adds a check if the bundle is enabled and installed before trying to fetch options from the factory.

[ECOMMERCE] Check if bundle is enabled before trying to fetch installer in IndexFieldSelectionCombo

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/AbstractBundleCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/DisableCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/EnableCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/InstallCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/ListCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/UninstallCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/UpdateCommand.php
pimcore/lib/Pimcore/Extension/Bundle/PimcoreBundleManager.php

As preparation for #1847. Exposes all methods provided by the extension manager as CLI commands. #1847 will implement a return channel from installers to the CLI allowing to output information from your installer to the CLI command.
* `pimcore:bundle:disable`
* `pimcore:bundle:enable`
* `pimcore:bundle:install`
* `pimcore:bundle:list`
* `pimcore:bundle:uninstall`
* `pimcore:bundle:update`

[BUNDLES] Expose extension manager functionality as CLI commands

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Extension/Bundle/Config/StateConfig.php
pimcore/lib/Pimcore/Extension/Bundle/PimcoreBundleManager.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/AbstractItem.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/BundleCollection.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/Item.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/ItemInterface.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/LazyLoadedItem.php
pimcore/lib/Pimcore/Kernel.php
pimcore/tests/unit/HttpKernel/BundleCollection/BundleCollectionTest.php
pimcore/tests/unit/HttpKernel/BundleCollection/ItemTest.php
pimcore/tests/unit/HttpKernel/BundleCollection/LazyLoadedItemTest.php
web/pimcore/static6/js/pimcore/extensionmanager/admin.js

Resolves #1750
* Bundles from `addBundlesToCollection` are registered first
* Extension manager bundles will be loaded after the ones which are manually registered and will only be added if the bundle is not already registered. This allows to safely enable a bundle manually without running into duplicate bundle errors.
* The bundle collection is kept on the kernel and is used by the extension manager to distinguish manually added bundles from configured ones
* Manually added bundles can be installed/uninstalled and updated but not enabled/disabled and can't change priority or environments

[BUNDLES] Support manually registered pimcore bundles

---

doc/Development_Documentation/18_Tools_and_Features/27_Website_Settings.md
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_php.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_twig.yml
pimcore/lib/Pimcore/Config.php
pimcore/lib/Pimcore/Controller/ArgumentValueResolver/WebsiteConfigValueResolver.php
pimcore/lib/Pimcore/Templating/Helper/WebsiteConfig.php
pimcore/lib/Pimcore/Templating/PhpEngine.php
pimcore/lib/Pimcore/Twig/Extension/WebsiteConfigExtension.php

* PHP templating view helper `$this->websiteConfig()` or `$this->websiteConfig('foobar')`
* Twig helper `{{ pimcore_website_config() }}` or `{{ pimcore_website_config('foobar') }}`
* Argument resolver `fooAction(\Pimcore\Config\Config $websiteConfig) {}`
Resolves #1835

[PIMCORE5] Expose website settings in controllers and views

---

pimcore/lib/Pimcore/Navigation/Renderer/AbstractRenderer.php

instead of `<a id="pimcore\navigation\renderer\menu-23">` => `<a id="pimcore-navigation-renderer-menu-23">`

convert invalid menu id prefix backslash to dash.

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DocumentController.php

raised a warning cause variable $site was undefined on line 1079.

[AdminBundle] fix qtip config for documents with site

---

pimcore/lib/Pimcore/Install/Installer.php

In our deployment process the installation overwrites existing files although we are using the no-overwrite option.
This is the scenario:
* we check out our code
* we run the deployment script
* deployment script downloads the setup files (they now have newer timestamp)
* the copy process will overwrite all older existing files - it won't preserve the existing files since they have older timestamp
This fix will stop the copy process for the whole folder, but I guess this should be fine. Otherwise we should maybe replace the Symfony's copy/mirror function with something else that doesn't overwrite existing files.

Skip the copy step if the target path already exists.

---

pimcore/lib/Pimcore/Twig/Extension/PimcoreObjectExtension.php

Kinda messed up the merge for PR #1878, so here is a new one.
In Multi-Site context, its often necessary to get the site to get its root-document and for example include snippets from its root document.

[Twig] add pimcore_site function

---

pimcore/modules/admin/controllers/ObjectHelperController.php

If using DI to override classes, CSV import was not creating a DI instance if the object if overwriting was not enabled

[Pimcore4] Fix to CSV Import

---

composer.json

Restricting to a specific PHP platform will make updates to libraries specifying a certain minimum
PHP 7 version impossible. E.g. Symfony 3.3.8 requires PHP 7.0.8 which doesn't match with
PHP set to 7.0.

Remove composer platform restriction to PHP 7.0

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/TemplatingEngineAwareHelperPass.php
pimcore/lib/Pimcore/Bundle/CoreBundle/PimcoreCoreBundle.php
pimcore/lib/Pimcore/Templating/Helper/Traits/TemplatingEngineAwareHelperTrait.php
pimcore/lib/Pimcore/Templating/PhpEngine.php

Currently a view helper implementing `TemplatingEngineAwareHelper` needs to be fetched through the PHP engine as the setter is called by the engine after loading the helper. This shifts the call to a compiler pass setting the engine as soon as the helper is built.

[TEMPLATING] Set PHP engine when building a TemplatingEngineAwareHelper

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/NavigationRendererPass.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_php.yml
pimcore/lib/Pimcore/Templating/Helper/Navigation.php

Preparation for #1629. Use a renderer locator to lazy load renderers.

Change navigation helper to use a renderer locator instead of the whole container

---

pimcore/models/Tool/Setup.php

We are using Deployer for automated setup and deployments. We now run into the issue when installing Pimcore for the first time (eg. running setup).
We share our system.php thru all releases of your applications, when running deployment for the first time, there is no system.php available yet (cause the installer should create it). Therefore deployer creates a empty file (symlinked to the shared dir). Pimcore then fails installing cause it tries to parse the empty file and expects an array. With this PR, this is resolved and should work fine with deployer, automated setups, deployments and a shared system.php

[Installer] improve installer when using deployer

---

doc/Development_Documentation/19_Development_Tools_and_Details/15_Magic_Parameters.md
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/TranslationDebugListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config_dev.yml
pimcore/lib/Pimcore/Translation/Translator.php

Resolves #1850 
This adds a flag to the translator which allows to set it into debug mode (translator will just return the given message id instead of actually translating the message). An event listener listens on a
configurable parameter and sets the flag on the translator.
Example: http://foo.bar/en?pimcore_debug_translations=1
Debugging can be disabled completely via config (enabled by default in dev).

[TRANSLATOR] Add a magic parameter to debug translation keys

---

composer.json
doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php
pimcore/lib/Pimcore/Extension/Bundle/Traits/PackageVersionTrait.php

Resolves #1888
We already have an API for composer package versions through `ocramius/package-versions` which already is installed via `ocramius/proxy-manager`.  This adds a trait which can be used from bundles to read and return the package version from `getVersion()`.

[BUNDLES] Add possibility to return composer package version in getVersion()

---

doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
pimcore/lib/Pimcore/Twig/Extension/TemplatingHelperExtension.php

Fix in the documentation about Cache Helper + add possibility to use it in the Twig templates
* properly working example for php engine for cache helper
* before example wasn't proper because in the `$this->cache("test_cache_key")->end();` 60 second from `$this->cache("test_cache_key", 60)->start()` was reset (it was output cache)
* added possibility to Twig caching and added example

[Pimcore5] Cache Helper - fixes

---

doc/Development_Documentation/18_Tools_and_Features/29_Custom_Reports.md
doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/02_V4_to_V5.md
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Reports/CustomReportController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Document/Newsletter/AddressSourceAdapter/ReportAdapter.php
pimcore/lib/Pimcore/Document/Newsletter/ReportAddressSourceAdapterFactory.php
pimcore/models/Tool/CustomReport/Adapter/CustomReportAdapterFactoryInterface.php
pimcore/models/Tool/CustomReport/Adapter/CustomReportAdapterInterface.php
pimcore/models/Tool/CustomReport/Adapter/DefaultCustomReportAdapterFactory.php
pimcore/models/Tool/CustomReport/Config.php
web/pimcore/static6/js/pimcore/report/custom/settings.js

related to #1399 
Adds the possibility to load CustomReport Adapters via configuration:
```yml
pimcore:
custom_report:
adapters:
identifier: service_name
```
This PR also creates a Factory class For ReportAddressSourceAdapterFactory to take advantage of DI for Newsletter Address Sources as well.
pimcore/models/Tool/CustomReport/Config.php::156 (getAdapter) is now deprecated, but still works for maybe BC reasons?
There is also a small change in ExtJS for CustomReports, they used to have a body-padding of 10px inside of Pimcore, which is very unusual. Nothing inside the main-tab-panel has a padding of 10px.

[CustomReportAdapter] make them available via service-locator

---

.travis.yml
.travis/php-redis.ini
.travis/run-tests.sh
.travis/setup-php.sh
pimcore/lib/Pimcore/Cache/Pool/Redis.php
pimcore/lib/Pimcore/Cache/Pool/Redis/Connection.php
pimcore/lib/Pimcore/Cache/Pool/Redis/ConnectionFactory.php

Resolves #1979 
Credis returns different responses when the redis extension is enabled leading to failures in the cache pool. This PR
* changes the cache pool behaviour to cope with different responses from credis
* updates travis config to enable redis extension by default and to run an extra environment with the extension disabled

Fix redis cache pool not working when redis extension is enabled

---

pimcore/lib/Pimcore/HttpKernel/BundleLocator/BundleLocator.php
pimcore/lib/Pimcore/HttpKernel/BundleLocator/BundleLocatorInterface.php

Areabrick template autodiscovery failed when the bundle was not situated in a directory ending in `Bundle`, e.g. when a bundle is installed via composer. This reuses the same logic as the TemplateGuesser in SensioFrameworkExtraBundle to look up a bundle dir.

Fix areabrick template autodiscovery for bundles installed via composer 

---

doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md

Link to example file for creating custom templating helpers was not reachable, now updated to correct url.
From 
https://github.com/pimcore/pimcore/blob/master/install-profiles/demo-basic/src/AppBundle/Templating/Example.php
to
https://github.com/pimcore/pimcore/blob/master/install-profiles/demo-basic/src/AppBundle/Templating/Helper/Example.php

Custom Templating Helper Link fix

---

pimcore/lib/Pimcore/Translation/Translator.php
pimcore/models/Translation/AbstractTranslation.php
pimcore/models/Translation/Admin.php
pimcore/models/Translation/TranslationInterface.php
pimcore/models/Translation/Website.php

Checks messages for admin domain against list of admin languages. Fixes #1842

[TRANSLATOR] Fix valid language check on adding new message for admin domain

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php

This PR makes form-attributes in the Ecommerce-Payments expandable. In some cases it might be necessary to set additional form html properties (e.g. <form ... data-paymentmethod='methods'>...</form>). By providing an formAttributes property additional form-attributes, other than those set by the EcommerceFramework, can be defined
- added an array-property which will be used in order to create the Symfony-FormBuilder.

[Pimcore 5] [Ecommerce] - make form-attributes in Ecommerce-Payments expandable

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/AdminBundle/Translation/AdminUserTranslator.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/documents.yml
pimcore/lib/Pimcore/Document/Tag/TagHandler.php

Needed when rendering admin elements outside of admin context (e.g.
areabrick toolbar in editmode). As the AdminUserTranslator implements
the TranslatorInterface, implementations can just use the new service
instead of the standard translator to get this behaviour.
Fixes #1857

Implement an AdminUserTranslator which uses the user's language as default locale

---

docs/Development_Documentation/08_Tools_and_Features/28_Marketing_Settings.md

This is the pull request for Pimcore 4 for #1882.
As there is no Marketing settings page in documentation I added one here, with a note about desactivate automatic Google Analytics code injection as it can be needed sometimes (to be able to layer some custom debugging code for instance wich need to inject custom code).
This page can be enriched later if neccessary for other marketing settings (they are self explanotory in the GUI for now).

[Pimcore 4] Adding Marketing settings to documentation

---

web/pimcore/static6/js/pimcore/overrides.js

The t() function fallback which was added in #1811 seems to be declared
even if the surrounding if() block does not resolve to true, resulting
in t() always being the fallback method instead of the real translator.
By setting it as function expression on the window object the fallback
should work properly without overwriting the actual t() function.
Fixes #1997

Fix admin translations not being loaded in Safari

---

pimcore/lib/Pimcore/Cache/Runtime.php

Incorrect annotation -` @returns` might cause AnnotationException

[Pimcore 5] Fixing annotation typo

---

doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings.md

This is the pull request for Pimcore 5 for https://github.com/pimcore/pimcore/issues/1882.
As there is no Marketing settings page in documentation I added one here, with a note about desactivate automatic Google Analytics code injection as it can be needed sometimes (to be able to layer some custom debugging code for instance wich need to inject custom code).
This page can be enriched later if neccessary for other marketing settings (they are self explanotory in the GUI for now).

[Pimcore 5] Adding Marketing settings to documentation

---

pimcore/lib/Pimcore/Routing/Staticroute/Router.php
pimcore/models/Staticroute.php

* Fixes `Staticroute::assemble()` when no request is available (CLI)
* Adds support for URL reference types for Pimcore's static routes (fixes #1902)

Pimcore Staticroute Improvements

---

pimcore/lib/Pimcore/Config.php
pimcore/lib/Pimcore/Install/Installer.php
pimcore/lib/Pimcore/Install/SystemConfig/ConfigWriter.php
pimcore/lib/Pimcore/Tool.php
pimcore/models/Tool/Setup.php
web/app.php

When the installer tries to build the container for the first time, it can happen that there's already built container in place (e.g. because of CLI scripts). Under certain circumstances (probably timing issues), it can happen that the kernel does not rebuild the container from the newly created config, but keeps using that cached container, resulting in errors (e.g. using root as DB user as it is in the default config). This makes sure:
* the cache dir is cleared before the application kernel is built
* `app.php` does not even try to build a kernel if no `system.php` is found (prevents building an invalid kernel)
* the `Setup` model is not loaded before building the kernel. The method writing config files was moved to an extra class
* the new kernel is always booted in dev mode (as we …

[INSTALLER] Fix installer sometimes relying on invalid container configuration

---

composer.json

Credis introduced breaking changes in 1.9 which cause cache tests to fail. Until this is fixed, keep using 1.8.

Set credis dependency to 1.8.*

---

composer.json

See #2026 for Pimcore 5 version. Won't fix in Pimcore 4 - just keep using 1.8.x here.

[PIMCORE4] Credis 1.8 dependency

---

install-profiles/demo-basic-twig/web/static/css/print.css

In the layout of the demo-basic-twig installation profile is a print.css included:
https://github.com/pimcore/pimcore/blob/master/install-profiles/demo-basic-twig/app/Resources/views/layout.html.twig#L18
But this file is missing. A add the one from the demo-basic installation profile.

Add missing print.css in demo-basic-twig installation profile

---

install-profiles/demo-basic-twig/app/Resources/views/layout.html.twig

Add possibility to use the predefined property "leftNavHide" within twig basic demo.

Add possibility to use property "leftNavHide" in twig basic demo.

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tools/Installer.php

Partially fixes #2004. Avoids doing multiple lookups on `isInstalled()`

[ECOMMERCE] Only check isInstalled() once

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php
update-scripts/134/preupdate.php

Partially fixes #2004 
* Disables legacy mapping by default. If a project already has the framework enabled, an update script will take care of creating a local config file enabling the mapping.
* Does not check for `isInstalled()` when applying legacy mapping as it is a performance hit which runs on every request and shouldn't be necessary for static class mapping.

[ECOMMERCE] Default legacy mapping to false

---

pimcore/lib/Pimcore/Model/AbstractModel.php

fixed issue #2000 
You had flexibility issue. Architecturally low level models should not care about performance. It's mostly task for server cache. I removed static mapping for several models for further easy overriding these models.

Hardcoded mapping in lib/Pimcore/Model/AbstractModel.php

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/migrations.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml
pimcore/lib/Pimcore/Migrations/Command/Traits/PimcoreMigrationsConfiguration.php
pimcore/lib/Pimcore/Migrations/Configuration/ConfigurationFactory.php
pimcore/lib/Pimcore/Migrations/Configuration/MigrationSetConfiguration.php

At the moment, two types of migration sets exist:
* the `app` set, which acts as global set for application migrations
* one set per bundle via `--bundle` option when using the migrate commands or via `MigrationInstaller`
This adds the possibility to add arbitrary migration sets via configuration and moves the definition for the `app` set to configuration as well. New migration sets can be defined as follows:
```yaml
pimcore:
migrations:
sets:
testset:
name: Test Migrations
namespace: Test\Migrations
directory: "%kernel.project_dir%/src/Test/Migrations"
testset2:
name: Test Migrations 2
namespace: Test\Migrations2
directory: "%kernel.project_dir%/src/Test/Migrations2"
connection: conn2
```
Note: this adds a small BC break in the `ConfigurationFactory` as the constructor and the …

[MIGRATIONS] Configurable Sets

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Model/AbstractCategory.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Model/AbstractFilterDefinition.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Model/AbstractProduct.php

As discussed in https://github.com/pimcore/pimcore/commit/40502c79514902788a0cb102a417b1f3db6e54d0#commitcomment-24803057 these methods are not needed.

[ECOMMERCE] Remove unneeded getById() methods on abstract models

---

pimcore/lib/Pimcore/Cache/Pool/Doctrine.php

Although the table column is a varchar, a PARAM_INT was passed. This seems to work fine until PHP 7.2 where this is apparently enforced and converted to an integer, resulting in too many tags being deleted.

[CACHE] Fix doctrine adapter failing on PHP 7.2 due to wrong type passed when clearing tags

---

composer.json
doc/Development_Documentation/00_Overview/00_Pimcore_Ecosystem.md
doc/Development_Documentation/01_Getting_Started/00_Installation.md
pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config_dev.yml
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Readme.md
pimcore/lib/Pimcore/Update.php
update-scripts/60/postupdate.php
web/pimcore/static6/js/pimcore/settings/update.js

This PR updated all outdated pimcore.org links in the repository.
Some were directed to a 404 page.

Update outdated pimcore.org links

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php

1. The static variables $baseUri and $contentType are not accessible, they aren't even existing. See https://developers.klarna.com/sdk-references/kco_v2_php_4_0_0/class-Klarna_Checkout_Order.html
2. Better idea would be to set the endpoint via the static variable of the Klarna_Checkout_Connector class.

Update Klarna PaymentProvider because of fatal errors

---

pimcore/models/Document/Tag/Wysiwyg.php

Cast array to object for wysiwyg
While testing with the api we discovered that the text from wysiwyg element isn't saved. $wsElement->value is an array and not an object.
- Create document with webservice api
- Expected result: text of wysiwyg is filled with "hoplaaa"
- Actual result: wysiwyg is empty
Data to test with:
`{
"path": "\/",
"userModification": 2,
"childs": null,
"controller": "Blog",
"action": "default",
"template": null,
"elements": [
{
"type": "wysiwyg",
"value": {
"text": "hoplaaa",
"options": null,
"name": "richtexteditor",
"realName": null,
"inherited": false
},
"name": "richtexteditor"
}
],
"parentId": 1,
"type": "snippet",
"key": "test-api-user",
"index": 2,
"published": true,
"userOwner": …

[Pimcore 4] Update for webservices, cast array to object

---

pimcore/modules/admin/controllers/TranslationController.php
pimcore/static6/js/pimcore/settings/translation/xliff.js
pimcore/static6/js/pimcore/tool/paralleljobs.js

Send documents/jobs to translate as POST to avoid "414 Request URI too long" errors when submitting many documents.

[XLIFF] Send XLIFF admin request as POST

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml

Profiler was resolved to `default` context resulting in frontend listeners (e.g. tracking codes) being injected into profiler page.

Fix context resolver not matching profiler due to wrong pattern

---

pimcore/static6/js/pimcore/overrides.js

In Pimcore 4 are the translations not loaded anymore, this is fixed in pimcore5. See related issue: #1997
#1997

[PIMCORE4] - Admin translations

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php

Voucher codes (coupon) is not lost any more when displaying the tracking code on the purchase page.

Track voucher codes in purchase

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/AbstractCart.php

Added a getter for ignoreReadonly so we can access the value from a extended class. 
E.g to automatically cance a active payment

AbstractCart - add getter for ignoreReadonly

---

doc/Development_Documentation/18_Tools_and_Features/17_Application_Logger.md
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/logging.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Log/ApplicationLogger.php
pimcore/lib/Pimcore/Log/Handler/ApplicationLoggerDb.php
pimcore/lib/Pimcore/Log/Processor/ApplicationLoggerProcessor.php

Implements #1998
Application Logger logic (file objects, related objects, source) is replicated to an `ApplicationLoggerProcessor` which is added to the `ApplicationLoggerDb` handler. In the long term the `ApplicationLogger` class itself won't be necessary as it is now possible to handle application logging entries completely via monolog's configuration. When we drop `Zend_Log` support we can remove the now duplicated logic from the `ApplicationLogger` class itself.

Application Logger: Monolog Handler

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/documents.yml
pimcore/lib/Pimcore/Extension/Document/Areabrick/AreabrickManager.php

Instead of injecting the whole container into the areabrick manager, now a scoped service locator only containing the bricks is injected.
Fixes #2104

[AREABRICKS] Add support for areabricks registered as private service

---

pimcore/models/Document/Tag.php

---
`$return` is confused name for a variable. We just have an example of mistake because of it on the gitter:

Variable confusing naming quickfix

---

web/pimcore/static6/js/pimcore/object/tags/fieldcollections.js

Problem: Context indices of elements inside fieldcollections aren't updated on adding/deleting/moving field collection entries 
Fix: this updates the indices after any add/delete/move operation

Context indices of elements inside fieldcollections aren't updated

---

pimcore/models/DataObject/ClassDefinition/Data/Multiselect.php

When you're using a multiselect in a classification store the definition of the class does not get returned if no options provider is present since the return statement lies within the option provider conditional check.
Moved return statement outside the conditional scope.

Multiselect didn't return definition without options provider present

---

.gitlab-ci.yml
.travis.yml
.travis/run-docs.sh
.travis/setup-docs.sh
.travis/setup-tests.sh
doc/README.md

Builds docs on travis for verification. Docs are built using [daux.io](https://daux.io) with the [pimcore/pimcore-docs](https://github.com/pimcore/pimcore-docs) setup.
Additionally, a config file for gitlab allows building docs on Gitlab CI.

[DOCS] Build docs on travis

---

pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/WorkflowManagementListener.php

This PR resolves following problem while opening object: Attempted to call an undefined method named "getParam" of class "Symfony\Component\EventDispatcher\GenericEvent".

Fix for calling undefined method

---

pimcore/models/Element/Service.php

Undefined index -1 warning when creating new folder by path.
On the line 751 variable $pathsArray is initialized as empty array.
On the first loop iteration (line 762) PHP tires to get value from element with index -1 what causes problems with tests.
Checking if key in array exists.

Fixing undefined index -1 error

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/SessionEnvironment.php

For the (hopefully rare) cases when a session is needed in cli mode, I'd propose making it available by explicitly starting it.

making SessionEnvironment available in CLI environment

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PricingManager/Action/Gift.php

Gift items should only be added to a cart or a order if they are still available based on the information of the availability system.

add gift item to cart only if available

---

pimcore/models/Element/Service.php

This PR makes it possible to clone Pimcore Objects which relate to Doctrine Objects (Collections). Otherwise cloning entities is impossible, since it throws a "container not clone-able" exception.

add Doctrine filter for DeepCopy

---

pimcore/lib/Pimcore/Update.php

Because the updateHost variables has private access, it is causing an error in the RunUpdateScriptCommand

Added getter for update host

---

doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/ResponseStackListener.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/documents.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/request_response.yml
pimcore/lib/Pimcore/Document/Tag/TagHandler.php
pimcore/lib/Pimcore/Extension/Document/Areabrick/AreabrickInterface.php
pimcore/lib/Pimcore/Http/ResponseStack.php

Areabrick `action` methods may need to return a response (e.g. a redirect after a form is submitted). This PR adds the concept of a `ResponseStack` which is used as follows:
- the return value of `action()` and `postRenderAction()` is evaluated, and if it is a response it is pushed onto the `ResponseStack`
- the `ResponseStackListener` operates on `kernel.response` and sets the last response from the response stack on the event if the stack contains responses.
The stack can also be used from other parts of the system which don't have direct access to the request/response cycle.

[AREABRICKS] Handle responses returned from an areabrick action and postRenderAction method

---

pimcore/lib/Pimcore/Console/Command/UpdateCommand.php

Update puts the system into maintenance mode, so the internal:update-process command should ignore maintenance mode when being run.

[PIMCORE4] Fix for the update command: --ignore-maintenance-mode

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php

When exporting voucher tokens via the button _Export CSV_ in the top right corner in the Voucher Details Tab inside an object of class `OnlineShopVoucherSeries` it failes, because of the missing class `Pimcore\View\Helper\TranslateAdmin`. Fixed by using the Pimore 5 Translation Service.

Pimcore 5 translation fix for exporting voucher-tokens

---

web/pimcore/static6/js/pimcore/object/tags/localizedfields.js

- Vanilla installation Pimcore 5.0.2 Build 147
- Creating class with localized fields element
- Set label width on localized fields element
- Add input element to localized fields element
- Set label name to input element
- Create object with class
- Label width of localized fields element is used for input element
- Label width of localized fields element is ignored and default of 100 px is used for input element
Add label width inheritance. It's just a proposal, maybe there are better ways to place that code or achieve it otherwise.

bugfix: inherit label width from localized fields configuration

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/TranslationController.php

funny, apparently no one has ever noticed that the xliffImport actually never worked in p5. The second parameter returns `false` which will lead to a `The HTTP status code "0" is not valid.` error message.

fix xliffImport header status

---

doc/Development_Documentation/19_Development_Tools_and_Details/15_Magic_Parameters.md
pimcore/lib/Pimcore.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Tool.php

Fixes #2268. Additionally adds support to disable debug mode via `pimcore_disable_debug` cookie.

[DEBUG] Use IpUtils to check debug mode adresses and to support IP ranges

---

doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
install-profiles/demo-basic/app/Resources/views/Areas/gallery-single-images/view.html.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/ImageSVGPreviewCommand.php
pimcore/lib/Pimcore/Tool/Requirements.php
pimcore/lib/helper-functions.php
pimcore/models/Asset/Image.php
pimcore/models/Asset/Image/Thumbnail.php

Adds support for small SVG placeholder images to thumbnails. 
The placeholder is placed into the `src` attribute of the `<img>` tag, the real paths are available in `data-src` and `data-srcset`. 
You have to use a script of your choice to replace the `src` with the proper image path in `data-src` / `data-srcset`. 
```php
<?= $this->image("image", [
"thumbnail" => "galleryThumbnail",
'svgPlaceholder' => true
]); ?>
```
Result: 
```html
```
- SVG preview/placeholder are generated when saving the asset
- existing images do not have a SVG preview, please use `./bin/console pimcore:image:svg-preview` to generate them (after the update and setting up SQIP

Image thumbnails: added SVG placeholder support

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/10_Fix_Performance_Issues_with_XAMPP_on_Windows.md

This documentation provides a step by step guide to fix the performance issue of the Pimcore/Symfony stack on Windows XAMPP installations by switching out Mod-PHP with FastCGI.
Tested with the latest version of XAMPP with Apache 2.4 and PHP 7.1

[Documentation] Fix Performance Issues with XAMPP on Windows

---

pimcore/config/texts/en.json
pimcore/static6/js/pimcore/object/classes/data/multihrefMetadata.js
pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js

This is a slightly different implementation of the boolean field on the multihrefmetadata component.
It forces a whole column of hrefs to be limited to one selection only. Similar to Magento 1's image selection component (that's why i had to implement it)
Currently only frontend, it probably needs some backend validation, I'm happy to PR too just let me know.
This is reletively easy to port to Pimcore 5, if you think its a good feature let me know and I will port.

PIMCORE4 MultihrefMetdata columnbool

---

pimcore/models/Staticroute.php

```php
$route = Staticroute::getById(123); // does not exist -> $route is null
$route = Staticroute::getById(123); // $route is empty object as it is saved in runtime cache
``` 
This pull request provides a fix.

fix for caching Staticroutes objects which doesn't exist

---

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
pimcore/lib/Pimcore/Extension/Bundle/Config/StateConfig.php

Fixes #2183
**IMPORTANT**: Targeted for 5.1 as this change potentially influences existing applications by changing the priority of bundles without a explicit priority.

[EXTENSIONMANAGER] Use a default priority of 10 for bundles enabled via extension manager 

---

pimcore/lib/Pimcore/Translation/Translator.php

Fallback languages did not work correctly in combination with case insensitive translations enabled.
for example:
Translation key is "myTranslation"
If the translation key is empty but a "mytranslation" TK exists with a translated value in one of the fallback languages the translation key was printed instead of the fallback value.
I'm not sure if my solution is a good one - escpecially the part where the original locale catalogue get's updated but I have no idea how to solve it differently.

fallback translation in combination with caseinsensitive website translations bugfix

---

pimcore/lib/Pimcore/Analytics/Piwik/Config/Config.php
pimcore/lib/Pimcore/Analytics/Piwik/WidgetBroker.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Controller/Reports/PiwikController.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Reports/Piwik/PiwikReportsProvider.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/public/js/bundle.js

Resolves #2047. Adds Piwik reports to ecommerce menu if Piwik is configured. If Piwik is not configured for iframe integration (logme) but a report token is set, a single overview widget will be openened.

[PIWIK][ECOMMERCE] Add Piwik reports to ecommerce menu

---

web/pimcore/static6/css/admin.css
web/pimcore/static6/js/pimcore/asset/tree.js
web/pimcore/static6/js/pimcore/document/tree.js
web/pimcore/static6/js/pimcore/helpers.js
web/pimcore/static6/js/pimcore/object/tree.js

#2383 
Added styling to the tooltip so it can now point left and right, fixed for object/asset/document the problem that it appeared on the left side

Bugfix for showing the tooltip on the leftside when righttree panel was open #2383

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Controller/PublicServicesController.php

An action has to result a response, in this case a 404 fits best.
Response before: LogicException - The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?
Response after: NotFoundHttpException - Asset with ID '12345' doesn't exist

Thumbnail-Action: Return NotFound-Response if asset does not exist

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/EmailController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Helper/Mail.php
pimcore/lib/Pimcore/Mail.php
pimcore/lib/Pimcore/Mail/Plugins/RedirectingPlugin.php
pimcore/models/Document/Email.php
pimcore/models/Tool/Email/Log.php
update-scripts/168/postupdate.php
web/pimcore/static6/js/pimcore/document/emails/settings.js
web/pimcore/static6/js/pimcore/settings/email/log.js

Allows to define replyTo Addresses in Pimcore Mail.
```sql
ALTER TABLE email_log ADD COLUMN `replyTo` VARCHAR(255) DEFAULT NULL AFTER `from`;
ALTER TABLE documents_email ADD COLUMN `replyTo` VARCHAR(255) DEFAULT NULL AFTER `from`;
```

implement replyTo in pimcore mail, see #2351

---

doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/09_Targeting_Storage.md
pimcore/lib/Pimcore/Targeting/Storage/Cookie/JWTCookieSaveHandler.php
pimcore/lib/Pimcore/Targeting/Storage/CookieStorage.php

Session cookies do not always behave as expected (expire when closing the browser):
> The cookie created above is a session cookie: it is deleted when the client shuts down, because it didn't specify an Expires or Max-Age directive. However, web browsers may use session restoring, which makes most session cookies permanent, as if the browser was never closed.
Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
This sets a fixed expiration for session storage cookies + enforces the expiration in the JWT signed variant by setting an explicit token expiration. Even if the client sets another expiration date, the data will still expire when the token expires.

[TARGETING] Expire session cookie storage with a fixed timeout instead of using session cookies

---

doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md
doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Permissions.md

This pull request add informations to the documentation to help setting permissions.
It is intended to resolve issue https://github.com/pimcore/pimcore/issues/2234, so the process can be more easy for new users.
(it doesn't resolve the Ocramius/PackageVersions touch problem which lead to the necessity to make a `chown -R YOURUSER:YOURGROUP *`, so setting directory by directory write permissions don't work for now).

doc permissions improvement

---

doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md

This pull request is for https://github.com/pimcore/pimcore/issues/1831
It add information to the documentation that setCondition and addConditionParam cannot be used together.
(as explained in the issue it lead to error/strange result)

Add doc information that setCondition and addConditionParam cannot be used together

---

pimcore/lib/Pimcore/Config.php

We upgraded from v3.1.1 to v4.0.0 and then from v4.0.0 to v4.6.2.
After the upgrade we noticed that no documents were being displayed in the admin, it was just displaying a white screen. Although they were working fine in the frontend.
That was due to PHP throwing a fatal error:
`PHP Fatal error:  Call to a member function getParam() on null in /var/www/branches/master/builds/build-14/pimcore/lib/Pimcore/Config.php on line 143`
That was because `$front->getRequest()` (see PR code change) was returning null. I'm not sure why though. We are not using multi-site or anything. It's just a standard install.
The fix was to wrap that code inside an if statement and only execute it if there is a request object.

Fixes broken document view in the admin

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php

This PR resolves problem with batch assignment. Due to the lack of parentheses in the SQL query, filters are not included when calculating objects for editing.

fix for "get batch jobs" action

---

doc/Development_Documentation/21_Deployment/03_Multi_Environment.md

This PR is to give clues how to configure a new environment name.
Even if it follow symfony standard, i think it is worth mentionning this in the documentation to help people (and those comming from Pimcore 4 can get trapped in the test environment which has a special signification in Symfony).
I state too that some environment file need to be created in `pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/` which seems is not documented.
This PR was done because of those issues relating some difficulties to set a new environment:
https://github.com/pimcore/pimcore/issues/2265
https://github.com/pimcore/pimcore/issues/2346

Doc for setting up a new environment name

---

web/pimcore/static6/js/pimcore/object/tags/objectsMetadata.js

#2447 This fixes the problem when opening a objectsMetadata

[#2447] Check if the value exists before splitting

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/SettingsController.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Update/IndexController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/InternalUpdateProcessorCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/UpdateCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
pimcore/lib/Pimcore/Cache/Symfony/CacheClearer.php
pimcore/lib/Pimcore/Tool.php

* resolves #2434 
* resolves #2452 
* resolves #1958
Symfony 3.4 introduced a new file structure for its cached container, splitting up service definitions which are loaded via `require_once` on demand. This introduces errors when clearing the container via code in the "clear cache" admin action and during updates as calls to a stale container can lead to `require_once` errors when the files don't exist anymore.
As an example, the `Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener` which runs in the `kernel.terminate` event fetches the Swiftmailer service to send mails. This fails and leads to errors as described in #2434.
This PR changes multiple things:
* it uses the Symfony `cache:clear` command logic to clear and optionally warm up the cache as there is much …

Fix Symfony 3.4 issues on cache clear and update

---

web/pimcore/static6/js/pimcore/asset/asset.js
web/pimcore/static6/js/pimcore/asset/folder.js
web/pimcore/static6/js/pimcore/document/folder.js
web/pimcore/static6/js/pimcore/document/page_snippet.js
web/pimcore/static6/js/pimcore/helpers.js
web/pimcore/static6/js/pimcore/object/folder.js
web/pimcore/static6/js/pimcore/object/object.js

This change consolidates the deeplink generation (helper).
Further more, it now respects the server port so links for Pimcore installations on non-standard ports are correct, e.g.:
https://example.com:81/admin/login/deeplink?object_12345_object

Deeplink: Added helper and respect server port

---

web/pimcore/static6/js/pimcore/object/tree.js

In method init variable class attribute treeDataUrl is not used (is uses just static url)

Use class attribute instead of static url in pimcore.object.tree class

---

pimcore/lib/Pimcore/Helper/Mail.php

The fallback for the host url has to be outside of the if() statement because otherwise this wouldn't work
\Pimcore\Web2Print\Processor::getInstance()->getPdfFromString($html)
beause no document is passed

Pimcore Mail helper bugfix

---

web/pimcore/static6/js/pimcore/document/tags/multihref.js

Check if subTypes exist because if we don't add subType to our multihref configuration we get: "Uncaught TypeError: Cannot read property 'object' of undefined" when we try drop object to multiherf.
How to reproduce bug:
Create filed like: {{ pimcore_multihref("slider", {types:['object'], classes: ['Product']}) }}
And try drop object to this multihref.

Fix problem with subType in multihref.js

---

web/pimcore/static6/js/pimcore/object/helpers/gridCellEditor.js

This PR fixes a nasty js error in grid cell editing. steps: to reproduce on demo:
- open folder with objects
- click "column configuration"
- add a "Operator Trimmer" and any field as child
- save
- click on a cell from the just created operater, a message appears "This element cannot be edited"
- now click on the refresh button on bottom which will trigger an error:
After that you need to reload the whole folder element.
By the way: the `startEdit` method is deprecated in extjs since 5.5:
http://docs.sencha.com/extjs/6.0.2/classic/Ext.grid.plugin.CellEditing.html#method-startEdit

check field editable in completed grid cell edit

---

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/CacheClearCommand.php

-o and -a now do not support values anymore. Instead of having to pass -o=1, just pass -o
-t is now handled as array
The change in options changes behaviour and can be considered a BC
break, but the current implementation is quite misleading as
"pimcore:cache:clear -o" clears the whole cache instead of only clearing
the output tag as expected.

[CACHE] Fix options behaviour in pimcore:cache:clear command

---

pimcore/lib/Pimcore/Tool/Requirements.php

[Install Command] if memory-limit for CLI is set to -1 install fails #2089
https://github.com/pimcore/pimcore/issues/2089
the install command failed if the php.ini setting for memory_limit was set to '-1'. 
I added a condition to convert the value of the memory_limit only if it is not set to -1
see issue: https://github.com/pimcore/pimcore/issues/2089

fixed: if memory-limit for CLI is set to -1 install fails

---

web/pimcore/static6/js/pimcore/document/tags/areablock.js

C/p support was removed in https://github.com/pimcore/pimcore/commit/007e77028c95c0876dbae0278be121abfb8bb4f4 as we decided to only support it for the new naming scheme. This re-introduces c/p for the legacy scheme, with the same errors and implications as outlined in https://github.com/pimcore/pimcore/issues/559.
Upgrade to the nested naming scheme is still highly recommended.

Re-introduce copy/paste for areablocks with legacy naming scheme

---

doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/Cache/Pool/Redis.php
pimcore/tests/cache/Core/RedisLuaCoreHandlerTest.php
pimcore/tests/cache/Pool/RedisLuaTest.php
pimcore/tests/cache/Pool/TaggableRedisLuaTest.php
pimcore/tests/cache/Pool/TaggableRedisTest.php
pimcore/tests/cache/Pool/Traits/RedisItemPoolTrait.php

In a high concurrency situation, the current Redis implementation can lead to inconsistencies resulting in items losing their cache tags. This happens when a save and an invalidateTag with a tag assigned to the saved item are issued within a short amount of time. 
This PR fixes only the Lua implementation of the cache adapter, the concurrency issue still exists in non-Lua mode. Changes include:
* Doing everything data related in a single script to ensure the data is accessed transactionally. This concerns mainly the oldTags clearing during a commit which previously handled the oldTags clearing outside of the script, leading to the same inconsistencies as in non-Lua mode.
* Defining Lua as properly intended and commented scripts instead of the unmaintainable blob it was before.
* Sending …

[CACHE][REDIS] Fix concurrency issues in Lua mode

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/DisableCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/EnableCommand.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Bundle/Helper/PostStateChange.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/extensions.yml
pimcore/lib/Pimcore/Bundle/InstallBundle/Command/InstallCommand.php
pimcore/lib/Pimcore/Cache/Symfony/CacheClearer.php
pimcore/lib/Pimcore/Install/Installer.php
pimcore/lib/Pimcore/Process/PartsBuilder.php
pimcore/lib/Pimcore/Tool/AssetsInstaller.php
pimcore/tests/unit/Process/PartsBuilderTest.php

* Runs `assets:install` after installation (see #1974)
* Fixes `assets:install` which is run after `pimcore:bundle:enable` not picking up the newly added bundle as it was executed from the same, old kernel
* Unifies `assets:install` and `cache:clear` process handling

Run assets:install after installation and fix assets:install after bundle CLI commands

---

doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/04_Bundle_Collection.md
pimcore/lib/Pimcore/HttpKernel/Bundle/DependentBundleInterface.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/BundleCollection.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/Item.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/ItemInterface.php
pimcore/lib/Pimcore/HttpKernel/BundleCollection/LazyLoadedItem.php
pimcore/lib/Pimcore/Kernel.php
pimcore/tests/unit/HttpKernel/BundleCollection/BundleCollectionTest.php
pimcore/tests/unit/HttpKernel/BundleCollection/ItemTest.php
pimcore/tests/unit/HttpKernel/BundleCollection/LazyLoadedItemTest.php

As described in #1780, dependencies between bundles are a common issue which currently needs to be solved manually. As we already have the `BundleCollection`, adding a way to handle dependencies on a simple level is possible without a performance hit coming from dependency resolution. This change:
* Removes the exception which is thrown on the bundle collection when a bundle is added multiple times. Instead, subsequent adds are simply ignored. An already added item can never be changed, so the first item added wins. This also means that an item which is added from the core or from another bundle can be overridden on the collection by adding it manually before it is added from core/dependency. See the new `createBundleCollection` method on the kernel which can be used to add items to the …

Dependency handling for Bundles

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php
pimcore/lib/Pimcore/Kernel.php

Resolves #2267
* Kernel now handles a `FileExistenceResource` for every possible location of the `extensions.php` to make sure a debug container is rebuilt when a file is created. For example, in the empty install profile the file doesn't exist at all and the container didn't track if it is created.
* When activating an extension via extension manager in a non-debug container, the cache is implicitly cleared.
* The Ecommerce Framework now checks for parameter existence before using them in `boot()`. This is done as fallback if previous the measures do not work, e.g. when activating an extension by manually editing `extensions.php` for a non-debug container.

Fix errors after activating extensions via extension manager which rely on parameters (e.g. ecommerce)

---

pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
pimcore/lib/Pimcore/DependencyInjection/ConfigMerger.php
pimcore/lib/Pimcore/Tool/ArrayUtils.php
pimcore/tests/unit/DependencyInjection/ConfigMergerTest.php
pimcore/tests/unit/Tool/ArrayNormalizerTest.php
pimcore/tests/unit/Tool/HtmlUtilsTest.php

Merging
access_control:
- { path: '^/test' }
- { path: '^/test2' }
with
access_control: ~
resulted in
access_control: ~
as the null overwrote the array. Now, only merging is done, and arrays
are never overwritten from scalars. This should make the merging behaviour
the same as the core config component handles it.

Fix config merging to never overwrite with scalars/null and add tests

---

web/pimcore/static6/js/pimcore/object/helpers/gridTabAbstract.js

CSV-Export loses settings for data inheritance and separator when number of exported items is more than 20.
**Expected behavior:**
When exporting csv data from grid view inheritance and separator character is considered in all exported data row.
**Actual Behavior:**
When exporting csv data from grid view inheritance and separator character is considered **only in the first 20 exported data rows**. In all other rows default separator is used and no inherited values are exported.

Bugfix - CSV-Export loses settings

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php

It seems that classification store fields are not saved due the lack of the important code.

fix for batch actions related with classification store fields

---

doc/Development_Documentation/01_Getting_Started/03_Configuration.md
doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
pimcore/config/bootstrap.php
pimcore/config/kernel.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Update/IndexController.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/UpdateCommand.php
pimcore/lib/Pimcore/Config.php
pimcore/lib/Pimcore/Config/EnvironmentConfig.php
pimcore/lib/Pimcore/Config/EnvironmentConfigInterface.php
pimcore/lib/Pimcore/Kernel.php
pimcore/lib/Pimcore/Tool/Housekeeping.php

Hardcoded environments are now handled in a configurable EnvironmentConfig class which is initialized at boot, but can be overridden/reconfigured during the startup process.
EnvironmentConfig can either be reconfigured using setters or completely replaced by implementing a custom config class. Environments to register in development are still hardcoded on the kernel, but extracted into a method which can be overridden.
* Resolves #2520 
* Resolves #2059

Re-Introduce support for /app/startup.php and remove hardcoded environments

---

web/pimcore/static6/js/pimcore/log/admin.js

With this change the search filter form is submitted on ENTER key, too.
E.g. when typing in a search term in "Message". Before the filter could only
be applied by clicking on button "Search".
Ext JS reference: http://docs.sencha.com/extjs/6.0.2/classic/Ext.panel.Panel.html#cfg-defaultButton

Application logger: Apply search form on ENTER key

---

doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/01_HeadLink.md
doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/03_HeadScript.md
doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/default.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_php.yml
pimcore/lib/Pimcore/Templating/Helper/HeadLink.php
pimcore/lib/Pimcore/Templating/Helper/HeadScript.php
pimcore/lib/Pimcore/Templating/Helper/Traits/WebLinksTrait.php
pimcore/lib/Pimcore/Templating/Helper/WebLink.php
pimcore/lib/Pimcore/Templating/PhpEngine.php

Resolves #1534 
Adds support for Symfony's [WebLink Component](https://symfony.com/blog/new-in-symfony-3-3-weblink-component) in both the PHP templating engine and in `HeadLink` and `HeadScript` helpers. The Head* view helpers need extra logic as they need to add processed assets with cache buster support.
Usage in templates:
```php
<link rel="stylesheet" href="<?= $this->webLink()->preload('/static/css/global.css', ['as' => 'style']) ?>">
<?php
// headLink usage
$this->headLink()->enableWebLinks();
$this->headLink()->appendStylesheet('/static/asset.css');
echo $this->headLink();
?>
```

WebLink Support

---

composer.json
doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/README.md
pimcore/lib/Pimcore/Bundle/CoreBundle/DataCollector/PimcoreTargetingDataCollector.php
pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/DebugStopwatchPass.php
pimcore/lib/Pimcore/Bundle/CoreBundle/PimcoreCoreBundle.php
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/profiler.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/targeting.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/targeting/listeners.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/templating_twig.yml
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Profiler/target.svg.twig
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Profiler/targeting_data_collector.html.twig
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/icon/close.svg.twig
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar.css
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar.html.twig
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar.scss
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar_js.html.twig
pimcore/lib/Pimcore/Targeting/Debug/TargetingDataCollector.php
pimcore/lib/Pimcore/Targeting/EventListener/ToolbarListener.php

Implements data debug feature of #2427. Implements a debug tool which works outside the Symfony profiler context (also in `prod`) when a user is logged in. To enable the toolbar, it's necessary to set a `pimcore_targeting_debug` cookie to true (see docs for a bookmarklet).

[TARGETING] Debug Toolbar

---

pimcore/models/DataObject/ClassDefinition/Data/BooleanSelect.php
pimcore/models/DataObject/Classificationstore.php

- Create a key definition of type "booleanSelect" in the classification store
- Assign the keyDefintion to a group
- Assign the classification store to an class attribute
- Create an object of this class
- Assign the above created group in the classification store attribute
- Assign all possible values ​​(No / Yes / Empty) to the booleanSelect attribute
- Correct values are saved
- Display the correct values ​​after reload
- Only saves the "Yes value" correctly
- The values ​​"No" and "Empty" are not stored in the database
- Even after manually setting the correct values ​​in the database (-1 for "No", and NULL for "Empty"), the values ​​are not displayed correctly
As discussed we implemented a workaround for this bug and inserted a TODO for a final fix

Implemented workaround for Bug in ClassificationStore booleanSelect

---

pimcore/lib/Pimcore/Bundle/InstallBundle/Resources/config/config.yml

Hi,
Maybe a little bit special, but i got an error because of undefined Service for `monolog.logger.pimcore` while Check Requirements Route.
best regards
Caused by undefined Service for `monolog.logger.pimcore` while Check Requirements Route.
The Exception:
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "monolog.logger.pimcore". Did you mean one of these: "monolog.logger.event", "monolog.logger.php", "monolog.logger.request", "monolog.logger.cache", "monolog.logger.console"?" at /var/www/html/client.local/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 348 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNot …
```

Workaround for Logging on Install - Checks

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DocumentController.php
pimcore/lib/Pimcore/Document/Renderer/DocumentRenderer.php
pimcore/lib/Pimcore/Event/DocumentEvents.php
pimcore/lib/Pimcore/Templating/Helper/Placeholder/AbstractHelper.php
pimcore/lib/Pimcore/Templating/Helper/Placeholder/ContainerService.php

* Fixes #2098 - SEO Document Editor now uses the `DocumentRenderer`. To make this possible, core view helpers keeping state (e.g. the `headTitle` helper) need a way to start with a fresh context for each rendered document. The newly introduced events `DocumentEvents::RENDERER_PRE_RENDER` and `DocumentEvents::RENDERER_POST_RENDER` are fired by the document renderer and allow components to start with a fresh state. In case of the placeholder helpers, they initialize a new placeholder container for each rendered document. Not doing so would result in a document including placeholder parts of the previously rendered one (e.g. the title containing the title from the previous document and getting longer for each rendered document).
* Fixes #2354 implicitely by using the document renderer
* …

DocumentRenderer/SEO Document Editor Improvements

---

pimcore/models/DataObject/AbstractObject/Dao.php

Added LIMIT to query that should only checks if object has children.
1. Create folder in Data Objects -> Home
2. Create 10 subfolders within folder created in 1.
3. Into each of subfolders generate 100 000 objects
4. Refresh page
5. Try to expand folder created in 1.

Checking if folder has children by searching only one child instead of all children

---

pimcore/models/DataObject/ClassDefinition/Data/Classificationstore.php

If a classificationstore group is deleted, getForWebserviceExport will fail for objects containing values for that group.
BugFix : 
Create a classificationstore group and assigne a key
Save a vlaue for an object for that group.
a websevice reading the object will fail with an error (xxx/webservice/rest/object/id/123)
Bug in Pimcore 5 & Pimcore 4

Classificationstore bug

---

pimcore/models/DataObject/ClassDefinition/Service.php

due to upgraded pimcore 4s (that may deliver ids in the classDefinitions) the generateObjectbrickJson function implemented a getById in order to correctly set the classname for generated json. 
Unfortunately fresh pimcore 5s deliver a real classname in the classDefinitions

fix json generation of objectbricks

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php

It was not possible to specify any "client_params" for Elasticsearch, since the option name differed in two pieces of code:
https://github.com/pimcore/pimcore/blob/b6ad9535cb95bc1ee4ae77fc27a9b1460c36f684/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php#L89-L99

Unified name of the "client_params" option for ElasticSearch indices

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/FilterService/FilterType/NumberRange.php

In case that the keyword {{empty}} is passed a number range filter only has to be applied if there is a precondition.

ECommerce | FilterService | Filter Type| Number Range | upport for {{empty}} placeholder.

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultElasticSearch.php

Compat-fix for Elasticsearch 5.x. The filtered-Query has been deprecated
since 2.0.0-beta1 and has been removed in 5.x.
See:
* https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-filtered-query.html
* https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-filtered-query.html

[ECOMMERCE/INDEXSERVICE/ELASTICSEARCH]: Use bool-Query instead of filtered-Query

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ClassController.php

Custom layouts import and export not working because of routing mismatch.
Import route has been changed from '/import-custom-layout' to '/import-custom-layout-definition'.
Export route has been changed from '/export-custom-layout-definitions' to '/export-custom-layout-definition'.
- Open a custom layout created for any class.
- Click on Export button. 
- This action is broken due to route mismatch.
- Likewise import action also have the same issue.

Issue in custom layouts import/export

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Command/ClassesRebuildCommand.php

This PR implements a delete-classes option flag to delete classes that don't have a class-definition file anymore. If the command is run interactively, the user gets a security question if he is sure about deleting classes and in consequence data as well.
This PR is related to #2591

implement delete-classes option for pimcore:deployment:classes-rebuild

---

pimcore/modules/admin/controllers/AssetController.php

Create 1 asset folder, then another one inside the first one, then try to delete the first one.

pimcore4 Delete Asset Syntax error

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php

Create class with at least one mandatory field and then create some objects. Leave mandatory field empty. Go to the grid and select created class. Choose column named "Published", select "Batch Assignment" option and then mark "Published" checkbox. Objects were published although mandatory field was empty.
If object is published then set ```$omitMandatoryCheck``` flag to ```false```.
There is one change in the class ```Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController``` (line 2307).

Fix for mass publication of objects.

---

doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md

Typo in `setForceImmediateWrite()`.
Changed `setForceImmendiateWrite()` to `setForceImmediateWrite()`.

Typo in setForceImmediateWrite()

---

pimcore/models/DataObject/Data/EncryptedField.php

Removes `: void` as it's not supported in PHP 7.0
phpcs is not failing anymore.
Removes void return type.
phpcs is failing because of the the return type void:
```
FILE: /var/www/consumer-cms/pimcore/models/DataObject/Data/EncryptedField.php
-----------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------
66 | ERROR | void return type is not present in PHP version 7.0 or earlier
82 | ERROR | void return type is not present in PHP version 7.0 or earlier
-----------------------------------------------------------------------------
```

Removes void return in EncryptedField.php

---

pimcore/models/DataObject/Data/EncryptedField.php

Return type void is not supported in php 7.0:
```
phpcs -p -n --standard=PHPCompatibility --exclude=PHPCompatibility.PHP.DefaultTimezoneRequired --ignore="vendor" --extensions=php --runtime-set testVersion $(php -r "echo phpversion();" | cut -d"." -f1,2) .
```
```
pimcore/models/DataObject/Data/EncryptedField.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
66 | ERROR | void return type is not present in PHP version 7.0 or
|       | earlier
82 | ERROR | void return type is not present in PHP version 7.0 or
|       | earlier
----------------------------------------------------------------------
```
- Void return type is not present in PHP version 7.0
- Removed …

Removed return type void because this is not present in PHP 7.0

---

web/pimcore/static6/css/login.css

Adds `max-width: 100%` so image is responsive in login screen.
Image/logo responsive on login screen.
Adds `max-width: 100%` to `#header img`

Makes image responsive on login screen.

---

pimcore/models/DataObject/Classificationstore.php

When calling getLocalizedKeyValue() inherited values were only used if
the store's object had a Localized Fields data component. However, the
classification store itself has the option to be localized.
As a workaround it was possible to add an empty Localized Fields to the
object and the values were inherited as expected. This commit removes
the unnecessary check.

Classification Store: Removed erroneous check for localized fields

---

pimcore/models/Version.php

Trying to create a link across filesystems creates a unhandled warning which let's the whole process fail. Thus suppressing the warning with this change since a failed link is handled by creating a copy.

Prevent warning when trying to create a hardlink

---

web/pimcore/static6/js/pimcore/document/pages/settings.js

Currently when using subsites the Serp preview shows the main domain + path, so this looks very strange (for example): `site.com/site.de/contact` because site.com is the main domain.
Checks for subsites and if the second idPath is equal to `subsites.data.rootId` then change the url to `subsite.data.domain` instead of `window.location.protocol + '//' + window.location.hostname`
This will look like: `site.de/contact` instead of `site.com/site.de/contact`
Strange url's in Serp preview when using subsites.
`web/pimcore/static6/js/pimcore/document/pages/settings.js`
When there are no subsites or the second idPath is not in subsites then it just uses the normal URL: `window.location.protocol + '//' + window.location.hostname`. As it was before.

Fixes serp preview with subdomains

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LogController.php

1. Install PimCore on MariaDB
2. Insert 50 records into application_logs table
3. Go to Application Logger view and set a limit to 25
4. You are not able to switch to page 2.

Fixed logs pagination for some databases

---

pimcore/models/DataObject/ClassDefinition/Layout/Text.php

By passing the layout information, the HTML of the text element is available and can be styled individually, for instance as a message output.

Make layout information available in renderer

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.php

- When images load slow (5 seconds) this script will not wait 5 seconds but 2 seconds and this will result in a javascript error and a white blank image
- Fixes slow images loading still editable with minipaint
- Fixes slow images loading still editable with minipaint
When images loading slowly the minipaint can not edit because of hardcoded timeout

Updated imageEditor wait for images to load

---

doc/User_Documentation/10_Administration_of_Pimcore/01_Data_Protection_and_GDPR.md
pimcore/lib/Pimcore/Bundle/CoreBundle/Command/EmailLogsCleanupCommand.php

Fixes #2649 
Added new command for email sent logs cleanup from db and file system. Required parameter "--older-than-days" to delete logs older than X days.

Add cleanup command for email logs

---

pimcore/lib/Pimcore/Install/Resources/install.sql
pimcore/lib/Pimcore/Version.php
update-scripts/224/postupdate.php
web/pimcore/static6/js/pimcore/document/pages/settings.js

Major Search engines (aka Google) raised their limit for the META-Description. This patch allows Texts up to 383 (255+128) bytes.
See: https://moz.com/blog/googles-longer-snippets
Fixes #2619

Raise document.description to 383 (255+128) chars

---

web/pimcore/static6/js/pimcore/document/pages/settings.js

Fixes check on array. 
It checks on `typeof subSites === 'array'` but should be `object` because typeof would not return array but object.
This fixes the subdomain show correctly instead of maindomain/subsite.
Changes the check on array must be `typeof subSites === 'object'`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#examples

Fixes check on array in settings.js

---

pimcore/models/Document/Tag/Input.php

According to the documentation (https://pimcore.com/docs/5.0.x/Development_Documentation/Documents/Editables/Input.html) the default value of "htmlspecialchars" is true, this does not seem to match the logic of the frontend method.

htmlspecialchars default value

---

pimcore/models/DataObject/Objectbrick/Data/AbstractData.php

The ObjectBrick container[ caches the result](https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/Objectbrick.php#L82) of getItems().
This resets the result to the initial value when a brick gets deleted.

Flush the container of a ObjectBrick on delete of a brick

---

pimcore/lib/helper-functions.php

This gives the same result as the previous 2 implementations without using a insecure source of random data
```
php > echo bin2hex(random_bytes(20));
191193afb3317e37c44df8b24c8fb70164a8d6c7
php > echo hash('sha1', openssl_random_pseudo_bytes(23));
b82291dc5a4de7861f4a494eba5a8c7fb52c6fc4
php > echo hash('sha1', uniqid(mt_rand(), true));
1ece0f9bbd0db3769aa7576438a8fc673f45e9b1
```
- [N/A] Features need to be proper documented in `doc/`
insecure generation of symfony tokens with `uniqid` or `openssl_random_pseudo_bytes`
- use random_bytes to get random data
- use bin2hex instead of sha1 to
a even better implementation would be
`base64_encode(random_bytes(24))`, this matches with the Symfony documentation about …

Secure generateRandomSymfonySecret

---

web/pimcore/static6/js/pimcore/element/abstract.js
web/pimcore/static6/js/pimcore/object/helpers/grid.js
web/pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
web/pimcore/static6/js/pimcore/object/tags/objectsMetadata.js

When objects in the grid view are edited fast enought ExtJs would batch those changes, which the backend is not compliant with, resulting in an error. The batching process has been disabled for grids created with `pimcore.object.helpers.grid`.
Both these tags had the issue that ExtJs's garbage collector would collect the cell editors if working long enought with the tag. Usually when adding / removing / sorting elements the garbage collector would destroy the cell editor leading to a javascript exception and disabling the layout rerender, which could only be fixed by refreshing the backend. By destroying and recreating the cell editors each time a cell is being edited, the issue could be fixed.
By recreating the combobox for the cell editor each time, the preselect of the current value is …

Fixed small Javascript Issues

---

web/pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js

Fixes #1609 
Added "not-editable" check for remove option in context menu of Advance Multihref Data Object field

Add "not editable" check for advance multihref remove context menu

---

web/pimcore/static6/js/pimcore/report/custom/report.js

Fixes #2695 
Added render for html content in custom report text column

Fixed custom report column view breaks with html content

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/NewsletterController.php
web/pimcore/static6/js/pimcore/document/newsletters/addressSourceAdapters/report.js
web/pimcore/static6/js/pimcore/document/newsletters/sendingPanel.js

Fixes #1344
1. Fixed email field load issue when selecting report in Newsletter sending panel.
2. Added a check for empty email address for test send newsletter

Fix newsletter test send fails when address source is empty

---

doc/Development_Documentation/03_Documents/01_Editables/16_Input.md

Twig does not support `;` so we need to remove this.
- Input breaks on `;`
- Removed `;` for Twig

Removed ; in documentation for Twig

---

doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/08_Dynamic_Select_Types.md

Updated the code example to explain how to get the default value back from the fielddefinition.

[DOC] Update documentation example, use the defaultValue

---

pimcore/models/DataObject/ClassDefinition/Data/Block.php

get() on a Block element in a DataObject doesn't return Data\Block but Data\BlockElement, and to be more specific an array of an array of BlockElements.
It's possible to specify that as FooBar[][], which as notation will be accepted by e.g. PhpStorm:
For testing this: unfortunately there's apparantly a bug in PhpStorm since the return hint won't suffice:
I'll file a bug report with PhpStorm as soon as possible.

Fixed PHPDoc for type

---

web/pimcore/static6/js/pimcore/object/folder/search.js

Added double click listener on "ID" & "Path" column to open object on grid.

Add object open listener on ID & Path columns in object grid

---

pimcore/models/DataObject/Data/ExternalImage.php

When you try to see the history of an object that has an external image that was empty the system prints an error message.
When you try to see the history of an object that has an external image that is empty you will get an exception that will be shown on the screen.
Examples:
[demo.pimcore](https://i.imgur.com/7X00YoD.png)
[localhost](https://i.imgur.com/wGNmjoo.png)
Changed the method __toString of the class ExternalImage, to return an empty string '', instead of null.

Fix _toString returning null instead of ''

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/Configuration.php

The cart price modificators are collected twice by PimcoreEcommerceFrameworkExtension::registerCartManagerConfiguration().
This fixes it.
Currently the read configuration results in an array like this:
The modificators are read twice, with their names as key and a numeric value.
This results in them being applied twice to the cart price.
This fix to the configuration definition results in omitting the numeric index:

Bugfix: Cart price modificated twice

---

pimcore/models/DataObject/AbstractObject.php
pimcore/models/DataObject/Fieldcollection/Data/AbstractData.php
pimcore/models/DataObject/Objectbrick.php
pimcore/models/DataObject/Objectbrick/Data/AbstractData.php

Added getters & setters short hand for Objects. 
Shorthand getter
`$value = $object->get($field);`
Shorthand setter
$language is optional. 
`$object->set($field, $value, $language);`

Short hand for getters/setters on Objects 

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/Configuration.php

Fixes [adding a checkout-step](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php#L137) to $checkoutStepOrder[] more than once.

Prevent duplicates in CheckoutStepOrder

---

pimcore/lib/Pimcore/Event/AssetEvents.php
pimcore/lib/Pimcore/Event/DataObjectEvents.php
pimcore/lib/Pimcore/Event/DocumentEvents.php
pimcore/models/Asset.php
pimcore/models/DataObject/AbstractObject.php
pimcore/models/Document.php

Added events for failure handling:
- DataObjectEvents::POST_ADD_FAILURE
- DataObjectEvents::POST_UPDATE_FAILURE
- DataObjectEvents::POST_DELETE_FAILURE
- AssetEvents::POST_ADD_FAILURE
- AssetEvents::POST_UPDATE_FAILURE
- AssetEvents::POST_DELETE_FAILURE
- DocumentEvents::POST_ADD_FAILURE
- DocumentEvents::POST_UPDATE_FAILURE
- DocumentEvents::POST_DELETE_FAILURE

Added failed add/save/delete events

---

install-profiles/demo-basic-twig/src/AppBundle/Controller/BlogController.php
install-profiles/demo-basic/src/AppBundle/Controller/BlogController.php

Now the blog can have any id and not the only one used in the example / demo.
Blog can have generic ids
Changed object_ view id to classId

Updated query for more generic approach

---

pimcore/models/Asset/Image/Thumbnail.php

Return correct filesystem path if no config was provided.
The getRealFullPath() method doesn't return the Document_Root

Bugfix - Thumnail - return correct file system path if no config is passed

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md

`try_files` directive should use `$uri` instead of `$request_uri` since the latter is not urldecoded.

[docs] fix nginx thumbnail rate limiting

---

pimcore/models/Document/Tag/Link.php

When I add an anchor to a ‚link‘ editable the double quotes (") should be urlencoded, so that a link does not break at the first double quote.
For some JS links you have, e.g. www.domain.de/page#{"selectedFilters"%3A[]}.
This is a Json String.
Double quotes in an anchor of a ‚link‘ editable will break the link.
Add an anchor to a ‚link‘ editable with double quotes like ‚#{„selectedFilters"%3A[]}‘.
Check the link which is rendered in the frontend.
You can check this with the element ‚Icon teaser‘ link on the following demo page.
https://demo-basic.pimcore.org/en/basic-examples/content-page
You will see the rendered link is https://demo-basic.pimcore.org/en/basic-examples/html5-video#{

urlencode double quotes (") for anchors in link editable

---

web/pimcore/static6/js/pimcore/treenodelocator.js

1. Create data object with key "aa" in folder x. Copy and paste it until tree items in folder x paginate and the last object on page 1 has a key "aa_*". 
1. Now create object with key "a_". Object gets opened
1. Go to page 1 in tree of folder x
1. click "show in tree" in object "a_"
1. Object does not get found in tree

Correctly determine pagination direction when using "show in tree" function

---

pimcore/lib/Pimcore/Image/Adapter/Imagick.php

If the path (folder or filename) has a colon (:), Imagick couldn't load the image.
Reason is: Imagick use the colon to specify the type of the image.
https://stackoverflow.com/questions/45878100/handle-colon-in-filename-with-imagemagick

Fix: Imagick couldn't load images with colon in path

---

web/pimcore/static6/js/pimcore/document/printabstract.js
web/pimcore/static6/js/pimcore/object/object.js

Setting ID, Options before preOpen Event, otherwise the event has no sense for objects. Also did it for print documents.

set options and id before firing preOpen Event

---

pimcore/models/DataObject/ClassDefinition/Data/QuantityValue.php

An error exists when you're exporting into csv file any field of type QuantityValue which is located under classification store. This PR resolves it.
Add classification store field with QuantityValue key to class. Try to export objects into csv file. You should get "Internal Server Error".
This PR fixes QuantityValue::getForCsvExport() method.

Fix for CSV export.

---

pimcore/models/Asset/Image/Thumbnail/Processor.php

resolves #2789
Replaced absolute path of svg file to render image when thumbnail type is "print"

Fixed web2print with svg not working

---

pimcore/models/DataObject/Localizedfield/Dao.php
update-scripts/236/postupdate.php

fixes #2110 
we always treat null and empty as indicator for using fallback - so this also has to be considered in localized views. 
TODO: resave of classes necessary.

Considers fallback languages in combination with empty values

---

web/pimcore/static6/js/pimcore/settings/translationEditor.js

translationkeys should never wrappet in a <p> tag by default.

Remove initial <p> on Translation Key WYSIWYG

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/OrderManager.php

Added phpDoc for getOrderParentFolder() to avoid false assumption of returning a static, as defined in AbstractObject::getById()

Added phpDoc

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/default.yml

- Go to extensions
- Install EcommerceFrameworkBundle
- Error message appears in popup
Unknown database type bit requested, Doctrine\DBAL\Platforms\MysqlPlatform may not support it.
Added the required mapping type as found [here](https://stackoverflow.com/questions/9744629/doctrine2-workaround-for-mapping-mysql-bit-data-type) (not marked as answer).
- Pimcore Version: 5.2.2
- Symfony Version: 3.4.6

Additional mapping type for doctrine

---

web/pimcore/static6/js/pimcore/asset/metadata.js

1. Create predefined metadata with field foo
1. Add metadata bar with Asset::addMetadata('bar', '', $data = '', null) // last parameter is language
1. Open asset with metadata bar in Pimcore backend, go to metadata tab and click "Add predefined definitions"
1. JS error occurs because in https://github.com/pimcore/pimcore/blob/9d71c0812fd3256a6a670d04597d326f85ff2717/web/pimcore/static6/js/pimcore/asset/metadata.js#L535 and https://github.com/pimcore/pimcore/blob/9d71c0812fd3256a6a670d04597d326f85ff2717/web/pimcore/static6/js/pimcore/asset/metadata.js#L397 toLowerCase() is executed on null.

Prevent JS error when adding predefined metadata 

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Asset/showVersionImage.html.php

Assets Metadata will be shown in the version views ( Image Assets only for now).

Integration of Pimcore asset metadata in the versions view of an Image 

---

pimcore/lib/Pimcore/File.php

The mkdir Method creates directories and files with wrong permissions.
1. Upload asset to some folder
2. Pimcore creates thumbnails in web/var/tmp
The folder has no group rights
3. After bugfix the rights are correct
See also: https://stackoverflow.com/questions/7878784/php-mkdir-permissions

Fixed wrong file creation mode

---

pimcore/lib/Pimcore/Tool/Glossary/Processor.php

Right now glossary terms skip self-linking on matching documents, which doesn't work if using glossary functionality on dynamic content (no underlying document).

Skip linking glossary terms that match custom routes

---

pimcore/models/DataObject/Service.php

The list used in this method did not take variants into account when checking if a key is already is use. I've added the variant type to the list as well.

Allow usage of the DataObject/Service::getUniqueKey method variants

---

pimcore/models/DataObject/AbstractObject.php

We're setting the sort order in Pimcore, we should retrieve getChildren() listing by the same order.

Retrieve getChildren() listing by index or key sort order

---

composer.json
pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
pimcore/lib/Pimcore/Google/Api.php

fixes #1209
- Google api client library updated to latest version 2.x
- Google API private key should be json now placed as /var/config/google-api-private-key.json
`Note: P12s are deprecated in favor of service account JSON, which can be generated in the Credentials section of Google Developer Console`

Google api client updated to latest version 2

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php

Branding is extended to lostpassword page according to login page
In 5.1.1 Backend branding was added as a new feature so the login page can be customized but the lostpassword page still looked the same, even with activated branding.
https://github.com/pimcore/pimcore/issues/1793

Added customization to lostpassword template

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php

This patch will assign the `$customerName` to the `customerName` key in the authorized data array instead of adding a random boolean value to the key `0`.

Fix a typo in the OGone payment provider

---

web/pimcore/static6/js/pimcore/overrides.js

Resolves #2739
Date component was breaking view layout randomly. Whenever date component was being used in scrollable container, screen was getting off randomly after clicking on date picker. Now date component works fine and displays date picker at correct position.

Date component breaks view layout randomly fix

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md

Once you include fastcgi_params and later fastcgi.conf. Shouldn't this include the same file? Or how are they different?

Include fastcgi_params vs. include fastcgi.conf

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/DefaultValue.php
pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/Href.php
pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/Objects.php
web/pimcore/static6/js/pimcore/object/helpers/grid.js
web/pimcore/static6/js/pimcore/object/helpers/gridConfigDialog.js

This pull requests fixes some minor issues with the object grid. 
First of all the fieldnames are not displayed in brackets in the object grid anymore to keep it compact. They are still displayed in the configuration panel, and for all columns except system columns. Previously columns that were displayed due to configuration in the class definition itself, did not contain the fieldname either. Consistency.
Second inherited values are used in the object grid for operators as well which resolves #2873.
Third the widths for columns could be saved in configurations. Operator columns were ignored and always returned to 200 pixels. They are now saved as well.

Object Grid Improvements

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php

It seems like this line was copied from below. As it results in `IStatus::STATUS_CANCELLED` in either case, we can get rid of the condition.
The condition would never evaluate to `true` anyway, because the `$response['paymentState']` is already checked above and thus can never contain the corresponding value.
---
**Note**: I'm not entirely sure this is the correct fix. Maybe we shouldn't remove the condition but check `$response['paymentState']` for `PENDING` instead and set the status to `IStatus::STATUS_PENDING` in this case?

[Ecommerce] WirecardSeamless payment provider - updated setting payment state to PENDING

---

pimcore/lib/Pimcore/Controller/Traits/TemplateControllerTrait.php

`$autoRender` is already a boolean as per the method signature. There's no need to cast it again.

Remove superfluous cast to boolean

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php

How to reproduce an issue:
`objecttype` `variant` is ignored during `Batch edit all` objects in the grid's column

fix: added variant object type to BatchJobs

---

pimcore/lib/Pimcore/Http/Request/Resolver/TemplateVarsResolver.php

The parameters `get_class($provider)` and `gettype($vars)` were after the closing parenthesis of the `sprintf()` and thus were applied as the parameters `$code` and `$previous` of the `RuntimeException`, which is obviously wrong.

Fix position of closing parenthesis

---

pimcore/lib/Pimcore/Bundle/CoreBundle/Command/ThumbnailsImageCommand.php

Instead of this:
get this:
gets a better feeling of how the total progress is and it also calculates a estimated time of finish.

use console progress to get a better status of the progress of thumbnail generation

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php
pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
web/pimcore/static6/js/pimcore/object/object.js

- Use the LinkGenerator for the preview-tab if no specific 'Preview Url' is set.
- The 'preview-tab' and the 'open-button' now use the same logik

refactor preview for objects

---

web/pimcore/static6/js/pimcore/object/tags/textarea.js

Set the name property for textareas to allow easier dom access. Input fields already have it, and this makes it easy to access their content from a custom handler script.
Initially discussed with Christian Fasching

Add name property to object textareas

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php

Update Init Payment URL from https://www.qenta.com/qpay/init.php to https://checkout.wirecard.com/page/init.php. 
For more details please see https://guides.wirecard.at/wcp:integration#starting_the_payment_process.
According to Wirecard support, the new URL is fully backward compatible, but it's not sure how long the old URL will be still supported.

[Ecommerce] Update Wirecard Init Payment URL

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Security/Guard/AdminAuthenticator.php

When you are directly going to /admin/login/login you get a 500 error.
Type error: Argument 2 passed to Pimcore\Event\Admin\Login\LoginCredentialsEvent::__construct() must be of the type array,
null given,
called in /phpapp/pimcore/lib/Pimcore/Bundle/AdminBundle/Security/Guard/AdminAuthenticator.php on line 157
The desired result should be to get the login form again when not logged
in, or the admin interface when you were already logged in.
There was already a check to verify if there was a username passed, but
it contained an always invalid condition so the exception was never
triggered.
if (!null === $username = $request->get('username')) { <-- never true
throw new AuthenticationException('Missing username');
}
If the $username check is changed to throw an exception when no username
is …

avoid 500 when doing GET on /admin/login/login

---

pimcore/models/DataObject/ClassDefinition/Helper/Dao.php
update-scripts/277/postupdate.php

When performing mass actions on the grid there is a problem with the "save" button when adding many elements, eg to a multihref
Add autoscroll to Window in gridTabAbstract

Fixes the problem with the escaping "save" button

---

web/pimcore/static6/js/pimcore/object/tree.js

Resolves #2772
Keys will show up in Admin Translations for each class, after displaying dialog for the first time:
If it's translated it will replace object add dialog (after ui reload):

Added option to customize object add dialog box 

---

pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultElasticSearch.php

Filter MultiSelectRelation (`Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\ElasticSearch\MultiSelectRelation`) doesn't work in admin panel with elasticsearch configuration. 
It doesn't show any value, instead of that there's msg like this in ajax response:
```
"{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_NULL in [from].","line":1,"col":34}],"type":"parsing_exception","reason":"Unknown key for a VALUE_NULL in [from].","line":1,"col":34},"status":400}"
```
It sends request to es with `from = null` instead of `from = 0`.

Fix "Unknown key for a VALUE_NULL in [from]"

---

pimcore/models/DataObject/ClassDefinition/Data.php

A PhpDoc with `Set ...` was created for getters.
This also fixes the indentation of the return statement for encrypted fields.

Fix generated PhpDoc of ObjectBricks

---

web/pimcore/static6/js/pimcore/object/tags/geobounds.js
web/pimcore/static6/js/pimcore/object/tags/geopolygon.js

Resolves #1047 
For geopolygon and geobounds datatypes search functionality, default zoom level has been set to 15. Also delete tool "Clear All" option will clear all data from map now, only if a layer has been created on map.

Replace Google Maps API by Leaflet & OSM Search functionality and delete tool fix

---

composer.json

Use a more open version constraint for ocramius/package-versions. This allows to use newer versions of the package and thus conflict in less version conflicts.

use more open constraint for ocramius/package-versions

---

web/pimcore/static6/js/pimcore/helpers.js

Video Edit UI is not consistent with brick editmode UI:
With this PR, it looks like this, so button ordering is the same:

fix button ordering for video editmode panel

---

web/pimcore/static6/js/pimcore/layout/toolbar.js
web/pimcore/static6/js/pimcore/log/admin.js
web/pimcore/static6/js/pimcore/object/object.js

Fix for multiple tab loading of Application Logger in admin view
Resolves #

Fix Application logger multiple tab loading

---

pimcore/models/DataObject/ClassDefinition/Data/Classificationstore.php

Reproduce:
- Create classification store
- Create classification store as attribute in class and select option "localized"
- Enter data
- REST call ([your.domain] / webservice / rest / object / id / ...)
- Result for all languages in JSON: `value: null`
Fix for PR #2875 in file Pimcore\Model\DataObject\ClassDefinition\Data\Classificationstore.php as proposed in https://github.com/pimcore/pimcore/pull/2875#issuecomment-393080149
Sorry for the delayed response!

Fix: getDataFromObjectParam for localized CS-Data

---

pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LogController.php

logged exceptions by the ApplicationLogger which are wrapped inside a `<pre>` tag were displayed as `text/plain`
Resolves #3133

[Application Logger] shows html piece as "text/plain"

---

pimcore/lib/Pimcore/Translation/Translator.php

Change method visibility of private method getFromCatalogue(..) and private field $caseInsensitive to `protected` for decorating the `Translator` service.

Visibilty of getFromCatalogue(..) and $caseInsesitive

---

pimcore/models/DataObject/Classificationstore/KeyConfig/Listing/Dao.php

Changed "is 0" to "= 0". Added parenthesis because of AND operator having higher precedence

Fixed syntax error in classificationstore

---

app/config/pimcore/customviews.example.php
web/pimcore/static6/js/pimcore/document/tree.js

Allow to hide single items in context menu like "addEmail". Currently it's only working by set "add" for all document types.

Feature / allow hide single items in context menu

---

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
bundles/CoreBundle/Resources/translations/en.extended.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_FilterDefinition_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolCustomProduct_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOfferItem_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOffer_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrderItem_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopTaxClass_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherSeries_export.json
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherToken_export.json
doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/01_Inheritance.md
doc/Development_Documentation/20_Extending_Pimcore/07_Parent_Class_for_Objects.md
models/DataObject/ClassDefinition.php
models/DataObject/ClassDefinition/Service.php
models/Webservice/Data/ClassDefinition.php
tests/_support/Resources/objects/class-allfields.json
tests/_support/Resources/objects/class-import.json
tests/_support/Resources/objects/classificationstore.json
tests/_support/Resources/objects/inheritance.json

Hello,
This PR add parent class and traits for listing data object model.
It resolve https://github.com/pimcore/pimcore/issues/1618 (1 year ago i know, long time to provide this PR ;-) ). But as we are going to Pimcore 5.4 i think it is good to release this feature in the same time.
It should not introduce any BC break and i tested import/export class too.
Documentation has been updated considering this feature will be available in Pimcore 5.4.0.
Thanks.

Add parent class and traits for listing data object model

---

lib/Cache/Core/CoreHandler.php
lib/Cache/Core/CoreHandlerInterface.php

During a CLI mass import we want to be able to add items to the cache. Currently this fails if there are more than 50 objects / assets related in the currently imported object (hard coded limit in CoreHandler). This PR adds a setter for this field.

Add setter for maxWriteToCacheItems

---

bundles/InstallBundle/Command/InstallCommand.php

Hello,
This pull request allow command-line install without password (for instance for dev env, automation/qa, etc.)
It resolves https://github.com/pimcore/pimcore/issues/2975
There is no way to detect if $value is empty or not set (because option 'mysql-password' is required in any case), so the if condition has been modified to handle this special case by testing directly the option name (even if i found that it is not a very proper solution).
Maybe better solution would have been to add a new option parameter, like 'allow-empty':
```
'mysql-password'    => [
'description'  => 'MySQL password',
'mode'         => InputOption::VALUE_REQUIRED,
'insecure'     => true,
'hidden-input' => true,
'allow-empty' => true,
'group'        => 'db_credentials',
],
```
And check in the if condition the …

Allow no mysql password on cli install

---

models/DataObject/ClassDefinition/Data/Multiselect.php

Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect::checkValidity(...) method throws \Exception while other Pimcore\Model\DataObject\ClassDefinition\Data throws ValidationException. It is inconsistent and, moreover, caused errors in our special validator.
Resolves #

in checkValidity changed exception type into ValidationException

---

bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
bundles/EcommerceFrameworkBundle/Type/Decimal.php
tests/ecommerce/Type/DecimalTest.php

If the amount gets passes with a comma "," as separation symbol for floating-point numbers in the `initPayment` call, the amount will be returned in the same format, which results in an Exception in the `Decimal::create(..)` call in the `handleResponse` function.
Solution: `Decimal::create(..)`  also accepts "," as separation symbol

Support comma as separation symbol for floating-point numbers

---

models/DataObject/ClassDefinition.php

Resolves #3152
Bug can be reproduced with the following command:
```
<?php
namespace AppBundle\Command;
use Pimcore\Console\AbstractCommand;
use Pimcore\Model\DataObject\ClassDefinition;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
class TestCommand extends AbstractCommand
{
protected function configure()
{
$this->setName('test');
}
protected function execute(InputInterface $input, OutputInterface $output)
{
$class = new ClassDefinition();
$class->setName('Test');
$class->save();
}
}
```
Command:
`php bin/console test` 
Output:
`09:53:12 ERROR     [pimcore] Exception: Class definition with name  or ID 9 does not exist in /var/www/blankse/pimcore-5.4.2/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:193`

Fix #3152: When creating a new class definition an error is logged

---

models/Element/Service.php

Bug can be reproduced with the following command:
```
<?php
namespace AppBundle\Command;
use Pimcore\Console\AbstractCommand;
use Pimcore\Model\Asset\Service;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
class TestCommand extends AbstractCommand
{
protected function configure()
{
$this->setName('test');
}
protected function execute(InputInterface $input, OutputInterface $output)
{
$folder = Service::createFolderByPath('/Test/Test2');
}
}
```
Command:
`php bin/console test`
Output:
```
13:44:05 WARNING   [pimcore] asset with path: /Test/Test2 doesn't exist [] []
13:44:07 WARNING   [pimcore] asset with path: /Test doesn't exist [] []
13:44:07 WARNING   [pimcore] asset with path: /Test/Test2 doesn't exist [] []
```

Fix: When creating folder by path multiple warnings are logged

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multihrefMetadata.js

When you have a multihref with metadata field which has a select or multiselect metadata column its values should be translated.
Reproduce:
1. Create multihref with metadata field in a data object class
1. Add meta column "test" of type "select" and add some options
1. Add admin translations with key=option key
1. go to an object and set value -> admin translations are not used
With this PR admin translations get used to display selected option.

Use admin translations for rendering meta column value

---

bundles/CoreBundle/EventListener/TemplateControllerListener.php

* Move the default AppBundle to an own namespace (e.g. AcmeAppBundle) by setting PIMCORE_SYMFONY_DEFAULT_BUNDLE
* Create a document with a default action
* An error will be thrown in the "Edit" tab since Symfony can not find the template

[Bugfix] Use Pimcore constant instead of hard-coded value

---

models/DataObject/Localizedfield.php

Getter of localized fields should return null on newly created field collection objects
Error: Call to a member function getClass() on null
1. Create field collection named `XYZ` with a localized field `test`
1. Anywhere in the code write:
```php
$fieldCollectionItem = new \Pimcore\Model\DataObject\Fieldcollection\Data\XYZ();
$fieldCollectionItem->getTest('en');
```
It happens because the field collection does not know which object it belongs to and nevertheless tries to get an inherited value.

[Bugfix] Getting value of localized field of newly created field collection should return null

---

pimcore/modules/admin/controllers/PortalController.php

Move the condition for the Document/Asset portlet to the list statement (otherwise documents... appear which are not editable).
It should also be fixed in the pimcore 5 version but there we may also check if the user is still allowed to edit the document. Otherwise the User gets an error each time pimcore is opened because the document is in the "remembered Tabs" - and the user is not allowed to view the document.

Portlet Bugfix - move condition to list statement

---

bundles/CoreBundle/Resources/migrations/Version20180830113528.php
bundles/CoreBundle/Resources/migrations/Version20180830122128.php
bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json

- fixes #2248 
- makes sure that payment is processed even if order is already committed - in order to have logs
- sets index or OnlineShopOrder:cartId

Minor payment refactorings

---

models/Document/Tag/Video.php

* add `mute` and `muted` (depending on the video source) to valid video tag parameter for embedded videos
* add `background` to the valid dailymotion parameters. This hides the control panel and automatically mutes the video  
Google Chrome blocks autoplay of video with audio, while muted autoplay is always allowed. [Source](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)
```php
<?= $this->video('background-video', [
"youtube" => ['mute' => true, 'autoplay' => true],
"vimeo" => ['autoplay' => true, 'background' => true, 'muted' => true],
"dailymotion" => ['autoplay' => true, 'mute' => true]
]) ?>
````

Add mute option to embedded video elements.

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md

When using the [suggested Nginx configuration](https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html), requesting files ending with (regex)
\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)
results in a `404` error. This happens for both `http` and `webdav` protocols:
* `http://pimcore.mysite.localhost/admin/asset/webdav/pimcore-logo-2013-grau.png`
* `webdav://pimcore.mysite.localhost/admin/asset/webdav/pimcore-logo-2013-grau.png`
When requesting the http URI (with a web browser or with curl), the returned page indicates that the 404 was caused by Nginx.
The prefix
/admin/asset/webdav(?=/)
is trimmed from `$uri` for the `try_files` check.
I've verified that …

fix WebDAV of the suggested Nginx config

---

bundles/CoreBundle/Command/ClassesRebuildCommand.php

Since 5.4 class definition ids may be manually specified (alphanumeric) rather than being auto-generated (integer). In the ClassesRebuildCommand the id is casted to integer when deleting class definitions, which results in alphanumeric ids being set to "0".
* Create a class with a manually specified identifier, e.g. "foo"
* Run `bin/console pimcore:deployment:classes-rebuild` with `--delete-classes` 
* See errors similar to this:
`[Doctrine\DBAL\Driver\PDOException (42S02)]
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'pimcore.object_query_0'`

[Bugfix] Class definition ids may now be alphanumeric

---

doc/Development_Documentation/10_E-Commerce_Framework/03_Installation.md

Added word "not" in the sentence:
That is because the framework does NOT limit you on specific classes or class structures. Literally every class can act as a product or product framework does not limit you on specific classes or class structures.

Missing word "not"

---

doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md

Update the location of the urls, they where pointing to the old location.

[DOCS] Update urls in documentation pointing to the wrong location 

---

bundles/AdminBundle/Resources/public/js/pimcore/log/admin.js

Messages with markup (e.g. <?xml version='1.0' encoding='UTF-8' standalone='no' ?>)
break the entire listing and other prepared content can lead to XSS.

Application Logger: Properly escape log message

---

lib/DataObject/Import/Service.php

Resolves #
The problem arises if one uses alphanumeric ID's for the new DataObjects, and tries to import some of said DataObject through CSV import.
This will result the following error: 
Message: An exception occurred while executing 'select distinct c.id from importconfigs c, importconfig_shares s where  c.id = s.importConfigId and s.sharedWithUserId IN (2) and c.classId = 93d3afe3 UNION distinct select c2.id from importconfigs c2 where shareGlobally = 1 and c2.classId = '93d3afe3'':
SQLSTATE[42S22]: Column not found: 1054 Unknown column '93d1afe3' in 'where clause'
Where 93d3afe3 is the ID of the ObjectData class.

Fix CSV import with alphanumeric ID's

---

docs/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md

Provides sample configuration for WYSIWYG/CKEditor to customize what is filtered out when using Paste with Word

Supply sample configuration for WYSIWYG/CKEditor for filtering out HTML tags in Paste with Word

---

bundles/AdminBundle/Controller/Reports/CustomReportController.php

When you select to include the headers in a custom report, they are exported as CSV (,), while the rest of the report is semi-colon separated.

Custom Reports: Fixed headers exporting CSV ","

---

bundles/AdminBundle/Controller/Admin/DataObjectController.php

Fixed localized fields filtering on layout change via event: https://pimcore.com/docs/5.x/Development_Documentation/Best_Practice/Showing_Custom_Layouts_based_on_Object_Data.html
1. Create custom layout
2. Restrict localized fields via workspace settings
3. Define event like here described: https://pimcore.com/docs/5.x/Development_Documentation/Best_Practice/Showing_Custom_Layouts_based_on_Object_Data.html
4. Change layout programmatically
5. On the first open of object you will see all possible languages in localized fields
6. After reload of object they are restricted to your workspace configuration
The bug appears because there is no localized fields filtering, if layout is changed via event.

Fixed localized fields filtering on custom layout change.

---

bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php

It's not a good idea to delete items from the elastic search based on the osParentId if they are added based on the virtual product ID. Depending on the use cases this could be a big difference and will result in undeleted items in the elasticsearch index.

[ecommerce][index service] Elasticsearch delete from index bugfix in combination with virtual product ids

---

lib/DataObject/Import/ColumnConfig/Value/DefaultValue.php

[CSV import] always pass the "target" to Field Definitions' `getFromCsvImport` method

---

models/Redirect.php

Resolves #
Redirects cache being blown for already delt with entries.
When running the maintenance job there query that is being used does not consider if the redirect is already disabled. Disabled redirects are disabled again causing the cache to be invalidated and affecting the performance for the web site.
To reproduce:
- Create a redirect with expiration date set to yesterday.
- Open a page on the web site.
- Run the Pimcore maintenance job.
=> Redirect is disabled
=> Cache is gone
- Reload the page (make sure it's not coming from cache, add a query parameter or something).
=> Redirects are saved to cache again.
- Run maintenance job again
=> Redirect is disabled again even though its already disabled
=> BAD Cache is gone
- Reload the page again (make sure it's not coming from cache, …

Do not disable already disabled redirects

---

models/DataObject/ClassDefinition/Data/QuantityValue.php

A check is needed whether the unit actually exists otherwise a problem will result if units get deleted as the unit ID might be still in the database.

QuantityValue webservice bugfix

---

doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/07_Piwik.md

The default configuration of Matomo prevents the inclusion via IFrame.
See: https://matomo.org/faq/troubleshooting/faq_147/

[DOCS] Additional config info for Matomo iframe

---

doc/Development_Documentation/26_Best_Practice/04_Showing_Custom_Layouts_based_on_Object_Data.md

I found an edge case using the example provided where if you have a custom layout containing an additional layout item, such as a text box, and then you attach a custom renderer to that text box, this example passes null through as the object (and context).
Adding the $object parameter in here catches this edge case :)

Updated best practice for custom layouts

---

lib/Config.php

When you have a invalid web2print or report config, pimcore fails. This PR makes Pimcore fail silently. 
BTW: Configs should be in symfony, but this is just a temporary fix to make deployments with shared empty files easier.

let Pimcore configs silently fail when invalid (eg empty or invalid PHP)

---

models/Workflow.php

Prevent Warning: array_keys() expects parameter 1 to be array, null given

Prevent warning array_keys() expects parameter 1 to be array, null given

---

models/DataObject/Localizedfield/Dao.php

The Exception "passing it on ..." is not good, it hides the problem
Resolves #
Showing meaningless message while trying to save an object
if you remove one column from the localized fields table and tries to save instead of saying that the column does not exist it says "passing it on..." but does not passes anything.

throwing up the error instead of hiding it

---

bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js

Otherwise the object just reloads and you have no clue that it actually failed.

display version publish errors to the user

---

doc/Development_Documentation/18_Tools_and_Features/35_GDPR_Data_Extractor.md

Documentation: typo "includeRelations" vs "includedRelations"

Documentation: typo "includeRelations" vs "includedRelations"

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md

Resolves #3386
Follow-up of #3291
The solution is to disable the `location` section for webdav entirely, to avoid any further issues with SabreDAV.

fix the suggested Nginx config: don't `try_files` on SabreDAV URLs

---

models/Asset/WebDAV/File.php

* install and set up pimcore
* mount `http://pimcore.test/admin/asset/webdav/` to `/mnt/` using `mount.davfs` (https://savannah.nongnu.org/projects/davfs2, https://en.wikipedia.org/wiki/Davfs2)
* `echo foo > /mnt/testfile`
the `testfile` is created, but it will stay empty. `foo` will never be put into the file. davfs2 will move the `testfile` containing `foo` into a local `lost+found` directory, right after the failed http `PUT`.
The SabreDAV server creates the file (0 Bytes in size) because davfs2 **locks** ( http `LOCK`) the not-yet-existing file. Every few seconds, davfs2 pushes its cache to the server. The `PUT` request contains an `If-Match` header with a hash in double-quotes, like this: `If-Match: "d41d8cd..."`. SabreDAV will respond `HTTP/1.1 412 Precondition failed` with the …

[fix] SabreDAV: surround ETag by double-quotes

---

models/User.php

Resolves #3390
Default keyboard shortcut for "Glossary" updated from **ALT+G** to **ALT+Shift+G**

Fix keyboard shortcuts

---

models/DataObject/ClassDefinition/Data/ObjectsMetadata.php

In the older version in class definition for field `objectsMetadata` in attribute `allowedClassId` was saved class id instead of class name.
Tested on pimcore 5.23.

[fix] Get class definition in ObjectsMetadata

---

models/Schedule/Maintenance/Job.php

This pull request makes it possible to create maintenance jobs with a different expire timestamp.
Default expire timestamp: 86400

Expire value should be a variable when creating maintenance jobs.

---

bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
bundles/CoreBundle/PimcoreCoreBundle.php
bundles/CoreBundle/Resources/config/services_symfony_workflow.yml
bundles/CoreBundle/Resources/config/services_workflow.yml

this causes issues with other services that already extend it or use it -> for example if you manually define a symfony workflow -> registering that again will cause to lose all of its configuration and therefore fail. even if it is configured properly.
this is quite urgent and has to be merged before 5.5, since this breaks default symfony behaviour in workflows.

[Workflow] Don't overwrite symfony registered services

---

lib/Tool/Mime.php

Some WebDAV clients create 0B files (zero byte files), e.g. as a mechanism for locking. 
For details, see http://sabre.io/dav/0bytes/.
This PR ensures that 0B files will always have type `application/octet-stream`.
Prior to this fix, when a file was detected e.g. as an image, it would become an `Image`, and tasks like dimension calculation (width/height) or thumbnail creation would fail.
If I push a 0B file to `dir/img.jpg`, I'll get the following error in the log:
```
[2018-10-11 10:16:41] pimcore.ERROR: ImagickException: insufficient image data in file `/var/www/pimcore/var/tmp/asset-temporary/asset_65_f1683f4c46a775391018314af9e99be4__img.jpg' @ error/jpeg.c/ReadJPEGImage/1039 in /var/www/pimcore/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:117
Stack trace:
#0 …
```

[WebDAV fix] Mime detection: check for 0Byte files

---

models/Asset/Image.php

This is a quick fix for an issue I discovered along with #3455.
If image dimension calculation fails (in #3455 it's due to a 0Byte file), `imageDimensionsCalculated` should be set `false`. (this is a fixup of 37caf9c.)
I removed a comment. It's obsolete. It was introduced in 37caf9c and referred to the `$this->getFileSize()` check, which was removed (shortly after) in 50dec26.

[minor] fixup Image::update()

---

models/Asset/Dao.php

The main improvement of this pull request is that now the `hasChildren()` method is faster because of the added `LIMIT 1` especially for folders with many assets in it. 
Additionally I've added some PHP doc fixes.

[assets] getChildren() performance improvement and php doc fixes for asset DAO

---

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/01_Update_from_5.x_to_5.4_or_above.md

Fix url of migration script in documentation. The previous url linked to the snippet's html version

[Docs] Fix url of migration script

---

bundles/InstallBundle/Resources/install.sql

And also make the schema end up like one would have migrated.
When you migrate from 5.4.x to 5.5.0 you get additional columns which are
described in doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/05_Workflow_Management.md
in element_workflow_state. The install.sql script does not properly
reflect the requirement of workflow which should end up as NOT NULL.
Signed-off-by: BlackEagle <ike.devolder@gmail.com>
Resolves #
This makes sure the upgraded schema and the clean install schema are more alike

fix sql error in element_workflow_state

---

bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php

If a variant is moved from one parent to another one the original document needs to be deleted as otherwise the variant will be stored twice in the index.
A proposed solution is added to this pull request.

[ecommmerce][elasticsearch] delete moved variants from old parents

---

bundles/CoreBundle/Command/ThumbnailsImageCommand.php

Only generate system thumbnails if "--system" option is provided an no thumbnails are passed to generate
e.g: php www/bin/console pimcore:thumbnails:image --system

System thumbnail generation

---

bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
bundles/CoreBundle/Resources/translations/en.json
models/Document/Service.php

Resolves #3231
Added new feature "Paste as new language variant"
---------------------------------------------------------------------
Copy Element
Select Paste/Paste(inheritance) -> Paste as new language variant
Select Language &  Apply
This option creates a new copy document with selected language & interlink with source document.

Documents paste as language variant

---

lib/DataObject/GridColumnConfig/Operator/WorkflowState.php
lib/Workflow/Place/StatusInfo.php

This pull request outputs the workflow state as html in the object grid and as simple text-list in the CSV export.
(see #3538)

workflow state grid operator: do not output html content in csv export

---

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md

Package python-uno is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
However the following packages replace it: libreoffice-script-provider-python
Resolves #

Package python-uno is referred to by another package

---

lib/Image/Adapter.php

If a focal point is set too close to the right edge or the  bottom of an image, the cover thumbnail transformation will crop the  image too much. The resulting thumbnail will be either narrower or  shorter than it's supposed to be. This fix puts a ceiling on the cropX  and cropY values so that cropX won't be too close to the right edge, and  cropY won't be too close to the bottom.

Fix cover transformation when focal point too close to edge

---

bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
lib/Event/AdminEvents.php

This pull requests adds basically the same event as **\Pimcore\Event\AdminEvents::CLASS_OBJECTBRICK_LIST_PRE_SEND_DATA** 
just for Fieldcollections
Adapted both usages from objectbrickbricks in 
- \Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController::objectbrickListAction:1315
- \Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController::objectbrickTreeAction:1245

add preSendData event for fieldcollectionList

---

models/DataObject/ClassDefinition/Data/Localizedfields.php

So, it will not throw the notice below.
```Notice: Undefined variable: validationExceptions in /data/projects/kh-pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php on line 1084```
Resolves #
A notice warning when we are checking for validation exceptions on localized fields.
You can reproduce it by creating a script to import an object that has some localized fields and those fields don't have any errors.

Fixed the checking for validation exceptions

---

models/DataObject/AbstractObject.php

When a get function is called with null or empty param it won't jump into infinite recursion.
Currently in works like:
```
public function get($fieldName, $language = null) // $fieldName = null $language = null
{
return $this->{'get'.ucfirst($fieldName)}($language); // is transformed into $this->get($language) - infinite recursion when $language is null;
}

Fix infinite recursion when get called on object with null param

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

Use `[]` instead of `[[]]` in link generator options.

Fix Double Nested Array in ObjectData Preview Url Generator

---

bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js

`findByType` is not available since ExtJs 4 anymore.... it was replaced with `query` in ExtJs 4

Fix findByType not available in system settings

---

models/DataObject/ClassDefinition/Data/Extension/Relation.php

currently it happens that those types are generated like
```\Pimcore\Model\Asset\image[]```
or it could happen like
```\Pimcore\Model\DataObject\product[]``` which is not correct, since classes are always upper-cased.
Resolves #

fix doc-blocks for relational types.

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

Fix bug when manually sorting objects in the tree. This was not working correctly for variants as the indices of siblings were not updated.

Fix sorting variants

---

models/Element/Service.php

When uploading an asset or creating a folder with a % sign in its name, the asset is not accessible via its URL. After uploading an asset with name "100%cotton.png", for example, its neither accessible via "example.com/100%cotton.png" nor "example.com/100%25cotton.png" (with the encoded percent sign).
I suggest to replace the % sign in asset keys as in this PR. I suspect that this is somehow related to the rewrite rules for assets, so changing them might also be a solution. But I have no idea what side effect that may have.

Replace % sign in asset keys

---

models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php

setting it to null, so it does not throw a warning.
This is an example of the stack trace of this warning.
```
Notice: Undefined index: context - #0 <project>/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(227): Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations->save(Object(Pimcore\Model\DataObject\Colour), Array)
#1 <project>/vendor/pimcore/pimcore/models/DataObject/Concrete.php(222): Pimcore\Model\DataObject\Concrete\Dao->update(false)
#2 <project>/src/Interceptor/Main.php(50): Pimcore\Model\DataObject\Concrete->update(false)
```
Resolves #

adding the key 'context' to the $params array

---

models/DataObject/Traits/DirtyIndicatorTrait.php

Resolves #
it will avoid getting the warning bellow:
```
Notice: Undefined index: o_parentId
#0 <project>/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(226): Pimcore\Model\DataObject\Colour->isFieldDirty('o_parentId')
#1 <project>/vendor/pimcore/pimcore/models/DataObject/Concrete.php(222): Pimcore\Model\DataObject\Concrete\Dao->update(true, Array)
#3 <project>/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(644): Interceptor\Main->update(true, Array)
#4 <project>/vendor/pimcore/pimcore/models/DataObject/Concrete.php(705): Pimcore\Model\DataObject\AbstractObject->save()
```

fixed the isFieldDirty to avoid uninitialised keys

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multihrefMetadata.js

Current solution produces this:
Cause the ending parenthesis is in the wrong place.
with this PR it looks like this:

fix multihref-metadata boolean

---

models/Document/Hardlink/Wrapper/Printcontainer.php
models/Document/Hardlink/Wrapper/Printpage.php

Currently hardlink wrappers for web2print documents are missing. Therefore hardlinks in combination with web2print documents do not work correctly. In the old pimcore 4 web2print plugin these wrappers where delivered within the plugin...

add hardlink wrappers for web2print documents

---

models/DataObject/ClassDefinition/Service.php

Issue: When importing class definition from exported JSON file the group is ignored.
Fix: Set the group when importing from JSON definition.

Set group when importing from JSON definition.

---

lib/Document/Tag/TagHandler.php

When decorating the TagHandler class the method handleBrickActionResult and the attribute $responseStack needs to be reimplemented in the decorating class because these are private in the original TagHandler. 
Changing them to protected would prevent reimplementation.

Changes private attributes to protected ones in TagHandler

---

bundles/AdminBundle/Controller/Admin/EmailController.php
bundles/AdminBundle/Controller/Admin/IndexController.php
bundles/AdminBundle/Resources/public/js/pimcore/document/email.js
bundles/AdminBundle/Resources/public/js/pimcore/document/newsletter.js
bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js

add option to choose a document
add option to add parameters
add from field (prefilled with system settings)
add send test mail button to email and newsletter documents (will prefill the email window with data)

Improve 'Send Test Email'

---

bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php

Add option to disable useIds only parameter (required in special situation where you need e.g. the variant ids in the response)

Add option to disable useIds only 

---

models/DataObject/ClassDefinition/Data/EncryptedField.php

Resolves #
This bugfix addresses the fix for the save/publish event of encrypted fields. Because of the typos it was unable to save and results in an ContextException.
Fixed two small bugfixes.

Fixed typo for return type and wrong usage of method_exist function.

---

lib/DataObject/Import/ColumnConfig/Operator/ObjectBrickSetter.php

Resolves #3667 
Check if brick is not empty before call "process" function on childs. Because brick is not necessary defined, calling "process" with a target on NULL displaying error on CSV import.

fix: don't set brick if brick is empty

---

lib/Targeting/Condition/ReferringSite.php

According to [RFC 2616][1], the header name is "Referer" instead of "Referrer".
[1]: https://tools.ietf.org/html/rfc2616#page-140
Resolves #3678

Fix correct spelling of "Referer"

---

bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
bundles/CoreBundle/Resources/translations/en.json
lib/Event/AssetEvents.php
lib/Event/DataObjectEvents.php
lib/Event/DocumentEvents.php
lib/Event/Model/AssetDeleteInfoEvent.php
lib/Event/Model/DataObjectDeleteInfoEvent.php
lib/Event/Model/DocumentDeleteInfoEvent.php
lib/Event/Model/ElementDeleteInfoEventInterface.php
lib/Event/Traits/ElementDeleteInfoEventTrait.php

which allows to determine what elements can be deleted from backend and which don't.
*Cause*
There is a Problem with pre-delete events. They would work in cases where the element doesn't have any childs. When the element has childs, Pimcore deletes those first and then the "selected" element. 
This event looks like that:
*Objects*
http://g.recordit.co/gADtiNMZY7.gif
http://g.recordit.co/6IgWGJ1out.gif
*Documents*
http://g.recordit.co/sYbBgnYYO9.gif
*Assets*
http://g.recordit.co/RgoK2PNjbh.gif

introduce new delete-info event

---

bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php

Prevent warning if no $authorizedData is set (e.g. Payment canceled)

Order agent bugfix

---

bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php

The actual name of the SQL field is "o_modificationDate", not "o_modification".
The bugfix is important so that aborted orders are cleaned up properly.

Correct field name: o_modificationDate instead of o_modification

---

bundles/AdminBundle/Resources/public/css/ext-modifications.css
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/externalImage.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numeric.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/textarea.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/time.js

When you set an input field to be not editable, Pimcore uses ExtJS's disable() method in the input field. This leads to being not able to highlight or copy contents of such readonly fields in Firefox. Anyway readonly is the more approprate attribute for setting something to be not editable.
With this PR readonly attribute is used.

Use readonly attribute for readonly input fields - not disabled

---

models/Asset/Image.php

Sometimes for dev instances it's usefull to just copy the database but not the assets in the filesystem. Currently the result for images can be that it is not possible to open the asset in the pimcore backend. This fix just returns an empty array instead of a exception and therefore the asset can be opened without a problem.

asset image: xmp data fix when file is not available in filesystem

---

bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js

This PR is a complete refacturing of the "Show in Tree" function in Pimcore backend.
Current implementation has many flaws. These are mainly:
- Resolving nodes below tree paging nodes sometimes works, sometimes it does not, see https://github.com/pimcore/pimcore/issues/3520
It mainly fails when dealing with multiple trees of the same type (custom views), like (objects)/products and (objects)/categories. The following object in demo-advanced for example will be resolved successfully in default view, but not in PIM view: https://demo-advanced.pimcore.org/admin/login/deeplink?object_9155_object 
- Tree search filters are not supported, an active tree search that hides the requested node or one of its ancestors won't be cleared.
- Current implementation is mainly based on try/catches - there …

Refactoring treenodelocator

---

bundles/EcommerceFrameworkBundle/CartManager/ICart.php

The implementation of the interface has already the correct type hint in its PhpDoc:
https://github.com/pimcore/pimcore/blob/8b3f023feb8ee06731d2aa0b65dd95d5e30085b2/bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php#L853

Fix PhpDoc parameter type of ICart::removeVoucherToken()

---

bundles/CoreBundle/Resources/config/services.yml

Fix following Deprecations:
`Using a colon after an unquoted mapping key that is not followed by an indication character (i.e. " ", ",", "[", "]", "{", "}") is deprecated since Symfony 3.2 and will throw a ParseException in 4.0`

Fix Symfony Deprecations

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php

1. Create class with Many-To-Many Object Relation
2. Select Many-To-Many Object Relation classes and visible fields
3. Save class
4. Create object
4. Remove Many-To-Many Object Relation classes
5. Save class
6. Open object

Fix: Unable to open objects with ManyToManyObjectRelation fields and visible fields but no classes

---

bundles/AdminBundle/Resources/public/css/object_versions.css
models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php

This pull request adds metadata columns of advanced multi relation data types to the data object version preview.
Styling is not that easy but should be acceptable:

add version preview for metadata fields of advanced multi relation types

---

models/DataObject/ClassDefinition/Data/Video.php

The `getFromWebserviceImport` method for videos referenced the wrong variable in some places. I have replaced the variables in this PR.

Fixed usage of wrong variable in webservice import of videos

---

models/DataObject/Concrete/Dao.php
models/DataObject/Fieldcollection/Dao.php
models/DataObject/Fieldcollection/Data/Dao.php
models/DataObject/Localizedfield/Dao.php
models/DataObject/Objectbrick/Dao.php
models/DataObject/Objectbrick/Data/Dao.php

1. Open Advanced Demo
2. Open Product
3. Try to save
After https://github.com/pimcore/pimcore/commit/81cbbd66e14bd8ec9e48108ec25eacca28efc936 it should be used `method_exists($fd, 'getDataForResource')` and `method_exists($fd, 'getDataFromResource')` consistently

Fix: Can't save object with CalculatedValue

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

When copying an object without children via "recursive, updating references" an exception is raised. This is due to the variable $childIds not being countable (not existent without children). Thus the for loop iterating over the children should only be accessible if there are children present.

Exception when copying an object recursive with updating references without children

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js

The many to many object relation tag freezes the browser, when sorting items via d&d. This happens with 3+ items in the tag. The issue was already resolved in the advanced many to many object relation tag.
Resolves #3559

Fixed endless recursion on d&d objects in manyToManyObjectRelation

---

models/DataObject/ClassDefinition/Data.php

The deprecation warning should also be generated with existing properties

[DataObjects] Fix: No deprecation warning if property exists

---

tests/cache/Factory.php

Without this fix I get an error, because the FilesystemCoreHandlerTest removes the complete cache dir with the container files. One of the next tests would like initiate a service and can't load the file:
```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                            
Compile Error: ContainerKyj7wso\appTestDebugProjectContainer::load(): Failed opening required '/var/www/pimcore-test/var/cache/test/ContainerKyj7wso/getInstallerService.php'
```
I have attached a subdirectory, as well as in normal use:
https://github.com/pimcore/pimcore/blob/82199d8cf1bee19844690b76f048ec01814ae5a0/bundles/CoreBundle/Resources/config/cache.yml#L63-L72
I don't know why it …

Fix: Can't execute tests locally

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

The field definitions of the keys for classification stores get enriched after the `pimcore.admin.dataobject.get.preSendData` is sent. So manipulating the field definitions of the classification store's keys is not possible yet.
I want to set a specific field of a single key in a classification store group to `notEditable`.

Enrich object layout before preSendData event

---

bundles/AdminBundle/Controller/Admin/TranslationController.php

Sorting by language value did not work in admin/website translations - with this fix it works.

admin/website translations backend - sort by language fix

---

lib/Workflow/Manager.php

if workflow place would be changed from admin area, all changes from the last version including publish status will be merge into dataobject. In this case the live product will be away from the shop. this fix avoid it.

fix workflow place issue

---

bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php

Adds permission check for ClassificationstoreController. Please re-check the list of `unrestrictedAction` in the `onKernelController()` method.
Resolves #3848

Missing permissions check for Classificationstore

---

bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php

> This PR is an addition to https://github.com/pimcore/pimcore/pull/3849
Adding classification store groups and collections inside an object is possible without `classes` permission.
Since resolving #3848 this is no longer possible due to missing `classes` permissions.

Editing classifications in object context without classes permission

---

bundles/InstallBundle/Command/InstallCommand.php

Fix installer options:
* skip-database-structure
* skip-database-data
* skip-database-dump
Resolves #3852
Comment and request from @dpfaffenbauer (https://github.com/pimcore/pimcore/issues/3852#issuecomment-456087497) is not included.

Option to skip database structure on install is not working

---

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/textarea.js
bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/wysiwyg.js
bundles/CoreBundle/Resources/translations/de.extended.json
bundles/CoreBundle/Resources/translations/en.extended.json
models/DataObject/ClassDefinition/Data/Textarea.php
models/DataObject/ClassDefinition/Data/Wysiwyg.php

Feature: exclude wysiwyg and textarea contents from the Pimcore backend search.
Use cases:
- exclude sensitive information in search result
- exclude irrelevant data and reduce the fulltext search index size.

Checkbox to exclude wysiwygs and textareas from the backend search index

---

lib/Kernel.php

If a WebTestCase with two or more test methods is used there will be a php error `Call to a member function get() on null`. After every test method the kernel will be shutdown and on every `bootKernel` will be ensured the kernel has been shutdown. Therefore it must be checked if there is a container instantiated.

WebTestCase: ensure on Kernel::shutdown a container was instantiated

---

bundles/EcommerceFrameworkBundle/CartManager/AbstractCartItem.php

`\Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\AbstractCart::isValidCartItem()` fails with an error "Call to a member function getId() on null" when trying to log a warning.
productId "0" was being handled as "unknown" in `AbstractCartItem::getProductId()`, trying to obtain the Item's object to get it's Id, which fails since the Id is not valid.
This patch fixes this.

Fixed a bug with isValidCartItem()

---

models/Webservice/Data/Mapper.php

- Go to any Pimcore site (with the webservice available) `<host>/webservice/rest/document/id/<existing-document-id>`.
- Add an area block to the document, if none is available.
- Find the area block by utilizing the browsers seach bar (search for _areablock_).
- Under value/indices you will see that there are a few entries (non-associative).
- Adds the keys to the non-associative arrays, therefore the information is not lost.
When using the webservice to acquire information about a document (and its content), one could not programmatically access the type of the brick within the area block (for example), unless index `1` is considered to _always_ be the type (which might change in the future).

Key of assoc array is lost when using the webservice

---

models/Version.php

If a version file contains a class which doesn't exist anymore we get a " __PHP_Incomplete_Class" response. 
Therefore the we can't open the object anymore in the pimcore admin.
In this case -> delete the version as it is done if we can't get the data.

[Versions] Handle incompatible/ missing class more gracefully

---

bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js

1. Create a predefined property
2. Open predefined property select in a document
3. Go to Admin translations (The property name doesn't exist)
4. Create Admin translation
5. Open predefined property select in a document (Predefined Properties are not translated)

Fix: Translation of predefined properties doesn't work

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

add interfaces and classes to the js data.
This allows very clean code for example in listeners: 
```   
postSaveObject: function (object, task) {
if(object.data.general.php.interfaces.includes('AppBundle\\Model\\DataObject\\MyInterface')) {
console.log('do something');
}
}
```

Expose all classes and interfaces of DataObjects for js

---

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php

In the AbstractBatchProcessingWorker when you call getDefaultDataForIndex the getCategories method is hardcoded to the object. 
It would be better to use the tenantconfig here. (like on all the other workers) 
So you can use a different function/field to retrieve "categories" for your object even if you already have categories defined in your object.

Bugfix: AbstractBatchProcessingWorker getDefaultDataForIndex() should respect tenantConfig

---

bundles/AdminBundle/Security/User/User.php

Not sure how this occurs but somethimes the roleId of a User can be empty - that results in a boolean value trying to call ->getName() and prevents the User from logging in.

Empty role prevents login fix

---

bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php

Resolves #3915 
Removed the cast to integer since the identifier can also be a string.

[Bug][Ecommerce] joinCustomer cast classId to integer

---

lib/Tool/Text.php

Importing a UTF-16 encoded file was not possible for me, since the encoding detection failed and the following conversion to UTF-8 messed up the file. According to the docs at http://php.net/manual/de/function.mb-detect-order.php, detection of UTF-8 and UTF-16 is not supported and will always fail. That why I've taken the BOM detection approach from http://php.net/manual/en/function.mb-detect-encoding.php#91051 and added it to the `detectEncoding` method.

Detecting UTF-16 encoding fails in CSV import

---

bundles/AdminBundle/Resources/public/js/pimcore/helpers.js

This function is also defined in line 2765
https://github.com/pimcore/pimcore/blob/f778e30b42aae7e4a771788d6f3b1ced85b874c2/bundles/AdminBundle/Resources/public/js/pimcore/helpers.js#L2642-L2648
https://github.com/pimcore/pimcore/blob/f778e30b42aae7e4a771788d6f3b1ced85b874c2/bundles/AdminBundle/Resources/public/js/pimcore/helpers.js#L2765-L2771

Remove redundant isValidPassword helper function

---

models/DataObject/ClassDefinition/Service.php
tests/_support/Resources/objects/brick-import.json

ObjectBrick import currently only sets parent class in general settings, but ignores title and group
To reproduce:
- Create an object brick
- Set parent class, title and group in general settings
- Export object brick
- Delete object brick
- Create new and empty object brick
- Import from json
- Title & group fields are empty

[Bug] ObjectBrick import does not import title & group

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/csvSettingsTab.js
bundles/CoreBundle/Resources/translations/en.json

Resolves #3864 
Added button to reload column configuration(with csv settings changes) on Import configuration

Add option to reload csv import column configuration

---

bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
models/Document/DocType/Listing.php

In the moment the select shows only undefined > undefined and doesn't work.

[DocType] Fix: Predefined Document Type Select in Settings Tab

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js

Loading field collections in Pimcore's backend with e.g. > 20 items can be quite slow. According to https://www.sencha.com/blog/performance-optimization-for-layout-runs/ it is a best practice to not redraw ExtJS component for every child item but to suspend layout calls until all child items have been added. 
Especially field collections and blocks would profit by suspending layout updates. If you can imagine this to be useful also for other data types please comment.
Performance comparison (for a field collection with 47 items) for reloading object:
Without suspending layout: 116 seconds
With suspending layout: 24 seconds

Better performance for loading field collections / blocks

---

lib/Image/Adapter/Imagick.php

Do not change the colorspace if "PreserveColor" is set. Otherwise cmyk images would be converted to rgb...

Thumbnail - preserve color space

---

models/WebsiteSetting.php

I think the WebsiteSetting::getByName function shouln't log an warning, if the setting doesn't exists.
It is impossible to check if a website settings does exists. So I can't avoid this warning.
Other get functions also doesn't log warnings. Return null should be enough.

[WebsiteSettings] getByName shouldn't log a warning

---

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js

Fixed custom layout saving
1. Remove preg match and create custom layout with name like "My Test Custom Layout" like allowed before preg_match intoduction.
2. Add preg match again and try to save layout. You get "Invalid name" message.

[Data Object] Custom Layouts: allow spaces in names

---

bundles/AdminBundle/Controller/Admin/AssetController.php
bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js

Some users it may find it confusing to see the path in the `filename` column, thus, the `filename` column should only show the `key` of an asset.
This also increases the usability of the grid view (for assets).
This PR adds the `filename` column (event though it just looks like the `fullpath` column was added).

Improvement: show file name separately from path in asset grid view

---

bundles/CoreBundle/EventListener/WorkflowManagementListener.php

The `WorkflowManagementListener` only allows to use permissions for elements of type `ConcreteObject`. However, in some situations it may be needed to restrict permissions for other element types (such as documents, and assets).
The code of the `WorkflowManagementListener` was updated to also allow other element types.

Improvement: support workflow permissions for all element types

---

bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml

Add service definitions. Otherwise
pimcore_ecommerce_framework:
index_service:
tenants:
test:
enabled: true
config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\ElasticSearch
worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\ElasticSearch\DefaultElasticSearch6
would not work.

Elasticsearch - add service definitions for version 5+6

---

lib/Placeholder.php

This fixes an fatal error in the "`\Pimcore\Placeholder`" class.
Code to reproduce:
```php
$html = '
%Text(whoami)
%Text(firstname);
';
$placeholder = new \Pimcore\Placeholder();
$placeholder->detectPlaceholders($html, []);
```

Fix fatal error in \Pimcore\Placeholder::detectPlaceholders

---

bundles/AdminBundle/Controller/Admin/AssetController.php

- The thumbnail processor might save the asset and then when the properties are already converted to an array an exception might occur.
- Therefore this fix does the array conversion later in the controller.

video properties bugfix

---

lib/Targeting/ActionHandler/AssignTargetGroup.php

There is no possibility to remove target groups from a visitor. This does add a function to reset (remove) the target groups.

Add option to reset target groups for a visitor

---

models/Document/Tag/Video.php

If I create a video editable without set the thumbnail option I get no poster.
```
{{ pimcore_video('video', {
'attributes': {
'class': 'video-js vjs-fluid vjs-default-skin vjs-big-play-centered',
'data-setup': '{}'
}
}) }}
```

[Video Editable] Fix: No poster if no thumbnail option is set

---

lib/Event/Targeting/TargetingResolveVisitorInfoEvent.php
lib/Targeting/VisitorInfoResolver.php

This allows to define a custom VisitorInfo. I have currently the use-case where I track page-views and sessions manually, but still wanna use the Targeting Engine. With this little change, it is possible for me to write my own VisitorInfo "Resolver" by defining the Visitor based on an event.

[Targeting] allow to set custom VisitorInfo via event

---

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
models/Property.php
models/Webservice/Data.php
models/WebsiteSetting.php
tests/_support/Util/TestHelper.php

The Property class loads the elements but the WebsiteSetting class doesn't:
https://github.com/pimcore/pimcore/blob/652a614a0c50d1b33212471e548e3cc96a517aad/models/Property.php#L140-L152
I know its a kind of bc break. Perhaps it is possible in 5.7.0 with a bc notice?

[WebsiteSettings] getData should lazy load like Property class

---

bundles/AdminBundle/Resources/public/js/pimcore/helpers.js

When using custom icons for objects, they are scaled incorrectly in tabs.

Fixing icons in tabs

---

lib/Tool/Console.php

Fix "nohup: can't detach from console: Inappropriate ioctl for device" error when generating PDFs on OS x using wkthmltopdf
Resolves #4022

[Web2print] Fix background PDF generation with wkhtmltopdf on OS X

---

bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php

Prevents key collisions where a regular order product item and a gift product item could otherwise get the same key
Resolves a key collision where a regular order product item and a gift product item could otherwise get the same key
To reproduce:
1. Create a Price Rule with a gift item product as an Action.
2. In the front end, add the same product as would be the gift to your cart.
3. Complete the Checkout steps. (Making sure the Price Rule applies and you also get the gift item).
4. Look at the order, result: The order now contains only one of the items.
5. If you now do `$order->getItems()`  and `$order->getGiftItems()` you will only get the same object and the same object for both methods. But you should get two different objects.

[Bug][Ecommerce] More unique keys for order items and gifts

---

models/DataObject/Traits/ObjectVarTrait.php
models/Element/Service.php

Currently when for example someone deletes an object brick Pimcore will throw an Exception when someone tries to show a previous version. This fix silently ignores these fields in the version preview.

do not throw exceptions when properties in data object versions do not exist any more

---

bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php

Resolves no issue, just tiny things I noticed reading the code.
`sizeof` is just an alias of `count` and computation time scales linearly with the size of the array, `empty` is a single operation. This might save many *μ-seconds* I tell you! ;)

PHPDoc and empty conditions checks in Bracket.php 

---

lib/Workflow/NotificationEmail/NotificationEmailService.php

Currently the translator locale does not work correctly

[workflow] email notifications: set correct translator locale

---

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.php

The language output does not make any sense here.

do not output useless language hint for field collections

---

lib/Migrations/Command/Traits/PimcoreMigrationsConfiguration.php

I get following error if I want execute the migrate command:
`php bin/console pimcore:migrations:migrate -s pimcore_core`
```
In PimcoreMigrationsConfiguration.php line 123:
Type error: Return value of Pimcore\Migrations\Command\MigrateCommand::getConnection() must be an instance of Pimcore\Migrations\Command\Traits\Connection, instance of Pimcore\Db\Connection returned
```
Regression from https://github.com/pimcore/pimcore/pull/4044

Fix pimcore:migrations:migrate command

---

models/DataObject/Localizedfield.php

This causes annotation parsers to throw an exception!

Fix wrong doc-block annotation

---

models/Version/Dao.php

Message was `PHP Notice: Undefined index: days in pimcore/vendor/pimcore/pimcore/models/Version/Dao.php on line 193`
Resolves no specific issue number, just something that kept appearing in our logs.

Fixes PHP notice on maintenanceGetOutdatedVersions

---

bundles/EcommerceFrameworkBundle/CartManager/CartItem.php

This is a possible solution for issue: #4100 
Please check for side effects.

[Ecommerce] fixed Getting sub items of cart item ignores defined cart item class

---

lib/DataObject/GridColumnConfig/Operator/TranslateValue.php

When value to translate is String "0" the condition in line 44 will be false. So no prefix is set and no translation is executed.

TranslateValue-Operator does not translate "0"

---

models/DataObject/ClassDefinition/Data/Classificationstore.php

Configured tooltips of classificationstore keys get overriden and so are not displayed in the objects. This PR fixes the issue and uses the previous value as fallback.
Resolves #4139

Fix classificationstore key tooltips

---

bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js

When you click on "Show in tree" on a data object there is a bug in the current version when the last element of the data object tree page is a folder. In this case in https://github.com/pimcore/pimcore/blob/edd0f3e8457f0a230bf37819668716b01f9edcab/bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js#L502-L508 it is only checked if last element is a folder - if it is, the tree gets paged forwards without checking if the folder name is alphabetically after the object being searched for.
This PR changes this behaviour and also simplifies the code. I have not understood why folders and objects are treated differently because - unlike as e.g. in Windows - Pimcore folders are not sorted after objects but alphabetically by name regardless of their type.

"Show in tree" did not work if last element in tree page is folder

---

bundles/AdminBundle/Controller/Admin/AssetController.php

Listing returned folders as well which results in empty tree preview on
instances with nested folder structures.
Fix it with limiting the
listing to asset types which actually have a thumbnail.
To reproduce....let's assume a nested structure like this:
As you see there are a lot of folders which finally have images in it. Hovering over the Artikel folder is showing just 5 tree preview images, although there are a lot more present.
Due that we fetch as well folders in our query and filter out assets afterwards, which are not a folder, we get this poor result.
Hence query just for assets which really have a thumbnail and show the first 35 we get

[Assets] exclude asset folder from tree preview

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js

Visible columns in advanced Many-to-Many object relations are 100px wide by default, often hiding parts of the content. The regular many-to-many-relation already makes use of the flex param, improving visibility.
Current view:
When using flex:

Use flex instead of fixed width for columns in an advanced many-to-many relation

---

bundles/AdminBundle/Controller/Admin/AssetController.php

Simply, call the following url: **\<your-domain\>/admin/asset/get-image-thumbnail?id=\<your-asset-id\>&thumbnail=\<your-thumbnail-name\>&cropPercent=false**.
_Obviously, you'll have to use proper values for the URL._
The parameter is additionally checked for its value, ultimately, resolving the issue with this PR.

AssetController cannot generate thumbnails

---

bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
lib/Helper/Mail.php

It looks like currently `Pimcore\Helper\Mail::logEmail()` only checks for plain text of an email by checking the text mime part. Which, I assume, is only set if you send a multi mime part e-mail but not for a plain text only e-mail. At least the current logging behavior suggests that this assumption is correct.
Hence an email sent like this:
```php
$mail = Tool::getMail([$user->getEmail()], 'Pimcore lost password service');
$mail->setIgnoreDebugMode(true);
$mail->setBodyText("Login to pimcore and change your password using the following link. This temporary login link will expire in 30 minutes: \r\n\r\n" . $loginUrl);
$mail->send();
```
Wont log any payload.
Additionally the text column in the email logging overview is permanently hidden - which makes access to the text unnecessarily …

Ensure mail text is logged for plain text mails too

---

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php

When compoaring versions of a data object, the system fields "path" and "published" have not been marked as "changed".
1. Create data object
1. Create folders A and B
1. Move object to folder A
1. Move object to folder B
1. Open object and compare versions
Result: Path was not marked as changed, with this PR it is.

Mark path and published fields as changed when data object comparing versions

---

lib/Mail/Plugins/RedirectingPlugin.php

Clone of #4142 as per request in comments.
Currently the mail redirecting in the mail debug mode leads to "information loss" in the email log.
The receivers are not retained and hence the log can't be searched for mails to a certain receiver. 
`Pimcore\Mail\Plugins\RedirectingPlugin` now adds the original sender / receiver data as parameters to the mail log.

Change mail log / redirect handling to retain the original message data - re-branched

---

models/Element/Service.php

If a version stores incomplete (sub-) class, the [renewReferences](https://github.com/pimcore/pimcore/blob/a03da421d921a39249b76f72a1275f98e03994ab/models/Element/Service.php#L625) method fails in line:
https://github.com/pimcore/pimcore/blob/a03da421d921a39249b76f72a1275f98e03994ab/models/Element/Service.php#L663-L668
because the `method_exists` check may fails with `Error: method_exists(): The script tried to execute a method or access a property of an incomplete object.`.
This PR checks the incoming `$data` against valid classes and returns `null` otherwise.

Skip Incomplete Classes in renewing References Process

---

models/Version.php

This is a follow-up for #4165. `$data` could be `false` which triggers an exception in `get_class`method.
PS: Yes, I'm currently struggling with a some messed up versions. 😄

Use instanceof instead of get_class in Version Data Check

---

models/Asset/MetaData/EmbeddedMetaDataTrait.php

Look for temporary file, if the asset wasn't found within the file system path.

Fixed a bug where meta data isn't saved when uploading a file.

---

bundles/AdminBundle/Controller/Admin/MiscController.php
bundles/AdminBundle/Resources/public/js/pimcore/functions.js
bundles/AdminBundle/Resources/public/js/pimcore/startup.js
lib/Translation/Translator.php

This PR fixes several issues with the current admin translations Javascript implementation:
- For objects with massive amounts of translations (for example select boxes with thousands of entries) the current call of `/admin/translation/add-admin-translation-keys` does not work. If there are massive amounts of keys the request will fail and Pimcore will show a 503 maintenance error. Additionally this call can contain the same keys multiple times. Therefore this PR limits the amount of a single request to 500 (and stores the rest for the next request). As this method is called each 30 seconds for each admin users the translation keys will be added anyway. 
- Currently not translated keys are added to the `/admin/translation/add-admin-translation-keys` call again and again. In complex …

fix admin translation javascript issues

---

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js

Using the "Batch edit all in a grid doesn't process all or to many items in the grid if the page size was adjusted.
This is because it doesn't sent the currently set page size - which causes `pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Helper/GridHelperService.php::prepareListingForGrid()` to fall back to it's default limit of 20 items.
`pimcore.object.helpers.gridTabAbstract.batchPrepare()` now sets the current pageSize as limit parameter.

Grid: "Batch edit all" doesn't edit all or to many items

---

bundles/AdminBundle/Resources/public/js/pimcore/functions.js

This is a important follow up to #4170 
There are situations when pimcore.system_i18n is not loaded but the t() function get's called. We should merge this PR urgently as otherwise very strange bugs can occur.

fix admin translation javascript issues - bug fix when translations are not loaded

---

bundles/AdminBundle/Resources/public/js/pimcore/element/notes.js

Load notes only when `Notes & Events` tab is activated.

Lazy load notes list

---

models/Search/Backend/Data.php

Adding data to the backend search is called on every object/asset/document save. The element save transactions are protected against database failures (deadlocks etc.)
Due that backend search transaction is called afterwards (EventListener) it is not protected and will not restart on failure.
To fix it go inline with element save methods
We are importing a big amount of objects and assets multi threaded and we ran into this issue

[BackendSearch] restart save transaction if it fails

---

bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js

When you have a bundle other than AppBundle which does not have its controllers being registered as services then its action methods have not been listed in static routes and document types settings.
1. Create Bundle named TestBundle
1. Create controller DefaultController with action method testAction
1. Go to static routes settings
1. Select Module=TestBundle, Controller=DefaultController
1. Open action dropdown -> it shows methods of AppBundle\DefaultController not of TestBundle\DefaultController
The same applies for choosing the action in document type settings.

Bugfix: Controllers in bundles have not been listed in static routes / document types settings

---

bundles/AdminBundle/Controller/Admin/AssetController.php
bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
bundles/CoreBundle/Resources/translations/de.json
bundles/CoreBundle/Resources/translations/en.json

Sometimes you want to clean up your assets. To be able to show assets which are not referenced in any object or document this PR introduces a new checkbox in the asset list view.

Show unreferenced assets

---

bundles/AdminBundle/Resources/public/js/pimcore/document/document_language_overview.js

Fixes "Create Translation" modals to always display on top

Fix create translation modal display in document language overview

---

lib/Tool/Glossary/Processor.php

When you have two Glossary entrys like:
Test 1 -> Link: /de/Test 1
Test 2 -> Link: /de/Test 1
in the old way the link looks like:
<a href="/de/<a href="Test 1">Test 1">">Test 1</a>
Now it looks if the Link is in a <a> Tag and ignore this one.

Do not replace a replaced link in Glossary

---

composer.json
models/Element/Service.php

Reverts pimcore/pimcore#4205
we need to revert this PR because myclabs/deep-copy 1.9.1 reverted the signature changes.

Revert "Use DeepClone 1.9"

---

doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
lib/Model/Listing/AbstractListing.php
models/Asset/Listing/Dao.php
models/DataObject/Listing/Dao.php
models/Document/Listing/Dao.php

[Elements] Allow array parameter binding for listing conditions

---

lib/Helper/Mail.php
models/Document/Email.php
models/Document/Newsletter.php

Set your default email settings (receiver and copy) to include spaces like `john.doe@example.com; jane.doe@example.com`.  
Send an email with these default settings. It should throw an error that the second email is not compliant to the RFC 2822, 3.6.2
Adds trim command for all email split strings (found with `preg_split('/,|;/'`)

Add missing trims for email-array getters

---

lib/Model/Listing/AbstractListing.php

Fixes bind params issue introduced in #4265

[Elements] Fix: Allow mixed bind params for listing conditions

---

bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
bundles/AdminBundle/Controller/Admin/Document/PageController.php
bundles/AdminBundle/Controller/Admin/Document/SnippetController.php

Fix snippet personalized content content cleanup

---

bundles/AdminBundle/Controller/Admin/AssetController.php

Error was: `CRITICAL: __clone method called on non-object ... _clone method called on non-object at vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/AssetController.php:69`
Resolves no specific bug report, but this has sometimes happened after assets were not fully uploaded and some traces of seemed to be left in caches (maybe).
Just hardening the code against those odd situations.

Fixes __clone method non-object by moving it to after instanceof

---

bundles/CoreBundle/Resources/migrations/Version20190403120728.php

Fix the used table when restoring the old primary keys.
Currently, this leaves the last modifed relation table without a primary key, and causes errors for the meta tables as you cannot add multiple primary keys to a table.

Fix down logic in Migration 20190403120728

---

doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md

There was a mistake in code example for getting admin session

Documentation: Fix method call for admin session

---

models/DataObject/ClassDefinition/Data/Numeric.php

Currently when calling the setter of a numeric field the data gets written to the object without any validation or cleanup. With this PR the field's settings "integer", "decimal precision" and "unsigned" are used to clean-up set data.

Use numeric field options also for cleaning up data in setter

---

bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
bundles/CoreBundle/Resources/translations/en.json
lib/Web2Print/Processor/PdfReactor8.php

Add possibility to enable debug mode when generating PDFs with PDFreactor.
This is especially useful when using Javascript, because console.log output is appended to the generated PDF.
This is a sample of the output (only the beginning, logs are really detailed) appended by PDFreactor at the end of the document

Add possibility to enable debug mode when generating PDFs with PDFreactor

---

lib/DataObject/GridColumnConfig/Operator/Concatenator.php

Currently when the concatenator operator has a child element which is null, the value of the previous element gets repeated, see
https://github.com/pimcore/pimcore/blob/606c231f9dddd5fbc6458077014aafe4af315493/lib/DataObject/GridColumnConfig/Operator/Concatenator.php#L46-L68

Concatenator operator: do not duplicate value of last non-empty child

---

bundles/CoreBundle/Resources/migrations/Version20190508074339.php
bundles/InstallBundle/Resources/install.sql

In the maintenance job at the step of removing excess versions the following SQL query gets executed (when using max. steps of object versions and not versioning by days):
https://github.com/pimcore/pimcore/blob/606c231f9dddd5fbc6458077014aafe4af315493/models/Version/Dao.php#L200
The actual query for example is then:
`SELECT cid,count(*) as amount FROM versions WHERE ctype = 'object' AND NOT public AND id NOT IN (0) GROUP BY cid HAVING amount > 10`
Currently this query is using a temporary table and filesort:
```
id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | versions | NULL | ref | PRIMARY,cid,ctype | ctype | 2 | const | 83065 | 5.00 | Using index …
```

Use index for version maintenance query

---

bundles/EcommerceFrameworkBundle/Environment.php
bundles/EcommerceFrameworkBundle/SessionEnvironment.php

Currently `Pimcore\Bundle\EcommerceFrameworkBundle::hasCurrentUserId()` isn't very reliable because it checks `userId` for the value defined in `Pimcore\Bundle\EcommerceFrameworkBundle\Environment::USER_ID_NOT_SET` (-1).
However, there are multiple locations in which `userId` is set to `null` as default/re-set value.
A loose `empty()` check in `hasCurrentUserId()` could be fair to handle that in a very generic way but I'd say it's preferable to fix the consistency first.
Change two locations to use `Pimcore\Bundle\EcommerceFrameworkBundle\Environment::USER_ID_NOT_SET` when "re-"setting the `userId` property.

Make EcommerceFrameworkBundle::hasCurrentUserId() more reliable

---

models/DataObject/ClassDefinition/Data/Fieldcollections.php
models/DataObject/Fieldcollection/Definition.php

`Definition::getByKey` should always return Fieldcollection/Definition objects. Otherwise it throws an exception. With try/catch it is possible to import the class and remove the missing fieldcollections.
The same is in the setAllowedTypes function:
https://github.com/pimcore/pimcore/blob/cc117f07839630a73063109f424d0b9ecf6aa5bb/models/DataObject/ClassDefinition/Data/Fieldcollections.php#L372-L377

[Fieldcollection] Allow class definition import with missing fieldcollections

---

bundles/CoreBundle/Controller/PublicServicesController.php

new Image cacheBuster Feature was not working because the prefix was not equal to asset path (cache-buster-...)
added preg_replace to resolve this issue

new Image cacheBuster Feature was not working

---

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridCellEditor.js

This PR translates the field name like in edit helper:
https://github.com/pimcore/pimcore/blob/8b21bdd0e5cbb42b4261e2e596849f57292d8529/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js#L134-L137

Fix: Missing field name translation in grid cell editor

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

Currently sorting of child objects of a data object in the tree is done alphabetically. When sorting by index it has to be numerically, otherwise the order is 0, 1, 10, 11, 12, 2, 20.
* Create folder and set children sorting to "by index"
* Create 10 objects within the same folder
* Move the second item to the bottom (position 10)
* Refresh tree -> the item is now on position 3

Sort objects numerically when sorting by index

---

bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php
lib/Mail.php
lib/Tool/Newsletter.php

If the domain of a recipient is misspelled or not existing, the existing process causes:
Expected response code 354 but got code "554", with message "554 5.5.0 No valid recipients have been specified
Improvement:
First Step: Avoiding any email domains with no MX entries.
Second Step: If any error occurs cancel the jamming smtp-process via $mailer->getTransport()->stop();
* Changed Logger:info to Logge r:warn otherwise no output in the “newsletter-sending-output.log”
* Added counter to see the exact progress of the sending process in the .log file, helps later in finding any further errors
* Added ReturnPath for hard bounces

[Newsletter] Improved error handling while sending newsletter

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
lib/DataObject/GridColumnConfig/Operator/Factory/TranslateValueFactory.php
lib/DataObject/GridColumnConfig/Operator/TranslateValue.php
models/DataObject/Service.php

The TranslateValue operator does not take into account the language setting of the grid configuration (for view and CSV export).
1. Configure gridview with "Transformers > Operator Translate Value" + Input attribute
2. Select other language than default language
3. Value in grid column and CSV export column will not be translated

Fix: Language for TranslateValue operator

---

models/Asset.php

Currently there is a bug when you want to create an asset from a remote stream, reproducable with the following script:
```php
<?php
$fileStream = fopen('https://picsum.photos/200', 'rb');
\Pimcore\Model\Asset::create(1, [
'filename' => 'test'.uniqid(),
'stream' => $fileStream,
'userOwner' => 0,
'userModification' => 0,
]);
```
Problem is that PHP does not support rewinding remote streams. For this reason I keep the temporary file which originally was used to determine the MIME type and use this also for the data import.

Bugfix: Create asset from remote stream

---

bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
bundles/AdminBundle/Resources/public/js/pimcore/startup.js

In the moment the contextmenu of document and object are not sorted by name if you have set translations.

[Document|Object] Sort contextmenu by translated names

---

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js

Tags as `manyToManyObjectsRelation` and `manyToManyRelation` already have CSS selectors for their panel's bodies defined in the schema `pimcore_object_tag_xxxxx`. This PR adds a CSS selector in the same schema to the classification store tag.

Add CSS selector for classification store tag

---

models/Asset/Image/Thumbnail/Config.php

This fixes a spelling error in the annotation block of `getByLegacyConfig`.

[Semantical Error] Fix `@depricated` annotation

---

bundles/AdminBundle/Resources/config/services.yml

The file is not used and takes Request as parameter, which cannot be autowired anyway.

remove NotificationServiceFilterParser from DI

---

lib/Google/Cse.php

Google CSE search doesn't accept language parameters such as "pl_PL" "fr_FR" etc, it wants the language to be "pl", "fr" etc.
With the fix only the part before the underscore is used.

Issue when System Language contains underscore

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

As described in #4332 there is a major performance issue when moving a data object to a folder with lots of objects because all siblings get updated separately:
https://github.com/pimcore/pimcore/blob/606c231f9dddd5fbc6458077014aafe4af315493/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1107-L1140
This PR updates all sibling's o_index values at once.
Performance comparison for a folder with 14.000 objects:
without this PR: 267 seconds
with this PR: 130 seconds
Resolves #4332

Performance enhancement when moving object to folder with lots of children

---

bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/MultiSelect.php
bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php

If a property is defined as "bool" the value in the query has to be a bool or a string "true" or "false". 
Otherwise a parsing exception is thrown.
"0" or "1" is passed from a filterdefinition which  won't work. 
Changing the value in the backend from 0/1 to true/false didn't worked either...

Es Bugfix - Bool filter

---

models/DataObject/Objectbrick/Definition.php

Now the getter functions in the localized fields are set in the objectbrick Definition.

Enable localized fields in object bricks

---

bundles/AdminBundle/Controller/Rest/AbstractRestController.php
lib/Tool/RestClient/AbstractRestClient.php

Removed useless & dangerous urldecode, which could cause an unwanted transformation, when take the query from the request to filter the results.
As indicated in the [PHP documentation](https://www.php.net/manual/en/function.urldecode.php#refsect1-function.urldecode-notes), the `$ _GET` and `$ _REQUEST` variables are already decoded, so the urldecode could accidentally transform the query.
For example the query `{"field":{"$like":"%6232%"}}` is transformed to
`{"field":{"$like":"b32%"}}` because `%62` represents the char `b`.
Below a screenshot with the first value corresponds to the query taken from the request and the second the value `urldecoded` two times.
The behavior can be reproduced on the latest demo, in all calls where filters are made:
- Search Assets
- Search Documents
- Search …

[Webservices] Remove useless & dangerous urldecode from query filter

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

#3934 
- treat the empty layoutId parameter in the getAction in DataObjectController as a null parameter
Basically, when you apply a custom layout to an object and ascribe this custom layout to a user or group, when you first log in as this user or group and open an object the layout is applied correctly. However, when you refresh the page the custom layout is gone. This is because upon refreshing the Pimcore frontend puts an empty-valued `layoutId` parameter in the request. Why it does that is a different matter, but this empty parameter is treated as an actual parameter - thus the layout set for the user or group is lost. This way or another, an empty parameter shouldn't be processed at all.
If the issue is wrong then tell me - I'll create a different one for this problem specifically.

Make the custom layout pop up properly after page refresh.

---

bundles/AdminBundle/Resources/public/css/icons.css

See edit icon in embed brick (Basic Demo):

[UI] Fix: Edit Icon in Areabricks

---

bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js

Due to Ext.js default timeout of 30 sec for ajax requests, when having a slow server or limited bandwidth one may soon run into a lot of error messages "communication failure" because Ext.js canceled the requests an Pimcore can't handle the responses. This actually is a thing which should be checked for all ajax requests in Pimcore, we especially experienced this as problematic for the asset tree store.
I gues a better solution would be to not show a popup modal for such communication failures, but just a toast in the bottom right corner (like the success notifications), it should also be considered that the message should only be shown once at a time. In addition the JS handler for the failing requests should be considered. (i.e. in the element trees the folder icons should not stay in …

Extend asset tree store timout

---

bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php

in case of the datatrans lightbox the additional attribute upp-start-target should be set to '_top'. this is necessary since chrome apparently blocks redirects from within the lightbox iframe.  Such a redirect may happen to the Access Control Server of the bank which can lead to the following error:
'Unsafe JavaScript attempt to initiate navigation .... The frame attempting navigation is targeting its top-level window, but is neither same-origin with its target nor has it received a user gesture'
@fashxp

[EcommerceFramework][Datatrans-Lightbox] - add upp-start-target attribute

---

models/Asset/Dao.php
models/DataObject/AbstractObject/Dao.php
models/Document/Dao.php

The problem appears when setting restrictive permissions on a child of an element to which wider permissions have been defined.
Restrictive permissions on the child are ignored.
The behavior can be reproduced on Documents, Assets and Objects.
The following steps were performed on the current basic demo.
1. Create a user with wider permissions to parent document and restrictive permissions on child
2. The user can rightly perform all operations on the parent document
3. The user can wrongly perform all operations on the child document even if more restrictive permissions have been defined

[User Permissions] Fix wrong inheritance of wider permissions

---

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js

When using the SQL editor in the grid view the selected language from grid config is not transfered.
After clicking the button to show SQL editor, the correct language is displayed but grid data is translated to default language.
This behavior is reproducable in demo system.

Send language param in grid tab

---

models/DataObject/ClassDefinition/Data/Numeric.php

currently you cannot see which field throws an exeption this should fix this
Resolves #

Extend Validation Exeption

---

bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/StringReplace.js

Currently set label does not get saved but reverted to default "Operator String Replace".

String-Replace-Operator: Commit configured label

---

bundles/CoreBundle/Resources/config/logging.yml

This PR is fixing a problem with using the `ApplicationLogger` with a [custom app logger](https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Application_Logger.html#page_Setting-an-individual-logger-level) in Pimcore 6.0.0.
1. create a custom logger instance with the `initDbHandler` option:
`$logger = ApplicationLogger::getInstance('MyCustomLogger', true)`
2. try to use it...
=> You will get the following exception: 
```
The "Pimcore\Log\Handler\ApplicationLoggerDb" service or alias has been removed or inlined when the container was compiled. 
You should either make it public, or stop using the container directly and use dependency injection instead.
```
Solving this issue is just a one-liner by making the `Pimcore\Log\Handler\ApplicationLoggerDb` service public. …

ApplicationLoggerDb service exception fix

---

bundles/AdminBundle/Controller/Admin/AssetController.php
models/Asset/Document.php
models/Asset/Video.php

When there is an error during document thumbnail generation Pimcore tries to load the SVG `PIMCORE_WEB_ROOT . '/bundles/pimcoreadmin/img/filetype-not-supported.svg'` (see https://github.com/pimcore/pimcore/blob/43e14cca6b5f9171ffc4abc21b1921b23feec33b/models/Asset/Document/ImageThumbnail.php#L123)
But in https://github.com/pimcore/pimcore/blob/43e14cca6b5f9171ffc4abc21b1921b23feec33b/bundles/AdminBundle/Controller/Admin/AssetController.php#L1329-L1332 there is always Content-Type image/png being set - also for the above SVG.

Output document thumbnail with correct content-type header

---

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search.md

Elasticsearch allows to put all kind of json data structures into the index. Nevertheless the ecommerce framework currently forces to set a mapping in a product index columns. There are situations where it's better to do not use a mapping at all. Therefore this pull requests ignores columns without any kind of mapping set in the index service attribute configuration.

[ecommerceframework][elasticsearch] allow product index fields without mapping

---

bundles/CoreBundle/Templating/LegacyTemplateGuesser.php

And getBundle does only accept one parameter.
When getParent returns a Bundle and we want to get the bundle from the
kernel there is a warning
```
Warning: array_pop() expects parameter 1 to be array, object given
```
Because \Symfony\Component\HttpKernel\Kernel::getBundle will always
return an object or throw an exception.
``` php
/**
* {@inheritdoc}
*/
public function getBundle($name)
{
if (!isset($this->bundles[$name])) {
$class = \get_class($this);
$class = 'c' === $class[0] && 0 === strpos($class, "class@anonymous\0") ? get_parent_class($class).'@anonymous' : $class;
throw new \InvalidArgumentException(sprintf('Bundle "%s" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your %s.php file?', $name, $class));
}
return …
```

getBundle returns object so array_pop does not work

---

bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultElasticSearchSubTenantConfig.php
bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md

Changes in this PR
1. Update mapping in elastic search worker to store subtenant assortments as a simple list of IDs
2. Default condition in eastic search config for subtenants
3. Default ElasticSearchConfig implementation
3. Update docs

Elastic search subtenants

---

bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js

Updates condition for showing the delete action column in the translations backend view.
Adds check for `this.translationType === 'admin'` to allow deleting admin translations.
Because of an added condition (in issues #2437 - commit 1af633f734035e0736ecb42c033e23644c010ac7) around the delete action column it was not longer possible to delete admin translation.

Re-enables delete action for admin translations

---

models/Asset/Service.php
models/DataObject/Service.php
models/Document/Service.php

This pull request makes it possible to use the copy methods within `Document\Service`, `Asset\Service` and `DataObject\Service` without an existing Pimcore user (e.g. request from Front-End).
Also the `copyRecursive` methods now also copy unpublished Documents and DataObjects as well as DataObject variants.

[ElementServices] Extend functionality

---

models/DataObject/Service.php

Nowadays custom layouts can have non-numerical IDs. In https://github.com/pimcore/pimcore/blob/eebc75491fffdc848d9435668f874d387b3cefa2/models/DataObject/Service.php#L913 they are used in an SQL query's IN-criteria but without quoting them. This results in an SQL error.
To reproduce:
1. Create custom layout with non-numerical ID
2. Assign custom layout to a user's workspace settings
3. Login with this user
4. Try to open an object where workspace settings from 2. apply

[Custom layouts] Prevent SQL error for non-numarical ID

---

bundles/AdminBundle/Helper/GridHelperService.php

With large datasets (especially gigabytes in size), grid performance can be really low. This is caused by large views used in listings and MySQL not using indexes in them.
Probably views themself could be optimized?
Nevertheless:
Unless grid is sorted or filtered, gridProxyAction will use listing with ignoreLocalizedFields flag ON. This speeds up queries, by ignoring unnecessary layer of views and using smaller temporary tables.
Default order key has been changed from oo_id to o_id as it appears to be faster.
Tests has been done on Ecommerce Demo on a grid with ~65k randomly generated products.
Query cache has been disabled in MySQL.
**GridProxyAction before changes:**
`1760-2160ms`
Slowest queries:
```SELECT COUNT(*) AS `totalCount` FROM `object_localized_12_en_GB` WHERE ((o_path = …
```

Unless grid is filtered or sorted - ignore localized fields when getting ids

---

lib/Config.php

Removes duplicate if().
Does stricter comparison for site ids (which should always be integers).
Fetches $key later, after some continue's to avoid unnecessary execution.
Resolves #

Minor config improvements in getWebsiteConfig()

---

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php

When you move multiple items in the data object tree to another folder their `o_index` values get updated. But as requests for all moved objects are sent in parallel a deadlock can occur (resulting in an SQL error). This PR catches those deadlocks and tries to re-execute the database updates.
(The simultanous update of all `o_index` values got introduced in #4381)

Prevent deadlock when updating sibling indexes

---

models/Notification.php
models/Notification/Service/NotificationService.php
models/Notification/Service/UserService.php

Users without `notifications` permissions  with a role that has permission are not listed on recipient list.
Same problem is when we want to send notification to group, users without permission dont get the message.
1. Add Role with `notifications` permissions
2. Add user without `notifications` permissions and add him to created role
3. Try to send notification:
3.1. Try to send notification to him - he isnt listed on recipient list
3.2. Send notification to created group - used dont get the message

[Notifications] Role permission are not inherited

---

bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js

1. Create 2 quantity value units "g" and "kg"
1. Set "kg" as base unit of "g", set conversion factor to 0.001
1. Create data object class with quantity value field, set allowed units to "kg" and "g", enable auto-conversion
1. Open / Create new object
1. Change quantity value field's unit
This results in an error because previously there was no unit being set and the controller returns `null`.

[Quantity Value] Error when auto-converting unset unit

---

bundles/AdminBundle/Resources/public/js/pimcore/report/custom/toolbarenricher.js

fixes a Bug where Custom Reports are loaded with a wrong reportClass
* Create at least two custom reports
* Set different reportClasses on both reports
* Check "Create Shortcut in Menu" on both reports
* Reload Backend
* Click on the first custom report in the menu
Every report loads with its **own** configured reportClass
Every report loads with the configured reportClass **of the last report**
The `reportClass` inside `toolbarenricher.js` is read synchronously inside a for loop. The Menu-Item click handler is triggered asynchronously and uses the last set `reportClass`

fixes a Bug where Custom Reports are loaded with a wrong reportClass

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the GitHub PR template to the new version 6 of Pimcore.
Is Pimcore 4 still maintained and should be kept in the template or is it EOL and can be removed?

Update GitHub pull request template to new Pimcore version
