pimcore/pimcore

- pimcore/modules/admin/controllers/SettingsController.php
A solution for the request
https://www.pimcore.org/issues/browse/PIMCORE-2631
> remove views from DB to prevent corrupted tables

- index.php
- pimcore/cli/backup.php
@brusch requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/pimcore/pimcore/
> Scrutinizer Auto-Fixes

- composer.json
- pimcore/lib/Pimcore/Composer.php
[PIMCORE-2690](https://www.pimcore.org/issues/browse/PIMCORE-2690)
Verification: 
```composer create-project hagith/pimcore-boilerplate ./pimcore-test-project dev-pimcore-2690 --stability="dev"```
```pimcore-test-project``` should be cleaned.
> Replace installer-core with composer's "post-create-project-cmd"

- pimcore/config/texts/en.csv
> Typo fixed

- pimcore/models/Object/ClassDefinition.php
List is renamed to Listing. (Fix for: PIMCORE-2725)
https://www.pimcore.org/issues/browse/PIMCORE-2725
> Listing.php generated survives after deleting Class

- pimcore/lib/Pimcore/Model/Listing/AbstractListing.php
AbstractListing::addConditionParam without value don't works
https://www.pimcore.org/issues/browse/PIMCORE-2731
> Fix [PIMCORE-2731] AbstractListing::addConditionParam without value

- pimcore/modules/install/mysql/install.sql
Added index on "modificationDate" field for Assets, Objects and Documents, this dramatically improves the response time of the status portlets
> Improvement: added index on "modificationDate" database fields

- pimcore/static/js/pimcore/object/tree.js
> Prevent that empty class groups are created if there are no permitted classes.

- pimcore/models/Asset/Image.php
To make a problem like https://www.pimcore.org/board/viewtopic.php?f=11&t=161 easier to handle, I added the possibility to check if a given image asset is animated or not. I use it to check if I should put the full image path in the html tag or if I should use a thumbnail.
> Check on an Asset\Image if it is an animated gif or png

- pimcore/static6/js/pimcore/object/tree.js
Fixed issue where imports would be set 1 level above where the user selected
> ExtJS6 importer

- pimcore/static6/js/pimcore/settings/system.js
related to https://github.com/pimcore/pimcore/issues/292
> corrected the name field of language

- pimcore/models/Object/ClassDefinition/Layout/Button.php
- pimcore/static6/js/pimcore/object/classes/layout/button.js
- pimcore/static6/js/pimcore/object/helpers/edit.js
> Added "icon" option to buttons in class definition layout

- pimcore/static6/css/admin.css
> Multiline entries in mainmenu

- pimcore/static6/js/pimcore/object/helpers/customLayoutEditor.js
Default Layout was always 1 and padding looked untidy on editorview
> Fixes to the customlayout editor

- pimcore/static6/js/pimcore/object/tags/geopoint.js
Fixes https://github.com/pimcore/pimcore/issues/368
> Fixed isDirtyCheck when geopoint is not initially rendered

- pimcore/models/Object/ClassDefinition/Data/KeyValue.php
- pimcore/static/js/pimcore/object/classes/data/keyValue.js
- pimcore/static/js/pimcore/object/tags/keyValue.js
Some implementations were missing on the KeyValues, added those and fixed keyWidht being used for unit and desc widths.
> bugfix keyValue unit, key and desc widths

- pimcore/models/Document/Tag/Image.php
> Add text from copyright only once to thumbnail title and alt tags

- pimcore/static6/js/pimcore/report/custom/settings.js
> removed autoscroll from customreport settings panel

- pimcore/models/Object/Data/ObjectMetadata/Dao.php
- pimcore/static6/js/pimcore/document/tags/multihref.js
- pimcore/static6/js/pimcore/object/tags/multihref.js
- pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
See: https://github.com/pimcore/pimcore/pull/453
I also needed to change the DAO of Objects with metadata: **type** column needed to be added to the Primary key in order to prevent duplicate keys.
> Multihref support for different types of elements with same IDs

- pimcore/static6/js/pimcore/document/tags/area.js
The popup for edit.php window didn't open at all.
> FIX - edit.php popup didn't work for area editable

- pimcore/lib/Pimcore/Config.php
> fix getEnv #475

- pimcore/static6/js/pimcore/asset/asset.js
Partially fixes #480 
Added the ability the rename assets from their main window.
> Added ability to rename an asset from the asset view

- pimcore/static6/js/pimcore/object/tags/video.js
> Get video id from vimeo groups url

- pimcore/lib/Pimcore/Db.php
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_default_storage_engine
> fixes pimcore/pimcore#490

- pimcore/lib/Pimcore/Model/Listing/AbstractListing.php
Now you can use ``addConditionParams`` with named parameters.
> addConditionParams with named params

- pimcore/models/Object/Data/QuantityValue.php
- pimcore/static6/js/pimcore/object/tags/quantityValue.js
Fixes the display of quantity value field in the grid. Before only this was displayed: [Object object]
> QuantityValue display in grid

- pimcore/lib/Pimcore/Tool/Newsletter.php
I had to check if e-mail already exists in the database. I found 159 line commented out what made my task more difficult.
Although it's easy to extend this class, I think the method which I added in this commit can be useful generally. Check it out and accept if you think so.
> Checking if email exists in newsletter

- pimcore/lib/Pimcore/Tool/Admin.php
- pimcore/modules/admin/controllers/MiscController.php
- pimcore/modules/admin/controllers/SettingsController.php
I had to add a few hooks to my project but I think they can be useful in other cases as well.
If you accept the Pull Request I will update this page of documentation: https://www.pimcore.org/wiki/pages/viewpage.action?pageId=16854309
**System / General**
| Name | Target | Parameters | Description |
| --- | --- | --- | --- |
| system.maintenance.activate |  |  | This event is fired on maintenance mode activation |
| system.maintenance.deactivate |  |  | This event is fired on maintenance mode deactivation |
| system.cache.clearOutputCache |  |  |  |
| system.cache.clear |  |  |  |
| system.cache.clearTemporaryFiles |  |  |  |
> New hooks for maintenance and cache

- pimcore/lib/Pimcore/Tool/Admin.php
Due to https://github.com/pimcore/pimcore/pull/555
> Renamed maintenance hooks

- pimcore/static6/js/pimcore/settings/httpErrorLog.js
fixed problem http error log in extjs 6 user interface
> http error log problem in extjs 6

- pimcore/modules/admin/controllers/EmailController.php
strict fix in EmailController.php
> strict fix in EmailController.php

- pimcore/modules/admin/controllers/ObjectController.php
> fix sort order when using objectbrick #669

- pimcore/modules/admin/controllers/EmailController.php
Fixes # 
Emails Dynamic Properties throwing an exception when using custom-models.
check class before populating more data.
> fix email - enhanceLoggingData for custom models

- pimcore/models/Tool/CustomReport/Adapter/Analytics.php
- pimcore/models/Tool/CustomReport/Config.php
- pimcore/modules/reports/controllers/CustomReportController.php
this pr fixes some config object / array issues when creating an custom report with google analytics. (try to create a custom report on demo.pimcore.org with analytics).
> fix custom report config  when using analytics

- pimcore/models/Object/AbstractObject.php
count() on is_array() won't work and is tested in the same line anyways.
> Small fix in property handling

- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Decorator.php
- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php
- website_example/config/workflowmanagement.example.php
Moved
notesRequired
noteTitle
noteType
into their own object "notes" ... much cleaner :-)
> Workflowmanagement notes

- pimcore/static6/js/pimcore/report/custom/definitions/sql.js
- pimcore/static6/js/pimcore/report/custom/item.js
Fixes # 
- Removed Duplicate field in the general menu
+ Added cooldown on the SQL editor of 500ms so that each keypress doesn't spam the server!!
> Improvements to customreport settings

- pimcore/lib/Pimcore/Tool.php
> Fixed PHP warning if an option is not set

- pimcore/modules/admin/controllers/DocumentController.php
- pimcore/static6/js/pimcore/document/seopanel.js
Fixes and improvements:
-  `seopanelTreeRootAction()` now produces the same results for the root document as for the other documents.
- The SeoPanel now shows the reason for it's warnings as a tooltip.
- The edit panel now updates the amount of characters on typing.
- Editing the root document now updates it's data in the grid.
> Seo editor improvements

- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php
Allows the actionData to be accessed in the preAction event.
> Moved preAction event after actionData is set

- pimcore/modules/admin/controllers/ClassificationstoreController.php
- pimcore/modules/admin/controllers/QuantityValueController.php
Just some minor legacy classname fixes, but should also be done ;)
> legacy class name fixes

- pimcore/models/Object/Concrete.php
Someone wanted to be absolutely sure the method_existed ;-)
> Removed Duplicate method_exists condition

- pimcore/lib/Pimcore/Console/Command/CacheWarmingCommand.php
Fixes # 
fix object cache warming issue
fix when try to cache warming objects, cache warming asset instead.
https://groups.google.com/forum/#!topic/pimcore/Q-1fV4bmsqc
> fix object cache warming issue

- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php
Whoops, my fault on this one, I forgot to check the type being returned
> Workflowmanagement bugfix foreach on null value

- pimcore/lib/Pimcore/Console/Command/ClassesRebuildCommand.php
The class definition files are not .psf anymore but .php, the usage description is now reflecting this.
> Updated usage description

- pimcore/lib/Pimcore/Controller/Action/Frontend.php
Hi, this is just a check that the HttpErrorLog plugin exists, like on this line https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Action/Frontend.php#L595. M.
> check if HttpErrorLog plugin exists

- docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/05_Date_Types.md
Fixes # 
Because it is not clear what Carbon is.
> Added link to Carbon

- pimcore/modules/reports/controllers/CustomReportController.php
- pimcore/static6/js/pimcore/report/custom/report.js
Happy Friday @brusch!
Here is PR as promised in https://groups.google.com/forum/#!topic/pimcore/5BiNaPD1izU
This needs a new language file entry with the key
"export_csv_include_headers" - I have not included it in the PR
> Added ability to export headers with custom reports

- docs/Development_Documentation/10_Extending_Pimcore/13_Plugin_Developers_Guide/05_Plugin_Backend_UI.md
- pimcore/static6/js/pimcore/asset/tree.js
- pimcore/static6/js/pimcore/document/tree.js
- pimcore/static6/js/pimcore/object/tree.js
Adds the event to modify context-menus for objects, assets and documents #949
> Custom Context Menu Entries

- pimcore/models/User.php
throw Exception if password is under 5 characters long instate of ignore user input
Update User.php
> throw Exception if password is under 5 characters long

- docs/Development_Documentation/12_Administration_of_Pimcore/07_Users_and_Roles.md
Removed an unnecessary parenthesis.
> Minor typo fix in users/roles documentation.

- pimcore/static6/js/pimcore/object/object.js
Related to https://github.com/pimcore/pimcore/issues/994
> Rollback to unpublish action

- pimcore/static/css/admin.css
> prevent logo container overlapping the Objects bar

- docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/01_Text_Types.md
- pimcore/static6/js/pimcore/object/tags/wysiwyg.js
- Dont allow Global Configuration to change important settings
- Allow Custom Configuration to add "removePlugins"
- Add Global Configuration to Documentation
> Fixes for WYSIWYG global configuration

- pimcore/lib/Pimcore/View/Helper/HeadMeta.php
Hi,
this is just a getter for the new headMeta raw entries, so we can access them.
M.
> headMeta getRaw() getter

- docs/Development_Documentation/13_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
> [DOCS] Utilize nginx' $is_args Variable instead of hardcoding "?"

- docs/Development_Documentation/13_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
- docs/Development_Documentation/13_Installation_and_Upgrade/README.md
> Fix Link to nginx configuration

- docs/Development_Documentation/13_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
mirrors .htaccess' mod_status.c rules
> [DOCS] Integrate FPM and Nginx Ping/Status Locations

- docs/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
Just some small typo fixes in the documentation
> Fix 03_Working_with_PHP_API.md typos

- docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/23_Localized_Fields.md
> Added code for getting available languages.

- pimcore/models/Element/Tag.php
Fixes # 
Small fix that helps autocomplete :)
> Corrected return docblock

- pimcore/modules/searchadmin/controllers/SearchController.php
Fixes # 
The sort variable was ignored, this prevented class sorting for objects
> Fixed object sort

- pimcore/lib/Pimcore/Tool.php
I added some API PhpDoc for some parts I'm currently working with - maybe it's useful ;)
> Added PhpDoc in Pimcore\Tool

- docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/09_Relation_Types.md
> Fixed minor typo

- docs/Development_Documentation/10_Extending_Pimcore/13_Plugin_Developers_Guide/05_Plugin_Backend_UI.md
- pimcore/static6/js/pimcore/object/folder/search.js
prepareOnRowContextmenu object folder context menu js event, similar to the one in object tree
> prepareOnRowContextmenu object folder context menu js event

- pimcore/models/Object/Concrete.php
> php-doc: Fixed return of Concrete::setPublished()

- docs/Development_Documentation/13_Installation_and_Upgrade/09_Upgrade_Notes/02_V3_to_V4.md
> Add missing semicolon in V3 to V4 upgrade notes

- pimcore/models/Object/ClassDefinition/Data/CalculatedValue.php
Hi,
this PR fixes a small namespace bug in calculated value localized fields getter code generator. Maybe a post-update script which rebuilds classes with such calculated value fields should also be added.
Martin
> fix calculated value localized fields getter code

- docs/Development_Documentation/12_Administration_of_Pimcore/01_Backups.md
> Docs: Fixed command for creating a single backup

- pimcore/modules/admin/views/scripts/index/index6.php
See compared profiles (almost 68% faster)
https://blackfire.io/profiles/compare/bfd2200f-ac71-4795-bc37-1b98b3e18945/graph
> Cache minified css generation 

- docs/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
Please read our [contributing guidelines](/CONTRIBUTING.md) before you submit a PR.
> Added chapter with WkHtmlToPdf settings

- docs/Development_Documentation/06_Multi_Language_i18n/README.md
> Clarified the differences in front end and back end

- docs/Development_Documentation/03_Documents/01_Editables/10_Date.md
Point PHP manual link to strftime instead of date
> Point PHP manual link to strftime instead of date

- docs/Development_Documentation/13_Installation_and_Upgrade/03_System_Setup_and_Hosting/README.md
> Fix (another) Link to nginx documentation

- docs/Development_Documentation/01_Getting_Started/00_Installation.md
> Fix Link to nginx Documentation

- pimcore/lib/Pimcore/Console/Command/ClassesRebuildCommand.php
Pull Request for pimcore/pimcore#1228
> Add Create Option to classes-rebuild

- docs/Development_Documentation/08_Tools_and_Features/07_Properties.md
> Fixed typo

- pimcore/models/Object/ClassDefinition/Data/QuantityValue.php
- pimcore/models/Object/Objectbrick/Definition.php
Issues Warnings in PHP Language Server: https://github.com/felixfbecker/php-language-server
> Type annotations should not have brackets

- docs/Development_Documentation/14_Web_Services/README.md
- pimcore/modules/webservice/controllers/RestController.php
This is a pull request for: https://github.com/pimcore/pimcore/issues/1086
I added three services:
- tags: list of tags
- tags for element: list of tags for an element
- elements for tag: list of elements for a tag
> Add webservices for tags

- pimcore/static6/js/pimcore/element/tag/imagecropper.js
getStyles is not a function. i replaced it with getStyle which is working.
> getStyles causes a javascript error

- pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php
> Fixes typo in phpdocType for MultihrefMetadata

- pimcore/modules/admin/controllers/ObjectHelperController.php
Fixes # 
csv export brick fix ambiguous o_id err
specify table name to fix err
> csv export brick fix ambiguous o_id err

- docs/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
Updated custom routes documentation:
Added an example to understand the meaning of priorities
> Updated custom routes documentation (added setting priorities)

- pimcore/models/Webservice/Data/ClassDefinition.php
Allow exporting of group in class definition export
> export group in class definition

- docs/Development_Documentation/04_Assets/README.md
Closes #1306 
Added note about google services.
> Added note about Google services for preview

- README.md
> adds missing line-break in README

- docs/Development_Documentation/09_Development_Tools_and_Details/23_Placeholders/01_Object_Placeholder.md
- pimcore/lib/Pimcore/Placeholder/Object.php
Added option to convert text with nl2br in object placeholders.
> nl2br option for object placeholders

- docs/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/23_Localized_Fields.md
> Added info on admin and website translations

- docs/Development_Documentation/08_Tools_and_Features/27_Website_Settings.md
The old way using config files ( like described here https://www.pimcore.org/board/viewtopic.php?t=936 ) is no longer valid but still very present in google so I added the current way to the docs.
> Add info about manipulating website settings in PHP

- pimcore/models/Document/Page.php
Fixes # 
Db wasn't included in Page.php class.
`$siteId = Db::get()->fetchOne($siteCheckQuery, [$this->getId()]);`
> Fixes update method in Page.php

- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
- pimcore/lib/Pimcore/Routing/Dynamic/DocumentRouteHandler.php
- pimcore/lib/Pimcore/Routing/Dynamic/DynamicRequestContext.php
- pimcore/lib/Pimcore/Routing/Dynamic/DynamicRouteHandler.php
- pimcore/lib/Pimcore/Routing/Dynamic/DynamicRouteHandlerInterface.php
- pimcore/lib/Pimcore/Routing/DynamicRouteProvider.php
- pimcore/lib/Pimcore/Routing/Staticroute/Router.php
- pimcore/lib/Pimcore/Service/Request/SiteResolver.php
- pimcore/models/Document/Dao.php
> Missing routing functionalities

- doc/Development_Documentation/01_Getting_Started/08_Pimcore_5_For_Pimcore_Devs.md
Fixed some spelling errors
Fixes #
> 08_Pimcore_5_For_Pimcore_Devs.md

- docs/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/03_Variants.md
> typo in doc

- pimcore/lib/Pimcore/Tool/Session.php
Deleted unreachable catch statement.
> Session Tool - Unreachable catch statement

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LogController.php
- web/pimcore/static6/js/pimcore/log/admin.js
Application Logger improvements #1437
> Application Logger improvements #1437

- pimcore/models/Object/ClassDefinition/Data/QuantityValue.php
This pull request contains the same bugfix as in #1456 for pimcore 4.
> QuantityValue getFromWebserviceImport bugfix (pimcore 4)

- doc/Development_Documentation/24_Web_Services/README.md
Fix typo in "Get Object Count"
> Fix typo in doc 24_Web_Services

- pimcore/static6/js/pimcore/helpers.js
> MultiRelation path formatter layout bugfix (pimcore 4)

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ObjectController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/VariantsController.php
> ported fix for #1453 to PC5

- pimcore/models/Object/Service.php
> Fixes possible SQL Injection

- pimcore/models/Document/Tag/Snippet.php
- [ x] Read and accept our [contributing guidelines](/CONTRIBUTING.md) before you submit a PR.
- [x ] Submit bugfixes for version 4 to the target branch `pimcore4`, version 5 is `master` branch.
> Fix: Errors are not logged if in debug mode

- install-profiles/demo-cms/app/Resources/views/Advanced/contactForm.html.php
- install-profiles/demo-cms/app/Resources/views/Advanced/objectForm.html.php
- install-profiles/demo-cms/app/Resources/views/Form/default/form_errors.html.php
- install-profiles/demo-cms/app/Resources/views/Form/default/form_row.html.php
- install-profiles/demo-cms/src/AppBundle/Controller/AdvancedController.php
- install-profiles/demo-cms/src/AppBundle/Form/ContactFormType.php
- install-profiles/demo-cms/src/AppBundle/Form/PersonInquiryType.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml
- pimcore/lib/Pimcore/Tool/HybridAuth.php
Resolves #1493. Changes forms used in the Demo to Symfony forms.
> [DEMO] Form usage

- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Command/GenerateBundleCommand.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Generator/BundleGenerator.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/PimcoreGeneratorBundle.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Resources/skeleton/bundle/Bundle.php.twig
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Resources/skeleton/bundle/DefaultController.php.twig
- pimcore/lib/Pimcore/Console/AbstractCommand.php
- pimcore/lib/Pimcore/Console/Style/PimcoreStyle.php
- pimcore/lib/Pimcore/Kernel.php
Resolves #1384.
Extends the `generate:bundle` command and adds template/config for Pimcore bundles.
> Pimcore Bundle Generator

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
- [ x] Submit bugfixes for version 4 to the target branch `pimcore4`, version 5 is `master` branch.
Add initial, slightly tested, but working Nginx Config for Pimcore 5.
> Initial Config Example for Nginx

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/11_Blocks.md
Single lone how to create a Element for a block
> Create a BlockElement

- pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/CacheCollectorPass.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/PimcoreCoreBundle.php
- pimcore/lib/Pimcore/Cache/Pool/PimcoreCacheItemPoolInterface.php
- pimcore/lib/Pimcore/Cache/Pool/TraceablePimcoreAdapter.php
Related to #1510. Adds pimcore core cache to web profiler toolbar.
> [CACHE] Collect pimcore core cache data with profiler cache collector

- doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/MiscController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/DependencyInjection/Compiler/ServiceControllersPass.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/PimcoreAdminBundle.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
- pimcore/lib/Pimcore/Routing/Staticroute/Router.php
fixes #1405 
Adds possibility to use a controller as a service in Static Routes.
> [Static Routes] load controller from service

- pimcore/lib/Pimcore/Console/Command/MaintenanceCommand.php
- pimcore/models/Schedule/Manager/Procedural.php
> Exclude Jobs from maintenance script 

- pimcore/lib/Pimcore/Bundle/CoreBundle/Command/MaintenanceCommand.php
- pimcore/models/Schedule/Manager/Procedural.php
> [PIMCORE5] Exclude Jobs from maintenance script

- pimcore/lib/Pimcore/Document/Tag/TagHandler.php
Fix HTML Markup for edit template of areabricks
> Fix HTML Markup for edit template of areabricks

- doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
- doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/Exception/TagNameException.php
- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/LegacyNamingStrategy.php
- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/NamingStrategyInterface.php
- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/NestedNamingStrategy.php
- pimcore/models/Document/Tag.php
- pimcore/models/Document/Tag/Area.php
- pimcore/models/Document/Tag/Areablock.php
- pimcore/models/Document/Tag/Areablock/Item.php
- pimcore/models/Document/Tag/Block.php
- pimcore/models/Document/Tag/Block/AbstractBlockItem.php
- pimcore/models/Document/Tag/Block/Item.php
> [Documents] Area/Areablock/Blocks fluent getElement() interface for new editable naming

- doc/.markdownlint.json
- doc/Development_Documentation/01_Getting_Started/00_Installation.md
- add Section 5.1 with a hint regarding randomness in start times of cron jobs
- add a minimalisitic markdownlint.json matching current style (more or less).
> [DOCS] maintenance cron, markdownlint

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DocumentController.php
add missing $request arg to verstionToAction call.
> add arg to versionToAction() call

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Controller/PricingController.php
Ecommerce Framework bugfix:
the price rule controller now also takes role permissions into account, not only user permissions.
> Consider role permissions in price rule overview.

- docs/Development_Documentation/13_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
I found that I had to make this adjustment to get /modules/static/* to return any static files in modules.
> [PIMCORE4] Support static files in modules

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/ICartPriceCalculator.php
> Ecommerce: Provide the possibility to recalculate/reset the price modificators manually

- website_demo/config/customviews.example.php
Unable to hide the import csv menu item via custom views.
Corrected flag naming
> Corrected importCsv flag

- pimcore/static6/js/pimcore/object/tags/objectbricks.js
Same bug as https://github.com/pimcore/pimcore/pull/1751 but here's PIM4 fix.
> [PIMCORE4] Fix "Limit reached" bug in objectbricks.js

- web/pimcore/static6/js/pimcore/object/classes/data/data.js
1. Create new class
2. Add a Panel and an Input
3. Name Input "property"
4. Save class definition
4.1. There is no Error in here
5. Try to create an object
5.1. Here we have an error
> Property added to forbidden names for object

- pimcore/static6/js/pimcore/object/classes/data/data.js
Same bug as #1757 but here's PIM4 fix.
> [Pimcore4] Property added to forbidden names for object

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
> $this->_getParam() -> $request->get()

- docs/Development_Documentation/10_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/lib/Pimcore/Web2Print/Processor/PdfReactor8.php
- pimcore/lib/Pimcore/Web2Print/Processor/WkHtmlToPdf.php
Added events (document.print.processor.modifyProcessingOptions + document.print.processor.modifyConfig) to modify the processing options of the Web2Print adapter.
> [PIMCORE 4] Web2print events

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PricingManager/Action/Gift.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
- Improved serialization of gift item objects in pricing rules.
- Allow assignment of object variants in pricing rules (gift items)
> Ecommerce | Pricing rule optimisations

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/External/AdminerController.php
This issue fixes local Problems (MAMP) I have with Adminer. MAMP uses fcgi, and fcgi throws an exception when multiple of the same HTTP Headers come. The issue is, that adminer sets HTTP-Headers using the header() function, and symfony sets them via the response object. Both of them set the Content-Type header and fcgi throws an error therefore. 
PS: It seems this fixes styling issues as well, but I am not sure, would be nice if somebody could confirm that.
> [Adminer] Issue with FastCGI (duplicate-headers)

- pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
- pimcore/models/Object/ClassDefinition/Data/Fieldcollections.php
- pimcore/models/Object/Fieldcollection/Dao.php
> Override fieldcollections

- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php
- website_example/config/workflowmanagement.example.php
The workflow Manager now checks all element types including object sub types such as variants
Can be easily ported to Pimcore 5 :)
> [Pimcore 4] Added type restrictions into workflow manager

- web/pimcore/static6/js/pimcore/object/objectbricks/field.js
re-adds my js changes introduced in #1594 and fixes case #1889
> [ExtJS] fixes for case #1889

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
see https://github.com/pimcore/pimcore/pull/1891
> [Pimcore5] Fix to CSV Import

- pimcore/lib/Pimcore/Tool/Mime.php
- pimcore/static/css/icons.css
- pimcore/static6/css/icons.css
photo shop big => like .psd but for large files
> Mime type support for .psb

- pimcore/models/Object/ClassDefinition/Data/Block.php
- pimcore/models/Object/ClassDefinition/Data/Localizedfields.php
- pimcore/models/Object/Localizedfield.php
Only allow full inheritance of blocks - not single fields in localized fields
> Only allow full inheritance of blocks - not single fields in localized fields

- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Command/GenerateBundleCommand.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Command/Helper/QuestionHelper.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Generator/BundleGenerator.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Model/Bundle.php
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Resources/skeleton/bundle/Bundle.php.twig
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Resources/skeleton/bundle/services.yml.twig
- pimcore/lib/Pimcore/Bundle/GeneratorBundle/Resources/skeleton/js/pimcore/startup.js.twig
> Bundle generator improvements

- web/pimcore/static6/js/pimcore/asset/document.js
> Fixed invalid GET parameter stacking

- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/TagManagerListener.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- web/pimcore/static6/js/pimcore/settings/tagmanagement/item.js
Resolves #1893. Allow to enable tags via flag on tag level.
> Tag and Snippet Manager: disable tags in editmode

- pimcore/static6/js/pimcore/object/tags/geo/abstract.js
Here is the pull request for https://github.com/pimcore/pimcore/issues/1866#issuecomment-326090844, adding changes made in Pimcore 5 to Pimcore 4.
> google offline

- web/pimcore/static6/js/pimcore/settings/docTypes.js
This PR adds the combo-box selection for bundle/controller/action/template to document-types.
> [ExtJs] add combo-box selection for bundle/controller/action/template to doc-types

- pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
> don't throw exception if adapter factory is not found in container

- doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
This is the pull request for https://github.com/pimcore/pimcore/issues/1935#issuecomment-328433533 adding a note on documentation about config YAML and environment when using custom environment tag to be able to install Pimcore.
> [Pimcore 5] Adding note on documentation about config YAML and environment.

- pimcore/lib/Pimcore/Cache/Pool/Redis.php
- pimcore/tests/cache/Pool/TaggableRedisTest.php
- pimcore/tests/cache/Pool/Traits/CacheItemPoolTestTrait.php
- pimcore/tests/cache/Pool/Traits/RedisItemPoolTrait.php
> [CACHE][REDIS] Fix redis cache with LUA not clearing invalidated tags from zc:tags set

- pimcore/models/Document/Tag.php
Just a proposition since this made migrating area bricks a lot smoother for me.
> Catch \Throwable instead of \Exception

- doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/01_Price_Systems_and_getting_Prices.md
> Fixed variable spelling mistake

- pimcore/models/Object/Concrete/Dao/InheritanceHelper.php
Inheritance can send some undefined errors.
This pull request prevent them for Pimcore 4.
Maybe Pimcore 5 need to be patched as well.
Thanks
> [Pimcore 4] Inheritance can send some undefined errors.

- pimcore/models/DataObject/Concrete/Dao/InheritanceHelper.php
This is the PR containing same fix than https://github.com/pimcore/pimcore/pull/1992 for Pimcore 5.
> [Pimcore 5] Inheritance can send some undefined errors.

- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
Fixes #2060 
* Fixes wrong condition preventing domain redirect
* Handles main domain redirect for admin requests
* Only redirect in master requests
> [ROUTING] Fix main domain redirect handling

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/01_Basic_Migration.md
Composer merge plugin introduced in PR #1625
> Doc update: mention composer.local.json

- doc/Development_Documentation/19_Development_Tools_and_Details/37_Migrations.md
updated wording in documentation
> updated wording

- doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/05_Klarna.md
Added the instructions how to provide Klarna the cart items.
> Added instructions for Klarna CartItems

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/IndexService/AttributeFactory.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php
This pull request fixes several bugs regarding elasticsearch index services.
> [ECOMMERCE] elasticsearch fixes

- pimcore/models/Object/ClassDefinition/Data/Select.php
- pimcore/static6/js/pimcore/object/classes/data/select.js
- update/4104/postupdate.php
Issue https://github.com/pimcore/pimcore/issues/2077
> Select datatype - Columnlength

- doc/Development_Documentation/03_Documents/01_Editables/16_Input.md
- doc/Development_Documentation/03_Documents/01_Editables/34_Table.md
- doc/Development_Documentation/03_Documents/01_Editables/36_Textarea.md
- doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
I updated some of the documentation about how to use a editable in twig.
> [DOCS] Update documentation for using a editable in twig

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/11_Blocks.md
More information how to create a block programmatically
> More information how to create a block programmatically

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/11_Blocks.md
> forgotten one quote

- doc/Development_Documentation/10_E-Commerce_Framework/19_Tracking_Manager.md
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/config/pimcore/config.yml
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/config/tracking_manager.yml
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/views/Tracking/piwik/calls.js.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/ICartProductActionAdd.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/ICartProductActionRemove.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/ICartUpdate.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/ICategoryPageView.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/IProductActionRemove.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/ITrackingManager.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/TrackingItemBuilder.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/TrackingManager.php
> [PIWIK] Ecommerce Tracker

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LogController.php
- web/pimcore/static6/js/pimcore/log/admin.js
- web/pimcore/static6/js/pimcore/log/detailwindow.js
* Now uses a SQL query builder to avoid SQL injection possibilities
* Removes obsolete filename entry handling
* Fixes fileobject link in grid and detail window
* Fixes related documents not being opened from detail window
> Application Logger: Admin Fixes

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
This PR add setHideUnpublished to the documentation.
Please see: https://github.com/pimcore/pimcore/issues/2158
> Adding setHideUnpublished method to documentation

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
Fixes #2090. Fixes deprecation warnings with ecommerce framework and advanced demo.
Additional changes:
* pimcore/demo-ecommerce@75aba5008da107553deebd2675bdf631e8ef9d64
* pimcore/customer-data-framework#35
* pimcore/advanced-object-search@f7997f2e72b2253f016ea8b70a49408a32b6559e
> [ECOMMERCE] Fix deprecation warnings for ecommerce service locators

- pimcore/lib/Pimcore/Mail.php
- pimcore/lib/Pimcore/Mail/Plugins/RedirectingPlugin.php
> [MAIL] Save debug actual recipients to mail log, not the original ones

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFindologic.php
fixed usage of legacy class
@maff @fashxp
> fixed usage of legacy class

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PricingManager/Action/Gift.php
> fixed usage of legacy-class

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PricingManager/Condition/DateRange.php
remove zend_date method usages and replace them with DateTime methods
@fashxp  @maff
> fix Zend_Date method usages

- doc/Development_Documentation/03_Documents/01_Editables/08_Checkbox.md
- doc/Development_Documentation/03_Documents/01_Editables/10_Date.md
- doc/Development_Documentation/03_Documents/01_Editables/12_Href.md
- doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
- doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
- doc/Development_Documentation/03_Documents/01_Editables/20_Multihref.md
- doc/Development_Documentation/03_Documents/01_Editables/25_Embed.md
- doc/Development_Documentation/03_Documents/01_Editables/26_PDF.md
- doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
- doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md
- doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
- doc/Development_Documentation/03_Documents/01_Editables/README.md
> Update the twig documentation

- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
- web/pimcore/static6/js/pimcore/layout/toolbar.js
- keep menu open when moving mouse over "files"
- fix offset of sub menu when clicking on menu icon
> Admin menu small fixes

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/implementation_factories.yml
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/OrderManager.php
- pimcore/lib/Pimcore/Loader/ImplementationLoader/ClassMapLoader.php
- pimcore/lib/Pimcore/Loader/ImplementationLoader/ImplementationLoader.php
- pimcore/lib/Pimcore/Model/Factory.php
- pimcore/lib/Pimcore/Model/FactoryInterface.php
Fixes #2198 
Model factory is injected via setter for BC.
> [ECOMMERCE] Build order manager models via model factory

- doc/Development_Documentation/01_Getting_Started/07_Homestead_Vagrant_Development_Setup.md
Added dependencies installation to after.sh script.
Added instruction for enabling NFS on Linux and Windows
> Update 07_Homestead_Vagrant_Development_Setup.md - dependencies and NFS support

- doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/lib/Pimcore/Event/ElementEvents.php
- pimcore/lib/Pimcore/Event/Model/ElementEvent.php
- pimcore/models/Element/Note.php
Added pimcore.element.note.postAdd event
> Added pimcore.element.note.postAdd event

- docs/Development_Documentation/10_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/models/Element/Note.php
Added element.note.postAdd Event
> Add element.note.postAdd Event

- doc/Development_Documentation/10_E-Commerce_Framework/17_Order_Manager/02_Working_with_Order_Agent.md
Code example was using old style (deprecated) namespaces
> Corrected namespace of OnlineShopOrder

- pimcore/lib/helper-functions.php
There was two "" at the end og the img tag
> There was two " at the end.

- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- web/pimcore/static6/js/pimcore/object/classes/data/multihrefMetadata.js
- web/pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
Converted functionality from #2266 to Pimcore5.
> PIMCORE5 MultihrefMetdata columnbool

- pimcore/models/DataObject/ClassDefinition/Data/Block.php
- web/pimcore/static6/js/pimcore/object/classes/data/block.js
- web/pimcore/static6/js/pimcore/object/tags/block.js
"Block" Object type - Added field to define custom CSS-Styles for the specific block panels
> Added field for custom element style in block Datatype

- doc/Development_Documentation/00_Overview/README.md
- doc/Development_Documentation/01_Getting_Started/02_Directory_Structure.md
- doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
- doc/Development_Documentation/01_Getting_Started/07_Homestead_Vagrant_Development_Setup.md
- doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md
- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
- doc/Development_Documentation/02_MVC/02_Template/README.md
- doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
- doc/Development_Documentation/02_MVC/04_Routing_and_URLs/README.md
- doc/Development_Documentation/02_MVC/README.md
- doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
- doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
- doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
- doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
- doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/README.md
- doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md
- doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
- doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/01_Loading_Service_Definitions.md
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
- doc/Development_Documentation/20_Extending_Pimcore/13_Dependency_Injection_Tags.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/02_V4_to_V5.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/03_Ecommerce_Framework/02_Ecommerce_Framework_Config_Signature_Changes.md
Now every reference to symfony docs points to 3.4 version.
> Update symfony doc urls (now points to 3.4 version).

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/AbstractCart.php
This fixes a bug in cart creation timestamp.
> Bugfix for creation timestamp in cart

- pimcore/lib/Pimcore/Translation/Translator.php
> Fallback translation in combination with caseinsensitive website translations

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
Note: Tested only on current Debian
> [Docs] add description on how to install SQIP / svg Placeholder

- doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/05_Analytics.md
- doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/README.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
- pimcore/lib/Pimcore/Analytics/Google/Config/Config.php
- pimcore/lib/Pimcore/Analytics/Google/Config/ConfigProvider.php
- pimcore/lib/Pimcore/Analytics/Google/Config/SiteConfigProvider.php
- pimcore/lib/Pimcore/Analytics/Google/Event/TrackingDataEvent.php
- pimcore/lib/Pimcore/Analytics/Google/Tracker.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/IndexController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/PortalController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Reports/AnalyticsController.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/GoogleAnalyticsCodeListener.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/analytics.yml
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Analytics/Tracking/Google/Analytics/asynchronousTrackingCode.html.twig
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Analytics/Tracking/Google/Analytics/universalTrackingCode.html.twig
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/AbstractAnalyticsTracker.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/Ecommerce.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/UniversalEcommerce.php
- pimcore/lib/Pimcore/Event/Analytics/GoogleAnalyticsEvents.php
- pimcore/lib/Pimcore/Google/Analytics.php
Google Analytics part of #2149.
> [Analytics] Refactor Google Analytics code generation to code blocks

- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Google/TagManager/codeBody.html.twig
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Google/TagManager/codeHead.html.twig
- pimcore/lib/Pimcore/Event/Analytics/Google/TagManager/CodeEvent.php
- pimcore/lib/Pimcore/Event/Analytics/GoogleTagManagerEvents.php
> [Analytics] Refactor Google Tag Manager code generation to code blocks

- doc/Development_Documentation/00_Overview/00_Pimcore_Ecosystem.md
Nothing important, but good to have all places in one resource list :smile_cat:
> Pimcore Community Forums added to the resources

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
> [docs] fix Nginx Config to make Adminer and Linfo work again

- pimcore/lib/Pimcore/Bundle/CoreBundle/Command/Composer/NormalizeConfigCommand.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Compiler/ComposerConfigNormalizersPass.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/PimcoreCoreBundle.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/services.yml
- pimcore/lib/Pimcore/Composer/Config/ConfigMerger.php
- pimcore/lib/Pimcore/Composer/Config/Normalizer/EndroidQrCodeRenamedPackageNormalizer.php
- pimcore/lib/Pimcore/Composer/Config/Normalizer/Php7PlatformNormalizer.php
- pimcore/lib/Pimcore/Composer/Config/NormalizerInterface.php
- pimcore/lib/Pimcore/Update.php
- pimcore/tests/unit/Composer/Config/Normalizer/EndroidQrCodeRenamedPackageNormalizerTest.php
- pimcore/tests/unit/Composer/Config/Normalizer/Php7PlatformNormalizerTest.php
> [UPDATER] Normalize composer.json on merge

- doc/Development_Documentation/01_Getting_Started/03_Configuration.md
- doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
- doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
- doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/README.md
- doc/Development_Documentation/18_Tools_and_Features/17_Application_Logger.md
- doc/Development_Documentation/18_Tools_and_Features/25_System_Settings.md
- doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Permissions.md
Every link should point to correct version now.
> Update symfony doc urls.

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/HardlinkController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LinkController.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- pimcore/models/Document/Hardlink.php
- pimcore/models/Document/Link.php
- pimcore/models/Document/PageSnippet.php
- pimcore/models/Document/Traits/ScheduledTasksTrait.php
- web/pimcore/static6/js/pimcore/document/hardlink.js
- web/pimcore/static6/js/pimcore/document/link.js
- web/pimcore/static6/js/pimcore/element/scheduler.js
> Scheduling support for links and hardlinks

- doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/lib/Pimcore/Event/MailEvents.php
- pimcore/lib/Pimcore/Event/Model/MailEvent.php
- pimcore/lib/Pimcore/Mail.php
public function onPreSendMail(ElementEventInterface $e)
{
$arguments = $e->getArguments();
//unset($arguments['mailer']); <- do completely custom sending
//$arguments['mailer'] = new \Swift_Mailer(...) <- custom implementation
$e->setArguments($arguments);
//change mail settings
$mail = $e->getMail();
$mail->setFrom('mofified@example.com');
}
> Added Event pimcore.mail.preSend event

- docs/Development_Documentation/10_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/lib/Pimcore/Mail.php
Added mail.preSend Event to modify settings before the email is sent.
> Added mail.preSend Event

- doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
> Add SQIP - SVG Placeholder

- pimcore/models/Asset.php
- pimcore/models/Asset/Document.php
- pimcore/models/Asset/Image.php
- pimcore/models/Asset/Video.php
- pimcore/models/DataObject/Folder.php
- pimcore/models/Document/Hardlink.php
- pimcore/models/Document/Page.php
- pimcore/models/Document/PageSnippet.php
This PR fixes all invalid "@params" annotations
> fix all params annotations

- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar.css
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/views/Targeting/toolbar/toolbar.scss
> Bugfix for overlay targeting toolbar

- pimcore/lib/Pimcore/Install/Installer.php
+(add) re-usability to checker-method and convert it into a extractor
- (fix) broken installer state if db requirements are missing
- (removed) unneeded duplicates
> BugFix - Installer - broken-web-installer

- pimcore/lib/Pimcore/Bundle/InstallBundle/Command/InstallCommand.php
- pimcore/lib/Pimcore/Bundle/InstallBundle/Resources/config/config.yml
- pimcore/lib/Pimcore/Console/ConsoleOutputDecorator.php
- pimcore/lib/Pimcore/Install/Event/InstallerStepEvent.php
- pimcore/lib/Pimcore/Install/Installer.php
Instead of dumping the whole install log to the CLI, the install command now shows a progress bar and points to the install log.
> [INSTALLER] CLI Installer UX

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/config/services.yml
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tools/Installer.php
- update-scripts/202/preupdate.php
> [ECOMMERCE] Refactor installer to use migrations

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
Resolves #2392
Availability of checkout steps is now checked at runtime when a state change is about to be processed.
> [ECOMMERCE] Do not demand checkout steps for checkout manager initialization

- composer.json
- pimcore/lib/Pimcore/Http/Response/CodeInjector.php
- pimcore/lib/Pimcore/Http/ResponseHelper.php
- pimcore/tests/unit/Http/Response/CodeInjectorTest.php
Resolves #2402 by adding support for arbitrary CSS selectors.
> Add support for arbitrary DOM selectors in CodeInjector

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/29_Image_Types.md
> example how to populate an ImageGallery

- doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing.md
- install-profiles/demo-basic/manifest.yml
- install-profiles/demo-basic/phpunit.xml.dist
- install-profiles/demo-basic/tests/AppBundle/Controller/ContentControllerTest.php
- install-profiles/demo-basic/tests/AppBundle/ExampleTest.php
- install-profiles/demo-basic/tests/AppBundle/Form/LoginFormTypeTest.php
- install-profiles/demo-basic/tests/bootstrap.php
- pimcore/lib/Pimcore/Kernel.php
- pimcore/lib/Pimcore/Test/KernelTestCase.php
- pimcore/lib/Pimcore/Test/WebTestCase.php
* Add PHPUnit test setup to `demo-basic` install profile
* Add documentation how to test applications with PHPUnit and/or Codeception
> Test docs and demo setup

- pimcore/modules/admin/controllers/AssetController.php
Create asset folder with contents
Try to:
1.  Delete it
2.  Copy it
> Several fixes with deleting, copying.

- pimcore/models/GridConfig/Listing.php
> Fixing typo in GridConfig\Listing

- pimcore/models/DataObject/Fieldcollection/Dao.php
I stumbled upon a call to the Logger class within the old namespace and fixed it in this PR.
> Added correct namespace for a call to the Pimcore\Logger class

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php
> [ECOMMERCE/INDEXSERVICE/ELASTICSEARCH]: Fix for checking for errors on bulk update

- pimcore/lib/Pimcore/Config.php
Just mistake about variable name
> Just a small mistake

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultElasticSearch.php
> [ECOMMERCE/INDEXSERVICE/ELASTICSEARCH] Compat-fixes for Elasticsearch 5.x

- web/pimcore/static6/js/pimcore/object/tags/video.js
fixes #2650
Youtube integration changes to no-cookie option
> Switched youtube integration to non-cookie option

- pimcore/models/DataObject/Listing.php
`loadIdList()` returns an array of int
> Fixed phpDoc

- doc/Development_Documentation/18_Tools_and_Features/07_Properties.md
> Add Twig example

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- web/pimcore/static6/js/pimcore/asset/tree.js
Fixes #2667 
Empty file(0 byte) check added to throw error messages
> Added empty file upload check in js and AssetController

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/NumberRange.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/NumberRangeSelection.php
* Fixed range-condition of Elasticsearch/NumberRange[Selection]
* Allow value zero in from/to of Elasticsearch/NumberRange[Selection]
> [ECOMMERCE][FILTERSERVICE] Misc FilterService fixes

- doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- pimcore/lib/Pimcore/Event/Model/TranslationEvent.php
- pimcore/lib/Pimcore/Event/TranslationEvents.php
- pimcore/models/Translation/AbstractTranslation.php
> Added Translation (admin and shared) events.

- pimcore/models/DataObject/Objectbrick/Data/AbstractData.php
Mixed up pimcore 4 and 5 here.
Sorry for that..
> Fixed Object -> DataObject

- web/pimcore/static6/js/pimcore/report/analytics/elementoverview.js
PR for https://github.com/pimcore/pimcore/issues/2583
> GA overview - missleading source tooltip (#2583)

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tracking/TrackingItemBuilder.php
Add getProductBrand for using a Brand for Products.
> Add getProductBrand in TrackingItemBuilder.php

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Utilize nginx rate limiting to protect the server from overload by too many thumbnail generation processes in parallel.
> [docs] nginx thumbnail overload protection

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/13_Amazon_AWS_Setup/03_Amazon_AWS_S3_Setup.md
copied the documentation from Pimcore 4 and modified according to how I configured Pimcore 5 to use S3 for assets
> add documentation for Amazon AWS S3 Setup

- doc/Development_Documentation/26_Best_Practice/03_Object_Bricks_vs_Classification_Store.md
object bricks vs classification store
> Added best practice article

- doc/Development_Documentation/26_Best_Practice/04_Showing_Custom_Layouts_based_on_Object_Data.md
Showing Custom Layouts based on Object Data
> Added best-practice article

- web/pimcore/static6/js/pimcore/helpers/generic-grid.js
- web/pimcore/static6/js/pimcore/object/classificationstore/collectionsPanel.js
- web/pimcore/static6/js/pimcore/object/classificationstore/groupsPanel.js
- web/pimcore/static6/js/pimcore/object/classificationstore/propertiesPanel.js
Fixes #2751 
Added `batchActions: false` property to all Grid Proxy
> Add batchActions false property to grid proxy

- pimcore/models/DataObject/Objectbrick/Definition.php
Made some minor fixes to satisfy some GUI inspections
> Fixed generated PHPDoc, fixed double semicolon

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Fixes #2786
Remove $1 at end of rewrite to install.php
> [docs] fix Pimcore Installer not working on nginx

- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/DataObject/diffVersions.html.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/DataObject/previewVersion.html.php
- Added field collection attributes in version preview
- Added field collection comparison in version diff preview
> Fieldcollection preview version

- web/pimcore/static6/js/pimcore/layout/portlets/customreports.js
> Support table view of custom reports on dashboards

- web/pimcore/static6/js/pimcore/document/document.js
- web/pimcore/static6/js/pimcore/document/tree.js
Update document path if open when it is moved within the document tree
> Update document path on tree move

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
- web/pimcore/static6/js/pimcore/object/folder/search.js
- web/pimcore/static6/js/pimcore/object/helpers/gridConfigDialog.js
- web/pimcore/static6/js/pimcore/object/helpers/gridTabAbstract.js
resolves #2774 
Added option to set "Items Per Page" in column configuration
> Store page size in column configuration

- pimcore/lib/Pimcore/Tool.php
Latvia flag icon instead of Lithuania flag
This PR fixes wrong lithuanian flag in admin panel
> Fix for lithuanian flag icon

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
> Edit Zend\Paginator Info

- web/pimcore/static6/js/pimcore/object/classes/data/inputQuantityValue.js
> Input Quantity Value - bug fix for default_value type

- pimcore/models/DataObject/ClassDefinition.php
fixes #2784 - Strange ClassDefinition formatting when saving via listing
> Optimized ClassDefinition Loading/Saving

- composer.json
- pimcore/lib/Pimcore/Localization/Locale.php
resolves #2622 
Tadschikistan and Turkmenistan will be shown in country list of objects country field. It uses 3rd party bundle umpirsky/country-list for listing all the countries.
> Tadschikistan and Turkmenistan not apear in the Countrylist 

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/EmailController.php
- web/pimcore/static6/js/pimcore/settings/email/log.js
Fixes:
* Escape mail subject
* Escape text email body
> Admin/Email: Escape email subject and text-body

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
Suggestion as bugfix for #2877. The change may be reviewed to match all possibilities.
Fixes #2877
> Support for product search with array of strings

- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/AbstractNamingStrategy.php
- pimcore/lib/Pimcore/Document/Tag/NamingStrategy/NamingStrategyInterface.php
- pimcore/models/Document/Tag.php
> [Documents] Blocks are not applied to target group variant of document if on first level

- doc/Development_Documentation/20_Extending_Pimcore/19_Install_Profiles.md
> corrected the links in the bottom of the page

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
> Replace Legacy ZF1 Examples

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
change Zend Framework1 Paginator to Zend Framework2 Paginator
> [DOCS] Paginator example fixes

- web/pimcore/static6/js/pimcore/object/classes/data/countrymultiselect.js
> code optimizations for country multiselect render type

- pimcore/lib/Pimcore/Twig/Extension/WebsiteConfigExtension.php
Update to use localized website config values.
fixes #2897
> Add ability to use localized website config values

- pimcore/models/Document/Tag/Link.php
> add missing getter for Class

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DocumentController.php
- pimcore/models/Document/Service/Dao.php
Fixes #2736
Fixes #2579
- Fixed document translation multi-join gets lost issue
- Restricted user to have multiple links to target translation document
> Fix document translations

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/11_Blocks.md
explanation on how to create a block with localized fields
> localized fields in block elements

- doc/Development_Documentation/26_Best_Practice/06_Integrating_Commerce_Data_with_Content.md
Integrating Commerce Data with Content
Resolves #
> Added article

- web/pimcore/static6/js/pimcore/settings/email/log.js
> Fix sent email log pagination on delete action

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Searchadmin/SearchController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/asset.html.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/document.html.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/info-table.html.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- pimcore/lib/Pimcore/Event/AdminEvents.php
- pimcore/lib/Pimcore/Tool/Text.php
- pimcore/models/User.php
- web/pimcore/static6/css/admin.css
- web/pimcore/static6/img/magnifier.svg
- web/pimcore/static6/js/pimcore/helpers.js
- web/pimcore/static6/js/pimcore/layout/toolbar.js
- web/pimcore/static6/js/pimcore/overrides.js
- web/pimcore/static6/js/pimcore/startup.js
> QuickSearch

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/QuantityValueController.php
> Translate quantity value units

- pimcore/models/Document/DocType.php
- pimcore/models/Document/DocType/Dao.php
- web/pimcore/static6/js/pimcore/document/settings_abstract.js
- web/pimcore/static6/js/pimcore/document/tree.js
- web/pimcore/static6/js/pimcore/settings/docTypes.js
Resolves #659  
Added Group for Document Types
> Document types grouping

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
- pimcore/models/Element/Tag/Dao.php
> Fix possible SQL Injections

- web/pimcore/static6/js/pimcore/document/versions.js
> issue-2915: Preview of older document version

- pimcore/lib/Pimcore/Sitemap/Document/DocumentUrlGenerator.php
> Fixed problem 2 from #2811: pretty urls in sitemaps.

- .travis/run-tests.sh
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ClassController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Rest/ClassController.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/GridConfigListener.php
- pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/ImportConfigListener.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Model/IIndexable.php
- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tools/Installer.php
- pimcore/lib/Pimcore/DataObject/Import/Service.php
- pimcore/lib/Pimcore/Install/Resources/install.sql
- pimcore/lib/Pimcore/Tool/RestClient/AbstractRestClient.php
- pimcore/models/DataObject/ClassDefinition.php
- pimcore/models/DataObject/ClassDefinition/CustomLayout.php
- pimcore/models/DataObject/ClassDefinition/Dao.php
- pimcore/models/DataObject/ClassDefinition/Service.php
- pimcore/models/DataObject/Concrete.php
- pimcore/models/DataObject/Listing/Concrete.php
- pimcore/models/DataObject/Objectbrick/Definition.php
- pimcore/models/Element/Service.php
- pimcore/models/GridConfigFavourite.php
- pimcore/tests/_support/Helper/ClassManager.php
- pimcore/tests/_support/Helper/Model.php
- update-scripts/269/postupdate.php
- web/pimcore/static6/js/pimcore/object/class.js
- web/pimcore/static6/js/pimcore/object/classes/class.js
- web/pimcore/static6/js/pimcore/object/folder/search.js
> Classes: possibility to define table identifier

- doc/Development_Documentation/01_Getting_Started/03_Configuration.md
> typo - Update 03_Configuration.md

- doc/Development_Documentation/18_Tools_and_Features/01_Versioning.md
Example: How to get previous version of an object
> Example added to versioning

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/Cart/Listing.php
- extended the valid order keys for carts by "creationDateTimestamp" and "modificationDateTimestamp"
- added PhpDoc
> Extended valid order keys

- pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/public/js/pricing/config/objects.js
- web/pimcore/static6/css/icons.css
- web/pimcore/static6/img/flat-color-icons/open_file.svg
- web/pimcore/static6/js/pimcore/asset/metadata.js
- web/pimcore/static6/js/pimcore/document/tags/multihref.js
- web/pimcore/static6/js/pimcore/element/history.js
- web/pimcore/static6/js/pimcore/element/notes.js
- web/pimcore/static6/js/pimcore/element/properties.js
- web/pimcore/static6/js/pimcore/layout/portlets/customreports.js
- web/pimcore/static6/js/pimcore/object/tags/multihref.js
- web/pimcore/static6/js/pimcore/object/tags/multihrefMetadata.js
- web/pimcore/static6/js/pimcore/object/tags/nonownerobjects.js
- web/pimcore/static6/js/pimcore/object/tags/objects.js
- web/pimcore/static6/js/pimcore/object/tags/objectsMetadata.js
- web/pimcore/static6/js/pimcore/object/variantsTab.js
- web/pimcore/static6/js/pimcore/report/custom/report.js
- web/pimcore/static6/js/pimcore/settings/gdpr/dataproviders/assets.js
- web/pimcore/static6/js/pimcore/settings/gdpr/dataproviders/dataObjects.js
- web/pimcore/static6/js/pimcore/settings/httpErrorLog.js
Multiple of our clients were really confused by the open icon in Pimcore (the cursor icon) - to the point that we had to modify Pimcore to make this understandable for their employes.
This Pull Request is a proposal for a new open icon. The icon was very well received by our client and they said that this icon immediately gave the sense of what the button does, contrary to the cursor icon.
> Proposal for the open icon

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/UserController.php
- web/pimcore/static6/js/pimcore/settings/user/workspace/asset.js
- web/pimcore/static6/js/pimcore/settings/user/workspace/document.js
- web/pimcore/static6/js/pimcore/settings/user/workspace/object.js
> Fix: Workspace permissions multiple paths issue

- pimcore/lib/Pimcore/WorkflowManagement/Workflow/Service.php
> Fixed for Issue #3002

- web/pimcore/static6/js/pimcore/helpers.js
> fix pdf editable add metadata issues

- web/pimcore/static6/js/pimcore/object/helpers/optionEditor.js
Resolves #3091
Fixes all select types option editor
> Fix dropdowns option editor empty apply

- web/pimcore/static6/js/pimcore/object/tags/geobounds.js
- web/pimcore/static6/js/pimcore/object/tags/geopoint.js
- web/pimcore/static6/js/pimcore/object/tags/geopolygon.js
Resolves #1047 
Changes will be saved properly now after editing layers using edit tool of leaflet( For all geo data types).
> Replace Google Maps API by Leaflet & OSM issues fix

- web/pimcore/static6/css/ext-modifications.css
> Fix for Object disabled fields to show tool tip

- web/pimcore/static6/js/pimcore/object/tags/date.js
- web/pimcore/static6/js/pimcore/object/tags/datetime.js
> update Date & Date Time format for Object edit view

- web/pimcore/static6/js/pimcore/settings/targeting/conditions.js
Resolves #1047 
Leaflet implementation in Pimcore Targeting section.
> Replace Google Maps API by Leaflet & OSM - leaflet implementation in Targeting

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
> Small typo misstake fixed resolves #3116

- pimcore/models/Tool/CustomReport/Adapter/Sql.php
> Fix for date filter 'ON' not fetching correct results

- pimcore/models/Element/Service.php
getValidKey expects "asset","document","object" to get the correct key - currenty the Class was passed so it didn't worked on Assets
> Bugfix sanitizedPath

- pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/SettingsController.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/Command/MaintenanceCommand.php
- pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/TagManagerListener.php
- pimcore/models/Tool/Tag/Config.php
- web/pimcore/static6/js/pimcore/settings/tagmanagement/item.js
> Add expiry date for Tag & Snippet Management

- bundles/AdminBundle/Controller/Admin/DocumentControllerBase.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
- models/Document/Service/Dao.php
> Fix document translations gets lost issue

- bundles/AdminBundle/Controller/Admin/DataObjectHelperController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/csvSettingsTab.js
> Added option to set CSV settings on Import

- bundles/AdminBundle/DependencyInjection/Configuration.php
- bundles/AdminBundle/DependencyInjection/PimcoreAdminExtension.php
- lib/Tool/Admin.php
Resolves #3090 
Added configuration for available admin languages (Admin translations and users section)
> Add configuration for available admin languages fix

- lib/Bootstrap.php
Related to #3190
Allows to set a Custom Kernel Class thru .env File, constants.php or Environment Variable.
> implement feature to set Kernel Class via constant/env/.env config

- lib/Navigation/Container.php
New function inside the navigation container for checking if children have at least one published/visible child pages
> Navigation: Added `hasVisiblePages()` convenience method

- lib/Twig/Extension/DocumentTagExtension.php
> Fix Twig edit template duplcate issue

- bundles/AdminBundle/Controller/Admin/MiscController.php
Resolves #
When there are a lot of Bundles, Actions, and/or Templates, the dropdown lists in Controller and View Settings can be difficult to navigate.  Sorting the names alphabetically makes it easier to find the one you are looking for.
> sort bundles, actiona, templates for frontend

- models/Element/Tag/Dao.php
> Fix multiple subtypes & classnames for getElementsForTag

- doc/Development_Documentation/06_Multi_Language_i18n/README.md
> Fixed translations broken URL

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
add upgrade note for build 143. 
See https://github.com/pimcore/pimcore/commit/8b2a14ddbd73b4e0a38ad376aae6141750b6c6af
> add upgrade note for build 143

- lib/Image/Adapter.php
- models/Asset/Image/Thumbnail/Processor.php
```php
<?php 
$thumbnailConfig = Asset\Image\Thumbnail\Config::getByName('content');
$thumbnailConfig->addItemAt(0, function (Imagick $imagick) {
/**
* @var \Imagick $i
*/
$i = $imagick->getResource();
$i->sepiaToneImage(80);
}, []);
$asset = Asset::getById(39);
$asset->clearThumbnails(true);
$thumb = $asset->getThumbnail($thumbnailConfig);
$file = $thumb->getFileSystemPath();
```
> [Assets] Custom callbacks for image transformations

- doc/Development_Documentation/18_Tools_and_Features/29_Custom_Reports.md
- doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/03_Conditions.md
- doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/07_Action_Handlers.md
- doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/11_Frontend_Javascript.md
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/11_Adding_Object_Datatypes.md
> [DOCS] Update the public url to inside the bundle inside the public path

- bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
- models/DataObject/Service.php
> Fixed variant tab actions based on permissions

- bundles/AdminBundle/Resources/config/export.yml
- bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/PropertyGetter.js
- lib/DataObject/GridColumnConfig/Operator/PropertyGetter.php
> [DataObject] Add property geter for Grid

- doc/Development_Documentation/02_MVC/README.md
Just a typo. Resolves nothing.
> Fixed missing word "is" in line 15

- lib/Workflow/MarkingStore/DataObjectMultipleStateMarkingStore.php
The marking store should not save the subject (like the other marking stores...). Additionally the code was simplified.
> [Workflows] data_object_multiple_state marking store fix

- doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details.md
- doc/Development_Documentation/07_Workflow_Management/02_Marking_Stores.md
- doc/Development_Documentation/07_Workflow_Management/04_Permissions.md
- doc/Development_Documentation/07_Workflow_Management/07_Workflow_Report.md
Just some fixes for the workflow docs...
> [workflows] docs fixes

- bundles/EcommerceFrameworkBundle/FilterService/FilterGroupHelper.php
- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service.md
> Option to add a nice name with HTML-icons in filter definition

- lib/Workflow/Manager.php
A helper method to get a workflow transition by name.
> [Workflows] add getTransitionByName helper method to workflow manager

- bundles/AdminBundle/DependencyInjection/Configuration.php
Typo: includeRelations vs includedRelations
> Typo: includeRelations vs includedRelations

- models/Dependency.php
> Fix dependency warning on delete for all elements

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- bundles/CoreBundle/Resources/translations/en.json
- models/DataObject/ClassDefinition/Data/QuantityValue.php
QuantityValue - add option to configure the width of the unit field
> QuantityValue - add option to configure the width of the unit field

- doc/Development_Documentation/07_Workflow_Management/02_Marking_Stores.md
Fixed two small typos in the documentation
> Update a typo in documentation

- composer.json
introduce branch alias to easier install dev versions of pimcore
> Introduce branch alias

- bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
> Fix variants tab gridconfig save option

- bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
(did't worked properly + not useful any more)
Resolves #2081
> Remove legacy view script rendering

- lib/Workflow/NotificationEmail/NotificationEmailService.php
The notifications worked for users only. This fix makes it working for roles too.
> [Workflows] email notification roles fix

- bundles/AdminBundle/Controller/Admin/TranslationController.php
> Fixed shared translation save and sorting

- doc/Development_Documentation/18_Tools_and_Features/01_Versioning.md
Documentation fixes for doc page on Versions.
> Fixes smaller typos and rephrases a sentence

- doc/Development_Documentation/18_Tools_and_Features/07_Properties.md
Does minor changes in the documentation page for Properties.
> Fixes typos and wordings on Properties page

- doc/Development_Documentation/10_E-Commerce_Framework/11_Cart_Manager.md
Removes incorrect statement from documentation. It is unfortunately not obvious because none on our team understand it
> Small update to Cart Manager documentation

- bundles/EcommerceFrameworkBundle/Resources/public/css/pricing.css
> Double ; not neccessary

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
> Add WebP in Additional Tools Installation

- models/DataObject/ClassDefinition/Data/BooleanSelect.php
Boolean select batch assignment does not work (reproducable in the advanced demo) - this fix makes it working.
> boolean select - batch assignment fix

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/01_Update_from_5.x_to_5.4_or_above.md
#Improvement for documentation
Initial and latest migrations missing as step
> Initial and latest migrations missing as step

- doc/Development_Documentation/04_Assets/README.md
> [DAM-Docs] Added supported file formats for previewing

- doc/Development_Documentation/01_Getting_Started/00_Installation.md
While installation of pimcore ecommerce demo memory limits for composer and install command weren't suitable.
Resolves #
> Update memory limit recommendation

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Web-Installer got removed -> so also remove it from the docs.
> Remove Web-Installer from nginx config

- bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
> Variant disappear issue fixed

- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
> Fixed pagination toolbar issue in object selector window

- lib/Mail.php
Before you get an Error by sending an Attachment.
> ::newinstance ist now new \Swift_Attachment

- bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
The orderdate is set on order creation, so when a user aborts and comes back later, there is a good chance that the cleanup takes place while the payment process is active. In this case it can happen that the payment provider executes the payment, while the Pimcore order becomes aborted. 
The update proposal also includes version notes to improve debugging based on the saved version note.
> Cleanup orders by modification date, not orderdate

- models/DataObject/ClassDefinition/Data/Classificationstore.php
> Fix Classificationstore::setAllowedGroupIds() for __setState()

- bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
This will delete orderItems if they are unused.
> Cleanup unused order items

- bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
> cleanup orderitems - fix wrong condition

- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Consent.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/ExternalImage.php
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Hotspotimage.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/Link.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/StructuredTable.php
- models/DataObject/ClassDefinition/Data/Video.php
- models/DataObject/Localizedfield/Dao.php
> Fix: OwnerAwareField shouldn't save Owner

- models/DataObject/ClassDefinition/Data/Table.php
> add version preview to table

- bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
- models/DataObject/ClassDefinition/Data/BooleanSelect.php
- models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Missing Interfaces implementations from #3715
> Fix missing interfaces

- bundles/AdminBundle/Resources/public/css/ext-modifications.css
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
Add border in the right color and margin-bottom
> Fix: ReverseManyToManyObjectRelation Admin UI Design

- models/DataObject/ClassDefinition/Data/Block.php
> Block data-type needs no query column

- bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js
Resolves #3767 
Regression from #3697
> Fix: Unable to open admin in IE11

- bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
> bugfix - delete from index

- models/DataObject/Listing.php
> Fix PHPDoc for setObjects() method

- bundles/AdminBundle/Resources/public/css/admin.css
- bundles/AdminBundle/Resources/public/js/lib/ext/ux/layout/ResponsiveColumn.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/multiselect.js
- bundles/CoreBundle/Resources/views/Targeting/toolbar/toolbar.scss
- bundles/EcommerceFrameworkBundle/Resources/public/css/voucherservice/style.css
Resolves: Just a few code style errors
> Removes duplicate semicolons

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/01_Basic_Migration.md
Add /app/AppKernel.php to avoid errors on composer update
> [Docs] Upgrade guide: add /app/AppKernel.php before Pimcore update

- models/DataObject/Listing.php
Resolves Documentation vs code mismatches
> Fixes incorrect return methods in PHPDocs

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
With multiselection of assets this adds possibility to drop more images in image gallery component.
> Image gallery drop of multiple images

- bundles/AdminBundle/Resources/public/css/icons.css
Add a Video Icon for .vob Files and for .ico files
> Add Icons for missing Asset Files

- doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/03_Full_Page_Cache.md
See original at https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Cache/Full_Page_Cache.html#page_Bookmarklet
Resolves #
> Improves bookmarklet markup

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- models/DataObject/ClassDefinition/Data/Checkbox.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
[Fix] Save default values for Checkbox and Quantity Value fields in database
resolves #3784 
resolves #3585
> [Fix] Save default values for Checkbox and Quantity Value fields

- bundles/InstallBundle/Command/InstallCommand.php
> Revert "Option to skip database structure on install is not working"

- models/DataObject/Objectbrick/Definition.php
Static code analysis will be failing otherwise.
> ucfirst brick classes in docblocks

- bundles/CoreBundle/EventListener/Frontend/CookiePolicyNoticeListener.php
- bundles/CoreBundle/Resources/misc/cookie-policy-default-template.html
> Add discernible name for link & button in cookie notice

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
- bundles/CoreBundle/Resources/migrations/Version20190131074054.php
- bundles/CoreBundle/Resources/translations/en.json
> [Documents] Add recursive option for paste as new language variant

- doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/01_Price_Systems_and_getting_Prices.md
Broken link in ecommerce framework documentation
> Fix dead link

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/11_Blocks.md
Add the Info how to get Values of Localized Block Entries
> Documentation: Get Values of Localized Block Entries

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
> datatrans cancel authorisation needs sign

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Controller/Admin/Document/EmailController.php
- bundles/AdminBundle/Controller/Admin/Document/FolderController.php
- bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
- bundles/AdminBundle/Controller/Admin/Document/LinkController.php
- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
same as https://github.com/pimcore/pimcore/pull/3906 but for assets
> Expose all classes and interfaces of Assets for js

- doc/Development_Documentation/03_Documents/03_Navigation.md
The word *Folder* is generally used throughout PimCore as far as I can see.
> [Documentation] Vocabulary change

- bundles/AdminBundle/Resources/public/css/icons.css
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
- lib/DataObject/GridColumnConfig/Operator/ObjectFieldGetter.php
> Fix search dialog grid operators

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
Added command for running Pimcore migrations manually.
Following discussion on Gitter
> Update upgrade Readme

- .github/ISSUE_TEMPLATE.md
Just a small nitpick that I wanted to adjust. No big thing. :)
Resolves #
Gives me peace of mind. ;)
> Removes trailing whitespace

- lib/Web2Print/Processor.php
Add jobConfig settings to pimcore.document.print.prePdfGeneration event so we can modify the html rendering depending on custom pdf generation settings...
E.g use different Thumbnails...
> Add jobConfig settings to pimcore.document.print.prePdfGeneration event

- bundles/AdminBundle/Controller/Admin/Document/LinkController.php
- bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
- bundles/EcommerceFrameworkBundle/PriceSystem/TaxManagement/TaxCalculationService.php
- bundles/EcommerceFrameworkBundle/VoucherService/Token/Dao.php
- lib/Image/Adapter/Imagick.php
- lib/simple_html_dom.php
- models/Document/Tag/Link.php
- models/Document/Tag/Video.php
Resolves some bugs that existed in code.
All bugs were reported by SonaryQube tool.
Please check carefully change that was done on  bundles/EcommerceFrameworkBundle/VoucherService/Token/Dao.php
models/Document/Tag/Video.php
> Fix multiple code bugs

- models/Asset/Listing.php
- models/DataObject/Listing.php
- models/Document/Listing.php
loadIdList does not return an integer array.
> PhpDoc - loadIdList does not return an integer array.

- bundles/AdminBundle/Resources/public/js/pimcore/document/hardlink.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/link.js
Make the relations inside link/hardlink document types look and feel more like normal relations.
-> add open, delete, search button
-> add context menu
> Link / Hardlink - relation improvements

- models/DataObject/ClassDefinition/DynamicOptionsProvider/MultiSelectOptionsProviderInterface.php
- models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectOptionsProviderInterface.php
This fixes the order of the type & parameter name in the PhpDoc and adds a missing use statement.
> Fix PhpDoc 

- bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
> [PredefinedProperties] ComboBox should sorted by name

- doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details.md
See at latest core bundle configuration class https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/DependencyInjection/Configuration.php
> notifyRoles and notifyUsers are only in notificationSettings configurable

- bundles/AdminBundle/Controller/Admin/TagsController.php
- doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
- models/Asset/Listing/Dao.php
- models/DataObject/Listing/Concrete/Dao.php
- models/DataObject/Listing/Dao.php
- models/Document/Listing/Dao.php
- models/Element/Note/Listing.php
- models/Element/Note/Listing/Dao.php
- models/Element/Service.php
- models/Element/Tag/Listing.php
- models/Element/Tag/Listing/Dao.php
> Dao::loadIdList() should return integer array

- lib/Targeting/ActionHandler/AssignTargetGroup.php
Sorry, I missed a debugging echo here.
> Remove echo

- doc/Development_Documentation/26_Best_Practice/13_Build_Custom_Rest_API.md
> Add docs for custom REST API

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Resolves #1232
Added full text search field(based on table `search_backend_data`) in object grid view
> [Data Objects] Added full text search field in grid view

- bundles/EcommerceFrameworkBundle/PricingManager/Condition/CatalogProduct.php
Resolves no specific issue, but just things I noticed while reading the code.
> Fix @var annotation and test for CONST with identical equals operator

- bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
- bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
- bundles/CoreBundle/Resources/translations/de.json
- bundles/CoreBundle/Resources/translations/en.json
> [Custom Reports] Add openUrl as row action

- bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
- bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
- bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
- bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
insertOrUpdateVoucherSeries() should return the generated codes if successfully (like it was in older versions)
> insertOrUpdateVoucherSeries() - return generated codes

- lib/Templating/Renderer/TagRenderer.php
- models/Document/Tag/Relations.php
> [Document] Fix multihref editable elements visibility

- bundles/AdminBundle/Controller/Admin/EmailController.php
> [GDPR Extractor] Fix sent emails full-text search condition

- models/Asset.php
> [Assets] Add dependency resolver for asset metadata relations

- doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md
Add routing.yml info to protect also img and video thumbnails
> Protect also img and video thumbnails

- lib/Model/AbstractModel.php
- lib/Model/Dao/AbstractDao.php
- models/Asset.php
- models/Asset/Document.php
- models/Asset/Image.php
- models/Asset/Video.php
- models/DataObject/AbstractObject.php
- models/DataObject/Concrete.php
- models/DataObject/Folder.php
- models/Document.php
- models/Document/Hardlink.php
- models/Document/Page.php
- models/Document/PageSnippet.php
> [Elements] Database transactions for delete() 

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
> [Custom Layouts] Fix to disallow custom layout invalid name on update

- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
- bundles/CoreBundle/Resources/translations/en.json
> [Document] Add recursive updating references option for documents paste as new language

- bundles/AdminBundle/Controller/Admin/RedirectsController.php
- bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
- bundles/CoreBundle/Resources/translations/en.json
> Add option to cleanup expired redirects

- lib/Translation/Translator.php
> Allow admin translations override

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/ClassDefinition/Data/Objectbricks.php
- models/DataObject/Concrete.php
- models/Version.php
> [DataObjects] Not Published VersionData of relations not shown correctly #4121

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
> [Gallery] set inline upload path of assets in datatype gallery

- doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing.md
Fixes/ improvements for the testing documentation.
pimcore/pimcore#3402
> [Docs] Improvements for "Testing" documentation

- models/DataObject/AbstractObject.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
- models/DataObject/Data/ObjectMetadata.php
- models/DataObject/Data/ObjectMetadata/Dao.php
- models/Element/Service.php
> [DataObjects] Optimize Loading Performance for AdvancedManyToManyObject Relation

- bundles/CoreBundle/Command/Definition/Import/CustomLayoutCommand.php
- doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
- models/DataObject/ClassDefinition/CustomLayout.php
- models/DataObject/ClassDefinition/CustomLayout/Dao.php
Resolves 
see: https://talk.pimcore.org/t/custom-layouts-via-bundle-installation/1851/2
Ability to import custom layouts through cli. You simply need to specify target class and filename to import.
- If not present it will be created.
- If present it will be updated
> [Deployment] add customlayout cli import

- composer.json
- models/Element/Service.php
> Use DeepClone 1.9

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
- bundles/CoreBundle/Resources/translations/de.json
- bundles/CoreBundle/Resources/translations/en.json
> Show unreferenced assets (Follow-up of #4211)

- bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
- bundles/CoreBundle/Resources/translations/en.json
> Add option to load all linked translation documents

- bundles/AdminBundle/Resources/public/js/pimcore/document/seopanel.js
> [Document] fix SEO Editor reload issue on page edits

- bundles/CoreBundle/DependencyInjection/Config/Processor/PlaceholderProcessor.php
- bundles/CoreBundle/DependencyInjection/Configuration.php
- bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
- doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/01_Placeholder_Example/README.md
- doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
- lib/Workflow/Place/StatusInfo.php
- tests/unit/DependencyInjection/PlaceholderProcessorTest.php
Support for placeholders in workflows. By using placeholders, it is possible, to reuse an existing workflow and reapply places and transitions onto a new workflow.
Example:
```
pimcore:
workflows:
product_workflow_local_de: &local_workflow_reference
placeholders:
'%%stateFieldName%%': 'translationStateDe'
'%%locale%%': 'de'
enabled: true
label: "Local Release Workflow"
type: "state_machine"
supports: &local_workflow_supports_ref
- \Pimcore\Model\DataObject\Product
initial_place: "local_300_basic_data_pending"
marking_store: &local_workflow_marking_store_ref
type: single_state
arguments:
-
%%stateFieldName%%
places: &local_workflow_places_ref
100_new:
label: "Basic Data Pending from Global Workflow (%%locale%%)"
visibleInHeader: true
color:  '#cddc39'
colorInverted: false
permissions:
- …
```
> Placeholder support in workflows.

- bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
add postAddObject event for the backend ui
> add postAdd(Object|Document)Tree event for the backend ui

- bundles/CoreBundle/Resources/migrations/Version20190403120728.php
> Avoid MySQL index size size issue

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
> Fix not-editable reverseManyToManyObjectRelations

- bundles/AdminBundle/Controller/Admin/SettingsController.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
- lib/Config.php
- models/WebsiteSetting.php
- models/WebsiteSetting/Listing.php
- models/WebsiteSetting/Listing/Dao.php
Resolves #4095
Follow up of #3973
> [WebsiteSettings] getData() should lazy load relations

- bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
> [Ecommerce] [Findologic Export] allow array values for export

- bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
> Fix condition for all translations menu option

- bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
> Fix tree reload after deleting elements

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
- models/DataObject/ClassDefinition/Data/Slider.php
> [DataObjects] Fix empty check for Slider data type

- lib/Event/AssetEvents.php
- lib/Event/DataObjectEvents.php
- lib/Event/DocumentEvents.php
- models/Asset.php
- models/DataObject/AbstractObject.php
- models/DataObject/Concrete.php
- models/Document.php
- models/Document/PageSnippet.php
> Add exception info to FAILURE events

- bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
- lib/Web2Print/Processor/api/v10.0/PDFreactor.class.php
> Integrate PDFreactor 10 API wrapper

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
> Cleanup DataObject controller

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/area.js
- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
> [Documents] Area editable improvements

- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- consider tenants
- consider missing items as valid
> Es Bugfix - deleting items:

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
> [Elements] Fixed: locked elements should not be deleted

- bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
Fixed Documents settings Controller & Action drop down to load without having to change Bundle
> [Documents] Fixed settings dropdown to autoload

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
> Fix Many to Many Relations Path Formatter

- doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
> [Docs] Add cache configuration warning

- bundles/AdminBundle/Helper/GridHelperService.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
> [Data Object] Grid: Avoid limit on batch edit/append all

- doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
> Fix twig syntax in documentation

- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
Adds documentation for how to use pimcore_inc passed parameters in the included view
> Add documentation for how to use pimcore_inc parameters

- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/newsletters/sendingPanel.js
Add the number of recipient to the dialog of "do you really want to send the newsletter to all".
> recipient calculation newsletter panel

- bundles/AdminBundle/Controller/Admin/NotificationController.php
> Update notification controller routing annotations to Symfony core

- bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
> Fix documents template setting load

- models/DataObject/ClassDefinition/Data/ImageGallery.php
Resolves no specific issue, just something to make code completion easier
> Adds return type to getDataFromGridEditor() method

- doc/Development_Documentation/24_Web_Services/README.md
Add example for creating an asset via Pimcore REST API with minimum data.
> Add rest example for asset creation.

- bundles/CoreBundle/Resources/config/commands.yml
- bundles/CoreBundle/Resources/config/services.yml
- bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
- bundles/EcommerceFrameworkBundle/Resources/config/commands.yml
> [Symfony 4] Define commands as services #3799

- bundles/AdminBundle/Resources/public/js/pimcore/element/dependencies.js
> Fix dependencies rendering

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
> [DataObject] If newer (not published) object version is  available, published state is not shown correctly in Pimcore Admin

- composer.json
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
- lib/Composer.php
- lib/Kernel.php
> [Symfony 4] Replace sensio/distribution-bundle #4340

- doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
Fix link to PrestaSitemapBundle bundle docs.
> Fix link to PrestaSitemapBundle bundle docs

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Since those files are very likely to be generated by a route to a controller
> Don't try to serve static files beginning with /admin

- composer.json
- lib/Config.php
- lib/Google/Api.php
- lib/Templating/Helper/Cache.php
- lib/Twig/Extension/DocumentTagExtension.php
- lib/Twig/Extension/HelpersExtension.php
- lib/Twig/Extension/NavigationExtension.php
- lib/Twig/Extension/PimcoreObjectExtension.php
- lib/Twig/Extension/SubrequestExtension.php
- lib/Twig/Extension/TemplatingHelperExtension.php
- lib/Twig/Extension/WebsiteConfigExtension.php
- lib/Twig/Node/AssetCompressNode.php
- lib/Twig/Node/GlossaryNode.php
- lib/Twig/TokenParser/AssetCompressParser.php
- lib/Twig/TokenParser/GlossaryTokenParser.php
- models/Asset/Image/Thumbnail.php
- models/Asset/Image/Thumbnail/Processor.php
Twig functions and tests write deprecation warnings
> Fix: Deprecations of Twig, Google Client and Pimcore

- bundles/CoreBundle/Resources/migrations/Version20190515130651.php
- bundles/InstallBundle/Resources/install.sql
> asset_metadata add primary key

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/13_Classification_Store.md
add setActiveGroups to show the Groups which are filled with data in backend
> add setActiveGroups in Documentation

- lib/Cache/Pool/AbstractCacheItemPool.php
- lib/Cache/Pool/CacheItem.php
- tests/_support/Util/TestHelper.php
- tests/cache/Factory.php
- tests/cache/Pool/SymfonyProxy/ArrayAdapterProxyTest.php
- tests/cache/Pool/SymfonyProxy/FilesystemAdapterProxyTest.php
> [Symfony 4] Cache Compatibility

- doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md
- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
> added nginx configuration example for proteced assets to documentaion

- doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/01_PimcoreEcommerceFrameworkBundle_Configuration_Reference.md
This MR provides a bit of documentation for `class` option in CartPriceCalculatorFactory. This might be useful for those who need to adjust CartPriceCalculator's implementation.
> Document "class" in CartPriceCalculatorFactory

- lib/Targeting/Maintenance/TargetingStorageTask.php
to make it possible to autoconfigure and autowire it using di
> Update TargetingStorage Maintenance Task

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/relations.js
- doc/Development_Documentation/03_Documents/01_Editables/13_Relations_(Many-To-Many).md
add reload option to relations editable
see https://github.com/pimcore/pimcore/issues/4441
> add reload option to relations editable

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
see https://github.com/pimcore/pimcore/issues/4310
I don't know if this causes any side effects so please double check this :)
> Fieldcollections: Master (Admin Mode) should unlock not-editable fields

- bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
> [Ecommerce] Remove deprecated methods of CheckoutManager

- bundles/AdminBundle/Resources/public/css/editmode.css
> Add z-index property for WYSIWYG editable dialog box

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
I stumbled upon this while trying to add a new navigation item, so I figured I should add a hint in the docs.
Improvements in the wording are very welcome, though ;)
> Add hint about magic id/variable names

- doc/Development_Documentation/26_Best_Practice/14_Master-Slave_Database_Connection.md
> [DOCS] update master slave database example

- doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
Resolves #
Updated Block-Docu with Twig Snippet for Manual-Mode
> Update Block-Docu with Twig Snippet

- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
Added Twig Code
Resolves #
Updated Area-Docu with Twig Snippet
> Update Area-Docu with Twig Snippet

- doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md
use urldecode for special characters to find the file on the Filesystem.
> use urldecode for special characters

- bundles/InstallBundle/Command/InstallCommand.php
This pull request resolve https://github.com/pimcore/pimcore/issues/4544
> Mysql password optional

- models/DataObject/Localizedfield/Dao.php
> Error when filter localizedfield in Grid with ObjectBricks in class

- lib/Tool/Requirements.php
Thias pull request resolve https://github.com/pimcore/pimcore/issues/4543
> Improve mysql requirements check

- doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
This pull request add some useful information for installing some tools and for activating archive format for database.
> Improve documentation for install requirements and tools

- bundles/CoreBundle/Resources/migrations/Version20190618154000.php
- bundles/InstallBundle/Resources/install.sql
> Fix #4495: user.classes column too short for custom identifieres

- bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
> [Ecommerce Payment] handle Response is called multiple times

- bundles/AdminBundle/Controller/Admin/PortalController.php
- bundles/AdminBundle/Controller/Reports/PiwikController.php
- bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
- bundles/AdminBundle/Translation/AdminUserTranslator.php
- bundles/CoreBundle/Resources/config/aliases.yml
- bundles/CoreBundle/Resources/views/Workflow/NotificationEmail/notificationEmail.html.twig
- bundles/CoreBundle/Resources/views/Workflow/statusinfo/allPlacesStatusInfo.html.twig
- bundles/CoreBundle/Resources/views/Workflow/statusinfo/toolbarStatusInfo.html.twig
- bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php
- bundles/EcommerceFrameworkBundle/Reports/Piwik/PiwikReportsProvider.php
- composer.json
- lib/Analytics/Piwik/Api/SitesManager.php
- lib/Analytics/Piwik/ReportBroker.php
- lib/Analytics/SiteId/SiteId.php
- lib/DataObject/GridColumnConfig/Operator/Factory/TranslateValueFactory.php
- lib/DataObject/GridColumnConfig/Operator/TranslateValue.php
- lib/Document/Tag/TagHandler.php
- lib/Templating/Helper/Translate.php
- lib/Translation/Translator.php
- lib/Workflow/EventSubscriber/NotesSubscriber.php
- lib/Workflow/EventSubscriber/NotificationEmailSubscriber.php
- lib/Workflow/NotificationEmail/NotificationEmailService.php
- lib/Workflow/Place/OptionsProvider.php
- lib/Workflow/Place/StatusInfo.php
> [Translation] Allow trans to support plurals & Fix transChoice

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/table.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
- bundles/CoreBundle/Resources/translations/en.extended.json
- models/DataObject/ClassDefinition/Data/Table.php
> [DataObjects] Add configuration option for header names to table data type

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
1. set up a workflow
2. add a node with an additional field checkbox to the workflow
3. status change at the object
I have extended the query to check if the object is empty or not.
fixes #4604
> [Workflow] note checkbox exception

- bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
> [Improvement] First day of week localized on calendars #4602

- bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
> [Templating] Fix twig auto rendering

- bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
This simplifies the code of #4628 a bit.
> [Templating] simplify condition and remove unused variable

- bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
As the index updater can run very long, it is helpful to show the progress in %.
> Show progress in Index Updater log.

- bundles/CoreBundle/Command/WorkflowDumpCommand.php
Fixed for command *pimcore:workflow:dump*
> [Workflow] Fixed parent for Command class and removed deprecated ContainerAwareCommand

- doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
Documentation addition
This recommendation was gathered by talking to @brusch on gitter.
> Adds section about colormanagement and images

- bin/pimcore-install
- doc/Development_Documentation/01_Getting_Started/03_Configuration.md
- lib/Bootstrap.php
- lib/Config.php
- lib/Tool/Console.php
- support for new DotEnv menachnism (resolves #4642) 
- avoid usage of `putenv()` and `getenv()` 
- support for `APP_DEBUG` and `APP_ENV` environment variable
- support for `.env.local.php` file
> Environment Variable Improvements

- bundles/CoreBundle/Command/Bundle/InstallCommand.php
- bundles/CoreBundle/Command/Bundle/UninstallCommand.php
- bundles/CoreBundle/Command/Bundle/UpdateCommand.php
- bundles/CoreBundle/Resources/config/commands.yml
> [Bundles] Clear cache after pimcore:bundle:install/uninstall/update command

- bundles/AdminBundle/Controller/Admin/AssetController.php
- models/Asset/Image.php
> [Assets] Fix Image focal points detection delete

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
- bundles/CoreBundle/Resources/migrations/Version20190708175236.php
- bundles/CoreBundle/Resources/translations/en.json
> [Documents] Restrict document translation linking without language

- bundles/AdminBundle/Resources/public/js/pimcore/object/layout/iframe.js
- Height of iframe
- Add missing margin-bottom
- Remove debug message in console
> Iframe Layout Component: Correction of height and distances

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-base.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-export.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-import.js
- bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
> [Data Objects] Partial classes bulk export #4609

- .travis/phpstan.s4.travis.neon
- .travis/phpstan.travis.neon
- .travis/run-stan.sh
> [TESTS] moved phpstan configs for travis to ./.travis folder

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
- doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/01_Text_Types.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
See #4411
And 32adcab6cf19aad7770ee3d20edf76c400cc183a
> [Data Objects]  Changed back WYSIWYG enter mode from using <br> to <p>

- bundles/CoreBundle/DependencyInjection/Configuration.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
- models/DataObject/ClassDefinition/Data/CalculatedValue.php
- models/DataObject/ClassDefinition/Data/Date.php
- models/DataObject/ClassDefinition/Data/Datetime.php
- models/DataObject/ClassDefinition/Data/Objectbricks.php
- models/Document/Tag/Date.php
Unfortunately not everything was removed with v6, this PR fixes this.
> Removed Zend_Date leftovers

- bundles/CoreBundle/Controller/PublicServicesController.php
S3, the MimeTypeGuesser can't handle the file from remote stream.
Specifically the error message is (in FileInfoMimetypeGuesser):
`Warning: finfo::file(): Failed identify data 0:invalid mode 00`
It seems that finfo extension can't handle remote streams. The extension
was installed on the system!
Since we are passing the MimeType with the Response, the MimeGuesser doesn't need to be used and thus finfo will not be used for S3.
> Set mime-type in BinaryResponse for thumbnails. When loading assets from

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- models/DataObject/Service.php
> [DataObjects] Fixed language restriction on collections

- lib/Routing/RedirectHandler.php
> [Cache] Avoid redirects cache stampede

- models/Document/DocType.php
> [DocType] Add missing save() and delete() method php docs

- models/Property/Predefined.php
> [Property\Predefined] Add missing save() and delete() method php docs

- models/Staticroute.php
> [Staticroute] Add missing save() and delete() method php docs

- lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
> Changed use of PropertyAccessor to PropertyAccessorInterface

- models/DataObject/ClassDefinition/Service.php
- models/DataObject/Fieldcollection/Definition.php
On Bulk export get error http://prntscr.com/ogbifc with unset($fieldCollection->fieldDefinitions) from Pimcore\Model\DataObject\ClassDefinition\Service line 129 and line 166
> [Classes] Changed protected to public for $fieldDefinitions

- models/Asset/Dao.php
- models/Asset/Image.php
> [Asset] Update image dimensions in database on the fly

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/29_Image_Types.md
> Twig Example for instanceof

- lib/Templating/Helper/WebsiteConfig.php
> [WebsiteSettings] Fix language specific settings

- bundles/EcommerceFrameworkBundle/Environment.php
- bundles/EcommerceFrameworkBundle/EnvironmentInterface.php
Add setter for default currency in ecommerce environment.
Resolves: #2466
> Add setter for default currency in ecommerce environment.

- models/Asset/MetaData/EmbeddedMetaDataTrait.php
Add is_file-check for getXMPData.
For IPTC and Exif metadata a filecheck is performed. This was overlooked for XMP data.
```php
$xmp = $this->flattenArray($this->getXMPData($filePath));
$iptc = $this->flattenArray($this->getIPTCData($filePath));
$exif = $this->flattenArray($this->getEXIFData($filePath));
```
See: https://github.com/pimcore/pimcore/blob/master/models/Asset/MetaData/EmbeddedMetaDataTrait.php#L140
Follow up of #3943 and #3979.
> Improve handling of Meta Data from Assets

- lib/Navigation/Renderer/Menu.php
Minor code changes in the way multi-level ulClass definition is handled
> Clean up multilevel ulClass definition

- composer.json
- models/DataObject/ClassDefinition/Data.php
Resolves #
When you are saving information at the classification store, you can receive an undefined raw index.
> Fixing and undefined index raw at data from class definition

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Backport from Pimcore 6 branch and resolves  #4408
> [Grid] Backport for send language param in grid tab from Picmore 6

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
> Ability to select variants in ManyToOne object grid

- models/Version.php
Follow up for #4676 
Problem occurs when trying to render a print page: 
```
Exception trace:
() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:185
DeepCopy\DeepCopy->copyObject() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:141
DeepCopy\DeepCopy->recursiveCopy() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:243
DeepCopy\DeepCopy->copyObjectProperty() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:205
DeepCopy\DeepCopy->copyObject() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:141
DeepCopy\DeepCopy->recursiveCopy() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:152
DeepCopy\DeepCopy->copyArray() at /www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:132
DeepCopy\DeepCopy->recursiveCopy() at …
```
> [Version] Added marshal-filter for container and view-model

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Rename upstream name to php-pimcore6
> [doc] Rename upstream name to php-pimcore6

- models/DataObject/Data/Hotspotimage.php
> Hotspotimage does not use crop data when medias are available

- doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/02_Wirecard_Seamless.md
If language is not passed 'de' is hard coded.
Resolves https://github.com/pimcore/pimcore/issues/4911
> Adding Language Option in the config in Wirecard seamless payment 

- bundles/AdminBundle/Controller/Admin/ElementController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/scheduler.js
> [Scheduler] Add version note in UI

- models/DataObject/ClassDefinition/Service.php
Followup on the discussion in https://github.com/pimcore/pimcore/pull/4887#discussion_r319880018
> Use ucfirst consistently in dynamic setters

- lib/Tool/DeviceDetector.php
> [Device Helper] add support for AWS CloudFront headers

- bundles/CoreBundle/Resources/migrations/Version20190904154339.php
- bundles/InstallBundle/Resources/install.sql
- models/Redirect.php
- models/Redirect/Dao.php
> [Redirects] Added user information (Owner & Modification)

- models/DataObject/Concrete.php
Reverting accidental change in https://github.com/pimcore/pimcore/commit/cef6aa4253fa6cde359fe8644e3240aa03ec1d48
See: https://github.com/pimcore/pimcore/commit/cef6aa4253fa6cde359fe8644e3240aa03ec1d48#r34977214
> Let's make GPL public again

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/27_Geographic_Types.md
Previous example was invalid, valid range for latitude is -90 to +90 degrees
> [doc] Fix latitude and longitude in example

- bundles/AdminBundle/Resources/public/css/admin.css
> Fix of the maintenance icon in the sidebar

- bundles/AdminBundle/Resources/public/css/icons.css
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/inputQuantityValue.js
Resolves #4773
It's all in the issue.
> Updating the quantity icons

- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/imagecropper.js
> [Data Objects] Image-Cropper wrong ratio - fixes

- bundles/AdminBundle/Resources/views/Admin/Misc/admin-css.html.php
- bundles/AdminBundle/Resources/views/Admin/Misc/iconList.html.php
- bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/info-table.html.php
- lib/Tool.php
Resolves #4880
`\Pimcore\Tool::getLanguageFlagFile("en", false);` for relative paths
> [Admin] Add absolute path option to getLanguageFlagFile

- bundles/CoreBundle/Command/LowQualityImagePreviewCommand.php
1. Support to generate previews for single asset ID(s).
2. Symfony progress bar.
3. Output message is displayed before generation starts, not afterwards.
> Low quality image preview generation: support for single asset ID(s) and progress bar.

- models/Asset.php
- models/Asset/Dao.php
- models/DataObject/Concrete.php
- models/DataObject/Concrete/Dao.php
- models/Document/PageSnippet.php
- models/Document/PageSnippet/Dao.php
Replace unspecific `@return array` by more specific `@return Version[]`
> [Code] Specify array item class

- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- new method for the creation of the ES alias.
- new method for the creation of the ES index.
- new method to fetch the active ES index based on the alias.
- ensure better modularity for simplified feature extensions.
- preparation for native ES reindexing process.
Attention: Has been tested with care, but please test within the Pimcore demo before rollout as well.
> Refactoring of the Elastic Search Worker

- models/Element/Recyclebin/Item.php
> Fix recycle bin recursive restore

- bundles/AdminBundle/Resources/views/Admin/Install/check.html.twig
> [Admin UI] Update warning icon for System requirement check

- doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
Fixed small typos in Database Model documentation page.
> Fixed small typos in Database Model documentation

- bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
> [Email] open action for element params

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #4868
Fix for object batch edit permissions
> [Data Objects/Grid] Object batch edit permissions fix

- bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
> [Admn UI] Fix no workspaces permission access

- bundles/AdminBundle/Controller/Admin/TargetingController.php
- lib/Event/Model/TargetGroupEvent.php
- lib/Event/TargetGroupEvents.php
Resolves #5044 for PimCore 6.x
> Target group events 6.x

- doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Documented actual information regarding IE11 based on  #2989
> [Documentation] Fix requirements about IE11 

- bundles/AdminBundle/Controller/Rest/Helper.php
Fixed less or equal to condition.
> Query filter conditional lte fixed

- bundles/AdminBundle/Controller/Admin/TargetingController.php
- lib/Event/Model/TargetGroupEvent.php
- lib/Event/TargetGroupEvents.php
> Target group events

- models/Tool/CustomReport/Adapter/Sql.php
Resolves #5008
regression of #3210
> Fix Custom Report Date filter

- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Fieldcollections.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
> [DataObject] Data loss when saving object with invisible fields

- doc/Development_Documentation/03_Documents/01_Editables/24_Numeric.md
> add Twig Documentation for Editable Numeric

- bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
- bundles/CoreBundle/Resources/translations/en.extended.json
show error message in case a group with the same name already exists
resolves #5072
> [ClassificationStore] show error message in case a group with the same name already exists

- models/DataObject/ClassDefinition/Data/Select.php
Resolves https://github.com/pimcore/pimcore/issues/5078
> Grid view doesn't filter by an item from the classification store

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/03_Number_Types.md
> [Documentation] Crosslink input quantity value

- lib/Image/Adapter/Imagick.php
> Workaround for Imagick PHP extension v3.4.4 which removed Imagick::roundCorners

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- lib/Model/Factory.php
- models/DataObject/AbstractObject.php
- models/DataObject/AbstractObject/Dao.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/ClassDefinition/Service.php
- models/DataObject/Concrete.php
- models/DataObject/Service.php
- models/Element/AbstractElement.php
- models/Element/Dao.php
- models/Element/ElementInterface.php
- models/Element/Service.php
Just some minor code and performance optimizations.
> Minor Code & Performance Optimizations

- composer.json
These URLs are used ar https://packagist.org/packages/pimcore/pimcore
> Update links to documentation and forum

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
> [DataObject] batch edit - checkbox fix

- doc/Development_Documentation/03_Documents/01_Editables/README.md
- models/Document/Tag.php
as discussed: https://github.com/pimcore/pimcore/issues/4353
resolves #4870 
resolves #4353
> add render function to document tag to allow throwing exceptions

- models/Document/Hardlink.php
- models/Document/Page.php
- models/Document/Traits/RedirectHelperTrait.php
> Fix auto generated redirects for multi-site

- models/DataObject/AbstractObject/Dao.php
> Fix: Empty Object Tree after update to v6.2.2

- lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php
> Fix undefined method errorerror

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js
> Transfer "width" and "columnLength" on cloning / copying calculated value field

- models/DataObject/Classificationstore/Dao.php
Only data of key definitions in active groups should be saved and loaded. 
@weisswurstkanone
> [ClassificationStore] - load/save data of active groups only

- doc/Development_Documentation/01_Getting_Started/00_Installation.md
> Fixed 3 demos => 2 demos

- bundles/AdminBundle/Resources/public/css/editmode.css
> [Documents] WYSIWYG editable - fix Phone Number field styling for Link

- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Resolves #
fire updateType(type) on pasting id/path for video to show correct options
nothing too special about it :(
> [Document|Data Object] Video dialog: switch video type when pasting a URL

- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
> [Documents] Pretty URL warnings

- models/DataObject/ClassDefinition/Data/Objectbricks.php
- models/DataObject/Concrete.php
> Objectbricks mandatory fields are not validated correctly

- models/Document/Tag/Checkbox.php
> Fix: Unable to save a checkbox editable

- models/Element/Recyclebin/Item.php
> Fix: Unable to restore deleted objects-folder recursively from recycle bin

- models/Dependency.php
> [Documents] Deleting snippet always shows dependency warning

- models/DataObject/ClassDefinition/Data/Classificationstore.php
Error message: Call to a member function getMessage() on array
Caused by a series of events:
- In ClassificationStore::checkValidity() the ValitionException sub items are set with an array of error data instead of nested ValidationExceptions.
- In Concrete::update() the ValidationException is rethrown when inheritance isallowed.
- In AdminExceptionListener::onKernelException() the method recursiveAddValidationExceptionSubItems() is called.
- This in turn causes the error because it expects the sub items to be ValidationException objects and tries to call getMessage() in the foreach loop.
Fixed by changing sub items to ValidationException objects in ClassificationStore::checkValidity()
Pimcore master
To reproduce:
- Data object allows inheritance
- Add a classification store to a data …
> [ClassificationStorre] Error validating mandatory fields

- bundles/AdminBundle/Resources/public/js/pimcore/startup.js
> Fix: JS Error in Request Exception

- bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
- bundles/AdminBundle/Helper/GridHelperService.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/grid.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridConfigDialog.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/abstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/checkbox.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/input.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/manyToOneRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/select.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/textarea.js
- bundles/CoreBundle/Resources/translations/en.json
> [Assets] Fix metadata grid issues

- bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/properties.js
- bundles/CoreBundle/Resources/migrations/Version20191114123638.php
- bundles/CoreBundle/Resources/translations/en.json
Resolves #3561
Set same language as of parent to enable inheritance
> [Documents] Properties - Add document language inheritance rollback option

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
- models/DataObject/ClassDefinition/Data/Objectbricks.php
Resolves #5221 & Resolves #5265
> [DataObjects] (Advanced)ManytoManyObjectRelation editmode fixes

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geobounds.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolygon.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolyline.js
At the moment we need to click at the search icon. With this PR it is possible to click the enter key.
> [DataObject] Start Map Search in Geo Data fields with Enter key

- bundles/AdminBundle/Resources/public/js/pimcore/object/folder.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
> [Admin] DataObjects - Allow 'Search and Move' on Empty Folders

- lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
- lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php
- lib/Maintenance/Tasks/LogArchiveTask.php
- lib/Maintenance/Tasks/LogErrorCleanupTask.php
- lib/Maintenance/Tasks/LogMailMaintenanceTask.php
- lib/Maintenance/Tasks/TmpStoreCleanupTask.php
> [Maintenance] Refactor Db connection layer for maintenance tasks

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> Add grid helpers refactoring notice #5304

- bundles/CoreBundle/Resources/migrations/Version20191125135853.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
> [Ecommerce] Updated data column of index store table to LONGTEXT

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/select.js
- doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
> [Documents] Add default value option for Select Editable

- lib/Helper/Mail.php
- models/Asset/Image/Thumbnail/Processor.php
- models/Asset/Thumbnail/ImageThumbnailTrait.php
- models/Asset/Video/Thumbnail/Processor.php
- models/Document.php
- models/Document/Hardlink.php
- models/Document/Hardlink/Service.php
- models/Document/Hardlink/Wrapper.php
- models/Document/Hardlink/Wrapper/Link.php
- models/Document/Traits/RedirectHelperTrait.php
Fix regression from https://github.com/pimcore/pimcore/commit/50662ce9eebf5b1f09aefff00b3a231d061e22eb
> Fix path of error image und thumbnail image with @ signs

- bundles/AdminBundle/Controller/Reports/CustomReportController.php
> [Custom Reports] Use Labels as headers instead of field name in export file

- lib/Tool/Text.php
My proposal as PR.
Resolves #5359
> WYSIWYG: Simplify Regex to check for dependencies with `pimcore_(id|type)` attributes

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
fixed #5367
considered #4909 and #4337
> [Data Objects] fixed grid row heights for images in (advanced)many-to-many-object relation fields

- bundles/AdminBundle/Resources/public/js/pimcore/object/gridexport/csv.js
Provide missing Checkbox for "Enable Inheritance"
Fixes #5389
> Fix for Bug #5389

- composer.json
composer.json "scheb/two-factor-bundle": "^3.26" 
see: https://github.com/scheb/two-factor-bundle/issues/253
> Fix for 2fa bypass

- models/DataObject/ClassDefinition/Data/Gender.php
> added missing third gender option in gender field

- models/DataObject/ClassDefinition/Data/Password.php
> fix password hash must also be calculate if info algorithm returns null

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
> Pimcore 6 Many-To-One Relation broken

- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
- models/Element/Tag/Dao.php
> [Tags] Allow shorter tag names

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
This PR improves logging within the payment field collections and adds a fix for the fetchPayment() method if no payment reference is given.
> [Ecommerce][Payment][Heidelpay] Improve logging and fix fetchPayment()

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
> [Documents] Add "Paste Only Contents here" option for all types

- models/DataObject/Fieldcollection.php
> Error when deleting an item in a Fieldcollection

- models/Element/Recyclebin/Item.php
> [Recycle Bin] Fix restoring relations in Localized Fields, Object Bricks and Field Collections

- doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
getData -> is the RAW string
frontend -> here you get the parsed version
> Update WYSIWYG docu

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
- bundles/CoreBundle/EventListener/Frontend/DocumentRendererListener.php
- bundles/CoreBundle/Resources/config/event_listeners.yml
- bundles/CoreBundle/Resources/config/pimcore/default.yml
- bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
- bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php
- bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
- bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
- bundles/EcommerceFrameworkBundle/PricingManager/PricingManagerInterface.php
- bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/AbstractAnalyticsTracker.php
- doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/14_Path_Formatter.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Analytics/Google/Tracker.php
- lib/Document/Renderer/DocumentRenderer.php
- lib/Document/Tag/TagHandler.php
- lib/Image/Optimizer.php
- lib/Routing/RedirectHandler.php
- lib/Templating/Helper/Placeholder/ContainerService.php
- lib/Templating/Renderer/TagRenderer.php
Resolves #4660
Need to add docs
> [Core] Fix TODOs

- lib/Tool.php
> Fix PHP Notice: Undefined index: REMOTE_ADDR (command line issue)

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
ClassController:
If you open an object with field collections in a group
DataObjectController:
If you rename the key of an object
> Fix: Undefined index notices

- bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
- bundles/CoreBundle/Resources/translations/en.json
- models/Asset/Image/Thumbnail.php
- models/Asset/Image/Thumbnail/Config.php
- models/Asset/Image/Thumbnail/Config/Dao.php
> [Asset] Possibility to force <picture> HTML tag on thumbnail config

- lib/Helper/Dashboard.php
Try to open the welcome dashboard with a new user
> Fix undefined index in Dashboard.php

- models/Document/Tag/Relation.php
Try to save a snippet with empty relation editable
> Fix undefined index in Relation.php

- models/Asset/Image/Thumbnail.php
- models/Asset/Image/Thumbnail/Processor.php
Old: 
```HTML
<picture data-alt="" data-default-src="/Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking.webp">
<source srcset="/Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking.webp 1x, /Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking@2x.webp 2x">
</picture>
```
New: 
```HTML
<picture data-alt="" data-default-src="/Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking.pjpeg">
<source srcset="/Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking.webp 1x, /Sample%20Content/Example%20Images/image-thumb__341__exampleCover/Chevy%20parking@2x.webp 2x" type="image/webp">
<source srcset="/Sample%20Content/Example%20Images/image-thumb__341__exampleCo …
```
> [Asset] include webp type in <picture> tag if target format is auto

- models/Document/Tag/Video.php
if a cdn is used invalid jsonld data is returned.
> invalid VideoObject jsonLd with cdn

- bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Helper/GridHelperService.php
- models/DataObject/Service.php
This errors occur if you want to set a workflow state operator in the object grid
> Fix: Undefined Indexes

- doc/Development_Documentation/02_MVC/00_Controller.md
Fix docs for using different template in controller action
> Fix template name in docblock

- bundles/AdminBundle/Controller/Admin/ElementController.php
for advaned object metadata with visible fields +  async loading enabled
> undefined index

- bundles/CoreBundle/Resources/migrations/Version20191230103524.php
- bundles/EcommerceFrameworkBundle/Tools/Installer.php
Added index to DB table ecommerceframework_cartitem
> [Ecommerce] Cart-Item Performance Improvement: added index to DB table

- lib/Targeting/VisitorInfoResolver.php
> [Targeting] Performance tuning multiple targeting rules check

- models/DataObject/Listing/Concrete/Dao.php
- tests/model/Inheritance/LocalizedFieldTest.php
enforces strict mode for localized listings
> Localizefield\Listing: added invalid locale check

- models/Element/Recyclebin/Item.php
> [Recycle Bin] Optimize relations serialization with ElementDescriptor

- lib/Translation/AttributeSet/Attribute.php
- lib/Translation/AttributeSet/AttributeSet.php
- lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
- lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
- lib/Translation/ExportService/Exporter/Xliff12Exporter.php
> [Translations] XLIFF Export - Add translated target values

- bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php
- bundles/EcommerceFrameworkBundle/Resources/config/event_listeners.yml
- bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/track_event.js.php
- bundles/EcommerceFrameworkBundle/Tracking/TrackEventInterface.php
- bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
- bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
- bundles/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
- bundles/EcommerceFrameworkBundle/Tracking/TrackingCodeAwareInterface.php
- bundles/EcommerceFrameworkBundle/Tracking/TrackingManager.php
- bundles/EcommerceFrameworkBundle/Tracking/TrackingManagerInterface.php
* add option to get the tracked tracking codes (for example for ajax requests)
* provide a way to forward them as flash message
* add call to track events
* Merge it and make it compatible with #5344 and #5348
* Some more testing (all together with the other PRs)
* Docs?
fixes #3754
> [Ecommerce][Tracking] TrackingManager improvements

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
> [Data Objects] Add Before/After options for Blocks & Field-collections

- .travis/run-stan.sh
- phpstan.neon
There are also phpstan level 2 errors that are not yet ignored
> [PHPSTAN] Load heidelpay-php

- lib/Cache/Runtime.php
> Deprecated array_key_exists in cache Runtime.php 

- models/DataObject/Concrete/Dao.php
- models/DataObject/Concrete/Dao/InheritanceHelper.php
- models/DataObject/Localizedfield/Dao.php
- models/DataObject/Objectbrick/Data/Dao.php
- tests/model/Inheritance/LocalizedFieldTest.php
> Inheritance fixes

- bundles/CoreBundle/Command/CacheWarmingCommand.php
- bundles/CoreBundle/Command/Definition/Import/AbstractStructureImportCommand.php
- bundles/CoreBundle/Command/Definition/Import/ClassCommand.php
- bundles/CoreBundle/Command/Definition/Import/CustomLayoutCommand.php
- bundles/CoreBundle/Command/Definition/Import/FieldCollectionCommand.php
- bundles/CoreBundle/Command/Definition/Import/ObjectBrickCommand.php
- bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php
- bundles/CoreBundle/Command/ThumbnailsVideoCommand.php
- bundles/CoreBundle/Controller/PublicServicesController.php
- bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php
- bundles/CoreBundle/DependencyInjection/Configuration.php
- bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- bundles/CoreBundle/EventListener/Frontend/CookiePolicyNoticeListener.php
- bundles/CoreBundle/EventListener/Frontend/ElementListener.php
- bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
- bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
- bundles/CoreBundle/EventListener/MaintenancePageListener.php
- bundles/CoreBundle/EventListener/PimcoreContextListener.php
- bundles/CoreBundle/Resources/migrations/Version20181115114003.php
- bundles/CoreBundle/Resources/migrations/Version20181128074035.php
- bundles/CoreBundle/Resources/migrations/Version20190527121800.php
- bundles/CoreBundle/Resources/migrations/Version20191230104529.php
Fix all phpstan level 2 PHPDocs errors in the CoreBundle
Before:
```
[ERROR] Found 3476 errors
```
After:
```
[ERROR] Found 3434 errors
```
> [PHPSTAN] Fix CoreBundle PHP Docs

- .travis/phpstan.s4.travis.neon
- .travis/phpstan.travis.neon
- bundles/AdminBundle/Controller/AdminController.php
- bundles/AdminBundle/Security/User/User.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
- bundles/EcommerceFrameworkBundle/PriceSystem/LazyLoadingPriceInfo.php
- bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php
- composer.json
- lib/Document/Tag/NamingStrategy/Migration/Analyze/ElementTree.php
- lib/Migrations/Command/Traits/PimcoreMigrationsConfiguration.php
- lib/Placeholder.php
- lib/Templating/Helper/HeadLink.php
- lib/Tool/Transliteration.php
- lib/Translation/Translator.php
- models/Element/Service.php
- phpstan.neon
Upgrade phpstan to the last version 0.12.4. After upgrade the level 1 had the following errors:
```
------ ---------------------------------------------------------------------- 
Line   bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php  
------ ---------------------------------------------------------------------- 
530    Cannot unset offset 'settings' on array('pimcore_revision' => int).   
------ ---------------------------------------------------------------------- 
------ -------------------------------------------------------------------------------- 
Line   bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php  
------ -------------------------------------------------------------------------------- 
1068   Cannot unset offset 'settings' on …
```
> [PHPSTAN] Upgrade to version ^0.12

- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
> Grid displayed empty if all attributes are assigned to operators #3978

- bundles/AdminBundle/Resources/public/css/editmode.css
Added some top padding to the areabrick toolbar in fixed mode.
> [Areabrick] Add some top padding

- models/DataObject/AbstractObject.php
Adding the same thing to getById i added to getByPath
see: https://github.com/pimcore/pimcore/commit/3f0e55f6046a977db3004a98d590f1bc7bebf042
> Adding null to getById

- models/DataObject/Localizedfield.php
> Revert "Update $context['fieldname'] to $context['containerKey']"

- bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
voucherCodeTabError.html.twig doesent exist seems to be renamed to snake_case
> fix wrong file in voucher controller

- bundles/AdminBundle/Security/Guard/WebserviceAuthenticator.php
- doc/Development_Documentation/24_Web_Services/README.md
> [Webservice] Add API key header option for REST

- bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
- lib/Event/Model/Ecommerce/IndexService/PreprocessErrorEvent.php
This PR adds the subObjectId to the PreProcessErrorEvent.
> [Ecommerce][IndexService] Errorhandling: add subObjectId to error event

- lib/Translation/AttributeSet/Attribute.php
- lib/Translation/ImporterService/Importer/DocumentImporter.php
see https://github.com/pimcore/pimcore/issues/5605
> DataImporter: Document Key

- models/DataObject/Localizedfield.php
see Inheritance performance issue #4997
> Inheritance performance issue  #4997 - Improve dirty detection 

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/date.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numeric.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- bundles/CoreBundle/Resources/translations/en.extended.json
- models/DataObject/ClassDefinition/Data/Checkbox.php
- models/DataObject/ClassDefinition/Data/Date.php
- models/DataObject/ClassDefinition/Data/Datetime.php
- models/DataObject/ClassDefinition/Data/Numeric.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/ClassDefinition/Data/Select.php
- models/DataObject/Concrete.php
- models/DataObject/Concrete/Dao.php
- models/DataObject/Objectbrick/Data/Dao.php
- models/DataObject/Traits/DefaultValueTrait.php
> [Data Object] Default values should be also set to database on create

- models/Element/AdminStyle.php
> Fix: AdminStyle throws PHP Error when having sites in project

- bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectCategory.php
- bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/SelectCategory.php
Deletes some unused code in `SelectCategory` filter types
> [Ecommerce][FilterService] Remove unused code

- doc/Development_Documentation/03_Documents/01_Editables/10_Date.md
> [DOCS] update Date documentation

- doc/Development_Documentation/03_Documents/01_Editables/22_Multiselect.md
> Update 22_Multiselect.md to include a code example for twig

- bundles/AdminBundle/Controller/Admin/AssetController.php
> [Assets][Metadata] - Fix missing config for editmode 

- models/Document/Tag/Link.php
> [Documents][Editable Link] Merge admin & code configuration

- bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
> [Workflow] Fix workflow on symfony 3.4

- bundles/AdminBundle/Resources/public/js/pimcore/functions.js
- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/customreports.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
- bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
This removes unnecessary semicolons in various JavaScript files.
> Remove dangling semicolons in JavaScript

- bundles/CoreBundle/Command/Web2PrintPdfCreationCommand.php
- bundles/CoreBundle/DependencyInjection/Configuration.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Web2Print] Add memory_limit config for pdf-creation command

- models/Asset/Video.php
> [Asset] Fix: Video dimensions don't correct after new video version

- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Log and display the detailed error message, e.g., when running the bootstrap command.
> [Ecommerce] Log and display index update errors

- bundles/CoreBundle/Resources/config/maintenance.yml
- lib/Maintenance/Tasks/HousekeepingTask.php
- lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
> [Thumbnails] Reduce probability of missing LowQualityPlaceholders

- bundles/AdminBundle/Controller/Admin/TagsController.php
- bundles/AdminBundle/Controller/Searchadmin/SearchController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
- bundles/CoreBundle/Resources/migrations/Version20200129102132.php
- bundles/InstallBundle/Resources/install.sql
Resolves #4725
also considered https://github.com/pimcore/pimcore/issues/4195 https://github.com/pimcore/pimcore/issues/4473
> [Tags] server side filtering

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/LazyLoadingSupportInterface.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/ClassDefinition/Data/Objectbricks.php
- models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
- models/DataObject/Concrete.php
- models/DataObject/Concrete/Dao.php
- models/DataObject/Fieldcollection/Dao.php
- models/DataObject/Fieldcollection/Data/AbstractData.php
- models/DataObject/LazyLoadingSupportInterface.php
- models/DataObject/Localizedfield.php
- models/DataObject/Localizedfield/Dao.php
- models/DataObject/Objectbrick/Dao.php
- models/DataObject/Objectbrick/Data/AbstractData.php
- models/DataObject/Service.php
allow other data types to be lazy loaded as well
> replace check against AbstractRelations with interface

- .github/PULL_REQUEST_TEMPLATE.md
- doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
> PHPStan docs (small) improvements

- bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
- bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
> [Ecommerce] Back Office Ordering - fix price rule filter

- models/Document.php
- models/Document/Hardlink.php
- models/Document/Hardlink/Wrapper.php
> [Documents] Fix getChildren() for hardlink & hardlink wrapper

- models/DataObject/Concrete/Dao/InheritanceHelper.php
> InheritanceHelper: Reduce memory consumption

- bundles/EcommerceFrameworkBundle/VoucherService/Statistic.php
fixes: https://github.com/pimcore/pimcore/issues/5737
> [Ecommerce] [Voucher] Statistics not working

- bundles/CoreBundle/Resources/translations/en.json
I want add a german translation for Uncategorized via POEditor
> Translations for "Uncategorized"

- doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
- doc/Development_Documentation/03_Documents/03_Navigation.md
- lib/Navigation/Builder.php
- lib/Templating/Helper/Navigation.php
- lib/Twig/Extension/NavigationExtension.php
> [Document] Navigation: Possibility to specify depth + introduced new param config based build() method

- bundles/CoreBundle/Resources/migrations/Version20200211115044.php
- models/DataObject/ClassDefinition/Dao.php
> [DataObjects] Recheck indices on relations table

- bundles/AdminBundle/Controller/Admin/RedirectsController.php
- bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
- bundles/CoreBundle/Resources/migrations/Version20200212130011.php
- bundles/CoreBundle/Resources/translations/en.json
- bundles/InstallBundle/Resources/install.sql
- lib/Routing/RedirectHandler.php
- models/Redirect.php
- models/Redirect/Dao.php
> [Redirect] Performance & Usability Optimizations

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
> add objects prefix to non admin additional users_workspaces_object condition

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
> [Bug] (Reverse) ManyToManyRelation tables stuck in refresh loop #5644

- models/Document/Tag/Video.php
add "playsinline" and "hl" according to https://developers.google.com/youtube/player_parameters?hl=en
> VideoTag add more valid youtube params

- models/DataObject/ClassDefinition/Helper/ClassResolver.php
- models/DataObject/ClassDefinition/Layout/Text.php
> Fix Text Layout BC Break

- doc/Development_Documentation/19_Development_Tools_and_Details/32_Google_Services_Integration.md
My best practices how to setup Google Services with Pimcore
> Documentation for full package Google Services - best practices

- lib/Analytics/Piwik/Api/SitesManager.php
- lib/Analytics/SiteId/SiteId.php
- lib/Google/Api.php
- lib/Http/ClientFactory.php
- lib/Image/Adapter/Imagick.php
- lib/Mail.php
- lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
- lib/Maintenance/Tasks/LogArchiveTask.php
- lib/Maintenance/Tasks/LogMailMaintenanceTask.php
- lib/Maintenance/Tasks/VersionsCleanupTask.php
- lib/Routing/Dynamic/DocumentRouteHandler.php
- lib/Routing/Staticroute/Router.php
- lib/Tool.php
- lib/Tool/Console.php
- lib/Tool/Newsletter.php
> [Core] Refactor System Configuration - Libraries

- bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
Query all documents by `path` and not only hardlinks
> Fix HardlinkController setValuesToDocument function

- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Fieldcollections.php
- models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
- models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
- models/DataObject/ClassDefinition/Data/UrlSlug.php
- models/DataObject/Concrete/Dao.php
> [Data Object] Improved lazy loading

- bundles/AdminBundle/Controller/Admin/RedirectsController.php
- bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
- bundles/CoreBundle/Resources/translations/en.json
- lib/Routing/RedirectHandler.php
> [Redirects] Filter by Test-URL

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
> [Data Object] Many To Many Relation field list reorder freeze #5683

- bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
> [DataObjects] Quantity Value - fix conversion response if unit is invalid

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
> [Grids] refactor params generation for export and batch jobs #5792

- doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
- lib/Mail.php
> [Mail] Update docs

- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
resolves #5802 
changed so that filter stays active if you open&apply grid config settings but removed if one changes the class selection.
> Filter stays active while changing classes #5802

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_V5_to_V6.md
Add steps to get the same behavior before the checkbox update
> Tri-State-Checkbox update docs

- bundles/AdminBundle/Controller/Admin/IndexController.php
- lib/Config.php
fixes regression introduced in #5745  https://github.com/pimcore/pimcore/commit/0a50951e7f0987fe082ec6d481316e3a6dab4eae#r37389605
> [Core] System Config email settings

- lib/Model/Listing/AbstractListing.php
- models/Asset/Listing/Dao.php
- models/DataObject/Listing.php
- models/DataObject/Listing/Dao.php
- models/Document/Listing/Dao.php
- tests/model/Asset/ListingTest.php
- tests/model/DataObject/ListingTest.php
- tests/model/Document/ListingTest.php
> Asset|Document Listing getCount with Limit and Offset always returns 0

- models/Document/Tag.php
Resolves #5872
Resolves #5875
Related #5872 
Related #5866
> [Document] editables: unset certain properties on clone

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
- models/DataObject/ClassDefinition/Data/UrlSlug.php
- models/DataObject/Data/UrlSlug.php
> [Data Object] Automatically create redirects for changed URL slugs

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
- models/DataObject/Concrete.php
- models/Element/Service.php
> [DataObjects] Refactor multiple assignments check for Advanced relation types

- .travis/app/config/system.yml
- bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
- bundles/CoreBundle/EventListener/UUIDListener.php
- models/Document/Service.php
fixes regression introduced in #5745 https://github.com/pimcore/pimcore/commit/0a50951e7f0987fe082ec6d481316e3a6dab4eae#r37428759
and clean up unused config `$config['general']['http_auth']..`
> [Core] System Config - fix pull page cache & UUID listener #5745

- models/DataObject/Classificationstore.php
> Dealing with undefined index if the field was empty before and the object is not dirty

- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
> Fix Twig example code in the docs

- models/Document/Dao.php
> Fix: Can't copy documents with block tag elements

- models/DataObject/Concrete.php
Follow up of #5894 
Related to #5658 
See also discussion here: https://github.com/pimcore/pimcore/pull/5658#issuecomment-590478950
> [Data Object] Method getClosestParentOfClass($classId) should be independent on the calling class

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Regression of #5777
Resolves #5956
> [Data Object] Batch action in UI not working in localized field context

- bundles/EcommerceFrameworkBundle/Resources/install/admin-translations/init.csv
- bundles/EcommerceFrameworkBundle/Resources/views/admin_order/detail.html.twig
Hello!
I have added the possibility to show the gift items in the order details. This is my first PR and I would like to know, if all is okay.
Thanks in advance!
> [Ecommerce][OrderManager] Show gift list in order details

- models/Document/PageSnippet.php
> Document::hasElement() should return true for inherited elements

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
> [DataObjects] Classification Store - Fix UI visibility issue for localized fields

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
needed for https://github.com/pimcore/data-hub/issues/163
> Class tree: show invisible fields if needed

- models/Version/PimcoreClassDefinitionMatcher.php
as a reference covering other aspects of this topic: https://github.com/pimcore/pimcore/issues/5813
> [Versioning] do not resurrect o_class

- bundles/CoreBundle/Command/ThumbnailsImageCommand.php
- composer.json
- doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
> [Thumbnails] Add option to parallelize thumbnail pregeneration command

- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/abstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/selector.js
- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
> [Search] always open as a new tab and display search term in title + type icon

- bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
- bundles/CoreBundle/Resources/translations/en.json
- doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
- lib/Routing/Staticroute/Router.php
- models/Staticroute.php
- models/Staticroute/Dao.php
Allow configurable HTTP Method for Staticroutes
Resolves #5938
> [Staticroutes] allow http method configuration

- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
> Fix PHP-Template example

- bundles/CoreBundle/Command/ThumbnailsImageCommand.php
- composer.json
- doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
> Reverted #5903 - causing Composer minimum-stability issues due to RC release

- models/DataObject/ClassDefinition/Service.php
- models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
> Fix: [Fieldcollection] Definition export generate wrong filename

- doc/Development_Documentation/26_Best_Practice/13_Building_Custom_Rest_APIs.md
doc link: https://pimcore.com/docs/6.x/Development_Documentation/Best_Practice/Building_Custom_Rest_APIs.html
There is two error coming on 1) undefined method name checkPermission 2) undefined method name adminJson
so I changed this way to element these errors by extends 'Pimcore\Bundle\AdminBundle\Controller\Rest\AbstractRestController' and changing routes.
Thank you
Resolves #
> [DOCS] Update 13_Building_Custom_Rest_APIs.md

- lib/Navigation/Builder.php
- lib/Templating/Helper/Navigation.php
> [Navigation] Possibility to set custom cache lifetime
