pimcore/pimcore

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Without this fix, it always shows every folder in the Search Dialog within a ManyToMany Object Relation
=> don't allow folders in ManyToManyObject Relations Search Dialog

.travis/web/app_test.php, doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing.md, lib/Bootstrap.php, tests/_bootstrap.php
BC (tests, existing web.php, ...) is assured by providing a deprecated
version with the old method name.
https://github.com/pimcore/skeleton, https://github.com/pimcore/demo-basic and https://github.com/pimcore/demo-basic-twig should be adjusted as well.
=> [Core] Fix typo in Bootstrap::bootstrap() method name

lib/Templating/Helper/HeadStyle.php
The HTML Tags "style" now get rendered without "text/css".
=> Fix w3c validation warning in HeadStyle template helper

doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/01_Text_Types.md
As discussed in #4411 there was a BC break in 6.0 because the default `enterMode` got changed. This PR explains the details how to reset it and what the consequences are.
=> [Documentation} Wysiwyg field configuration -> enterMode

models/DataObject/ClassDefinition/CustomLayout/Dao.php, models/DataObject/ClassDefinition/Dao.php
Resolves (bulk) importing Custom Layouts that do not exists yet
```
Timestamp: Tue Jul 09 2019 10:35:22 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/class/bulk-commit
Method: post
Message: Argument 2 passed to Doctrine\DBAL\Connection::fetchColumn() must be of the type array, null given, called in /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php on line 303
Trace: 
#0 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(303): Doctrine\DBAL\Connection->fetchColumn('SELECT name FRO...', NULL, 0, Array)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/CustomLayout/Dao.php(73): Pimcore\Db\Connection->fetchOne('SELECT name FRO...', NULL)
#2 …
```
=> Fix bulk importing new custom layout

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
I understand that on the face of it may look like there is a degree of p.a. here, but it is not my intention. I really *do* want Pimcore to heed best practices and be clear about the places where steps have been taken to deviate from them:
> Changing the Enter Mode setting to BR or DIV is not recommended. The default CKEDITOR.ENTER_P mode is fully supported by all editor features and plugins and is also the most correct one in terms of best practices for creating web content.
=> Clarifies 6.x Upgrade notes wrt WYSIWYG

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
When sorting data objects in the tree, the new index isn't reflected in the object instance that is passed into the event listener.
While technically the object sort index hasn't been updated yet, it is still
confusing that the postUpdate listener doesn't get the updated index value.
I'm not sure if there is a reason for updating indexes of siblings after the save,
that is why I didn't put everything in one if statement.
The index in the object that is passed into the postUpdate listener has the correct index.
=> When sorting data objects in the tree, the new index isn't reflected in event listener

bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
With this change it is possible to translate the menu items in the perspective toolbar tree.
/app/config/pimcore/perspectives.php
```
return [
'default' => [
],
'location' => [
],
];
```
=> [Perspective] Translation for name in toolbar

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Currently there is an exception thrown if you open an object which got deleted in the meantime.
1. Open Pimcore backend in 2 browser tabs
1. Browse the tree till you see a certain object in both browser tabs
1. Delete the object in browser tab 1
1. Try to open the object in tab 2
=> No exception if opened object got deleted in the meantime

models/Asset.php
Currently it is not possible to set a remote stream as the new data source for an asset.
Reproducable with this script:
```php
$asset = \Pimcore\Model\Asset::getById(<ID of an existing Asset>);
$asset->setStream(fopen('https://picsum.photos/200/300', 'rb'));
$asset->save();
```
Results in lots of exceptions because PHP cannot rewind a remote stream (as discussed in #4416 -  the code in this PR is just copied from there).
=> [Assets] Set remote stream

lib/Pimcore.php
Fixes #4709 
tl;dr
Change https://github.com/pimcore/pimcore/commit/4f7725c70586767fc5ddd7e0fb8399adffd0be0f#diff-ff0c921492cef999788fd76dcb807a22R306 introduced code that isn't working properly with a cache warmup scenario.
=> #4709 Workaround for shutdown handling during cache warmup

models/Document/Tag/Areablock.php
When importing data from another Pimcore instance using REST, the `getFromWebserviceImport` method in the `AreaBlock.php` file incorrectly parses the `$indices`. This causes an error when trying to open the corresponding `document`, as the database now contains `stdClass` in the serialized data.
The `$indices` are now properly parsed as seen in the commit. This resolves the issue, ultimately, making the content available as exptected.
=> [Bug-Fix] Areablock not processing data from rest import properly

models/Document/Tag/Areablock.php, models/Document/Tag/Link.php
Pretty much the same thing as https://github.com/pimcore/pimcore/pull/4712 only for `Link.php`.
For internal links, the `internalId` is not updated with the local document ID, resulting in a `null` value when saving the document.
Ultimately, this means that links are not imported as the data is lost.
If the link is `internal` the ID is updated with the local ID.
=> [Bug-Fix] Link not processing data from rest import properly

bundles/AdminBundle/Resources/public/js/pimcore/startup.js, bundles/AdminBundle/Resources/views/Admin/Misc/admin-css.html.php
- Icon is black on active now
- Icon is in center
The size of the icons are 24x24 but in this case they should 30x30. I tried to resize with background-size but it doesn't work (Chrome). Maybe it works if we remove the fixed size in the SVGs? Does someone have an idea?
=> [Customview] Icon not in center and doesn't invert on active

models/Document/Tag/Video.php
Wenn direkt im Video-Asset ein Posterimage zugewiesen wird, funktioniert die Funktion "getImageThumbnail" nicht -> habe es auf "getThumbnail" geändert.
Zusätzlich noch mit "Current player position as image" getestet und in der pimcore_video Funktion ein Posterimage zugewiesen.
=> Update Video.php - getImageThumbnail() to getThumbnail()

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
It would be good to display the translated name of tab panels.
We use translation identifiers for this panel labels.
=> [DataObject] GridConfigDialog: Layout items in tree are not translated

lib/Routing/Staticroute/Router.php, lib/Templating/Helper/PimcoreUrl.php
If you add the param encode in pimcoreUrl() (4. param) now you get the url with all utf8 stuff
=> [Static Routes] Delegate `encode` Param to the Generator

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js, bundles/CoreBundle/Resources/migrations/Version20190729085052.php, models/User/Permission/Definition.php
added a category column to the database
sort permissions for user & roles by category
if no category is available the permissions will be sort in a default group
=> Sort permissions for users & roles by categories

bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php, bundles/AdminBundle/Resources/public/css/icons.css, bundles/AdminBundle/Resources/public/js/pimcore/document/newsletter.js, bundles/AdminBundle/Resources/public/js/pimcore/document/newsletters/plaintextPanel.js, bundles/AdminBundle/Resources/views/Admin/Index/index.html.php, bundles/CoreBundle/Resources/translations/de.json, bundles/CoreBundle/Resources/translations/en.json, lib/Tool/Newsletter.php, models/Document/Newsletter.php
Spam filters like SpamAssassin rate multipart emails higher than just html-email. Having the text part is worth one score point. The existing version just sends html-emails, also with the detour via html2text. (See comment in code).
Following database change has to be done first: (I don't know how to send the db-update in a PR)
ALTER TABLE `intranet`.`documents_newsletter` 
ADD COLUMN `plaintext` LONGTEXT NULL DEFAULT NULL AFTER `sendingMode`;
Best regards
Lexi
=> [Documents] Newsletter: add option to maintain a manual edited plain-text version

bundles/AdminBundle/Resources/public/js/pimcore/document/edit/dnd.js
Removed unused variables `iFrameElement` and `xy`
* `iframeElement` (spelled differently) is passed through initialize parameters
* `xy` is never used in the function scope
=> Remove unused variables in document editmode dnd

bundles/CoreBundle/Resources/config/pimcore/default.yml, bundles/CoreBundle/Resources/config/pimcore/security.yml, doc/Development_Documentation/19_Development_Tools_and_Details/40_Custom_Admin_Login_Entry_Point.md
Hello,
This PR make context matching more robust so it does not include URLs like:
```
/admin-project
/webservice-project
/plugin-project
...
```
Actually they was resolved as admin/webservice/plugin context.
Firewall paths have been changed too, so firewall is not activated on these custom URLs.
Now, something like:
```
project_myfront_entry_point:
path: /admin-front
controller: AppBundle\Controller\DefaultController::testFrontAdminAction
```
will work ! : )
And custom admin pimcore entrypoint can now begin with /admin* too.
Doc for admin entrypoint is updated in this PR too.
https://github.com/pimcore/pimcore/issues/4790 is resolved with this PR.
Tested locally, all seems to works pretty fine.
Thanks.
=> Fix paths in yml files for more robust context and firewall

bundles/CoreBundle/Resources/config/logging.yml
When using Pimcore 6, it is no longer possible to call `ApplicationLogger::getInstance()` due to the `pimcore.app_logger.default` being private.
This PR sets `pimcore.app_logger.default` public, which allows us to call `ApplicationLogger::getInstance()` again.
=> Application::getInstance throws error

lib/DataObject/GridColumnConfig/Value/DefaultValue.php
Currently there is an error if you add a date formatter operator to a grid config and assign this date formatter operator the modificationDate or creationDate system columns. 
(This screenshot is done including this PR's changes)
This results in the error
´´´
Call to a member function isEmpty() on null
Trace: 
#0 /path/to/pimcore/vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Value/DefaultValue.php
...
´´´
This PR fixes this problem.
=> Transmit values of system columns to grid operators

models/Asset.php
Currently it is not possible to get the checksum of an asset before it got saved.
Code to reproduce:
```php
$fileStream = fopen('https://picsum.photos/200/300', 'rb');
$asset = \Pimcore\Model\Asset::create(1, array(
'filename' => 'test.jpg',
'stream' => $fileStream
), false);
var_dump($asset->getChecksum());
```
This outputs 
* without this PR: null
* with this PR: actual hash of the file
PS:
The same happens for 
```php
$fileStream = fopen('https://picsum.photos/200/300', 'rb');
$asset = new \Pimcore\Model\Asset();
$asset->setStream($fileStream);
var_dump($asset->getChecksum());
```
=> [Assets] Get checksum of remote assets before they got saved

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
When batch editing in Grid Tab (ie: Advanced Object Search) errors are not returned and only show ids.
Suggestion:
Show the a list of failed IDs and error message (once that we already have the request with this message)
This allow our users to see the error and take some action after this.
- Push the error message to allow with the job ID,
- Display the error message in the error message alert.
Resolves #4404
=> Grid Tab batch edit error only show the IDs

doc/Development_Documentation/03_Documents/03_Navigation.md, lib/Navigation/Renderer/Menu.php
Changes in this pull request  
Resolves #4741
```php
<?php
echo $this->navigation()->menu()->renderMenu($mainNavigation, [
'maxDepth' => 2,
// apply different ulClass on depth levels 
'ulClass'  => [
0 => 'nav navbar-nav', //ulClass for first level
1 => 'nav navbar-nav-second',
2 => 'nav navbar-nav-third'
],
//or apply same ulClass on depth levels
'ulClass'  => [
'default' => 'nav navbar-nav'
]
]);
?>
```
=> [Documents] Navigation - Added option to provide class for sub menus

bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php, bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php, bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculatorInterface.php
This PR fixes calculating a already calculated cart.
Whenever getGiftItems or getGiftItem is called the calculate method is executed. This also triggers the applyCartRules function. However, this should not be the case if the cart was calculated before.
@fashxp
=> [Ecommerce][CartManager] Calculate GiftItems of Cart only if not already calculated

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
I had the case that there was invalid json data in my index store table. As the json_decode failed the data was not added to the index itself and there always was some inconsistency between store and index - without any errors shown. This PR now throws an error if the json_decode fails.
=> [Ecommerce] Consider json_decode errors on updating index

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
In previous versions there was no regex name check therfore some legacy names do not work anymore. I suggest to allow _ here as it is not a dangerous character.
=> Allow _ in custom object layout names

models/Version.php
Otherwise, it would also copy entity-manager and that is not possible, this fixes CoreShop Builds: https://travis-ci.com/coreshop/CoreShop/jobs/224293440#L991
=> Update Version marshal to ignore Doctrine

models/DataObject/ClassDefinition/Data/Hotspotimage.php
When exporting data using the `RestImporter`, `HotspotImage`s fail (i.e., they are not imported).
Importing `HotspotImage`s simple works without any trouble - so that they are set in the new Pimcore instance.
`HotspotImage`s are not set.
The file `models/DataObject/ClassDefinition/Data/Hotspotimage.php` was changed in order to properly access they keys.
The following `JSON` shows an example of the "before and after" behaviour.
```json
{
type: "hotspotimage",
value: {
headerImage__image: 243,
headerImage__hotspots: "a:3:{s:8:"hotspots";a:0:{}s:6:"marker";a:0:{}s:4:"crop";N;}"
},
name: "image",
language: null
}
```
```json
{
type: "hotspotimage",
value: {
headerImage__image: 243,
headerImage__hotspots: {
hotspots: [ ],
marker: [ ],
crop: null
}
},
name: "image",
language: null
}
```
=> [REST] hotspot images are neither properly exported nor imported

bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php
As the only practical possible solution for handling this exception is to recreate the order it's better if the ecommerce framework directly handles this.
=> [ecommerceframework][v7 CheckoutManager] recreate order if trying to start a payment with an aborted, cancelled or commited order

bundles/AdminBundle/Resources/public/js/pimcore/settings/fileexplorer/file.js
The original styling has no visible effect. I suppose the intention was to display the file-explorer with a monospace font so I adjusted for that with fieldStyle:
https://docs.sencha.com/extjs/6.2.0/classic/Ext.form.field.TextArea.html#cfg-fieldStyle
=> [UI] Use monospace font for server file explorer

bundles/CoreBundle/DependencyInjection/Configuration.php, lib/Workflow/Place/PlaceConfig.php
Object/custom layouts can have a string as ID. However, when configuring those for a workflow the system will throw an exception because of the configuration validation.
=> [Workflows] Allow non-integer object layout IDs

models/Asset.php
Return `$this` from the three metadata setters `setMetadata`, `setHasMetaData` and `addMetadata` to make them chainable.
Resolves #4858
=> [Assets] Make metadata setters chainable

bundles/CoreBundle/Resources/config/pimcore/default.yml
Presta Sitemap now sets dump_directory to public by default for Symfony Flex.
Since Pimcore does not use Symfony Flex yet, this should be set by default.
=> override default dump_directory from public to web

bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php, bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
If you have got a lot of products (several hundred thousand) with a complex data structure the preparation may sometimes take quite some time if i.e. a product category with a lot of dependencies gets updated. So if I configured the preparation (`ecommerce:indexservice:process-queue preparation`) to run every 5 minutes but it takes about an hour to finish the job the server load continues to increase as more and more processes are running.
This PR now adds several new options to the `ecommerce:indexservice:process-queue` command:
- `ignore-lock` (default true for bc)
- `unlock`
- `lock-timeout`
- `timeout`
The lock-name is a checksum of the `queue` argument and the `tenant ` option.
=> Process queue improvements

bundles/CoreBundle/Controller/PublicServicesController.php
robots.txt should be served with a Content-Type: text/plain header.
robots.txt is served with a Content-Type: text/html header.
* Adds the Content-Type header to the robots.txt Response.
* Adds the Response code 200 by Response class constant.
=> Adds missing content type to robots.txt

models/Asset.php
Currently if an asset had metadata and `$asset->setMetadata(null)` or `$asset->setMetadata([])`gets called, the property `hasMetaData` stays true.
=> [Assets] hasMetaData should be false if setMetaData(null) gets called

bundles/AdminBundle/Controller/Admin/AssetController.php, bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Controller/Admin/Document/FolderController.php, bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php, bundles/AdminBundle/Controller/Admin/Document/LinkController.php, bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php, bundles/AdminBundle/Controller/Admin/Document/PageController.php, bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php, bundles/AdminBundle/Controller/Admin/Document/SnippetController.php, bundles/AdminBundle/Resources/public/css/icons.css
When two users open the same data object in Pimcore backend there is the message "The desired element is currently opened by another person" with the option to open it anyway. This dialogue's goal is to prevent the object from being edited by multiple users in parallel because this would overwrite the changes of each other. As it is currently too complex to implement a mechanism to allow parallel editing (#4810) this PR shows the edit-lock dialogue only to those users who have the right to edit the opened object. If a user does not have the right to open the object the dialogue does not make much sense because he cannot alter the object anyway.
Use case: Multiple support employees wiht only read permissions use Pimcore for researching data. When they open the same object the edit-lock …
=> [Data Objects] Show editlock dialog only if user has permissions to edit object

models/Element/Tag.php
I'd say we can skip to attempt loading a 0 / empty parent tag id as it will lead to null anyways.
Checking that in the function itself is less overhead (no db query, no exception handling)
=> Don't load by tag parent by empty id

models/DataObject/ClassDefinition.php, models/DataObject/ClassDefinition/Listing/Dao.php
If another developer forgets to check in a class definition, it would be good if the page were still usable.
The `DataObject\ClassDefinition::getById` method log the missing class now.
=> [DataObject] Avoid fatal errors if class definition file is missing

bundles/CoreBundle/Resources/migrations/Version20190828142756.php, bundles/InstallBundle/Resources/install.sql
This fixes the Percona Error:
`WSREP: Percona-XtraDB-Cluster doesn't recommend use of DML command on a table (fotobuchDB.http_error_log) without an explicit primary key with pxc_strict_mode = PERMISSIVE`
=> add primary key to http_error_log

bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js, bundles/AdminBundle/Resources/public/js/pimcore/object/object.js, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
when user has no publish permission, he sees only save button in documents and data objects controller.
hitting this button must not unpublish element (if already published). it only should save new version.
=> fixed #4905 - [Elements] Save button must not unpublish element

bundles/CoreBundle/Resources/migrations/Version20190828142756.php
I get following error in this migration with MySQL 5.7:
```
Migration 20190828142756 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `http_error_log` ADD `id` int(11) NULL AUTO_INCREMENT PRIMARY KEY FIRST;':
SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```
See #4900
=> Fix syntax error in migration

tests/cache/Pool/SymfonyProxy/ArrayAdapterProxyTest.php, tests/cache/Pool/SymfonyProxy/FilesystemAdapterProxyTest.php, tests/cache/Pool/Traits/CacheItemPoolTestTrait.php
Fix error in Travis tests:
```
Fatal error: Declaration of Pimcore\Tests\Cache\Pool\Traits\CacheItemPoolTestTrait::tearDownAfterClass() must be compatible with Symfony\Component\Cache\Tests\Adapter\FilesystemAdapterTest::tearDownAfterClass(): void in /home/travis/build/pimcore/pimcore/tests/cache/Pool/SymfonyProxy/FilesystemAdapterProxyTest.php on line 15
```
=> [Tests] Fix Compile Error in Symfony 4

doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md, models/Asset/Image/Thumbnail.php
Resolves #4737
Introduced new option '**defaultalt**' to provide fallback alt, as **alt** is already being used to override meta information in Image
priorities:
1. **alt** option in getHtml()
2. **alt** from Image metadata
3. **defaultalt** option in getHtml()
4. **title** - from Image metadata
example 
```
$asset->getThumbnail("content")->getHtml(['defaultalt' => 'default alt']);
```
=> Image thumbnail fallback alt option

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
ExtJs closes Ext.Tooltip instances automatically after 5s (see https://docs.sencha.com/extjs/6.2.0/modern/Ext.tip.ToolTip.html#cfg-dismissDelay).
When you have long or complex helper texts in the tooltip of a data object field this can be annoying. This PR disables automatic closing of tooltips while the mouse is still on the field - of course it gets still hidden when the mouse leaves the field label.
=> [Data objects] Do not hide tooltips automatically after 5s

bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
It would be nice to be able to extend the Datatrans Payment Method without the need to defined new required configuration properties.
Currently the check if all required configuration options are set: `$config = array_intersect_key($config, $required);` overwrites possibly optional options.
=> Don't strip optional datatrans config properties

models/DataObject/ClassDefinition/Data/QuantityValue.php
If a quantity value has no valid units defined, all units are available. Rhese units are not sorted.
=> [DataObject] Unsorted Quantity value units

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolygon.js
1. Create a object with geopolygon field
2. Create a polygon and save the object
3. Edit the polygon and cancel the edit mode
4. Save the object
5. Reload the object
6. Edited polygon is saved instead of old version
Noticed at #4942
=> [DataObject] Geopolygon field doesn't respect cancel in edit mode

bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
Small fix in the regex of the FrontendRoutingListener. `.` matches all characters not only the dot, thus it needs to be escaped.
=> Small fix in the regex of the FrontendRoutingListener

doc/Development_Documentation/19_Development_Tools_and_Details/23_Placeholders/README.md
Actually the placeholder does not contain the quotes. Or the other way around: the quotes do not belong to the placeholder and thus do not get replaced.
=> Fix readme: Placeholders

lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
Only text fields can be exported. Images, relations and other field types need to be ignored.
=> [XLIFF] ignore not exportable tags in localized blocks

models/Element/Service.php
When using keys that start with dot and space (e.g. `. test`) we get a key that still begins with aspace (eg. ` test`).
=> Element\Service::getValidKey - fix for names starting with both dots and spaces

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
I had the case that there were encoding errors (Error code 5) for some product related data. As the json_encode failed the data was added to the mysql store table but not sent to the elastic search index, so there always was some inconsistency between store and the elastic index - without any errors shown. 
This PR now throws an error if the json_encode fails. This PR is related to https://github.com/pimcore/pimcore/pull/4827.
=> [Ecommerce] Consider json_encode errors on updating index

bundles/EcommerceFrameworkBundle/CartManager/CartItem.php
The getCart() method must appy the user-defined cart class, and not the default one.
If the default one is used, the application may throw random errors as soon as custom methods are applied to a cart, which do not exist within the default class implementation of Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\Cart.
=> Ecommerce: getCart() in CartItem class must use user-defined class definition 

bundles/EcommerceFrameworkBundle/Command/IndexService/BootstrapCommand.php, bundles/EcommerceFrameworkBundle/IndexService/IndexService.php
Add an option to the ecommerce index bootstrapping command, which will build/update the index only for specific tenants.
=> Ecommerce index bootstrapping for specific tenants.

bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Ran into this issue after updating to version 6.2.1.
How to reproduce
- Create a classification store with collections
- Add a classification store field to a data object
- Add classifications using collection(s)
No classifications are added since none are found. When debugging the controller I noticed the groups data query didn't return any results and when checking the file history I noticed this change, which causes the problem: https://github.com/pimcore/pimcore/commit/ccfc5c30869a18b05ba4cc415fdc32fedd8854e2
=> [DataObject] Classificationstore cannot add collections

models/DataObject/Objectbrick/Dao.php
This fixes issue #4999 .
The problem can not be easily reproduced in the demo shop because we had it during our product update scenario from outside of Pimcore.
Changing one product in Primcore leaded to a deletion of objectbricks of an another product which was in relation to the one being updated. Why?
Simply because the dirty flag map of the object bricks were handled incorrectly.
=> changed marking flag for complete object instead of 'last' field

lib/Templating/Helper/Cache.php
Make the cache templating helper more modular, so that 
1. content can be added to the cached data before writting it to the cache, 
2. the cached data can be modified after retrievela and before output.
=> Make the cache templating helper more modular

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Mass updates on the ecommerce product index store can cause the system to slow down, because no index is used when updating the worker. By adding a new index, the performance increases massively.
On index updates, the ecommerce queue is processed. SQL update queries, such as follows, occur frequently.
```sql
UPDATE ecommerceframework_productindex_store_elastic SET worker_id = '5d97121450e87', 
worker_timestamp = '1570181652' WHERE (crc_current != crc_index OR ISNULL(crc_index)) AND 
tenant = 'AT_hr_elastic' AND (ISNULL(worker_timestamp) 
OR worker_timestamp < '1570181352') 
LIMIT 200
```
This caused our system to slow down, so we analyzed the update statement by rewritting it into a sql statement, and then using SQL ``explain``. We found out that no index is used on the update statement! …
=> [Ecommerce][IndexService][Elastic] Add database index to ecommerce index

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js, models/DataObject/ClassDefinition/Data/CalculatedValue.php
Currently calculated value fields are always displayed as input fields. With longer texts this has the disadvantage that not all content is visible (or only via horizontal scrolling). For example we have cases where whole product descriptions get generated by lots of object fields.
This PR adds an option to display calculated value fields as textareas. You can choose in class definition whether you want an input field or a textarea - input being the default.
=> Add option to display calculated value field as textarea

bundles/EcommerceFrameworkBundle/IndexService/Getter/DefaultClassificationAttributeGetter.php, bundles/EcommerceFrameworkBundle/IndexService/Getter/DefaultCustomAttributeGetter.php
This PR provides an index getter that retrieves data from a classification store attribute of an object.
It can be defined through through the index_service config in which the getter can be defined through a getter_id as usual. It is required to additionally provide getter_options:
- key_id    - id of the classification store attribute
- group_id  - id of the group related to the id | key can occur multiple times in classification store field through multiple groups
- fieldname - name of the field upon which the classification store is saved on the specific object [defaults to attributes]
the getter_options can contain multiple items. if the current item sepcified by fieldname, key_id and group_id is not present or null the next item will be evaluated as fallback. 
Note that Localization …
=> [Ecommerce] index getter that retrieves data from a classification store attribute

models/Asset.php, models/DataObject/AbstractObject.php, models/DataObject/Concrete.php, models/Document.php, models/Element/ValidationException.php, models/Property/Predefined/Listing.php
Some doctypes in Asset class only declared parameters of type `array`. As this makes auto-complete implossible this PR specifies the type of the array.
=> Asset doctype specification

models/DataObject/Classificationstore/KeyConfig.php
This PR adds caching to `getByName()` classification store keys similar to `getById()`.
=> Add cache to getByName Classification Store Key

bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js, bundles/CoreBundle/Resources/translations/en.json, lib/Web2Print/Processor/PdfReactor8.php
We had to change our SSL certificates some days ago. PDFreactor is now unable to access images and css file hosted on the Pimcore server. 
`SSLHandshake: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 11:53:05.905 `
The newly installed SSL certificate is perfectly valid and accepted by every major browser, no intermediate or other certificates need to be installed manually (our certificate is issued by Swiss Sign, it isn't a self-signed certificate).
PDFreactor supports to suggests to set the following option: https://support.realobjects.com/support/solutions/articles/7000016828-how-can-pdfreactor-connect-to-a-server-using-https-
This PR adds an option to enable this option on the web2print …
=> PDFreactor: Add httpsMode option to work around ssl connection problems

models/Asset.php
When you set an asset's metadata via `setMetadata` method it is possible to have two metadata items with the same name (and language).
To reproduce:
```php
<?php
$asset = \Pimcore\Model\Asset::getById(1234);
$asset->setMetadata([
[
'name' => 'test',
'type' => 'input',
'data' => 'test',
'language' => null
], [
'name' => 'test',
'type' => 'input',
'data' => 'another_test',
'language' => null
]
]);
$asset->save();
```
The result is:
This PR changes this behaviour to overwrite existing items with same key (or same key+language for localized metadata items).
=> [Assets] Metadata name must be unique (or unique for certain language)

doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Curl should be be a required extension, since following the installation instructions without curl installed results in the following error:
=> Update system requirements docs

bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- Be sure to have asset tree preview enabled
- open quicksearch
- hover over the asset tree
- preview will be opened
another case
- implement an iFrame with whatever application or target
- open quicksearch
- try to close quicksearch with click in the area of the iframe
- quicksearch does not close
current implementation allows the application to consume mouse events behind the quicksearch overlay
This is a bad UX on several places....e.g. if asset tree preview is enabled or if an iframe is implemented
which will consume the mouse events and prevent the quicksearch overlay to be closed.
Simply add an additional div to control this behaviour
=> [quicksearch]: do not allow to consume mouse events behind quicksearch overlay

models/Document/PageSnippet.php
Fixed doctype of PageSnippet::setElement()
Shortened some other doctypes.
Are there actually any plans for a future major version to add typehints (parameter and return types) to all functions?
=> Fix doctype for PageSnippet::setElement()

bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
When using a subtenant with the basic implementation, the o_id column is ambigious since it is used in the product index table and the subtenant assortment table as well.
This will lead to an error when using the variant mode "VARIANT_MODE_INCLUDE_PARENT_OBJECT". Using the default alias "a" in the condition solves the issue.
=> Ecommerce Subtenant ambigious column o_id

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Many to many (object) relations had a typo which prevented changing the order within a relation field.
Additionally this PR allows text selection in edit mode for all relational fields when they are configured as readonly / non-editable (as done in #5125 for the folder object grid).
=> [Data object > Relation fields] Sort items by drag & drop

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
Render calculated fields with `readOnly` attribute instead of `disabled` to be able to select and copy the content. Somehow we forgot this in #3693.
=> [Calculated value fields] readOnly instead of disabled

models/DataObject/ClassDefinition/Data/CustomVersionMarshalInterface.php, models/Version.php, models/Version/PimcoreClassDefinitionMatcher.php, models/Version/PimcoreClassDefinitionReplaceFilter.php
This makes a lot of Problems with complex custom data-types where we in CoreShop link DataObjects with Doctrine Entities. This PR basically adds support for Custom Data Types to marshal and unmarshal Data for Versions as they need id.
=> allow custom field-definitions to marshal and unmarshal version data differently

models/Version/Dao.php
I extended #4983's version by the following points:
* Only one SQL query to get all outdated versions (via ordered GROUP_CONCAT) instead of n+1 with n being the number of elements which have outdated versions
* Remove `array_unique` calls as in my opinion it is not possible for one version to belong to multiple elements
I kept the `LIMIT 1000` as in https://github.com/pimcore/pimcore/blob/22a337f716b99409db2746410abbe2ba53b87513/models/Version/Dao.php#L166-L169 the loop gets aborted if there are more than 1000 outdated versions. And as for 1000 outdated versions at most 1000 elements (with at least one outdated version) are needed, the limit is correct (if some elements have more than 1 outdated versions, some elements are fetched to no avail - but this is also the case with the current …
=> Better performance for retrieving outdated versions

doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
If the complete url is used, css and images will not be shown with wkhtmltopdf and web2print-output.log will have errors like this:
> Warning: Failed to load http://http//example.com/static/css/custom.css (ignore)
Warning: Failed to load http://http//example.com/images/example.png (ignore)
=> Don't use complete url

models/DataObject/Fieldcollection/Definition.php
Before:
```
/** 
Fields Summary: 
- basicMaterial [manyToOneRelation]
- localizedfields [localizedfields]
*/ 
```
After:
```
/** 
Fields Summary: 
- basicMaterial [manyToOneRelation]
- localizedfields [localizedfields]
-- appearance [input]
-- surfaceModification [input]
*/ 
```
=> Add localizedfields to Fieldcollection and Objectbrick field summary

bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Base64.js, bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js, bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/columnConfigurationTab.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/Ignore.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/Iterator.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/ObjectBrickSetter.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/PHPCode.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/Published.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/Splitter.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/operator/Unserialize.js, bundles/AdminBundle/Resources/public/js/pimcore/object/importcolumn/value/DefaultValue.js, lib/DataObject/Import/ColumnConfig/Value/DefaultValue.php
If I drag and drop a object brick field in the column tab of the csv import, the attribute fields are empty/incorrect and readonly.
=> Fix: Objectbrick csv import

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Resolves #
Pimcore doesn't allow to edit an object with empty required fields, directly from the grid even if the user doesn't want to publish changes, but only save.
After below changes editing and saving from the grid is possible.
=> Omit mandatory check when an object is not to publish

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js
Currently when you copy or clone a calculated value field its element type (input or textarea) does not get copied. This PR fixes that.
=> Transfer elementType on cloning / copying calculated value field

models/DataObject/Classificationstore.php
adds the given group to active groups in case setLocalizedKeyValue is called. this is useful whenever you  are inserting values via php api
not sure if we should add a check if the given group really exists there too. what do you think @weisswurstkanone
=> [ClassificationStore] - add given group to active groups

models/DataObject/ClassDefinition/Data/Classificationstore.php
there may be data for a specific classification store key in the object_classificationstore_data_X table although the refered group in this table is not among the active groups.
in this case data should not be put out for editmode/webserviceexport/searchindex
this pr checks if a group is among said active groups and only then outputs the referring value
@weisswurstkanone
=> [ClassificationStore] - don't output data of non active groups

models/Document/PageSnippet.php, models/Document/PageSnippet/Dao.php, models/Document/Tag.php, models/Document/Tag/Area.php, models/Document/Tag/Area/Info.php, models/Document/Tag/Areablock.php, models/Document/Tag/Block.php, models/Document/Tag/Link.php, models/Document/Tag/Scheduledblock.php, models/Document/Tag/Wysiwyg.php
I have an areablock with items. These items have editables like an input.
In the moment it is impossible to get the current data from this input in the controller.
Because the getElement method loads the saved version of the document.
I add a setDocument and getDocument method. So we can use the modified document.
=> [Document] Fix: Tags getElement method returns only saved data

bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
In the versions tab sometimes it would be useful to be able to copy the timestamp of a certain version. This PR makes this possible.
=> [Data objects] Enable text selection for version data

lib/Video/Adapter/Ffmpeg.php
Helps to avoid longer encoding times, see [https://www.nrg-media.de/2010/11/creating-screenshots-with-ffmpeg-is-slow/](https://www.nrg-media.de/2010/11/creating-screenshots-with-ffmpeg-is-slow/)
This one appears on large local video files, in my case it was an full-HD *.wmv. When picking a frame to generate a preview it would take more time, the higher the time offset is.
**how to reproduce:**
Click "Use current position as preview" on a long bing video file with a big offset (e.g. > 300)
=> Move ss option of ffmpeg to the beginning

bundles/InstallBundle/Command/InstallCommand.php, bundles/InstallBundle/Installer.php
This PR adds a possibility to install Pimcore with databases where [SSL connection](https://dev.mysql.com/doc/refman/5.7/en/encrypted-connections.html) is required. 
An example here can be [Azure Database for MySQL](https://azure.microsoft.com/en-us/services/mysql/) where SSL connection is recommended: https://docs.microsoft.com/en-us/azure/mysql/concepts-ssl-connection-security 
This PR should make no changes to the actual installation process - it is just an addition:
- `mysql-ssl-cert-path` won't be asked interactively
- if `mysql-ssl-cert-path` parameter will be omitted in CLI (or env variables) then the installation is like it was until now
=> Pimcore installation on MySQL with required SSL connection

bundles/AdminBundle/Controller/Admin/LoginController.php, bundles/AdminBundle/Controller/Admin/UserController.php, bundles/AdminBundle/Security/Guard/AdminAuthenticator.php, lib/Tool/Authentication.php
Old link: `/admin/login/login?username=<username>&token=<token>`
New link: `/admin/login/login?token=<token>`
=> [ADMIN] Token login links shouldn't contain the username

bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js
Reproduce:
* Create a brick containing a pimcore_areablock('ident')
* Insert any brick in the newly generated brick
* delete the parent brick containing the pimcore_areablock
=> Cannot read isAncestor of 'null'
Fix: inserted check if 
```
Ext.get(id) 
```
gets an element at all
Resolves #
=> Fix: deleting element containing pimcore_areablock

models/Asset.php, models/DataObject/AbstractObject.php, models/Document.php
Currently when you call Asset::getList() or Document::getList() the listing object is not only generated but also its items get loaded. This makes it impossible to have something like
```php
$listing = Asset::getList();
$listing->addConditionParam('type != "folder"');
// without this PR listing's items contain also assets with type="folder" 
// because Listing::load() is already executed in Asset::getList()
// thus any change to the listing parameters afterwards will be ignored
foreach($listing as $asset) {
...
}
```
For documents applies the same.
This is especially a bug as it is possible to modify a data object listing object after having it created via `AbstractObject::getList()`.
=> [Assets, Documents] Do not load listing data on Asset::getList() / Document::getList()

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
This PR brings a new button "Copy & Close" to the "Login as this user" dialog, so the user isn't required to select & copy the URL.
Also included are minor changes such as
* Meaningful alert title
* Increased textarea height so URL will usually fit
* Make textarea readonly, as changing the value doesn't make sense
=> [UI][User] "Copy to clipboard" feature for "Login as this user" dialog

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
Currently there is the following bug:
1. Create class
1. Create field of type `input` (but the bug happens for all fields which support a unique index)
1. In the field's properties on the right panel there is no `unique` checkbox
This PR solves this.
I wonder what the tooltip is good for:
https://github.com/pimcore/pimcore/blob/b42962724ab4f1d8343e2afea5bab854c462350e/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js#L201-L202
While it currently does not even work (at least I have not seen any tooltip on hovering the checkbox), I wonder why `t("unique")` should be shown as tooltip while this is already the checkbox's label. Is there a translation missing which shall explain what `unique` means?
=> [Class definition] Show unique checkbox for newly created fields

models/DataObject/Service.php, models/Element/Service.php
Resolves #4333 
This PR truncates unique fields on pasting an object because such objects could otherwise not be saved.
It also unpublishes the object if it has unique fields because otherwise it could not be saved if the unique field was also mandatory - and also to show the user that it was not a 1:1 copy but something was modified.
=> [Data objects] Truncate unique fields on copying

bundles/AdminBundle/Resources/public/css/admin.css, bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
... and should be closed by default
=> Move Symfony toolbar trigger to left navigation bar

bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
We use jQuery in the frontend.
Now we get in the editmode following exceptions and all JS is broken:
`Uncaught TypeError: $ is not a function`
I think its a regression from https://github.com/pimcore/pimcore/pull/5222
=> Fix: Don't call jQuery.noConflict

doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/33_Calculated_Value_Type.md, models/DataObject/ClassDefinition/CalculatorClassInterface.php, models/DataObject/ClassDefinition/Helper/CalculatorClassResolver.php, models/DataObject/ClassDefinition/Helper/ClassResolver.php, models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php, models/DataObject/ClassDefinition/Helper/PathFormatterResolver.php, models/DataObject/Service.php
As (multi-)select fields, fields with path resolver and link formatter support providing a symfony service, this would be also quite nice for calculated value calculators. This PR implements this.
This enables developers to also use dependency injection for calculator classes.
At the moment this PR is implemented in a way that the `compute` and `getCalculatedValueForEditMode`methods do not need to be static, but can be. On the one hand this is quite handy, on the other hand this prevents us from providing a clean interface which would be really nice for calculator classes.
Imho calculator methods should not be static at all but changing that would result in a backward incompatible change - which is no option at the moment, I think.
=> [Data objects] Symfony service as calculated field calculator

lib/Maintenance/Tasks/ImageOptimizeTask.php, models/Asset/Image/Thumbnail/Processor.php
Currently, file paths of thumbnails to be optimised are written to the tmp_store.id column which has a stipulated length of 190.
In some cases, file paths will be longer than that and any characters over the limit will be cut off when inserted into the database.
The ImageOptimizeTask maintenance script then dies, as it cannot find any files with the faulty paths.
This PR creates an md5 hash of the file path as the id and writes the actual file path to the tmp_store.data column.
=> [ImageOptimizerQueue] write file path to 'data' column instead of 'id' column

lib/Config.php
Save access of $config values array in Config::mapLegacyConfiguration to avoid exceptions if values are missing.
Resolves #
Broken Codeception tests packages ecommerce, model, rest an service with inital Skeleton config and DB.
On loading page and on running Codeception tests with initial skeleton DB and config exceptions occur because of missing config values, e.g. service.google.*. This breaks the tests and cause errors when loading the web app.
=> Fix: exception  'undefined index google' on running tests

models/DataObject/Localizedfield.php
I stumbled upon multiple notices like "Undefined index" for the context variables. There are a lot of conditions like `if ($context && $context['containerType'] === 'fieldcollection') ...` As $context can be not empty and still not contain the key `containerType` this notice gets emitted. With this PR it is checked whether `$context` really contains the index `containerType`.
=> [Data objects] Prevent "undefined index" notice

lib/Pimcore.php
Resolves #5300 
```
Error: Call to a member function getParameter() on null in /var/www/vendor/pimcore/pimcore/lib/Pimcore.php on line 275
```
My case.
There is a conflict between `\Symfony\Bundle\FrameworkBundle\Test\KernelTestCase` and `\Pimcore\Kernel`. When you create a test that extends the `KernelTestCase` it will cause an error after execution:
```
Error: Call to a member function getParameter() on null in /var/www/vendor/pimcore/pimcore/lib/Pimcore.php on line 275
```
This error caused by trying to call the `getParameter()` method on the nullable container because it was deleted by `KernelTestCase` already. [See this link](https://github.com/symfony/symfony/blob/996d8a708fd5fe5043c5098c3da4921f75b95e52/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L134) (doesn't …
=> Fixes the nullable container issue in Pimcore::shutdown() mentod

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
To reproduce bug:
1. Create data object class
2. create many-to-many object relation field, allow a class an select some visible fields
3. clone the field
Visible fields have not been copied. This PR fixes that.
=> [Data object] Copy visible fields when cloning many-to-many object relation field

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Getting Admin Layout without permissions:
To reproduce this bug, simply open a object but set the "layoutId" param to an empty string beforehand. Now pimcore will show the admin layout to the user even without the necessary permission.
=> Fixed layout bug which granted access to admin layout without permissions

doc/Development_Documentation/01_Getting_Started/00_Installation.md
The change from `bash` to `text` type for Cron config is because the `text` renders as very dark text on very dark background and is currently unreadable:
=> Minor readability changes on instalaltion docs

bundles/EcommerceFrameworkBundle/Command/IndexService/ResetQueueCommand.php
Allow reset of index for all tenants at the same time (option  ``--tenant=*``).
=> Ecommerce | Reindex Command Improvement

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/OptimizedMysql.php
resolves #5259 
- store previous routing for each element to store table in metadata field
- when routing changes, add delete to bulk update before new index row of element.
=> fixed #5259 - [IndexService][ElasticSearch] - Duplicate entries (same  _id) in elastic search

bundles/AdminBundle/Controller/Admin/Document/PageController.php
You can verify the current behaviour on the error messages by switching to the *SEO & Settings* tab, then clicking in the *Pretty URL* input and then by clicking anywhere else, you will get an error message.
I considered first checking for string length in 1f64da0, but settled for an early exit due to edge cases.
=> Refactor PageController::checkPrettyUrlAction()

models/Asset/Document.php, models/Tool/TmpStore.php
The thumbnails are only generated during the update. Should be also generated if they are deleted.
=> Fix: Multi page document thumbnails are not generated

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
Use `new pimcore.element.helpers.gridCellEditor` instead of wrong `new pimcore.object.helpers.gridCellEditor` namespace.
=> Fix GridCellEditor Namespace

bundles/EcommerceFrameworkBundle/Tracking/AbstractData.php, bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php, bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/UniversalEcommerce.php, bundles/EcommerceFrameworkBundle/Tracking/TrackingItemBuilder.php
Simplify custom product data attribute tracking. 
The method ``addProductAttributes`` has been introduced. It
- initializes the most common product data tracking attributes on one site,
- provides a hook to override the default behavior: just call ``item->addAdditionalAttribute('ean', 'test-ean');`` to add your custom attributes.
In addition, each tracking item has an additional ``addAdditionalAttribute`` method. This method can be used to add custom attributes not only to product data, but also to transactions, checkout steps etc.
=> Simplification of the ecommerce tracking for custom product data

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/multiselect.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
- While cloning a select field default value and column length are not saved in the cloned field.
- While cloning a multi select field optionsProviderClass and optionsProviderData are not saved in the cloned field
=> While cloning a Select or Multiselect field, all attributes are not saved in cloned field.

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js, bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
fixing #5136 
- if element `published` -> save button (which is visible to users with `save` but without publish permission only) calls `saveVersion()` and does not update DB/grid data
- if element `not published` -> save button (which is visible to all users with at least `save` permission) calls `save()` and does update DB/grid data
=> fixed Inconsistency in versioning system

bundles/AdminBundle/Resources/public/js/pimcore/element/dependencies.js
Currently UI is not consistent: Sometimes you can open elements by left-click, sometimes by double click, sometimes via context menu -> Open.
This PR adds a contextmenu when you right-click a dependency element, so you can choose `Open`.
=> Open dependency elements via context menu

bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php, bundles/AdminBundle/Resources/public/js/pimcore/document/printpages/pdf_preview.js, lib/Web2Print/Processor/PdfReactor8.php
For processing options of type bool the value was incorrectly stored as
string. When loading previously stored options, a value "false" (string)
evaluated true and therefore the option was incorrectly checked.
This fix lets ExtJS encode the options as JSON (preserving types) and
the controller action JSON decodes the request body. When storing the
options, all types are preserved.
=> [Web2Print] Preserve type of processing options

bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectCategory.php
indexedValues was not added to the ElasticSearch version of the SelectCategory.php, which results in an error if using ElasticSearch instead of default MysqlSearch.
Resolves #
=> Add indexedValues to the variables passed to view

bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
Steps to reproduce bug:
1. Add language via system settings > localization
2. Go to shared translations
3. All translations for the newly added language show "undefined"
Fortunately this is only a display error: When you access a translation for the new language it is handled as empty translation.
=> [Translations] Bugfix: "undefined" translation for new language

bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
Empty is not a valid check as an empty array is empty too.
=> [Ecommerce][PricingManager] Rules should not not be loaded multiple times if no active rules exist

models/User/AbstractUser.php
Regression from #5356 
The error occurs when trying to save a user
=> Fix: Cannot instantiate abstract class Pimcore\Model\User\AbstractUser

bundles/CoreBundle/Command/ThumbnailsImageCommand.php
The command now generates all necessary thumbnail files for the given configurations (incl. @2x, WebP and media queries) not only the main one. 
This is the expected behavior, so this is default. 
Introduced 3 new flags to give more control over the generation process: 
```
--skip-medias 
--skip-webp 
--skip-high-res
```
Resolves #5295
=> [Asset] Improvements for pimcore:thumbnails:image Command: high-res, webp and media queries support

bundles/CoreBundle/Resources/migrations/Version20191208175348.php, bundles/InstallBundle/Resources/install.sql, models/DataObject/ClassDefinition/Dao.php, models/DataObject/Classificationstore/Dao.php, models/DataObject/Concrete/Dao/InheritanceHelper.php, models/DataObject/Data/ObjectMetadata/Dao.php, models/DataObject/Fieldcollection/Definition/Dao.php, models/DataObject/Localizedfield/Dao.php
There is no advantage in single-column database indexes when there also exists a composite index which has the same column(s) as prefix. For example index on column A does not make any sense if you additionally have an index on columns A,B. - see for example https://stackoverflow.com/questions/51046457/find-duplicate-index-in-mysql-using-query#answer-51048636
As example the query execution plan for the following query stays the same - with or without the removed index:
```mysql
explain select * from objects where o_path='abc'
```
Including the index path(o_path):
id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | objects | NULL | ref | fullpath,path | fullpath | …
=> Remove duplicate indexes

models/Asset/Image/Thumbnail.php, models/Asset/Thumbnail/ImageThumbnailTrait.php
The result is that thumbnails which are generated on demand (because they do not exist on the filesystem and are served by `\Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::thumbnailAction`)  may return the wrong mime-type, e.g. `image/jpg` instead of `image/webp`.
=> [Asset] getMimeTime() on an image thumbnail may return the wrong type

bundles/CoreBundle/Controller/PublicServicesController.php
Currently it could happen that the requested format is different from the delivered format. 
Example use case: 
AWS CloudFront: 
The format delivered to the browser is WebP because of the built-in WebP browser support detection, but when CloudFront requests the thumbnail from the backend, the detection fails and so the fallback format get's delivered, which doesn't make sense at all.
=> [Asset] Image Thumbnails: deliver the requested image format when using auto format (ignore detection, webp, ...)

bundles/CoreBundle/Controller/PublicServicesController.php, bundles/CoreBundle/Resources/config/aliases.yml, models/Document/Tag/Link.php, phpstan.neon
In certain cases where an event listener starts a session (e.g. when there's a firewall configured for the entire site /*) the session event listener shouldn't modify the cache control headers of this response. 
This is especially useful when working with any kind of CDN or caching proxy.
=> [Asset] HTTP headers of the public thumbnail generation service shouldn't be overridden by the SessionListener

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js, models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php, models/DataObject/Service.php
Grid editing works for example for AdvancedManyToManyObjectRelations but not for ManyToManyObjectRelations. This PR adds the grid editing feature for ManyToManyObjectRelations.
=> Enable grid editing for ManyToManyObjectRelations

lib/DataObject/GridColumnConfig/Operator/PHPCode.php
There is an uncaught exception if you 
1. go to a grid view
1. click "grid options"
1. add operator "Others > Operator PHP Code"
=> [Grid operators] PHPCode: Catch Exception if no class has been set

bundles/CoreBundle/Resources/migrations/Version20191126130004.php
`CREATE INDEX IF NOT EXISTS <index_name> on <table> (<column>);');` is not valid in MySQL.
Results in `SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS ecommerceframework_cart_user  
id_index on ecommerceframework_cart (u' at line 1`
=> [Migration] Fix compatibility with MySQL

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
In ES version 6.8.5 I get the following error using mapping type `nested`:
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [myField] has unsupported parameters:  [store : false]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [sizes] has unsupported parameters:  [store : false  
]"},"status":400}                                                                                                                                                                                                                                                           ```
=> [Ecommerce][ElasticSerach] Fix unsupported mapping parameter "store"

lib/Model/Listing/AbstractListing.php, models/Notification/Listing.php
I have this error after upgrade the master branch. Regression from #5354
I have a wrapper class around the listing, which set the data to null if the the limit/offset is changed. Otherwise it is not possible to geht a new offset.
Now I can't set it to null...
=> Fix: Argument 1 passed to AbstractListing::setData() must be of the type array, null given

bundles/CoreBundle/Resources/migrations/Version20191121150326.php, bundles/CoreBundle/Resources/migrations/Version20191125200416.php
The current migration implementation does not work if multiple tenants with the same store table implementations are configured.
=> [ecommerceframework] store table migration fixes

models/Version.php
When using AWS S3 for storing versions the version preview does not work.
To reproduce use the following `app/constants.php`:
```php
$s3BucketName = "bucket-name";
define("PIMCORE_VERSION_DIRECTORY", "s3://".$s3BucketName."/versions");
```
In app/startup.php:
```php
<?php
use Aws\S3\S3Client;
$config = [
'version' => 'latest',
'region' => 'eu-central-1', // choose your favorite region
];
$s3Client = new S3Client($config);
$s3Client->registerStreamWrapper();
// set default file context
\Pimcore\File::setContext(stream_context_create([
's3' => [
'seekable' => true,
'ACL' => 'public-read',
'StorageClass' => 'STANDARD_IA',
]
]));
```
When opening a version preview, an error occurs:
`User Warning: Mode not supported: r+. Use one 'r', 'w', 'a', or 'x'.`
This PR fixes that by using mode `rb` …
=> [Versions] Fix fopen mode

phpstan.neon
Ignores all phpstan level 2 errors:
`Method Doctrine\DBAL\Driver\Connection::query() invoked with 1 parameter, 0 required`
Line is from https://github.com/doctrine/dbal/blob/master/phpstan.neon.dist
=> [PHPSTAN] Ignore Doctrine\DBAL\Driver\Connection::query() errors

models/DataObject/Localizedfield.php
In case of AbstractRelations the fallback values have not been considered when lazy loading is used beacause the loadLazyField function only loads the current language. This PR fixes this issue by resolving the fallback language lazy load fields in case they are needed
@weisswurstkanone
=> fix using fallback language values for AbstractRelations

lib/Event/Ecommerce/IndexServiceEvents.php
This PR fixes the namespaces in the annotations of the indexservice events.
=> [Ecommerce] fix index events namespaces in annotations

bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
additional fix for #4916
(source filtering existed in ES version 2.x too => therefore this should work for all supported versions: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-source-filtering.html)
=> [ecommerceframework][elasticsearch] price sorting does not work with elasticsearch 6

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php, lib/Event/Model/Ecommerce/IndexService/PreprocessAttributeErrorEvent.php, lib/Event/Model/Ecommerce/IndexService/PreprocessErrorEvent.php
This PR 
- **fixes** the namespace of the error event - otherwise the `->dispatch()` of the error event will again throw an error
- **changes** the index preparation exception handling to also catch Errors not only Exceptions (i.e.:
`call to a member function XXX on null in ...`)
- **changes** adds a setter to the event whether to throw an exception or not
=> [Ecommerce][Productindex] Errorhandling

bundles/AdminBundle/Resources/public/js/pimcore/report/custom/definitions/sql.js, models/Tool/CustomReport/Adapter/Sql.php
If you use a sub select in the where field the SQL text is wrong. It should only check for SELECT/FROM/WHERE/GROUP BY at the beginning of the value.
It's also not necessary to save it.
Example in the demo:
=> [CustomReport] Fix wrong sql text

bundles/CoreBundle/Resources/migrations/Version20191230104529.php, bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php, bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php, bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Problem: 
Index on column `cartId` cannot be used by e.g. the following query: 
```sql
SELECT object_EF_OSO.o_id as o_id, `object_EF_OSO`.`o_type` FROM `object_EF_OSO` WHERE ((cartId = 'AppBundle\\Ecommerce\\CartManager\\Cart_2596' AND  object_EF_OSO.o_type IN ('object','folder')) AND object_EF_OSO.o_published = 1);
```
Suppressed error message when saving the `OnlineShopOrder` class: 
```
An exception occurred while executing 'ALTER TABLE `object_query_EF_OSO` ADD INDEX `p_index_cartId` (`cartId`);': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```
=> [Ecommerce] OnlineShopOrder class: change column length of field cartId to 190 -> max. index length

.travis.yml
is PIMCORE_TEST_SETUP_SKIP_PHP_REDIS_EXTENSION not considered anymore
see https://github.com/pimcore/pimcore/commit/66e48187b9311baedf2463e82ae8fe95e268d34f
=> removed obsolete job

lib/Maintenance/Tasks/CacheCleanupTask.php
This reduces the load significantly on the cache backend (Redis or Database).
=> [Cache] Cleanup in maintenance should only be executed once within a day

bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/DatatransRequest.php
Added AbstractRequest to DatatransRequest because without it can't be used for its purpose
While working with DatatransRequest (https://pimcore.com/docs/6.x/Development_Documentation/E-Commerce_Framework/Checkout_Manager/Integrating_Payment.html#page_Initialize-Payment-in-Controller) i realized that this Example is not working because `$checkoutManager->startOrderPaymentWithPaymentProvider(AbstractRequest $config);` only accepts AbstractRequests.
In DatatransRequest this abstract was missing, therefore i had to add it.
=> FIX: DatatransRequest now extending AbstractRequest

lib/Model/Listing/AbstractListing.php, models/Asset.php, models/Asset/Listing/Dao.php
Currently in https://github.com/pimcore/pimcore/blob/5cb4a06b041e8b3f45337743836ef3430602e7b0/models/Asset/Listing/Dao.php#L47-L51
only assets with non-empty type get loaded.
I have the following script:
```php
<?php
$asset = new \Pimcore\Model\Asset();
$asset->setFilename('abc.txt');
$asset->setParent(\Pimcore\Model\Asset::getByPath('/'));
$asset->save();
$listing = $asset->getList();
$listing->addConditionParam('Filename = ?', 'abc.txt');
var_dump($listing->loadIdList()); // returns array including id of above asset
var_dump($listing->load()); // returns empty array
```
The array does not appear in the Pimcore backend (because of above's restriction in the Dao) - so I cannot delete the asset in the GUI.
Executing above script again results in a primary key collision because there …
=> [Assets] Set type to unknown for assets without data

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, bundles/AdminBundle/Controller/Admin/ElementController.php, bundles/AdminBundle/Controller/Admin/TranslationController.php, bundles/AdminBundle/Helper/GridHelperService.php, doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/13_Locking_Fields.md, lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php, models/DataObject/ClassDefinition.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/Block.php, models/DataObject/ClassDefinition/Data/Localizedfields.php, models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php, models/DataObject/Concrete.php, models/DataObject/Fieldcollection/Dao.php, models/DataObject/Fieldcollection/Definition.php, models/DataObject/Localizedfield.php, models/DataObject/Localizedfield/Dao.php, models/DataObject/Service.php
This PR set all getFieldDefinition(s) consinstently. This is no BC, because PHP function names are case-insensitive (https://www.php.net/manual/en/functions.user-defined.php)
It corrects also all phpstan level 2 errors:
- `Cannot call method getFieldDefinition() on bool|Pimcore\Model\DataObject\ClassDefinition\Data`
- `Call to an undefined method Pimcore\Model\DataObject\ClassDefinition\Data::getFieldDefinitions()`
- `Call to an undefined method Pimcore\Model\DataObject\ClassDefinition\Data::getFieldDefinition()`
=> Consistently getFieldDefinition(s) method name

bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
+ transform stdClass to json
+ check if return is json
PayPalSmartPaymentButton fix wrong Parameter-Type in `startPayment`
In PayPalSmartPaymentButton `startPayment(...)` failed because 
`$this->initPayment(...)` returnes `stdClass` and `Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\V7\Payment\StartPaymentResponse\JsonResponse` is only acception `string` as value.
Added check for json and encoding if necessary
=> FIX: PayPalSmartPaymentButton

bundles/AdminBundle/Controller/Admin/LogController.php
fixing directory bug 
The problem is that, on Windows, file paths contains the backslash "\" character instead of the slash "/" as linux. now it can work on both
=> adding DIRECTORY_SEPARATOR resolves #5518

lib/Tool/AssetsInstaller.php
Related to #5532, increasing the process timeout fixes the issue. This was fixed in a similar fashion for #3681, so I suggest doing the same here.
Resolves #5532
=> Increase process timeout for asset installation

phpstan.neon
Ignores all phpstan level 2 errors with:
```
Method Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch() invoked with 2 parameters, 1 required.
```
=> [PHPSTAN] Ignore EventDispatcherInterface errors

models/Asset.php, models/Webservice/Data/Asset.php
When fetching asset data via REST webservice you get something like
```json
{
"success": true,
"data": {
"id": 22905,
"parentId": 29682,
"type": "image",
...
"metadata": [
{
"name": "ItemCode",
"type": "input",
"data": "123",
"language": ""
},
{
"name": "Name des Artikels",
"type": "input",
"data": "abc",
"language": "de"
}
],
...
}
}
```
When trying to convert this back to a `Pimcore\Model\Asset` via 
`Pimcore\Model\Webservice\Data\Asset\File` you get an array of stdclass items in https://github.com/pimcore/pimcore/blob/97a3f4de67c8c1bb35d6283b4eb06ed87f3126b3/models/Webservice/Data/Asset.php#L143-L144
Since #5076 this was not possible anymore - only associative array was. With this PR also an array of stdClass items is allowed (as it was before #5076).
=> [Webservice] Convert stdclass metadata items to associative array

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/Link.php, models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php, models/DataObject/Service.php, models/Dependency.php
Fix following phpstan level 2 errors:
```
Line   bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php
178    Class Pimcore\Model\DataObject\ClassDefinition\Data\Objectbricks referenced with incorrect case: Pimcore\Model\DataObject\ClassDefinition\Data\ObjectBricks.  
Line   models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
1050   Class Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect referenced with incorrect case: Pimcore\Model\DataObject\ClassDefinition\Data\MultiSelect.
Line   models/DataObject/ClassDefinition/Data/Link.php
409    Class stdClass referenced with incorrect case: stdclass.
Line   models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
759    Class …
```
=> [PHPSTAN] Fix: Classes with incorrect case

bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php, bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php, lib/helper-functions.php, models/Asset.php, models/DataObject/ClassDefinition/Data/Localizedfields.php, models/Document/Tag/Video.php, models/Webservice/Data/Document/Element.php
Fix following phpstan level 2 errors:
```
Line   bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
787    Binary operation "." between string and array<string> results in an error.
Line   bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
171    Binary operation "*" between string and 100 results in an error.
198    Binary operation "*" between string and 100 results in an error.
Line   lib/helper-functions.php
269    Binary operation "*=" between string and 1024 results in an error.
Line   models/Asset/Image/Thumbnail.php                                                                                        
246    Binary operation "." between '© ' and array|null results in an error.                                            
247    Binary …
```
=> [PHPSTAN] Fix: Wrong binary operations

models/DataObject/AbstractObject.php
The method returns not just the Object but also null. 
I just added it to this one currently, but it should be added to every single model to satisfy phpstan
Resolves errors with phpstan and null comparison on model methods
Reproduce with:
- phpstan active: we have max level activated
- write something like Object::getByPath('/') === null
this results in:
Strict comparison using === between null and                            
Pimcore\Model\DataObject\AbstractObject will always evaluate to false.
=> Adding extended return type declaration

bundles/GeneratorBundle/Command/Validators.php, bundles/GeneratorBundle/Manipulator/ConfigurationManipulator.php, bundles/GeneratorBundle/Model/Bundle.php, bundles/InstallBundle/Installer.php
Fix all phpstan level 2 PHPDocs errors in the GeneratorBundle and the InstallBundle
Before:
```
[ERROR] Found 3476 errors
```
After:
```
[ERROR] Found 3468 errors
```
=> [PHPSTAN] Fix GeneratorBundle/InstallBundle PHP Docs

bundles/CoreBundle/Request/ParamConverter/DataObjectParamConverter.php, bundles/CoreBundle/Resources/config/services.yml, doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
Usage: 
```php
/**
* @Route("/news/{news}")
*/
public function testAction(DataObject\News $news) {
return [
'news' => $news
];
}
```
For details see docs page.
=> [Core] Generic Data Object Param Converter

bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRangeSelection.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRangeSelection.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractWorker.php
Fixes the parameter order of `implode()` that has been [deprecated in PHP 7.4](https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.implode-reverse-parameters).
=> Fix deprecated (PHP 7.4) parameter order of implode()

doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
hover seems to be the default value, see: https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js#L50
not sure if this is on purpose i would rather prefer fixed as the default value.
=> [DOCS] Areablock configuration controlsTrigger is wrong

lib/Document/Adapter/LibreOffice.php, models/Asset.php, models/Asset/Dao.php, models/Asset/Document.php, models/Asset/Document/ImageThumbnail.php, models/Asset/Folder.php, models/Asset/Image.php, models/Asset/Image/Thumbnail.php, models/Asset/Image/Thumbnail/Config.php, models/Asset/Image/Thumbnail/Config/Dao.php, models/Asset/Image/Thumbnail/Config/Listing.php, models/Asset/Image/Thumbnail/Processor.php, models/Asset/Listing/Dao.php, models/Asset/Service.php, models/Asset/Thumbnail/ImageThumbnailTrait.php, models/Asset/Video.php, models/Asset/Video/ImageThumbnail.php, models/Asset/Video/Thumbnail/Config.php, models/Asset/Video/Thumbnail/Config/Dao.php, models/Asset/Video/Thumbnail/Config/Listing.php, models/Asset/Video/Thumbnail/Processor.php, models/Asset/WebDAV/File.php, models/Asset/WebDAV/Folder.php, models/Asset/WebDAV/Service.php
Fix all phpstan level 2 errors in Pimcore\Model\Asset namespace with following schema:
```
PHPDoc tag @param has invalid value ($xyz)
```
Before:
```
[ERROR] Found 2731 errors
```
After:
```
[ERROR] Found 2646 errors 
```
=> [PHPSTAN] Fill empty php doc param types (Asset)

bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js, bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js, bundles/CoreBundle/DependencyInjection/Configuration.php, doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md, lib/Workflow/ActionsButtonService.php, lib/Workflow/EventSubscriber/NotificationSubscriber.php, lib/Workflow/GlobalAction.php, lib/Workflow/Notes/NotesAwareTrait.php, lib/Workflow/Transition.php
This PR adds a option for transitions and global layouts to force a object layout after the transition/action was performed via the actions button.
Additionally some PHP notices are fixed.
=> [Workflows] add option to force a object layout after a transition or global action was performed

models/DataObject/ClassDefinition/Data/Objectbricks.php
After upgrade to 6.4.0 the return type in phpdocs of objectbricks are without \ at beginning.
=> Fix wrong objectbricks phpdoc type

models/DataObject/Localizedfield.php
Update a bug from previous changes for the Block element.
$context['fieldname'] to $context['containerKey']
Regression of #5471
=> Update $context['fieldname'] to $context['containerKey']

models/DataObject/ClassDefinition/Data.php
Solves #5584 
Now the `filterByXYZ` method always uses parameters `$data`and `operator`. It was not necessary to use the real field name here.
=> [Data object listings] Prevent name collision for field named "operator"

models/Webservice/Data/DataObject/Concrete.php
In 59cc53bb872836ac29dbc66a113b773c50a88e57 the behaviour of AbstractObject::setParent() was changed: Before `o_parentId` got only updated if the parent existed. Now it gets set to 0 if the parent does not exist.
When creating a data object via `Pimcore\Model\Webservice\Data\DataObject\reverseMap` the data object gets recreated for each attribute via its setter methods. When inheritance is enabled the following chain gets executed:
1. Setter calls getter to get current value to mark field dirty on change. 
1. If value is empty, getter calls:
1. Concrete::getValueFromParent() which calls:
2. Concrete::getParent() which calls:
3. Concrete::setParent(AbstractObject::getById($this->getParentId())  - as it could be the case that no object with the parent id exists (as it was potentially …
=> [Webservice] Set data object's parent id when no parent with this id exists

models/DataObject/Localizedfield.php
If you had a localizedfield in the Block "containerType" in your Object, and would insert some Data, you get an error about the fieldDefinition.
So after change to "containerType" they can find the correct fieldDefinition
See: #5581
=> [Block] Localized fields inside Block cannot be updated via API

bundles/CoreBundle/DependencyInjection/Configuration.php, bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php, bundles/CoreBundle/Resources/config/maintenance.yml, lib/Maintenance/Tasks/HousekeepingTask.php
```yml
pimcore: 
maintenance: 
housekeeping: 
cleanup_tmp_files_atime_older_than: 1234 # in seconds
cleanup_profiler_files_atime_older_than: 6789 # in seconds 
```
Also changed the default value for profiling files to 30 minutes, which should be sufficient for most cases.
=> Make the housekeeping maintenance task configurable

bin/pimcore-install
Regression of #5310 (@blankse): otherwise the installer uses `E_ALL` as default which will rise up all the notice errors while trying to boot the system.
=> respect error reporting in installer

bundles/AdminBundle/Controller/Admin/SettingsController.php
As discussed (a lot 😄), this PR only uses the current environment to clear the symfony cache after system settings has been updated. This will improve three things:
- **Performance**: only one cache container gets regenerated instead of two or three
- **Security**: there will be no "dev" container on production or any other environment but on dev only!
- **Stability**: if "prod" is not available in a given installation, this action will fail completely (`Uncaught InvalidConfigurationException: File config_prod.yml  cannot be found`)
=> Only use active env to rebuild cache in system settings save action

bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php, bundles/AdminBundle/Controller/Admin/SettingsController.php, lib/Web2Print/Processor.php, lib/Web2Print/Processor/PdfReactor8.php, lib/Web2Print/Processor/WkHtmlToPdf.php, models/Document/PrintAbstract.php
Fixes following notices:
- Notice: Undefined index: HTTPS
- Notice: Undefined index: disableBackgroundExecution
- Notice: Undefined index: cmd
- Notice: Array to string conversion
- Notice: Undefined index: document
- Notice: Undefined index: hostUrl
- Notice: Undefined index: 1
- Notice: Undefined index: values
- Notice: Undefined property: stdClass::$author
- Notice: Undefined property: stdClass::$title
- Notice: Undefined property: stdClass::$links
- Notice: Undefined property: stdClass::$bookmarks
- Notice: Undefined property: stdClass::$colorspace
- Notice: Undefined property: stdClass::$encryption
- Notice: Undefined property: stdClass::$tags
- Notice: Undefined property: stdClass::$loglevel
- Notice: Undefined property: stdClass::$addOverprint
- Notice: Undefined property: …
=> [Web2Print] Fix Notices: Undefined index, Save template errors in lastGenerateMessage

bundles/AdminBundle/Controller/Admin/IndexController.php, bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js, lib/Tool.php
Currently it is hardcoded to `['dev','prod']`
=> [Admin] Clear cache functionality only for available Symfony environments

doc/Development_Documentation/03_Documents/01_Editables/12_Relation_(Many-To-One).md
The array key is correct in the PHP code example (few lines above) but wrong in the Twig example.
It's wrong in the docs of v6.x, too. Should I create a PR with a fix targeting the master branch or do you merge the branches somehow?
=> Fix array key in relation editable docs

lib/Translation/Translator.php
Partly resolves #4979
It isn't possible now to use translation pluralization from symfony.
message.de.xlf
```
<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
<file source-language="en" datatype="plaintext" original="file.ext">
<body>
<trans-unit id="1">
<source>{0} Maximum number of participants reached.|{1} One registration possible.|]1,Inf[ %count% more registrations possible.</source>
<target>{0} Maximale Teilnehmerzahl erreicht.|{1} Noch eine Anmeldung möglich.|]1,Inf[ Noch %count% Anmeldungen möglich.</target>
</trans-unit>
</body>
</file>
</xliff>
```
template.html.twig
```
{{ '{0} Maximum number of participants reached.|{1} One registration possible.|]1,Inf[ %count% more registrations possible.'|trans({'%count%': count}) }}
```
It would be …
=> [Translation] Fix pluralization

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/05_Preview.md
Allow `%_locale` as variable in data object's preview URL. Of course you could use a link generator but often it is easier (and configurable via GUI) to enter a URL with placeholders.
=> [Data objects] Allow %_locale in data object preview URL

bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/videothumbnail/item.js
(Image / Video) Thumbnail config name should be copyable.
=> Thumbnail config name should be copyable

doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/02_Filter_Nested_Documents.md
- Uses `ProductListInterface` instead of `IProductList`, which was deprecated some time ago.
- Fixes a typo
=> [DOCS] Fix types & typos

models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
Analogous to advanced many-to-many relation, see https://github.com/pimcore/pimcore/blob/296fc17f0b00dc8f07926b5c34d127aa4ddb4f1b/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php#L1103-L1106
Does anyone know a way to document getters / setters for meta columns of advanced relation fields?
=> ObjectMetadata as return / param doctype for advanced many-to-many object relation getters / setters

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstractRelations.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
Originally I was annoyed of an advanced many-to-many relation with a lot of meta fields. When you want to open the related object you have to scroll to the complete right. This PR adds support for opening the related element via double-click.
To be consistent I also implemented this behaviour for all other relational types.
=> [Data objects] Open element when double-clicking relation item

bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
The variable `insertPoint` is not used anywhere else in the function in which it is declared.
=> Remove unused JavaScript code

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js, bundles/AdminBundle/Resources/public/js/pimcore/report/custom/definitions/analytics.js
This PR removes some duplicate keys in JavaScript objects.
When there are duplicate keys in an object, the last one wins. 
Thus, I deleted the first one (if values are different).
=> Remove duplicate JavaScript object keys

bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js, bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js, bundles/AdminBundle/Resources/public/js/pimcore/startup.js, bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
There are some places where `new Array()` / `new Object()` are used wheras everywhere else `[]` / `{}` are used. This PR adjusts the code to use the latter everywhere.
=> Simplify JavaScript array/object instantiation

bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js, bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js, bundles/AdminBundle/Resources/public/js/pimcore/functions.js
There are some duplicated JavaScript functions.
Methods in Objects:
- `getColumnWidth()` and `getExportButtons()` are exactly the same in https://github.com/pimcore/pimcore/blob/f1cfacf128a7ae511fdeaf7cd11bb38ae6219694/bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js#L397-L449
- `columnConfigurationSavedHandler()` is exactly the same in https://github.com/pimcore/pimcore/blob/f1cfacf128a7ae511fdeaf7cd11bb38ae6219694/bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js#L111-L115 and https://github.com/pimcore/pimcore/blob/f1cfacf128a7ae511fdeaf7cd11bb38ae6219694/bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js#L730-L734
Global functions:
- `ucfirst()` is exactly the same in …
=> Remove JavaScript function duplicates

bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/select.js
The renderer is overridden in the config object through the duplicate key in line 38. 
I'm not completely sure this is correct and if the custom one should be used instead of removing it, though.
=> JavaScript: Remove unused renderer

bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js
this PR fixes https://github.com/pimcore/pimcore/issues/5648
Background: Ext.data.JsonStore has a default pagination limit of 25, setting it to 0 disables it.
=> [QuantityValue] fix default limit on ExtJs BaseUnit store

bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/date.js
- `data` should be set if it **is not** `null` or `undefined`
- this check doesn't need to be repeated in the `else if` case
=> JavaScript: Fix condition

bundles/CoreBundle/Resources/migrations/Version20200124170034.php, bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php, bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
=> [Pimcore 5.8][Ecommerce] OnlineShopOrder class: change column length of field cartId to 190

doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/01_Basic_Migration.md
It will download Pimcore 6 instead of Pimcore 5. I used 1.3.0 as pimcore.phar does use the same now.
=> Do not use master for downloads

bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
The Paypal Smart Button integration allows to pay via credit card or debit card without a paypal account. The response data paypal sends in that case is slightly different from the one you get when using a paypal account.
When using a paypal account, the response contains four fields:
```
{
"orderID": "12AB...",
"payerID": "AJ...",
"paymentID": null,
"facilitatorAccessToken": "A21...LIQ"
}
```
When using the credit card option, paypal does not include the paymentID in the response. Pimcore's integration marks the field as required. The value of this field is not used or stored in the db, however, so I think its okay to remove the field from required value list.
=> Fix error with Paypal Smart Button integration when using the Credit/Debit card payment option

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Currently the column `ID` always appears in an advanced many-to-many object relation - ignoring if this has been set as visible field. 
If you have set `ID` as visible field it appears twice in the object edit panel.
=> [Advanced object relation] Removed hard-coded visible field "ID"

models/DataObject/ClassDefinition/Data/Table.php
Speichern eines Objektes mit einer Tabelle ohne Zeilen führt zu fehlerhaftem Speichern.
Fehler wird nicht ans Frontend durchgereicht.
Resolves #
=> prevent invalid foreach argument if table has no rows

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
The default nginx client_max_body_size is set to 1m (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size). On default nginx config the directive is not set in the highest level in "http". Based on the Pimcore Documentation client_max_body_size is set to 100m to prevent the "413 Request Entity Too Large" error.
Resolves #
"413 Request Entity Too Large" error using nginx while upload in frontend and backend files larger then 1m.
=> Add client_max_body_size directive to nginx config

bundles/CoreBundle/Resources/config/pimcore/default.yml
The values of those PDO constants tend to change between PHP versions (see: https://stackoverflow.com/a/20990359) so it's better to not rely on them and use the real constant instead of its "magic number" value.
Follow-up to #5727
=> Use constant instead of its value

bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
When joining the mysql productindex with a sub tenant an error is thrown on ordering since the o_id column is ambiguous. The default order key should be a.o_id instead of just o_id.
=> Error when sorting product list with sub tenants

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
The settings window should display the translated name of perspective and doc type
=> Translate perspectives and docTypes in user/role settings

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
Resolves #5721
Pasted element published status set to false, in case of "There is a newer not published version"
=> [Document|Data Object] consider latest version for copying elements

bundles/EcommerceFrameworkBundle/Controller/IndexController.php, lib/Event/Ecommerce/AdminEvents.php, lib/Event/Ecommerce/IndexServiceEvents.php
This PR makes it possible to adjust the displayed value in the FilterDefiniton object.
In the screenshot the actual value is in brackets.
=> [Ecommerce][IndexService] add pre-send-data event in FilterDefinition Object

bundles/CoreBundle/Resources/translations/en.extended.json
The current translation was confusing and did not indicate, whether the copied tree, or the original tree should be used for the export.
I believe the new translation would give clearer instructions to the user.
=> Update Important Notice Text of XLIFF Export

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
If the `$data = $this->doPreIndexDataModification($data);` gets called after the categorization of 
`$indexSystemData = [];
$indexAttributeData = [];
$indexRelationData = [];` 
the data in the mockup cache and the data which is written to the index may get inconsistent!
- Data `$data` which considers the adjustments done in `doPreIndexDataModification` is written to the cache in line https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L436
- Data `$this->bulkIndexData` which does not consider the adjustments done in `doPreIndexDataModification` is collected in https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L425
=> [Ecommerce][Indexservice] Fix doPreIndexDataModification call

lib/Translation/ImportDataExtractor/ImportDataExtractorInterface.php, lib/Translation/ImportDataExtractor/Xliff12DataExtractor.php
Resolves #5768
The fix in the pull request above resolves the issue #5764 
The extractElement function of the DataExtractor now returns null instead of an exception, but its not defined as return value, so the import throws exception 
```Return value of Pimcore\Translation\ImportDataExtractor\Xliff12DataExtractor::extractElement() must be an instance of Pimcore\Translation\AttributeSet\AttributeSet, null returned```
=> XLIFF Import - DataExtractor returns null

models/DataObject/ClassDefinition/Data/Objectbricks.php
Currently for object brick fields in a data object class its getter only says `@return \Pimcore\Model\DataObject\Objectbrick`. While this is correct it could be more specific by documenting the brick container class as return type, for example `@return \Pimcore\Model\DataObject\DataObjectClassName\ObjectBrickContainerFieldName`.
=> [Object bricks] More specific return type for object brick container getter

models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php, models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/ManyToManyRelation.php, models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Further cleanup related to #5772
=> [Data Object] Relations should be always lazy loaded, remove config option in definition #5772

bundles/CoreBundle/Command/DeleteUnusedLocaleDataCommand.php
We have classes with same beginning. For example: magazine and magazineblock
This command causes an error. Because of the missing underscore in the sql:
```
An exception occurred while executing 'DROP TABLE IF EXISTS object_localized_query_magazine_object_localized_query_magazineblock_de'
```
=> DeleteUnusedLocaleDataCommand: Fix wrong SHOW TABLES

doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/04_HeadStyle.md
Fixes the  currently broken part of the documentation for [HeadStyle](https://pimcore.com/docs/6.x/Development_Documentation/MVC/Template/Templating_Helpers/HeadStyle.html) by quoting the `<style>` tag properly.
=> [Docs] Fix formatting in HeadStyle documentation

models/User/AbstractUser.php
I just stumbled about this when trying to get all users below a certain role folder via 
```php
$roleListing = new Listing();
$roleFolder = Role\Folder::getByName('abc');
$roles = array_filter($roleListing->load(), static function(AbstractUser $role) use ($roleFolder) {
return $role->getParentId() === $roleFolder->getId();
});
```
=> [Users] Type-cast parent id to int

lib/Migrations/Configuration/Configuration.php
Currently the install migration gets added to `pimcore_migrations` table but in https://github.com/pimcore/pimcore/blob/65720840f7219cb0d061c818eff5cfc0499b3d5c/lib/Migrations/Configuration/Configuration.php#L373-L383 only migrations in the migration folder get used to determine available migrations. This leads to the following error when trying to execute migrations after the inital installation:
```
WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
>>  (00000001)
```
This PR adds the installer migration to the list of available migrations.
To reproduce bug:
1. Install bundle with installer which extends `Pimcore\Extension\Bundle\Installer\MigrationInstaller`
1. Execute `bin/console pimcore:migration:status -b <Bundle name>`
`Executed …
=> [Bundles] Add install migration to available migrations

bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
The product list converts the aggregation bucket values returned from elastic search to "value" and "count" pairs. If I want to use nested aggregations, but only count the source documents I have to use reverse nested aggregations. The returned values in this type of aggregation gets lost in the `convertBucketValues()` method. 
This PR considers the values and adds an additional field `reverse_count`.
Also see https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-reverse-nested-aggregation.html
=> [Ecommerce][Productlist] Consider ElasticSearch reverse nested aggregations

models/User/AbstractUser.php
When you call `User::getById()` you get a `User` object. When you call `Role::getById()` you get a `Role` object etc.
=> [Users] Doctype: Return type for getBy*

models/DataObject/ClassDefinition/Data/User.php
Currently it seems to be only possible for Input and Numeric fields to add a unique index as they are the only classes which override 
https://github.com/pimcore/pimcore/blob/453a87daed484e85ad00120e264f5a04def5492b/models/DataObject/ClassDefinition/Data.php#L1197-L1200
This PR adds the possibility to create unique indexes also for `User` datatype.
I wonder why unique index is currently only possible for Numeric and Input datatype because the unique checkbox actually is present for all datatypes.
=> [Data objects] unique index for field type "User"

models/DataObject/ClassDefinition/Data/Numeric.php
If `'decimalPrecision' => ''` and `'decimalSize' = NULL` the resulting column type is `decimal(64,0)` which is wrong, correct would be the default type which is `double`.
=> [Data Object] Numeric Data-Type: fix schema if 'decimalPrecision' => ''

bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
This PR checks if `redirect_to_maindomain` is a true boolean. Otherwise, every instance will be redirected to `domain` => always!
=> Check if redirect_to_maindomain is set to true

bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Altered the way how pages (here: key, navigation) are created:
Key and navigation follow the entered title
Why? Since key is representing the navigation-url of the node in the backend tree those 2 values should match by default (but can still be altered) and the navigation entry will by default be a valid url with replacing invalid chars
Even if you think the replacement won't be sufficient, this might serve as a starting point to enhance it further
=> [Document] "Create Page" dialog: title should be the first field, the rest should be pre-filled

bundles/AdminBundle/Controller/Admin/IndexController.php
still one regression left from https://github.com/pimcore/pimcore/pull/5745
email settings detection was false positiv
Frontend still has notification that email settings are not completed although completed (and other way round). False positive detection
=> [System-Config]: fix email settings detection

bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
If you write a Asset Listener to throw an error on certain conditions the error message was not showing in the backend UI.
XMLHttpRequest error is only called if there was an error transmitting.
if the transmission was successfull "load" is called, even if the status code is 400 and up
=> Exceptions did not trigger an error message box

models/DataObject/Classificationstore/Service.php
During the save process, getFieldDefinitionFromJson is called multiple times. In vanilla Pimcore at least twice for each definition - during save and when pushing data to backend search. When AOS plugin is installed - that's another one.
This change caches the result of getFieldDefinitionFromJson in static array. As the gain during regular save is minimal, the real benefit can be seen when saving a lot of objects in one go.
Here's the comparision for importing data from file (~100 objects with classification store). Before:
https://blackfire.io/profiles/43a7d2bf-0adc-45e9-9bf0-530a8c3e564a/graph
After:
https://blackfire.io/profiles/0be9a7e9-162a-40fa-90f7-247605a5895f/graph
=> Cache definition in Classification Store Service

lib/Config.php
Fixes Pimcore\Config::$systemConfig being not initialized in ::offsetExists().
Resolves #5919
=> Fix $systemConfig not initialized in Config::offsetExists()

models/DataObject/ClassDefinition/Data.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php, models/DataObject/ClassDefinition/Data/Block.php, models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/ManyToManyRelation.php, models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php, models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php, models/Element/Service.php
Resolves #5902
Multiple assignments check for Relation Types moved from setter `preGetData` to `save` method so that it is still possible to assign relations without Id before persisting data.
=> [DataObjects] Multiple assignments check for Relations Types bugfix

models/DataObject/Listing.php
... (see Assets & Documents) otherwise this will break existing pagination implementations -> regression of #5837
=> [Data Object] \Pimcore\Model\DataObject\Listing::count() needs to return the value of getTotalCount()

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Fixes a bug which prevents pagination in object custom views.
Resolves #5944
To reproduce:
1. Create object custom view
2. Create a folder in the custom view
3. Create >30 objects in that folder
4. In the custom view tree, there are only 30 objects and no pagination
=> Fix pagination in object custom view

bundles/CoreBundle/Resources/config/pimcore/prod.yml, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Reasons: 
- is triggered by `HttpNotFoundException` as well, so fills up the logs with useless info
- higher memory usage due to buffering
=> [Logging] Do not use fingers_crossed as default in prod environment

bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
Output the actual (short) name of the class instead of "product". This is useful as other entities might get indexed as well, and it that case the message "Updating product ..." might get confusing.
=> Output actual name of Product class on indexing.

lib/Event/AdminEvents.php, models/Element/AbstractElement.php
This event gives developers a way to add their own custom logic when determining whether a user should be granted a certain permission.
I was facing a situation where, in a multi-tenant-setup, all tenants have similar basic roles.
Say, for data objects, I have folder structure like:
```
/My Tenants
|-- tenant 1
|-- customers
|-- products
|-- orders
|-- tenant 2
|-- customers
|-- products
|-- orders
|-- tenant 3
|-- customers
|-- products
|-- orders
```
A role "Product Manager" should have access to `/My Tenants/<whatever tenant I belong to>/products`. With hundreds of tenants and half a dozen or so roles it can be
cumbersome to handle this with the default setup of workspaces. With this event, I have to possibility to fine-tune permissions in any way I like.
=> Add event to allow programmatic manipulation of element permissions

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
most checkboxes have boxLabel in User and Role tab. Permission checkboxes should go inline.
This will allow long descriptions for custom permissions as well.
=> [User|Role] be consistent on checkbox UI and use boxLabel

models/Element/Recyclebin/Item.php
If you want to use the Recyclebin functionality in custom code, the Item::create function needs a user. However the save() function which is called inside the create function allows the user to be null.
This changes makes it possible to have the user parameter omitted in the create call.
=> Allow the user to be null in create function, save already allows this

lib/Image/HtmlToImage.php
On most server, the document version compare does not work (It works on your demo instance though). Most of the time, this process will run for 60sec before a timeout kicks in. After that, no image has been generated.
After some research, I found a similar issue: https://github.com/KnpLabs/KnpSnappyBundle/issues/42
This PR will fix this issue.
=> Trigger useSession before executing HtmlToImage Command

bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php, models/DataObject/ClassDefinition/Data/Extension/Relation.php, models/DataObject/ClassDefinition/Data/ManyToManyRelation.php, models/DataObject/ClassDefinition/Data/ManyToOneRelation.php, models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php, models/DataObject/ClassDefinition/Data/Relations/AllowObjectRelationTrait.php
As `AbstractRelations::getClasses()` really exists we do not need the `@method string[] getClasses()` in the `Relation` trait - this only confuses the IDE.
I actually wonder why all the other methods do not exist or what the `@method` documentations are for - because there is neither a `__call()` function nor do the methods `getAssetTypes()`, `getDocumentTypes()` etc. exist.
They actually only confuse the IDE and if you use those functions you will get errors depending on the actual relation `Data` class.
=> Fix return types for Relation::getClasses

models/Document/Tag/Renderlet.php
If I have a error in a renderlet template I get following error:
`An exception has been thrown during the rendering of a template ("There are no indexes to pop from as index list is empty").`
```
UnderflowException:
There are no indexes to pop from as index list is empty
at vendor/pimcore/pimcore/lib/Document/Tag/Block/BlockState.php:92
at Pimcore\Document\Tag\Block\BlockState->popIndex()
(vendor/pimcore/pimcore/models/Document/Tag/Areablock.php:263)
at Pimcore\Model\Document\Tag\Areablock->blockDestruct()
(vendor/pimcore/pimcore/models/Document/Tag/Areablock.php:128)
at Pimcore\Model\Document\Tag\Areablock->loop()
(vendor/pimcore/pimcore/models/Document/Tag/Areablock.php:94)
at Pimcore\Model\Document\Tag\Areablock->frontend()
(vendor/pimcore/pimcore/models/Document/Tag.php:521)
at …
```
=> Renderlet: frontend method should not catch errors

bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
There was a duplicate declaration of `defaults` which overrode the width/labelWidth settings inside the Controller, Action & Template fieldset.
Now it looks like this:
=> Fixes settings_abstract.js to align inputs & elements

models/Element/Service.php
Just a nice thing to have: If an element key already ends with _copy or copy_N, append/increment a digit to avoid _copy_copy_copy chains if pasting the same object multiple times.
For example, in Windows, pasting a file multiple times will result in: *filename - copy* and then *filename - copy (2)*, in Ubuntu it becomes *filename (copy 1)* and *filename (copy 2)* and similarly will MacOS.
Edit: By the way, I'm using `array_key_last` here, it's a PHP 7.3 requirement, but I'm assuming symfony/polyfill-php73 is loaded if anyone is using PHP 7.2.
=> Feature: Change getSaveCopyName() to behave more like Operating Systems

bundles/AdminBundle/Resources/public/css/editmode.css, bundles/AdminBundle/Resources/public/js/lib/ckeditor/plugins/dialog/styles/dialog.css
This PR has two changes:
1. In editmode, the CKE modal dialogues did not properly position themselves above the WYSIWYG button panel, using `.cke_dialog_container` resolved that.
2. Any time a CKE modal dialogue were opened the background document jumped sideways due to the disappearing scroll bar, this keeps the scrollbar. The modal will still be centred in the viewport if the user scrolls and scrolling scrollable fields in the modal works as expected.
=> CKE and editmode adjustments/fixes

bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
Fix following exceptions:
```
ErrorException: Notice: Undefined index: exclude_patterns in vendor/pimcore/pimcore/bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php:221
Stack trace:
#0 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(126): Pimcore\Bundle\CoreBundle\EventListener\Frontend\FullPageCacheListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#1 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', …
```
=> Fix Notice: Undefined index: exclude_patterns

doc/Development_Documentation/26_Best_Practice/20_Building_Custom_Rest_APIs.md
if REST API is deprecated then routes endpoint also needs to change . because using these routes "/webservice/rest/*" , it is using the deprecated api key method for authentication.
Resolves #
=> [DOCS] Update 20_Building_Custom_Rest_APIs.md

.travis/run-stan.sh, composer.json, doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
With the new version 0.12.18 its easier to generate a new baseline file:
https://github.com/phpstan/phpstan/releases/tag/0.12.18
=> [PHPStan] Use new generate baseline option

bundles/AdminBundle/Controller/Admin/AssetController.php
If I want open a new video in the admin interface I get following exception:
```
Error: Call to a member function getInherited() on array in vendor/pimcore/pimcore/models/Asset.php:770
Stack trace:
#0 vendor/pimcore/pimcore/models/Asset/Video.php(76): Pimcore\Model\Asset->update(Array)
#1 vendor/pimcore/pimcore/models/Asset.php(519): Pimcore\Model\Asset\Video->update(Array)
#2 vendor/pimcore/pimcore/models/Asset/Video.php(262): Pimcore\Model\Asset->save()
#3 vendor/pimcore/pimcore/models/Asset/Video.php(280): Pimcore\Model\Asset\Video->getDimensions()
#4 vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/AssetController.php(110): Pimcore\Model\Asset\Video->getWidth()
#5 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(146): …
```
=> [AssetController] Fix: Call to a member function getInherited() on array

doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/04_PayPal.md
casting the object to an array will loose some nested objects that are needed.
=> [docs] [paypal] casting object to array looses data

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, models/Asset/Image/Thumbnail.php, models/Asset/Image/Thumbnail/Processor.php
This solves issues e.g. with mime detections by object storages like S3 and probably also für CDNs and other services. 
There is also no reason to not use the standard file extension at all.
=> [Asset] JPEG Thumbnails should only use .jpg as file extension, not pjpeg or .jpeg

bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js, bundles/CoreBundle/Migrations/Version20200324141723.php, bundles/CoreBundle/Resources/translations/en.extended.json, models/Asset/Image/Thumbnail.php
Resolves #5201
In the past only `max-width` media queries were supported, now any media query can be defined.
=> [Asset] Support for all/custom media-queries in thumbnails

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
When editing multiselect values in an advanced many-to-many relation, the edit window will already show translated values. In the grid, however, the values are not translated as of yet. This PR adds a renderer to the multiselect column that applies the translation method to every selected option.
=> Make multiselect values in advanced many-to-many-relations translatable

models/Asset/Image/Thumbnail.php
Currently there's an inconsistency since between the fallback image used in the data-attribute and the one used for the <img> Tag. 
This PR fixes this inconsistency and uses always the default configuration as the fallback.
=> [Asset] Thumbnails: fallback image of <picture> element should be always the default configuration

bundles/AdminBundle/Resources/public/js/pimcore/settings/recyclebin.js
Fix the TypeError while recyle a object from bin
TypeError: Cannot read property 'rendered' of undefined
at klass.doRestore (script-proxy?scripts=minified_javascript_core_5b0dd417454df3797f350320a8b61740.js&_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:21354)
at klass.<anonymous> (script-proxy?scripts=minified_javascript_core_5b0dd417454df3797f350320a8b61740.js&_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:21389)
at Object.callback (ext-all.js?_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:22)
at E.onComplete (ext-all.js?_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:22)
at E.onStateChange (ext-all.js?_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:22)
at XMLHttpRequest.t (ext-all.js?_dc=c49d5fbce4cee1eb2a6d6fb619de3e45fc5e5532:22)
=> Frontend error while refresh all trees after recycled bin #6107

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Resolves #5874 
May be a bc-breaking, if there are interpreters getters in the application which do not return the correct type: a string or integer field may receive "false" - if `false` was returned which should actually be `null`. 
This may result in a filter like so:
=> [Ecommerce]IndexService] ElasticSearch Worker only filter null values

bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
Passing the document context will trigger the "resolve upload target" event and gives the developer an opportunity to change the target folder.
(In my specific use case, I want to choose a folder based on the sub-site the document belongs to)
=> Pass context when adding an asset via drag and drop to a document

lib/Routing/Staticroute/Router.php
Respect base-url in static-routes. Use case:
I started developing Frontend Tests for CoreShop, since I need a fixed environment, I created `web/app_test.php` where I force an ENV. Since that is now my base-path for all generated Routes, Pimcore Static Routes should respect that as well.
=> [Staticroute] respect base url

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- Add obejctbrick fields to folder grid and save it.
- Delete objectbrick
- Load folder grid with saved config => error
=> [Admin] DataObjects Grid - Fix grid config error when object brick is deleted

bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
=> Fix: Navigation Excludes of Links are not shown in tree

models/DataObject/ClassDefinition/Data/Extension/Relation.php
##Changes in this pull request  
Resolves #6122 
regression caused by https://github.com/pimcore/pimcore/pull/6032/commits/e402dce9643389b926efe809db1c9ca4be271037
=> [DataObjects] Relations - fix getClasses() return value

bundles/CoreBundle/EventListener/Traits/PreviewRequestTrait.php
Not 100% sure if this is the most optimal location for this change, but I'm submitting it like this. This change resolves no issue, but it helps with previewing Snippets and such objects.
=> Allows PreviewRequestTrait to discover primcore_preview

bin/pimcore-install
Same behaviour as in issue #5495 but this time during installation.
I think the line I added was forgotten?
Otherwise the variable `$projectRoot` makes no sense.
=> Fixed wrong project root on pimcore-install command

models/DataObject/ClassDefinition/Data/Select.php
In admin object grid, filtering on select fields that use an option provider does not work. Select fields that use option providers use a free text search instead of letting you pick from a list of options. Filter type is 'string' and not 'list' and operator is 'like' instead of 'in'. 
In getFilterConditionExt method of the Select class only the '=' operator is allowed. It needs to allow 'LIKE' operator as well for filtering to work when using option provider.
Additionally for filters using the = operator, the produced query was using LIKE operator. This is not needed. Using = as operator in query should be slightly better performance wise.
=> Allow LIKE operator on Select data type filter condition

doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/01_Application_Testing.md
Hello,
This pull request add a missing kernel bootstrap in documentation for codeception.
I was working with codeception 4 and Pimcore 6.6.0, and without this, it was not possible to use Pimcore API on unit tests.
Same for any custom php file needing Pimcore API (php my-script.php), kernel must be run (I think on older Pimcore kernel was bootstraped in `\Pimcore\Bootstrap::bootstrap();` before). I don't know if there is some other places in documentation which need to be updated about this.
Thanks.
=> Add kernel bootstrap to codeception boostrap file example in documentation

models/Search/Backend/Data.php
```
ErrorException: Notice: Array to string conversion in vendor/pimcore/pimcore/models/Search/Backend/Data.php:449
```
`$value` can be a array:
=> [Search/Backend] Fix Notice: Array to string conversion

bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php, lib/Event/AdminEvents.php
Description:
Currently there is no event in pimcore if you change object brick definition. With this new event it is possible to listen to the object brick changes.
=> - Added new generic event to the object brick update method.

doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md, models/Document/Tag/Area/Info.php
Resolves #4057
```
public function action(Info $info)
{
$editable= $info->getDocumentElement('editableName');
if ($editable) {
$editable->getData();
}
}
```
=> [AreaBricks]  Add possibility to access editables from brick info

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php
Alternative approach to #5991 
In the long term diffVersions should use the data object's isEqual method instead of comparing the version preview.
This however requires that every data type properly implements this method. Currently only done for 
relational data types and url slug (needed for dirty detection).
Default implementation in Data returns false not really useable currently.
=> [DataObject] Fix inconsistent version diffs

models/DataObject/Service.php
=> Opening object grid in admin throws getPermission() on null error

bundles/AdminBundle/Resources/public/css/icons.css
set priority of pimcore_icon_asset_default otherwise it overrides the icons in quick search
=> Update icons.css for Quick Search

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/reportTab.js
So if you import many items, you are not able to see the whole result set.
This PR adds possibility to scroll in reporting tab
=> Import reporting is currently not scrollable.

bundles/AdminBundle/Resources/public/js/pimcore/settings/profile/panel.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js, bundles/AdminBundle/Resources/views/Admin/Login/login.html.php, bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php, bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
Autocomplete=off on login forms is [not really a thing any more](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields).
Also, added autocomplete hints to improve compatibility with password managers.
=> Refactors login/lost-pw/2-factor form autocomplete functionality

models/DataObject/ClassDefinition.php, models/DataObject/ClassDefinition/CustomLayout.php, models/DataObject/Fieldcollection/Definition.php
Resolves #6211
As discussed there's not much added value in having this data in the docblocks. The disadvantages (merge conflicts when working with several feature branches) outweigh the advantages, so we remove this.
=> Remove docblock data which changes everytime

bundles/EcommerceFrameworkBundle/Exception/PaymentNotSuccessfulException.php
PaymentNotSuccessFullException misses Getters for protected properties `order` and `status`.
=> Add missing getter for PaymentNotSuccessFullException

bundles/AdminBundle/Controller/Admin/ElementController.php, bundles/AdminBundle/Controller/Admin/IndexController.php
There are current 2 phpstan errors. See https://travis-ci.com/github/pimcore/pimcore/jobs/321052738
```
------ ------------------------------------------------------------ 
Line   bundles/AdminBundle/Controller/Admin/ElementController.php  
------ ------------------------------------------------------------ 
123    Call to an undefined method                                 
Psr\Container\ContainerInterface::getParameter().           
------ ------------------------------------------------------------ 
------ ---------------------------------------------------------- 
Line   bundles/AdminBundle/Controller/Admin/IndexController.php  
------ ---------------------------------------------------------- 
314    Call to an undefined method …
```
=> [PHPStan] Fix current errors

lib/Routing/RedirectHandler.php
When you create a redirect without target site currently the general domain from the system settings gets used. This PR extends this by trying to find the target site by the request's hostname if no target site has been specified for the redirect. If none is found, the general domain gets used (as before)
=> [Redirects] Fetch target site by domain if no target site set

bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js, bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
As it was already implemented for objects, we would like to have a proper JS validation for documents as well. Without these changes, we can't close the validation box correctly (the background is still unclickable)
=> show validationExceptions for documents correctly as well

bundles/CoreBundle/Resources/config/services_routing.yml, doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/30_Link_Generator.md, lib/Routing/Element/Router.php
It would be nice to can use the symfony/twig functions path/url to generate urls for elements.
I know it from other systems to use this functions also for objects.
It is also supported from symfony with the `VersatileGeneratorInterface` interface.
=> [Feature] Element Router

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/block.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/classificationstore.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/countrymultiselect.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/date.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/email.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/externalImage.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/fieldcollections.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/geo/abstract.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/hotspotimage.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/inputQuantityValue.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/languagemultiselect.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToOneRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/objectbricks.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/table.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/textarea.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/time.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/user.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/wysiwyg.js
While cloning or copying data fields in class settings, all the specific settings of the field are not copied to the destination field.
applySpecialData function is modified or added to resolve the same for following data fields:
- Input  - Default value was number field, changed to text field
- Increased the default value width to 600.
- Textarea 
- Wysiwyg 
- Iinput qualtity 
- Numeric
- Date
- Date & Time
- Time  - reset button also corrected
- User  
- Country Multiselect
- Language Multiselect
- External Image 
- Advanced Image
- Many-to-one- Relation
- Many-to-many Object Relation
- Advanced many-to-many Relation
- Reverse Many-To-Many Object Relation
- Many-to-many Relation
- Advanced many-to-many Object Relation
- All geographic points
- Block
- Classification Store
- Table
- …
=> Correction in applySpecialData fuction for different data types

models/DataObject/ClassDefinition/Data/Fieldcollections.php
Resolves #
params info(other than context) should not be overwritten in fieldcollections save
=> [DataObjects] Respect params passed to Fieldcollections save

bundles/AdminBundle/Resources/public/js/pimcore/functions.js
Resolve #6277
Only changes on the javascript side because of backwards compatibility - there are no good options to validate it in PHP.
But this prevents that several keys that are invalid are written to the database.
=> Resolve "[Bug] Texts that are longer than 190 characters cannot be translated"

bundles/CoreBundle/Migrations/Version20200428111313.php, models/DataObject/ClassDefinition/Data.php, tests/_support/Helper/Model.php, tests/model/Inheritance/GeneralTest.php
1. Create class `Category`
1. Create class `Product` with inheritance enabled and add a many-to-many object relation field `categories` with allowed class `Category` and `lazy-loading` enabled
1. Create `Category` object with path `/category`
1. Run `bin/console pimcore:run-script` with the following script:
```php
<?php
$parent = new \Pimcore\Model\DataObject\Product;
$parent->setParentId(1);
$parent->setKey('parent');
$category = \Pimcore\Model\DataObject\Category::getByPath('/category');
$parent->setCategories([$category]);
$parent->save();
$child = new \Pimcore\Model\DataObject\Product;
$child->setParent($parent);
$child->setKey('child');
$child->save();
```
After this the child object with path `/parent/child` inherits the field `categories` from its parent.
Now …
=> [Data objects] Override inherited value with same value (break inheritance)

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
Follow up of #6276 
Fieldcollections controls should be hidden for read-only fields
Before change:
After change:
=> [Admin] DataObjects - Improve Fieldcollections controls visibility

bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Currently if column width is not explicitly set ExtJS's default column width gets used. This is not optimal as it is not responsive. This PR sets `flex: 1` attribute for all columns which have no width being set. This way the columns use the whole available panel width.
=> [Reports] Flex column width if width not explicitly set

bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
Steps to reproduce bug:
1. Create redirect with source `/test?test=1&amp=1`
1. Save redirect
Expected behaviour: Redirect source is `/test?test=1&amp=1`
Actual behaviour: Redirect source is `/test?test=1&=1`
This is only a bug in the user interface - in the database and program logic everything works correctly.
=> [Redirects] HTML-encode redirect source and target

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/imagegallery.js
Resolves #6314 
applySpecialData function removed from image gallery as this can be inherited from the parent.
=> Error in cloning image gallery or copying any layout having image gallery 

lib/Sitemap/Document/DocumentTreeGenerator.php
The sitemap generation command does not work when using hardlinks. If the linked element has subpages.
In Pimcore Admin:
```
vagrant@homestead ~www/...forked/dev (git)-[fix-sitemap-generator] % php7.3 ../bin/console presta:sitemaps:dump --base-url=http://pimcore-forked.twocream.local/ -vv
Dumping all sections of sitemaps into web directory
In DocumentTreeGenerator.php line 158:
[ErrorException]
Warning: Invalid argument supplied for foreach()
Exception trace:
at /var/www/...forked/dev/lib/Sitemap/Document/DocumentTreeGenerator.php:158
Pimcore\Sitemap\Document\DocumentTreeGenerator->visit() at /var/www/...forked/dev/lib/Sitemap/Document/DocumentTreeGenerator.php:159
Pimcore\Sitemap\Document\DocumentTreeGenerator->visit() at /var/www/...forked/dev/lib/Sitemap/Document/DocumentTreeGenerator.p …
```
=> Fixed bug with sitemap generation for hardlinks

bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
With this change you can control "add blank document" in document menu to hide it for users. 
You can add `['treeContextMenu']['document']['items']['addBlankDocument'] => 0` in customviews to hide it for users.
=> [Documents] add option to hide "add blank document" in documents menu

bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
Resolves #
Bug fix: If there are metadata rows with same name and different language then onDrop always take the first occurrence in grid.
=> [Admin] Asset Custom Metadata grid - fix data for rows with same name

bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
Reported in #6279
> I would like to report just something strange too, id seems duplicated when i inspected the link generated in BO:
https://demo.pimcore.fun/admin/asset/get-image-thumbnail?id=410&thumbnail=standardTeaser&id=410&pimcore_editmode=1
You will notice the id parameter is defined twice.
=> [Asset] Image previews with duplicate id params

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Related to #6350
> I have found this line that disables the validation:
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1719
I think instead of || you mean &&?
=> [DataObject] Fix OmitMandatoryCheck for Grids

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Tries to fix #5499 
As discribed in the issue, we experience deadlocks in the store table as well.
This PR adds a method `executeTransactionalQuery` which tries to commit a query for n times (default 3) with a given sleep timeout (default .5 seconds). 
There may be some more places in the worker class(es) where it could help to utilize this method, I added the calls to our pain points only.
The solution is inspired by `AbstractObject::save()` in https://github.com/pimcore/pimcore/blob/master/models/DataObject/AbstractObject.php#L664
=> [Ecommerce][Indexservice] Utilize transactions for avoiding deadlocks

bundles/AdminBundle/Controller/Admin/AssetController.php, models/Asset/Image/Thumbnail/Processor.php
* Modifies Admin/AssetController to replace the Assets file extension with case insensitive regexp
* Modifies Image/Thumbnail/Processer to create tmp files with correct filename by replacing the original file extension with case insensitive regexp
* Upload an Asset with an uppercased file-extension (e.g. `picture.TIF`)
* Download the "Web-Format" of this Asset
* Downloaded file is named `picture.jpeg`
* Downloaded file is named `picture.tif`
=> [Asset] fix download-filename when file extension of Asset is uppercased

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
Margin bottom added for Advanced Image so that it doesn't sticks to the elements added after it.
Resolves #6316
=> Bottom margin added for  advanced image container

bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
Fixes CheckoutManager bug when using EcommerceFramework V6
If V6 is still used, and no 'handle_pending_payment_strategy' is set, the
payment strategy Service Locator gets initialised without any locators set.
This causes an exception whenever the CheckoutManager gets initialised, thus
this commit sets a default locator.
=> <fix> Set default value for "handle_pending_payment_strategy"

doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
Headlines need a space after the `#`'s to be rendered correctly.
=> Fix headline in the docs

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
By the way: What does `Passing multiple relations (w/o multiple assignments check) in data objects is deprecated and will throw exception in Pimcore 7` actually mean or to which pull request / commit does it refer?
=> [Documentation] Fix typos

stubs/dynamic-constants.php
`pimcore/config/constants.php` doesn't exist anymore, they're generated in `lib/Bootstrap.php` nowadays.
=> Fix reference to where the constants are generated now

bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Merge.js
This fix solves the issue when you try to add or edit an 'Operator Merge' column with a custom label (other than 'Operator Merge').
The column label was uncorrectly reported in the grid display and in the related CSV export. It displayed 'Operator Merge' whatever you edited for this label in the 'Grid Options' window.
=> Fix column label loss for the 'Operator Merge' type in object grids

models/Asset/Image.php, models/Asset/Thumbnail/ClearTempFilesTrait.php, models/Asset/Video.php
Currently when a thumbnail definition gets saved or when thumbnails get deleted with the "Clear thumbnails" button at an asset, PHP's glob() function gets used to find the thumbnail files to be deleted.
But glob() does not work with stream wrappers (when thumbnails get stored on AWS S3 or Google Cloud Storage like described in https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html). For this reason thumbnail deletion does not work at all when thumbnails are not stored locally: once a thumbnail for an image has been created there is no way to update it.
=> [Image / Video thumbnails] Make thumbnail deletion compatible with stream wrappers

bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
This PR fixes two issues in the object variant grid:
1/ broken batch edit for 'select' fields: the code worked for the object type 'object', not 'variant', so the select options were not populated in the batch edit popup,
2/ broken 'batch edit all' when some lines were selected in the grid.
=> Fix on object variant grid: batch edit for 'select' fields + batch edit all with selected items

bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
Currently the `GoogleTagManager` will always track quantity 1, this PR considers the passed quantity in the method signature.
=> [Tracking] fix quantity for trackCartProductActionAdd

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
This fix is intented to correct CSV/XLS data export for merged values via the 'Operator Merge' formatter for object grids.
Before:
| Operator Merge   |
|----------|
| Array |
| Array |
| Array |
Now:
| Operator Merge   |
|----------|
| value1,value2 |
| value1,value3 |
| value4 |
=> Fix uncorrect CSV/XLS export for 'Operator Merge' values

bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
Change date format to ISO to match flatpickr date format.
The Orderlist filtering tool shows a different date than what the filter uses.
Go to orderlist, check the date in UI, go to browser  inspection tools and see that the value given is correct, but in wrong form
```html
<input 
type="text" 
id="date-from" 
class="form-control date flatpickr-input active" 
name="from"
placeholder="Date from" 
value="01.05.2020"
> 
```
it should be: 
```html
<input 
type="text" 
id="date-from" 
class="form-control date flatpickr-input active" 
name="from"
placeholder="Date from" 
value="2020-05-01"
>
```
=> fix flatpickr compatibility

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Calling `sleep` will cast the given value to `int` so a default value auf `0.5` would be treated as `sleep(0)`. This PR utilizes `usleep` to be able to use float values.
=> [Ecommerce][Indexservice] Fix timeout for transactional queries

bundles/EcommerceFrameworkBundle/Command/IndexService/EsSyncCommand.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php, composer.json, doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
this is an alternative implementation to #5744 for the reindexing part. 
Removes ecommerce framework reindexing mode completely and forces user to start ES native reindex when mapping update is not possible. 
During ES native reindex
- any other mapping updates are not possible
- data updates are only updated in store table and updated via process update queue to ES index after reindex is finished 
Thus it would reduce complexity. 
Open question: 
- does ES serve requests from old index while building the new one? 
- what to do with delete operations when reindex is running?
=> [Ecommerce][Elastic Search] Replace reindexing-mode with ES Native Reindexing

models/DataObject/ClassDefinition.php
There is no point in checking for permission when it's not used anyway.
=> ClassDefinition: don't check for permission when you don't intend to use it

bundles/AdminBundle/Controller/Admin/ElementController.php, models/Element/PermissionChecker.php
Resolves #
when there's a user folder then Permission Analyzer throws exception
=> [Admin] Users - Fix user type for Analyze Permissions

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
=> Block fields have no spacing to next field

bundles/CoreBundle/Command/ThumbnailsImageCommand.php, bundles/CoreBundle/Command/ThumbnailsVideoCommand.php, composer.json, doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md, lib/Console/Traits/Parallelization.php
This PR enables the parallel generation of thumbnails based on their generator commands.
It includes a demonstration of the auspicious [ParallelizationTrait](https://github.com/webmozarts/console-parallelization) which has been extended to fit into Pimcore.
**Parallelization usage in general:**
```php
bin/console pimcore:thumbnails:image
bin/console pimcore:thumbnails:image --processes 1
bin/console pimcore:thumbnails:image --processes 5
```
**Usage image generation command:**
```php
bin/console pimcore:thumbnails:image
bin/console pimcore:thumbnails:image --processes 1
bin/console pimcore:thumbnails:image --processes 5
bin/console pimcore:thumbnails:image --processes 20
```
**Usage video generation command:**
```php
bin/console pimcore:thumbnails:video
bin/console …
```
=> Parallelization of thumbnail commands

lib/Tool/Admin.php
As this was deprecated in `v6.7` it can be already removed in `v7.0`.
=> Update deprecation message for `Pimcore\Tool::getMinimizedScriptPath($asUrl=true)`

lib/Translation/Escaper/Xliff12Escaper.php
- Export a localized data object input field with content "A & B"
- Export it via XLIFF
- Translate and reimport it with the same content
=> The target input field will contain `"A &amp; B"`
This PR fixes this problem by implementing an improved version for parsing the inner XML of the target nodes.
=> [xliff import] fix XML special characters for input fields

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
Currently when an image field is set to `not editable` for a data object class, one cannot open the assigned image from the edit panel on an object. This PR adds the "Open" button in the tag's toolbar as well as in the context menu.
=> [Data objects] Add "open" button for non-editable image fields

bundles/CoreBundle/Command/CacheClearCommand.php
Currently the `pimcore.system.cache.clear` event does only get dispatched when the cache gets cleared via GUI, see https://github.com/pimcore/pimcore/blob/fb4af6928847b0635b6f782b53055e7fbdff9d8b/bundles/AdminBundle/Controller/Admin/SettingsController.php#L750
With this PR the event gets also dispatched when the cache gets cleared via CLI command `bin/console pimcore:cache:clear`
=> Dispatch pimcore.system.cache.clear event when calling pimcore:cache:clear command

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
Currently you can filter a select field in a data object's edit panel only be prefix. For example when you have the options `Test` and `My test` and you type `test` in the input field, you will only get `Test` suggested but not `My test`. With this PR the searched string can be anywhere in the option to get suggested.
=> [Data objects] Fulltext search for select fields

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/password.js, doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md, models/DataObject/ClassDefinition/Data/Password.php
It makes no sense to have an upper limit* on password length. Anyway, it was never enforced in the backend if you did a `$account->setPasswordField('somestring');`, only in the UI, and even then it never actually prevented submitting the data.
This PR also removes an unneccesary duplicate declaration of inputType = password.
Hashes which are harder to detect are generally always in the HEX 00 to FF `a-f0-9` character range and of a set length (4 bits per char, e.g. SHA512 = 512/4=128), only checking for >= 32 is too weak and makes very little sense in the world of password managers and diceware passwords.
\* Well, technically maybe a password in the kilobyte range or larger would be uneccesarily large and a [problem in itself](https://arstechnica.com/information-technology/2013/09/long-pas …
=> Removes limitation on password length

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js, bundles/CoreBundle/Resources/translations/en.json
If you have a csv file with empty columns only on the end of the data rows, all seems okay in the admin interface. It shows the data in preview. Only the import is immediately successful without importing anything.
I think pimcore should immediately display an error message and not mislead the user.
=> [CSV Import] No error if header and data rows have different number of columns

models/DataObject/Localizedfield.php
Check if localized-field should be lazy-loaded during fallback-language handling, otherwise existence check will always fail and fallback will never be loaded.
In case a localized-field is marked as lazy-loaded (default for all relations now?) and no data exists for the required locale, fallback handling should be applied. 
But this is not possible because **_languageExists( $l )_** will most likely always return false as the fallback-language itself has never been loaded in the first place.
**Locale**: de_DE
**Fallback**: de
_Localized Data for Relation:_
- **_de_DE_**: EMPTY
- **_de_**: Any valid Element (Object, Asset, Document)
Recursive call to _**getLocalizedValue**_ will never happen, as data for **_de_** has not been loaded yet.
Any class with relations inside localized-fields …
=> [DataObject] Fix Localizedfield lazyloading for fallback

bundles/AdminBundle/Controller/Admin/RecyclebinController.php
Resolves #6495
When deleting multiple elements, if childs are also selected for deletion (in case of grid selection -> delete)  then `recyclebin/add` request returns false for childs which are already from parent request, which in turn breaks the deletion process. 
This PR changes success status, which is returned false only, if there is any exception while adding element to recyclebin.
=> [Recyclebin] Fix deleting multiple elements - #6495

doc/Development_Documentation/06_Multi_Language_i18n/README.md
There should be no line break here, because otherwise it results in being rendered as follows:
=> Remove erroneous line-break from the docs

lib/Translation/ImporterService/Importer/DataObjectImporter.php
This is a bug fix for latest release and master. The bug was introduced with https://github.com/pimcore/pimcore/pull/4529/files.
Having a translated block doesn't work properly when importing an XLIFF file.
As seen in this screenshot, the language isn't changed, but the value is, that caused Pimcore to override it's original value instead of the source value. (Which by some magic later on is set anyway. - Didn't investigate)
I enforce the '_language' variable in the block element which is supposed to be present when in context of a translation.
I hope I didn't miss something and I'd be happy to hear some feedback!
=> Fix xliff import overriding source values

bundles/AdminBundle/Resources/views/Admin/Misc/admin-css.html.php
Previously larger icons from the library would not look good, such as Twemoji and flags, because they did not properly fit into the available box.
=> Fix to keep icon sizes regular and centered

bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Should only invert white flat icons.
Resolves #6553
=> Fix to avoid inverting colour icons

models/Document/TargetingDocument.php
`Pimcore\Model\Document\TargetingDocument::getElement()` often returns `parent::getElement()` which may return `null`:
https://github.com/pimcore/pimcore/blob/1e49e5cb106b1e701e979782fdf7cefaae96174d/models/Document/PageSnippet.php#L402-L404
=> Fix return type annotation

models/Document/Tag/Areablock/Item.php, models/Document/Tag/Block/AbstractBlockItem.php, models/Document/Tag/Block/Item.php
They're not allowed anymore since PHP 7.2: https://wiki.php.net/rfc/get_class_disallow_null_parameter
This also removes some duplicated code.
=> Prevent `get_class(null)` calls

models/Document/PageSnippet.php
This was introduced in #3908.
The ones on `Element::getById()` were deleted in 8fffea84 right after merge, but this one was forgotten.
=> Remove unnecessary `@throws` annotation

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Admin translations are not applied to localized classification store tab labels. Also see https://github.com/pimcore/pimcore/pull/6022
=> Localized classification store tab label translations

.php_cs.dist
Also Symfony do this:
https://symfony.com/doc/current/contributing/code/standards.html#structure
`Add a comma after each array item in a multi-line array, even after the last one`
=> [CS-Fixer] Add trailing comma in multiline array rule

doc/Development_Documentation/26_Best_Practice/55_Primary-Replica_Database_Connection.md
Following [Doctrine/DBAL's recent deprecation](/doctrine/dbal/commit/7047798fbb5484703e2f628ab6110b08f887d550) of master/slave in favour of primary/replica Pimcore should do the same
=> Update Pimcore DB master/slave to primary/replica

bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
At the moment it is only possible to remove the "> Blank" menu item in page documents. It should be possible in all document types (print, snippet, email, newsletter)
perspectives.php
```
<?php
return [
'default' => [
'iconCls' => 'pimcore_nav_icon_perspective',
'elementTree' => [
[
'type' => 'documents',
'position' => 'left',
'sort' => -30,
'treeContextMenu' => [
'document' => [
'items' => [
'addBlankDocument' => false,
'addBlankPrintPage' => false,
'addBlankEmail' => false,
'addBlankSnippet' => false,
'addBlankNewsletter' => false,
],
],
],
],
[
'type' => 'assets',
'position' => 'left',
'sort' => -20,
],
[
'type' => 'objects',
'position' => 'left',
'sort' => -10,
],
],
],
];
```
=> Possibility to remove "> Blank" menu items in all document types

bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js, doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
Checking only for custom set toolbarGroups and (in case none is found) passing a default for toolbarGroups won't allow to overwrite the settings given in the customConfig file passed via options.
One could argue, that the customFile is not passing a toolbarGroup config, but the user could at least then overwrite the default settings from line 86 - 97 or accept the default given in ckeditor settings.
=> Check for customConfig passed to ckeditor

models/Document/Tag/Block.php
=> [Documents] Blocks - Fix getElements() throws exception with defaults

bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig, lib/Document/Tag/TagHandler.php, lib/Extension/Document/Areabrick/AbstractAreabrick.php
Added a "getOpenTagCssClass" method to the AbstractAreabrick class that can be used to add additional css classes to the basic wrapper div around every areabrick "pimcore_area_content".
The rendering mechanism for areabricks in the TagHandler has been extracted and moved to a twig template with various blocks in it. This way its easy to alter the way an areabrick is rendered (surrounding divs, wrapper classes, ...) by extending the twig template via symfonys template inheritance.
```twig
{# /app/Resources/PimcoreCoreBundle/views/Areabrick/wrapper.html.twig #}
{% extends "@!PimcoreCoreBundle/Areabrick/wrapper.html.twig %}
{% block areabrickWrapper %}
<div class="my-custom-wrapper">
{{ parent() }}
</div>
{% endblock
```
=> Areabrick rendering via twig template

models/Asset/Document.php, tests/_support/Util/TestHelper.php, tests/model/Asset/AssetTest.php, tests/model/Asset/ListingTest.php
When you create new documents via symfony command you get following exception:
```
12:14:00 ERROR     [pimcore] Exception: Unable to get page-count of /var/www/pimcore/web/var/assets/test.pdf in /var/www/pimcore/vendor/pimcore/pimcore/lib/Document/Adapter/Ghostscript.php:148
```
Because the file doesn't yet exist in this moment.
=> Document should first update data and then process page count

bundles/AdminBundle/Controller/Reports/AnalyticsController.php
When you have access to multiple profiles over die analytics API, the list of available profiles can be unclear if many profiles have the same names.
This proposed change prefixes the profile names with the names of their property, making them easier to distinguish.
=> Prefix GA profiles with the name of their properties

models/DataObject/ClassDefinition/Data/Table.php
I'm not 100% sure if this is the best solution, but the fact that an empty table will return a string should be accounted for. Personally I would prefer that it always returned an array, but since that might be a (minor) BC break I want to avoid doing that change for now.
=> Corrects doctype for Table ClassDefinition inputs

bundles/CoreBundle/DependencyInjection/Configuration.php, bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php, bundles/CoreBundle/Resources/config/l10n.yml, doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md, lib/Translation/Translator.php
In some projects I had issues with the admin locale, for example: When you open a document with the locale "hr" or "zh" in Pimcore backend, it shows just the basic key without translation because "hr" is not available as an admin translation and "zh" is only available as "zh_Hans".
This PR allows you to override the admin locale with following mapping like:
```
pimcore:
translations:
admin_translation_mapping:
'hr': 'en'
'zh': 'zh_Hans'
```
=> Possibility to override the admin locale in view templates

doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md, lib/Event/Model/NotificationEvent.php, lib/Event/NotificationEvents.php, models/Notification.php
Hi,
This PR is intented to bring new events regarding the notification feature.
This adds the pre/post add/update/delete events.
For example, this could be useful to send an email for a new notification.
=> Notification events for add/delete

bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
**Before**
```
<?php
return [
"enableInDefaultView" => TRUE,
"displayfield-1581-inputEl" => "Enables Web2Print documents in default documents view in default perspective. Either activate this or create custom views and perspectives for managing Web2Print documents.",
"generalTool" => "pdfreactor",
"generalDocumentSaveMode" => "default",
"displayfield-1584-inputEl" => "Document Save Mode = cleanup deletes all not used document elements for current document. This might be necessary for useage reports in print documents.",
"pdfreactorVersion" => "9.0",
"pdfreactorProtocol" => "https",
"pdfreactorServer" => "cloud.pdfreactor.com",
"pdfreactorServerPort" => "443",
"pdfreactorBaseUrl" => "https://demo.pimcore.fun",
"displayfield-1568-inputEl" => "BaseURL for PDFreactor. This is prefixed to each …
```
=> [Web2Print] Remove unnecessary displayfield settings in web2print.php

models/Webservice/Data.php
Depending on how you convert the JSON of a Pimcore Webservice REST API call the properties can be an `array` or an instance of `stdclass`, see second parameter of `json_decode()`. 
The RestImporterBundle only calls `json_encode()` so the JSON objects get converted to `stdclass` objects:
https://github.com/pimcore/RestImporter/blob/6aea1943de0a7bbea8a134a29db88d4f7d495941/src/Elements/Bundle/RestImporterBundle/RestClient.php#L217
As an example a JSON response of https://<Pimcore-Host>/webservice/rest/document/id/<ID> might look like
```json
{
"success":true,
"data": {
"path":"/path/to/document",
"creationDate":1582810483,
...
"properties":{
"language":{
"name":"language",
"data":"de",
"type":"text",
"inheritable":true,
"inherited":true
},
...
}
}
```
When the properties get decoded to a …
=> [REST webservice] Handle properties as stdclass object

models/Webservice/Service.php
When you override a document class, its data is not accessible via REST API.
1. Put the followiing to app/config/config.yml:
```yml
pimcore:
models:
class_overrides:
'Pimcore\Model\Document\Page': 'AppBundle\Model\Document\Page'
```
2. Clear cache.
3. Create page document
4. Access document via https://\<Pimcore-Hostname\>/webservice/rest/document/id/\<ID of new document\>
PS: I know, REST webservice is deprecated but as long as it is not removed we should make it work correctly.
=> [REST Webservice] Support overridden document classes

bundles/CoreBundle/EventListener/WorkflowManagementListener.php, lib/Workflow/Manager.php
- fixes invalid place "" exception as of Symfony >= 4.4.8
- set place on load for compat with objects created prior to fix
Resolves #6013 
Tested mainly with marking store of type `single_state` where on adding objects the initial place was not saved. The custom [StateTableMarkingStore](https://github.com/pimcore/pimcore/blob/master/lib/Workflow/MarkingStore/StateTableMarkingStore.php) seems not to be affected by the bug b/c loose checking is still applied (also, on object add the initial place get's stored to the `element_workflow_state` table).
Setting the initial place programmatically in [onAdminElementGetPreSendData](https://github.com/macghriogair/pimcore/blob/bugfix/issue-6013-initial-workflow-place-on-add/bundles/CoreBundle/EventListener/WorkflowManagementListener.php#L167) seems …
=> [Workflow] fix #6013 initial place empty on add with `single_state` store

models/Document/Tag/Areablock.php
After #6515 I get following notice in every Areablock tag:
```
Notice: Undefined index: xyz in vendor/pimcore/pimcore/models/Document/Tag/Areablock.php (line 218)
```
=> [Areablock] Fix Notice: Undefined index

bundles/AdminBundle/Resources/public/js/pimcore/document/seopanel.js
SEO Document editor does not work because of wrong route definition. Regression of https://github.com/pimcore/pimcore/pull/6146.
=> fix seo panel tree route

lib/Tool/Newsletter.php
Default param value `null` makes no sense.
=> [Newsletter] classId param is required

bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js
"Use current player position as preview" button now is working again
Rearranged small block in video.js (line 202)
Bug can be reproduced on https://demo.pimcore.fun/
Video-thumbnail should be set when clicking on "Use current player position as preview" button.
Nothing happens, but the browser console logs error: 
`TypeError: Cannot read property 'getTime' of undefined`
Upload Video, try to set thumbnail
=> Bug fix: "Use current player position as preview" Button not working

lib/Navigation/Builder.php
I want to use the navigation builder inside a console command but it fails because obviously there's no request available which results in a `There is no master request available.` exception.
The builder actually doesn't need a request if the first parameter (`$activeDocument`) is not `null` because it uses that document to determine which pages are active if it could not be determined from the request.
=> Allow usage of `Pimcore\Navigation\Builder` without request

bundles/AdminBundle/Controller/Admin/AssetController.php, bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Controller/Admin/Document/DocumentController.php, models/Asset/Dao.php, models/DataObject/AbstractObject/Dao.php, models/Document/Dao.php
Sort rows correctly to ensure that access rights for specific document are fully taken into account
Resolves issue #6654 with overlapping roles for the same tree element
With the old select statement and the following setup, this will get false values for checking if a right has to be given or not
2 Roles:
GiveRight  
| cid  | cpath  | userId  | list  | view  | ... |
|---|---|---|---|---|---|
| 2 | /tree-element  | 100  | 1  | 1  | ...  |
DeclineRight  
| cid  | cpath  | userId  | list  | view  | ... |
|---|---|---|---|---|---|
| 2 | /tree-element  | 100  | 0  | 0  | ...  |
=> expected result: the user should be able to list and view the element _/tree-element_, but he won't since:
```
$permissionsParent = $this->db->fetchOne('SELECT `' . $type . '` FROM users_workspaces_document WHERE …
```
=> Correct ACL for overlapping roles

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, models/DataObject/Concrete.php
=> [Data Objects] Fix API-saving unpublished with empty mandatory field throws exception

bundles/AdminBundle/Controller/Admin/AssetController.php
It is not possible to generate the link without a path.
I add the '/' as BaseUri to generate the rigth URI
=> Bugfix Webdav Link Generating

lib/Twig/Extension/PimcoreObjectExtension.php
Needed to retrieve the current site in a Twig template not related to a document and figured it would be useful to add this to the core.
=> Add additional Twig functions for Site model

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
Preview fails for datatypes that don't provide a grid config renderer
=> Gridconfig dialog: renderer should not be mandatory

lib/Http/Request/Resolver/DocumentResolver.php, models/Document/PageSnippet.php, models/Document/Tag.php
Follow up of  #6793
Fixed regression of #6203 and #5905, regarding the document parameter on the view model, which isn't set/updated when view model was created before the document was resolved by the event listener (onKernelController)
=> ViewModel: "document" parameter doesn't get set/updated when view model was initialized before document was resolved 

lib/Extension/Bundle/Traits/PackageVersionTrait.php
The bundle description in the extension list in the Pimcore backend gets fetched from the Bundle classes' `getDescription()` method. This PR uses the description from a bundle's composer.json when its bundle class uses the `PackageVersionTrait`. If someone wants to provide an alternative description in the Pimcore backend compared to the one in the composer.json he can of course override the `getDescription()` method in the bundle class (as before).
=> [Bundles] Use bundle's description from composer.json for extension list

bundles/AdminBundle/Controller/Admin/ElementControllerBase.php, bundles/AdminBundle/Controller/Admin/RecyclebinController.php, models/DataObject/AbstractObject.php
This PR consists of 2 changes:
1. Slight modification of `RecycleBinController::addAction()`: 
Refactored to use `getList()` method which all deletable elements have. And it now also checks for unpublished child elements (in the check if there are more than 100 children).
1. Change of `AbstractObject::delete()`: 
- It first checked for `hasChildren()` and if this was `true` called `getChildren()` - this is redundant because `hasChildren()` does a database query and afterwards we fetch the children via `getChildren()` which needs an additional database query. Currently only `hasChildren()` can reuse the results of `getChildren()` but not vice-versa.
- Currently the dependencies of the deleted element get fetched. This is not necessary as in the next line they get cleared by …
=> Performance enhancements when deleting elements

lib/Bootstrap.php
When implementing app/constants.php access to environment variables may be required, for instance when setting up a connection to S3 based on a docker environment.
This PR recommends to initialize the .env variables before the initialization of the constants take place.
=> Pimcore | Bootstrap | Initialize .env variables before constants init

models/Document/Tag/Relation.php, models/Document/Tag/Relations.php, models/Element/Service.php
While `Pimcore\Model\Document\Tag\Relations` checked for both, `DataObject`s and `Document`s whether to hide unpublished ones, `Pimcore\Model\Document\Tag\Relation` only checked this for `Document`s.
=> Hide all unpublished elements in document relation tags

models/Search/Backend/Data.php, models/Search/Backend/Data/Dao.php
Currently duplicate words are removed in `search_backend_data` datasets. But as search results are ordered by relevance (by default) an object with multiple occurences of the search term should be ranked higher than an object where the search term only occurs once.
=> [Search] Allow duplicate words in search_backend_data

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
This allows you to fetch the current layout id in a custom path formatter. Makes it much easier for example to output a localized based custom path. Editors can switch to a custom layout and see immediately where content is still missing.
=> [Data Object] Add current layout id to context

lib/Sitemap/Document/DocumentTreeGenerator.php
If an empty hardlink is present, the DocumentTreeGenerator will throw an Exception "canBeAdded on null" / "hashChildren on null"
=> Sitemap - Empty Hardlinks causing error

lib/Console/Dumper.php
I wanted to write a Test according to https://symfony.com/doc/4.4/console.html#testing-commands but it fails because Symfony injects a `Symfony\Component\Console\Output\StreamOutput` instance, while Pimcore expects a `Symfony\Component\Console\Output\ConsoleOutput`.
As `ConsoleOutput` is a subclass of `StreamOutput` and all methods that are used in the `Dumper` are actually defined in `StreamOutput` it should be safe to switch the dependencies.
=>  Depend on `StreamOutput` instead of `ConsoleOutput` in `Pimcore\Console\Dumper`

bundles/AdminBundle/Resources/public/css/admin.css
Prevents portrait preview images in the search to overflow and keeps image within the container.
Overflow of image in the search preview
##Additional Info
Example Screenshots: 
Before:
After:
=> adjusts portrait images in the search preview to prevent overflow

lib/Image/Adapter/Imagick.php
Workaround for ImageMagick (e.g. 6.9.10-23) bug, that let's it crash immediately if the tagged colorspace is different from the colorspace of the embedded icc color profile.
=> [Asset] Thumbnail workaround for Imagick in case colorspaces are different

bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
Looks like the pull request #5439 didn't adjust the V7 OrderManager.
Copy / paste 
```
if ($rule = $modification->getRule()) {
$modificationItem->setPricingRuleId($rule->getId());
} else {
$modificationItem->setPricingRuleId(null);
}
```
from `EcommerceFrameworkBundle/OrderManager/OrderManager.php`  to `EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php `
=> Follow-up for #5439: OrderManager\V7 - Save applied pricing Rule ID in the order / OrderPriceModification Fieldcollection

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
Error: CSV DataObject import, tab panel "CSV Settings", button "Reload column configuration" triggered error "Uncaught TypeError: this.callback is undefined" in updateColumnConfig
Caused by: Argument "showReload" was missing in constructor call
Introduced by: 62202949a129c806754f57c15498a60bf753943b
Relates to: Issue #6462
- Create a CSV file
- Start a CSV DataObject import with any random class
- Go to the CSV Settings tab
- Change settings and hit "Reload column configuration"
- Nothing happens, browser console displays: Uncaught TypeError: this.callback is undefined in updateColumnConfig
=> fix: csv dataobject import reload column configuration

models/DataObject/AbstractObject.php, models/DataObject/Concrete.php, models/DataObject/Folder.php, models/Document.php, models/Document/Hardlink.php, models/Document/Hardlink/Wrapper.php, models/Document/Page.php, models/Document/PageSnippet.php
Not sure if this is desired or an oversight (actually, I don't understand the necessity of this parameter at all) but I've noticed that the method's argument is ignored when calling `parent` and instead the value is hardcoded to `true`.
Maybe someone of the core-developers can validate if this behavior is correct (in that cast I think it should be documented!) or if it should be patched by this PR.
=> Remove unused `$isNested` parameter in `delete()` methods of `DataObject`'s and `Document`'s

models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
On the current implementation calling `allowObjectRelation(null)` would throw `Fatal error: Uncaught Error: Call to a member function getClassId() on null`.
=> [Reverse object relation] More defensive check if item is allowed

lib/Console/Dumper.php
In #6839 I already changed the output dependecy from `ConsoleOutput` to `StreamOutput`, but this is not sufficient in all cases, so it should depend on `OutputInterface` instead.
A use case is when running commands programmatically, like this:
```php
function runCommand(Application $application, string $command, array $parameters = []): void
{
$input = new ArrayInput(array_merge(['command' => $command], $parameters));
$output = new BufferedOutput();
if (0 !== $application->run($input, $output)) {
throw new \RuntimeException(sprintf('Error running "%s": %s', $command, $output->fetch()));
}
}
$kernel = ...
$application = new Application($kernel);
$application->setAutoExit(false);
runCommand($application, 'awesome:command', ['-v' => true]);
```
The `BufferedOutput` implements …
=> Depend on `OutputInterface` instead of `StreamOutput` in `Pimcore\Console\Dumper`

lib/Routing/Dynamic/DataObjectRouteHandler.php
If I create a DataObject with UrlSlug and enter the domain relative URL /test there, I expect that I can call this DataObject with http://127.0.0.1/test.
If I have a MultiSite (example1.local and example2.local) and give the DataObject the URL /test at page ID 0, page ID 1 the URL /test1 and page ID 2 the URL /test2. Then I should be able to call both example1.local/test and example2.local/test. /test1 and /test2 only under the respective page
I cannot call anything and the DataObject is not found, whether the data is stored correctly in the database.
Currently the matchRequest function found the page and created an array with page IDs, but it did not evaluate the page. Furthermore the URL was converted to a document page path. This must remain 1:1 and may not be adjusted. So the URL was …
=> fixing matchRequest resolving for dataobjects with urlslug

bundles/CoreBundle/Command/Document/MigrateTagNamingStrategyCommand.php, bundles/CoreBundle/DependencyInjection/Configuration.php, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, lib/Document/Tag/DelegatingTagHandler.php, lib/Document/Tag/NamingStrategy/AbstractNamingStrategy.php, lib/Document/Tag/NamingStrategy/Exception/TagNameException.php, lib/Document/Tag/NamingStrategy/LegacyNamingStrategy.php, lib/Document/Tag/NamingStrategy/Migration/AbstractMigrationStrategy.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/ConflictResolver.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/ConflictResolverInterface.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/AbstractBlock.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/AbstractElement.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Areablock.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Block.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Editable.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/ElementTree.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Exception/BuildEditableException.php, lib/Document/Tag/NamingStrategy/Migration/Analyze/Exception/LogicException.php, lib/Document/Tag/NamingStrategy/Migration/AnalyzeMigrationStrategy.php, lib/Document/Tag/NamingStrategy/Migration/Exception/NameMappingException.php, lib/Document/Tag/NamingStrategy/Migration/MappingError.php, lib/Document/Tag/NamingStrategy/Migration/Render/MigrationSubscriber.php, lib/Document/Tag/NamingStrategy/Migration/RenderMigrationStrategy.php, lib/Document/Tag/NamingStrategy/NamingStrategyInterface.php, lib/Document/Tag/NamingStrategy/NestedNamingStrategy.php, lib/Document/Tag/TagHandler.php, lib/Document/Tag/TagHandlerInterface.php
=> [Document] Deprecate legacy naming scheme of editables as well as the migration tool

lib/Navigation/Renderer/Breadcrumbs.php
I did some minor changes on Breadcrumbs.php
* Return `$this` from the `setTemplate` method.
* Make `getPartial` and `setPartial` real aliases of `getTemplate` and `setTemplate` by actually calling the alias methods.
* Reorder: getters before setters.
=> Update getters/setters in Breadcrumbs.php

lib/Maintenance/Tasks/VersionsCompressTask.php, lib/helper-functions.php
When stream wrappers do not support binary operations, version compression will fail. This is for example the case for Google Cloud Storage and AWS S3, see https://github.com/googleapis/google-cloud-php-storage/blob/9412bf831a3fdd895378203b7e42b782deee8795/src/StreamWrapper.php#L147-L193
To nevertheless support version compressing for such cloud storage providers this PR adopts the suggested way from https://github.com/aws/aws-sdk-php/issues/1576#issuecomment-404446446
=> [Versions] Support version-compressing for stream wrappers which do not support gzopen

lib/Navigation/Renderer/Breadcrumbs.php
I added a public method `getPages` to Breadcrumbs.php which returns an array of all pages between the currently active page and the container's root page. The content of this method is extracted from the `renderTemplate` method. With this new method it's possible to remove an additional template file just to loop through some pages.
=> Add public method to get pages in Breadcrumbs.php

lib/Model/Listing/AbstractListing.php
* Fix collecting parameters which were added to DataObject listing via `$listing->addConditionParam($key, $value, $concatenator)`
Example listing that fails:
```
$listing = new \Pimcore\Model\DataObject\Product\Listing();
$listing->setObjectTypes(['object', 'folder', 'variant']);
$listing->setOrderKey('o_id');
$listing->setOrder('ASC');
$listing->setOffset(0);
$listing->setLimit(25);
$listing->setUnpublished(true);
$listing->addConditionParam('3256 = 3256 AND suppliers LIKE ?', '%,15793,%', 'AND');
$listing->addConditionParam('8665 = 8665 AND manufacturer__id = ? AND manufacturer__type = ?', ['7', 'object'], 'AND');
$listing->load();  // Throws exception
```
```
An exception occurred while executing 'SELECT object_localized_6_en.o_id as o_id, `object_localized_6_en`.`o_type` FROM …
```
=> Fix collecting condition parameters

models/Document/PageSnippet.php
The type of the `$data` parameter in [`Pimcore\Model\Document\Tag\TagInterface::setDataFromEditmode($data)`](https://github.com/pimcore/pimcore/blob/master/models/Document/Tag/TagInterface.php#L53-L60) is `mixed`.
=> Fix PhpDoc type

bundles/InstallBundle/Command/InstallCommand.php, bundles/InstallBundle/Installer.php
Resolves #6638
`./vendor/bin/pimcore-install  --skip-database-config` use this option to skip writing database config (database.yml)
=> [Installer] Added option to skip database connection setup (database.yml)

lib/Document/Adapter/Ghostscript.php
This PR resolves #6911 
It adds the `--permit-file-read` flag with the file's path so that ghostscript is allowed to read the file.
**Note:** I am not sure, if this still works with older Ghostscript versions. I used Ghostscript version 9.52 to test it.
=> Add --permit-file-read flag to ghostscript command.

models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Discovered while saving a lot of objects with no Delations, there were no need to actually load the DB connection when no Relation should be saved anyway.
=> Only get DB if relation is available to save

bundles/CoreBundle/DependencyInjection/Configuration.php, doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md, lib/Image/Adapter/Imagick.php
https://github.com/pimcore/pimcore/issues/5505 introduced auto clipping for images
with embedded clipping path.
This is a pretty wonky feature and often broken through several ImageMagick releases. As well
this is a high cpu intensive task. People should be carful to use it.
hence we make it globaly configurable
follow up on discussion:
https://github.com/pimcore/pimcore/issues/5505
and regression fix
https://github.com/pimcore/pimcore/pull/6949
As mentioned a pretty wonky ImageMagick feature especially if used with Imagick. Several stable ImageMagick releases are broken (again current 7.0.10 release since 8 minor releases) as well some popular 6.9 releases.
The most reliably implementation would be to call convert / imagick over cli. We are doing this over enqueue queues in background if …
=> change[Thumbnails]: make auto clipping configurable

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md
This MR adds some documentation on how to configure MySQL Server for pimcore using a .cnf file. Options listet in the file can also be helpful while setting up a managed mysql service such as AWS RDS.
=> Add example of pimcore.cnf for MySQL

lib/Model/Listing/AbstractListing.php
This PR introduces a deeper variable type casting to prevent sloppy data comparing.
E.g. `value (int)  >= var_char_column (pimcore dropdown data)`.
=> Assert PDO Variable Type Casting

bundles/AdminBundle/Controller/Admin/Document/DocumentController.php, bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php, bundles/AdminBundle/Controller/Admin/Document/EmailController.php, bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php, bundles/AdminBundle/Controller/Admin/Document/PageController.php, bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php, bundles/AdminBundle/Controller/Admin/Document/SnippetController.php, bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
Resolves #6951
Fixes 2 issues:
- Publish icon on Version Tab list
- "This is a newer not published version" Notification on documents.
=> [Document] Fix missing info for only save new version

lib/Navigation/Page.php
Resolves no specific issue. However, I am currently having trouble with performance with the Navigation system. While hunting down the reason for my problems I found some quick micro-optimisations which could be done.
Moving from `spl_object_hash()` to `spl_object_id()` should be faster by [skipping XOR:ing and using integers rather than strings](https://github.com/php/php-src/pull/2611) ([polyfill exists](https://github.com/symfony/polyfill/commit/c3ce3729c1697d865e0ae7ba7af8a289bf672f33)). I could see some memory gains (250kB/request with a large menu).
Using the root namespace (e.g. https://github.com/symfony/symfony/issues/21020) for the `spl` function saved two steps of stack trace for each call when Opcache was active, performance improvements was a few hundreds of a second for the …
=> Micro-optimisation: Change from spl_object_hash() to _id()

models/Document/PageSnippet.php
```
$doc = Document::getById(99);
$doc->setEditable("somekey", "somedata");    // it doesn't check if existing editables are already loaded, so overwrites them ...
$doc->save();
```
=> PageSippet: set/remove editable loses existing elements on save

models/Document/PageSnippet.php
Reverts pimcore/pimcore#6982
needs to be reverted because causes endless recursion.
`getEditables` calls `setEditable`
=> Revert "PageSippet: set/remove editable loses existing elements on save"

models/DataObject/AbstractObject.php
Regression from #6947 and #6945
as discussed external bundles with class override on DataObject\Folder class will still break.
Fix it with explicity checking if class is instanceof Concrete before constructing DataObject class and listing
=> [DataObject] Fix deleting folders with class override

lib/Model/AbstractModel.php, models/Asset.php, models/DataObject/AbstractObject.php, models/Document.php, models/Element/AbstractElement.php
Just to not repeat `getDependencies()` in Asset, Document and AbstractObject class.
=> [Refactoring] Extract getDependencies method to AbstractElement

doc/Development_Documentation/03_Documents/03_Navigation.md
Updated the [breadcrumbs section](https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/03_Documents/03_Navigation.md#breadcrumbs) to include a Twig example that accompanies the PHP example.
=> [Docs] Update 03_Navigation.md

doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md, doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/02_HeadMeta.md, doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/04_HeadStyle.md, doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/05_HeadTitle.md, doc/Development_Documentation/02_MVC/02_Template/04_Thumbnails.md, doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md, doc/Development_Documentation/03_Documents/01_Editables/04_Area.md, doc/Development_Documentation/03_Documents/01_Editables/12_Relation_(Many-To-One).md, doc/Development_Documentation/03_Documents/01_Editables/13_Relations_(Many-To-Many).md, doc/Development_Documentation/03_Documents/01_Editables/14_Image.md, doc/Development_Documentation/03_Documents/01_Editables/16_Input.md, doc/Development_Documentation/03_Documents/01_Editables/18_Link.md, doc/Development_Documentation/03_Documents/01_Editables/22_Multiselect.md, doc/Development_Documentation/03_Documents/01_Editables/24_Numeric.md, doc/Development_Documentation/03_Documents/01_Editables/25_Embed.md, doc/Development_Documentation/03_Documents/01_Editables/26_PDF.md, doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md, doc/Development_Documentation/03_Documents/01_Editables/30_Select.md, doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md, doc/Development_Documentation/03_Documents/01_Editables/34_Table.md, doc/Development_Documentation/03_Documents/01_Editables/36_Textarea.md, doc/Development_Documentation/03_Documents/01_Editables/38_Video.md, doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md, doc/Development_Documentation/03_Documents/01_Editables/README.md, doc/Development_Documentation/03_Documents/03_Navigation.md, doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/45_Image_Types.md, doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md
In some places, the code examples, when given in Twig & PHP, are already displayed in tabs, like here: 
https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Block.html#page_Using-Manual-Mode
But in other places, they're just displayed below each other, like here: 
https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Video.html#page_Basic-Usage-a-Local-Asset
This PR tries to align it, so that all examples existing in both languages are displayed in tabs.
=> [Docs] Display all code examples with two languages (php & twig) in tabs

bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php, bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, bundles/AdminBundle/Controller/Admin/MiscController.php, bundles/AdminBundle/Controller/Admin/WorkflowController.php, bundles/AdminBundle/Controller/Reports/CustomReportController.php, bundles/CoreBundle/EventListener/WorkflowManagementListener.php, bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectCategory.php, bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php, bundles/EcommerceFrameworkBundle/Tracking/TrackingManager.php, bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php, bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php, bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php, bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php, lib/DataObject/GridColumnConfig/Operator/DateFormatter.php, lib/Db/PhpArrayFileTable.php, lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php, lib/DependencyInjection/ConfigMerger.php, lib/Mail.php, lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php, models/Tool/CustomReport/Adapter/Analytics.php
Some functions in PHP have aliases. For consistency in the codebase, these should be avoided.
=> Avoid function aliases

models/Asset/Video/ImageThumbnail.php
image thumbnails for videos should be created the same way ordinary image thumbnails are. 
Thumbnails will be generated according to the thumbnail config format 
Thumbnails are created with the png format in case of "source"-format (=Auto). See [Video-ImageThumbnail](https://github.com/pimcore/pimcore/blame/master/models/Asset/Video/ImageThumbnail.php#L199)
This PR changes the behaviour to match the image - thumbnail logic (see [Image-Thumbnail](https://github.com/pimcore/pimcore/blob/master/models/Asset/Image/Thumbnail.php#L467))
=> video image-thumbnails should be delivered web-optimized

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
The part referenced in the update guide is at the very bottom of the linked page, thus I added an anchor do jump right to this part.
=> Add fragment identifier to jump to the right part of the page

bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js, bundles/AdminBundle/Resources/public/js/pimcore/report/custom/toolbarenricher.js
The report name and group only translated in the left menu of the report page.
=> Report niceName/group not translateable in Panel Title and Menu

models/User/AbstractUser.php
PHPStan classify `$role = User\Role::create($options);` as AbstractUser now. Should be Role.
=> AbstractUser: Fix return PHPdoc

bundles/CoreBundle/Migrations/Version20200902111642.php, bundles/InstallBundle/Resources/install.sql
Resolves #
This fixes the problem when you have complex workflows with too many parallel places.
255 characters is not enough to create complex workflows, hence the field is updated to text
When you have more then a few places in your workflow you run out of characters in the database table.
for instance 
translation_english_done,translation_spanish_done, etc. etc.
This results in the final string being cut off and breaking the workflows. You then have to enter the database and reset the field manually. Changing this to a text instead of varchar makes sure you can create much more complex workflows.
=> Increase the number of characters for workflow places

bundles/CoreBundle/Migrations/Version20200828091305.php, bundles/InstallBundle/Resources/install.sql, lib/Maintenance/Tasks/LogArchiveTask.php
I prepared this PR, and then I remembered that it had [no effect on storage](https://dev.mysql.com/doc/refman/5.7/en/integer-types.html)/memory or anything like that, it's just a display value as long as it is a `tinyint`, oh well, do what you like with it, at least now it's consistent for all boolean-type columns :)
=> Migrates tables from tinyint(4) to tinyint(1) for boolean-type content

doc/Development_Documentation/02_MVC/02_Template/README.md, lib/Controller/Config/ControllerDataProvider.php
[Using Symfony's location](https://symfony.com/doc/current/templates.html#template-location) `templates` for templates already work fine, but they never show up when selecting a template for a document, this resolves that problem.
=> Symfony templates location

doc/Development_Documentation/07_Workflow_Management/README.md
Fixed typo in documentation for Pimcore Notifications. In code Constant is pimcore_notification.
=> [DOC] Fixed channelType in Workflow configuration

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Hi, I would like to discuss and improve the performance of batch processes and exports. I think it would be best if we discuss this using examples, that's why it is a PR not an issue.
In this PR I found two places that influence performance:
- size of the chunks that are being exported in a single request - currently set to 20, I've raised it to 100, gaining great general performance boost with the cost of longer requests
- the delay between requests - I reduced it from 400 to 50ms. I guess its purpose is to not overload backend or frontend of the application but in most cases, it is the main factor of the processing time.
Bigger chunks in export.
Lower the delay between batch processes.
- implement working in chunks in batch processing, similar to the export
- work on the list of ids in …
=> Batch processes performance

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/panel.js
Currently when you click `Search` on the user panel the input field (actually it is a combo box) does not get auto-focussed because the `afterrender` event fires too early.
=> [Users] Fix auto-focus on user search

lib/Document/Adapter/Ghostscript.php
Currently the code compares versions with floats:
```php
if ($this->getVersion() >= 9.50) {
```
This works as long as there won't be a version 9.100 - for sure this is more of a hypothetical case but in my experience comparing versions is not as trivial as a numerical comparison.
=> [Ghostscript] Use version_compare to compare ghostscript versions

models/Asset/Image/Thumbnail/Processor.php
The image optimize pipeline only works if format is set to "source".
I don't understand why that is.
However, even with format set as "source" the image optimization is _not_ triggered if an image url is directly requested for the first time.
E.g. requesting `/content/hero-slider/2020/09/image-thumb__52057__hero-slider-image/hero-slider-image-1.png` will pass through `Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::thumbnailAction()`.
Now if the format is set to "source" this action will adjust the thumbnail config to set the format to the file extension.
Which then leads `\Pimcore\Model\Asset\Image\Thumbnail\Processor::process()` to never enable `$contentOptimizedFormat`  because of this condition `if ($format == 'source' || empty($format)) {`.
Format is never empty or …
=> Image Optimization "dead lock"

lib/Event/Model/NotificationEvent.php, lib/Event/Model/TranslationEvent.php
Actually `ElementEventInterface` is designed to be used by Element events, must be a copy & paste leftover I guess.
=> Deprecated getElement() method on NotificationEvent and TranslationEvent

bundles/AdminBundle/Resources/public/js/pimcore/document/document.js, bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js, bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
We're validating documents (and their editables) on the server-side when publishing them and throw a `ValidationException` when they're not in a valid state.
The moment I click on the "Save & Publish" button, the buttons in the admin UI changes: the "Save" button disappears and the "Unpublish" button appears, etc.
But if now the exception is thrown, the document is not saved and the buttons display a wrong state. 
This PR tries to fix this.
=> Change admin UI state only when (un)publishing documents succeeds

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
Caused by case sensitive check while field name is changed to lower case in the isValid() check.
Fixed by converting all forbidden names to lower case.
To reproduce: add the field 'parentid', 'parentId', 'parentID' or 'pArEnTiD' to a class (you get the idea). It's all allowed.
Relates to https://github.com/pimcore/pimcore/issues/2677
=> fix: forbidden names can be added to class

models/DataObject/Traits/DefaultValueTrait.php
DefaultValueTrait::handleDefaultValue() determines the parent's value
and decides whether or not to use the default value. This worked for
the first child (1st level of inheritance) but not for the next child
(2nd level), as GetInheritedValues is disabled in save() context.
The result is unwanted persisting of the default value to store table
for the 2nd child as thus effectively breaking inheritance.
```
* object
|-- variant 1: OK
|-- variant 2: NOT OK
|-- variant 3: OK
|-- variant 4: NOT OK
...
```
This fix enables inheritance while determining the value from the parent
and thus make the right decision whether to use the default or not.
1) Create a data object class with fields supporting default values (e.g. input) and set a default value
2) Run this code
```php
<?php
namespace …
```
=> [DataObject][Inheritance] Fix inheritance when using default values

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Currently it is possible that a user with the permission "save" can unpublish or publish an object even though the user explicitly has no permission to do so. 
When right-clicking in the tree, the options "publish" and "unpublish" may not appear, but the user could currently unpublish a DataObject with the following (exemplary) cURL request:
```
curl 'http://localhost:1337/admin/object/save?task=unpublish' \
-X 'PUT' \
-H 'Connection: keep-alive' \
-H 'Pragma: no-cache' \
-H 'Cache-Control: no-cache' \
-H 'X-Requested-With: XMLHttpRequest' \
-H 'X-pimcore-csrf-token: TOKEN' \
-H 'User-Agent: an agent' \
-H 'DNT: 1' \
-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
-H 'Accept: */*' \
-H 'Origin: http://localhost:1337' \
-H 'Sec-Fetch-Site: same-origin' \
-H …
```
=> [Data Object] unpublish-publish-permission-fix

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php, bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.php
Closes #7098 
Not sure if this is ok with " \Pimcore\Model\Translation\Admin::getByKeyLocalized" but " $this->translate" is only for the shared translations.
=> Added translation support in the version tab of the data objects

models/DataObject/ClassDefinition/Data/QuantityValue.php
This PR fixes two things:
1. Make zero (0) a legitimate value.
2. Doesn't enforce value zero (0) when a default unit is configured for the QuantityValue field.
=> [DataObject][QuantityValue] Fixes for zero value, default unit (and inheritance)

bundles/AdminBundle/Resources/public/js/pimcore/object/class.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js, bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js, bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollection.js, bundles/AdminBundle/Resources/public/js/pimcore/object/objectbrick.js
Because of #7082 I took a deeper look at the forbidden names checks in the admin backend. 
Here are some fixes/improvements:
- consistent naming: forbiddennames → forbiddenNames
- consistent definition as class fields instead of locale variables in functions
- consistently check via `in_arrayi` instead of `in_array` (so it doesn't matter if someone adds them in mixed case again)
- use `regex.test(string)` instead of `string.match(regex) == string`
=> Improve forbidden names checks

models/Asset/Image.php
As https://github.com/pimcore/pimcore/blob/5dba19710d71e7843d19d2fed8e82feec022c348/lib/Image/Adapter/Imagick.php#L71-L76 correctly says Imagick does not support stream wrappers. The `LowQualityImagePreviewTask` does currently not handle this. 
This is especially necessary when `PIMCORE_TEMPORARY_DIRECTORY` uses a stream wrapper.
=> Support stream wrappers in LowQualityImagePreviewTask

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, models/DataObject/AbstractObject.php
When programmatically creating an object and its variants then setting the variants via `setChildren($variants)` will result in unexpected behaviour when trying to call `getChildren([AbstractObject::OBJECT_TYPE_VARIANT])`, if the object/variants is/are never saved.
Whenever the method `setChildren` is called, I'd expect it to return the same children when calling `getChildren`.
When calling `getChildren([AbstractObject::OBJECT_TYPE_VARIANT])`, the returned array is empty.
```php
$product = new Product();
$product->setChildren($variants);
p_r($product->getChildren([AbstractObject::OBJECT_TYPE_VARIANT]));
```
Setting the children works differently than getting the children when it comes to building the cache key.
In the method `getChildren` one automatically defines the cache key with the …
=> Fixed: programmatically setting children of type "variant" will not be loaded when calling getChildren([AbstractObject::OBJECT_TYPE_VARIANT])

models/DataObject/ClassDefinition/Data/Localizedfields.php, models/DataObject/Concrete.php
This pull request fixes and improves very incomplete display of validation messages when saving Data Objects. The fix will improve validation messages of Localized Fields and Field collections. The context is also added so it now can be recognised in which language and which Field-Collection-Entry the field is incomplete. 
Before:
After:
Above messages are based on this empty form:
The example message above might seem too complex, but this is because a huge amount of fields was on purpose left empty for demonstration purposes.
=> Improve the verbosity of validation messages

lib/Navigation/Builder.php
#5747 added the possibility to limit the navigation depth, but misses passing the `$maxDepth` value in the recursive call.
Thus, it only works if `$maxDepth` is `1` (when the method is called directly). After that, in the recursive calls, `$maxDepth` is always `null` which means it will never trigger.
=> [Document] Navigation: Add missing argument to recursive method call

models/Document/Hardlink/Wrapper/Email.php
In my opinion this class should extend the email document class, as all the other wrapper classes extend their own base document class too.
The current state causes errors if you want to call an email document via hardlinks. The problem is that "isDirectRouteDocument()" will always return false because it doesn't extend the PageSnippet class (pimcore/lib/Routing/Dynamic/DocumentRouteHandler.php:361).
Because of that the route never gets assigned the _controller attribute and therefore the page can't be rendered in the frontend and throws the following error:
=> Extend correct document class in email hardlink wrapper

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Changes:
Add "Permissions-Policy" alongside "Feature-Policy" to http headers.
Fixed a small typo in documentation.
--
Roundabout 2 weeks ago the W3C formally acknowledged the shift from Feature-Policy to Permissions-Policy. 
They are, metaphorically speaking, the same shoe from a different manufacture. However, eventually they will entirely replace them.
To ensure we have similar (same) configuration here, we basically copied the settings we already have to the new standard.
=> Add Permissions-Policy alongside Feature-Policy for nginx configuration

bundles/AdminBundle/Controller/Admin/External/AdminerController.php
When cookie expiration is set in http headers e.g. "Set-Cookie: PHPSESSID=***; expires=Wed, 24-Sep-2021 08:20:14 GMT; Max-Age=31536000; path=/; HttpOnly" then it is merged here -> https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/External/AdminerController.php#L160 but not properly because of the ":" in the time of the expire param.
=> [Adminer] Fix http headers generation when cookie expiry is present

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
fixes #7168  
`fillupPreparationQueue` got moved, so that children are updated nevertheless if parent is in index or not
=> fixed [Ecommerce][Productindex] elasticsearch preparation queue children do not update if parent is not in index

lib/Targeting/Condition/Browser.php
When defining a global targeting rule, you can choose to target Internet Explorer using the "Browser" condition. The corresponding rule is defined in `lib/Targeting/Debug/Form/DeviceType.php` as follows:
```php
$builder->add('browser', ChoiceType::class, [
'label' => 'Browser',
'required' => false,
'choices' => [
'Internet Explorer' => 'ie',
'Firefox' => 'firefox',
'Google Chrome' => 'chrome',
'Safari' => 'safari',
'Opera' => 'opera',
],
]);
```
Thus when you choose "Internet Explorer" the value `ie` is persisted into the database.
However, when device detection happens in `lib/Targeting/DataProvider/Device.php`, any Internet Explorer user agent is resolved to `Internet Explorer`. When the condition is checked in `lib/Targeting/Condition/Browser.php`, the string `ie` (stored in …
=> [Targeting] Check for Internet Explorer uses wrong value

bundles/AdminBundle/Controller/Admin/Document/PageController.php, bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
Resolves #6673
- Client side: Resets the required editable prompt for a document, if settings are changed.
- Server side: Document is rechecked for missing required editables, if settings are changed.
=> [Documents] Fix Can't change to a template with a required editable

lib/Maintenance/Executor.php
Fixes exception "getData() on null" inside getLastExecution()
Regression of #7223
=> [Maintenance] getLastExecution() should check if TmpStore item exists

.travis.yml, composer.json
Just uncommented the jobs in `.travis.yml` because we can reuse them for 5.0
=> Removed Symonfy 3.4 from composer.json an Travis jobs

models/Asset.php, models/DataObject/Concrete.php, models/Document/Hardlink.php, models/Document/Link.php, models/Document/PageSnippet.php, models/Element/AbstractElement.php
This improves performance a bit by not calling `array_merge` inside loops (which was already done in `Pimcore\Model\Element\AbstractElement` and `Pimcore\Model\DataObject\Concrete'`) and pulling a container fetch outside a loop. Also, there's some general code cleanup.
=> Improve `Element::resolveDependencies()` implementations

composer.json
Set fixed constraint to `"symfony/monolog-bundle": "3.5.0"` 
Seems to be only an issue with Symfony 3.4
=> Fixed Monolog Bundle incompatibility cased by 3.6.0 release of symfony/monolog-bundle

composer.json
Only the `v3.6.0` is incompatible, so only this one should be prevented from being installed.
Followup of: #7255
=> [Followup] Fixed Monolog Bundle incompatibility caused by 3.6.0 release of symfony/monolog-bundle

lib/Bootstrap.php
In https://github.com/pimcore/pimcore/blob/1430b30519dd28af41c938944eb431ae2593e01c/lib/Bootstrap.php#L76 it is tried to change directory to current working directory. This can be a problem when user `abc` calls a command with `sudo -u xyz bin/console command:name` when user `xyz` does not have access to the directory from which the script was called (e.g. user `abc`'s home folder).
=> Only go to current working directory if it is accessible

models/DataObject/Localizedfield/Dao.php, tests/Model/LazyLoading/AdvancedManyToManyObjectRelationTest.php, tests/Model/LazyLoading/AdvancedManyToManyRelationTest.php, tests/Model/LazyLoading/ManyToManyObjectRelationTest.php, tests/Model/LazyLoading/ManyToManyRelationTest.php, tests/Model/LazyLoading/ManyToOneRelationTest.php
=> Untouched relations get lost when contained in localizes fields in object bricks on save

lib/Maintenance/Executor.php
`$lock->isAquired` respects only aquired locks from the SAME process.
This will never happen. Like the maintenance task is ment it should check over
all running proccesses (tasks) if a lock with the process name exists and skip
See as well Symfony docs:
We run on several instances the maintenance task every 5 Minutes in parallel overlapping mode......means if the maintenance task is still not finished (for whatever reason...image optimisation etc) 5 minutes later cron is starting the next maintenance task process. To avoid conflicts it should skip the task already running in another process
=> [Maintenance] fix parallel execution of maintenance tasks

bundles/AdminBundle/Controller/Admin/AssetController.php, models/Asset.php
The public url displayed in the admin backend of pimcore always displays an url, with the hostname of the Pimcore application as a base. 
If you use AWS S3 or AWS Cloudfront for example, the public url should be the specific url of the used system.
This PR generates the public url of an asset via the asset events. 
If the url does not include http (no public url) it will prepend the hostname of the Pimcore application.
=> generate public url through asset listeners

bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
The Order Details Tab for the ecommerce backoffice detail view has stricter access check than the actual detail page.
It doesn't seem to be related to `bundle_ecommerce_pricing_rules` but there was an access check for that in place - re-organized.
Maybe the proper base for https://github.com/pimcore/pimcore/pull/7389
=> Order Details Tab - fix inconsistent permission check

lib/Maintenance/Executor.php
TmpStore does not get updated till default expiration time of 7 days (86400 * 7).
Just use TmpStore::set instead of TmpStore:add to always update the maintenance entry as soon
it is executed.
fixes #7347
=> [Maintenance] fix not updating TmpStore on executing maintenance task

bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js, bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
Currently there is an error when trying to import a brick definition via a JSON file. After uploading the file, the panel just disappears, JS console shows an error - and the complete Pimcore backend is not usable anymore. You have to reload the backend but as it was not possible to save the imported object brick definition, you are not being able to import the brick definition at all.
To be honest, I did not check what actually happens in the changed code, I just copied the code from https://github.com/pimcore/pimcore/blob/7f802ce45eef4b43da2468b2a622b23c2cb6f41a/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js#L169-L171
PS: I used base branch 6.8 as this is clearly a bugfix. If I shall use master, please comment.
=> [DataObject] ObjectBrick/FieldCollection - Fix error when importing json definition

lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
Resolves #7353 
Non exportable fields inside field-collections and object bricks should be skipped in Xliff Export.
=> [XLIFF Export] Fix exporting localizedfields inside fieldcollections and objectbricks

bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
`GoogleTagManager::formatPrice()` accepts and defaults to NULL for `$price`. But `Decimal::fromNumeric($price)` wont work with that and throw a `\InvalidArgumentException`.
Add a check to be compatible with the method signature - similar to the code handling in `EnhancedEcommerce::transformProductImpression()`
=> Make "GoogleTagManager::formatPrice()" compatible with its default value

doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md, lib/Console/AbstractCommand.php
This PR adds all default formats of Symfonys OutputFormatter to AbstractCommand.
The AbstractCommand currently only supports `error`. With this PR `info`, `comment` and `question` will be added.
=> Add all default formats of Symfonys OutputFormatter to AbstractCommand

models/User/Permission/Definition/Dao.php
Currently the code 
```php
$permission = \Pimcore\Model\User\Permission\Definition::create('my_permission');
$permission->setCategory('my category');
$permission->save();
```
does result in a permission `my_permission` but without category `my category`. This PR changes that by allowing to set a permission category after creating it.
=> [Permissions] Allow setting permission category after creating it

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js, bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
Currently permissions are not sorted at all, making it difficult to find a certain one (especially if there are some plugin- / project-specific ones added or if the current user's language is not english):
This PR sorts permissions based on their (translated) labels.
Resolves #7245
=> [Roles] Sort permissions by label

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Currently in object edit mode you can only select 1 referenced item for a relational field at the same time. This PR adds multi-select. This is for example useful when you want to move multiple objects via drag & drop. Multiple items can be selected via Shift or Ctrl key + mouseclick.
=> [Data Objects] Support selecting multiple items for relational fields

doc/Development_Documentation/02_MVC/02_Template/00_Twig.md, lib/Twig/Extension/PimcoreObjectExtension.php
Currently there are only twig helpers to get elements by id: pimcore_document, pimcore_asset, pimcore_object. This can be a problem when you transmit data between Pimcore systems because then Ids may change. For this use case this PR introduces helpers to get elements by path: pimcore_document_by_path, pimcore_asset_by_path, pimcore_object_by_path
Also they are better understandable as `pimcore_object_by_path("/path/to/special/category")` is more expressive than `pimcore_object(123)`.
=> [Twig] Add template helpers to get elements by path

bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php, composer.json, models/DataObject/ClassDefinition/Data/Country.php, models/DataObject/ClassDefinition/Data/Countrymultiselect.php, models/DataObject/ClassDefinition/Data/Gender.php, models/DataObject/ClassDefinition/Data/Language.php, models/DataObject/ClassDefinition/Data/Languagemultiselect.php, models/DataObject/ClassDefinition/Data/Multiselect.php, models/DataObject/ClassDefinition/Data/Select.php, models/DataObject/ClassDefinition/Data/TargetGroup.php, models/DataObject/ClassDefinition/Data/TargetGroupMultiselect.php, models/DataObject/ClassDefinition/Data/User.php, models/DataObject/ClassDefinition/Service.php
When you use option provider for selects or the User/Language select data type you have all options in the export.
But these a unnecessary and can create git diffs/conflicts.
=> [DataObject] Class Export: Remove Dynamic Options from Select data types

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, models/DataObject/Listing/Concrete/Dao.php, models/DataObject/Localizedfield/Dao.php, models/DataObject/Service.php
1. Create class `Test` with `object brick` field `bricks`
2. Create object brick `testbrick` with an input field `testfield`
3. Create object `A` in `Home` folder (tree root)
4. Open `Home` in grid view
5. Edit table configuration and add field `testfield` of brick `testbrick`
6. Save configuration under `My configuration`
7. Delete object brick `testbrick`
8. Reload grid for `Home` folder
9. Try to open previously saved table configuration `My configuration` -> results in error `Call to a member function getFieldDefinition() on null`
This PR fixes that. If the brick of a field in the saved table configuration does not exist anymore, this field will be skipped when generating the table.
=> [Grid config] Error when opening saved configuration which contains fields of deleted object brick

models/Asset/Dao.php
Remove strlen > 0 condition to allow saving of empty values. Allow unchecked checkboxes.
Co-Authored by @dpfahlbusch 
Resolves #6332
=> [Asset] Allow empty asset metadata

lib/Translation/Translator.php
Resulting in Pimcore in an error that the cache is using invalid characters. I think we should allow any character here, since symfony does too
=> sylius/theme-bundle allows translations per theme, by that it adds the theme-name to the locale with @

bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/customreports.js
Like in https://github.com/pimcore/pimcore/blob/12900c5c22d5cde7284295ba155f9a23dce8ba99/bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js#L71-L75 this PR sets flex width for columns, which do not have a width being explicitly set, to use the full availyble width of the portlet.
=> [Dashboard] Set flex=1 for columns without specified width for custom report portlet

lib/Image/Adapter/Imagick.php
When there is a clipping path embedded in a JPG it is tried to clip the image by this path. When this goes wrong for whatever reason, you get an error with the default placeholder image. 
The reason in our case was that ImageMagick did not support SVG: `ImagickException: no decode delegate for this image format "SVG"`
This PR adds a fallback that if clipping goes wrong for whatever reason, then the unclipped image will get delivered.
This is especially useful because `clip_auto_support` is enabled by default and when upgrading Pimcore versions some image thumbnails might suddenly break.
=> [Thumbnails] Fallback if clipping by embedded clipping path does not work

bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
Identical to #7370 but with the author email corrected so that the CLA can be approved.
Pull #6146 introduced an issue that causes editmode to break in the admin if you are using asset versioning. A file path is generated using `$this->package->getUrl()` which also includes asset versioning (if used) in the path, and since the file is fetched with `file_get_contents()` at one point, this fails because `file_get_contents()` does not understand the query param appended to the path.
Add this to your `app/config/config.yml` file and load a document in editmode.
```
framework:
assets:
version: 'xxx'
```
You should get an error from file_get_contents() failing to read from a path like this:
`/var/www/html/web/bundles/fosjsrouting/js/router.js?23471` <-- see query param
Using a relative path …
=> Correct file path to fosjsrouting router.js

bundles/AdminBundle/Controller/Admin/MiscController.php
Sorts Actions, Bundles, Controllers, Templates better. The previous `sort()` method was triggered on a nested array and did not actually work. Also adds flag to sort naturally case insensitive.
Previously:
```
Areas/templage.twig
Documents/template.twig
bundles/template.twig
```
Now:
```
Areas/templage.twig
bundles/template.twig
Documents/template.twig
```
=> Fixes/improvements to sort in MiscController

bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js, bundles/CoreBundle/DependencyInjection/Configuration.php, doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
This PR enables the configuration of numeric fields in Pimcore workflow notes.
Screenshot:
Example configuration:
```yml
pimcore:
workflows:       
production_workflow:
...
transitions:
...
notes:
commentEnabled: true
commentRequired: true
commentSetterFn: setRejectReason
additionalFields:
- name: 'trackedHours'
title: 'Totally tracked hours'
fieldType: "numeric" #todo -> PR for numeric fields
fieldTypeSettings:
minValue: 0
```
=> Support numeric fields in workflow notes.

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
It seems that quoting the null value to insert into preparation_worker_id `$data['preparation_worker_id'] = $this->db->quote(null);` leads to the value stored being `''`. This means preparation_worker_id is not empty which will prevent the processor from picking up the entry!
=> Quoting null value when for preparation_worker_id leads to '' being the value

lib/Cache/Core/CoreHandler.php
Additional error message is not necessary, all messages are logged in storeCacheItem(). Not every return=false is an error, in this case we get a false negative.
=> [Cache/Core] No error message if storeCacheItem() returns false

lib/Helper/Mail.php
Resolves a bug where rfc2822 3.6.2 did not validate on re-sending email from the admin log due to:
https://github.com/pimcore/pimcore/blob/cf90256bcbd3dc55b7ad49159c26575d524c966e/lib/Helper/Mail.php#L408-L436
and Swiftmailer:
https://github.com/swiftmailer/swiftmailer/blob/f7d2961c858520dc83a594c66cde9d550f6d2226/lib/classes/Swift/Mime/Headers/MailboxHeader.php#L345-L357
Pimcore would prior to this patch save the email in the Mail Log in the format `address@domain.ext (Name)` but it would then fail.
=> Fix formatDebugReceivers for rfc2822 3.6.2 validation

composer.json
Piwik changed its name to Matomo some time ago and the package got a new name, too. The old one is abandoned.
=> Require `matomo/device-detector` instead of `piwik/device-detector`

models/DataObject/ClassDefinition/Data/Objectbricks.php
At our customer's system there was the problem that a data object could not be opened anymore in Pimcore backend because its object brick container contained an object brick which had been removed since last saving. I do not know exactly how the brick got deleted, I cannot reproduce the problem in the Pimcore demo. But nevertheless I think it is a good idea to check if the called dynamic method exists.
=> [Data objects] Do not try to load deleted object bricks

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
I get following error if I load a object grid with error reporting E_ALL:
=> Fix Notice: Undefined index: locked

models/DataObject/Objectbrick/Definition.php
https://github.com/coreshop/CoreShop/pull/1511/checks?check_run_id=1392926768#step:15:205
```Notice: Undefined index: BehatBrickTest5fadaeefb140b in vendor/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php line 620```
=> Fix undefined index error

lib/helper-functions.php
Allows attributes such as `data-*`, `contenteditable`, `required`, or `autofocus` now which may be used without any value by using the attribute name as key and `null` as the value.
=> Fixes array_to_html_attribute_string to allow value-less attributes

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js, bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Resolves #7423
Numeric grid filters now have the same `decimalPrecision` as in the class definition. Previously it defaulted to 2.
=> Numeric filter fix

models/Element/Note.php
Since the other methods on `Note` support chaining, it would be nice if `addData()` did too, so you could do stuff like this:
```php
(new Note())
->setElement($product)
->setType('notice')
->setTitle('Text')
->addData('originalPath', 'text', $oldPath)
->save();
```
Not completely sure if this should be considered a bugfix or an improvement though :) An improvement I think, but let me know if I should rebase it against 6.9.
=> Make Note->addData() chainable

bundles/AdminBundle/Controller/Admin/LogController.php
Currently stream wrappers are not supported when using a `Pimcore\Log\FileObject` together with stream wrappers in constant `PIMCORE_LOG_FILEOBJECT_DIRECTORY`. This PR solves that.
=> [Application Logger] Support opening FileObject when using stream wrappers in PIMCORE_LOG_FILEOBJECT_DIRECTORY

bundles/EcommerceFrameworkBundle/Model/ProductInterface.php
Is used very often. For example:
https://github.com/pimcore/pimcore/blob/b926dc320b5ccda17e20665303ca239404a3d821/bundles/EcommerceFrameworkBundle/Model/AbstractSetProductEntry.php#L82
=> Add getId method to ProductInterface

bundles/AdminBundle/Controller/Admin/Document/DocumentController.php, bundles/AdminBundle/Controller/Admin/Document/PageController.php, bundles/AdminBundle/Resources/public/js/pimcore/document/pages/preview.js, doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md, doc/Development_Documentation/22_Administration_of_Pimcore/07_Users_and_Roles.md
QR-Codes were removed in #7262 but there was still some code left.
The Document preview panel has a "QR-Codes" button that's now broken because the route doesn't exist anymore, as its controller has been removed.
Note: there's a translation with the key `qr_codes` left, that doesn't seem to be used anywhere. Not sure if it should be deleted, too (and if so, in which translation files - only English or all?)
=> Remove leftover QR-Code parts

bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
Currently you can open the "Sent emails" panel multiple times when clicking Tools > Email > Sent Emails in the main menu. This PR fixes this.
=> [Sent emails] Prevent multiple open panels

bundles/AdminBundle/Helper/GridHelperService.php
The problem appears when apply search in data objects grid, where objects that don't match the search could be found
if there are documents or assets with the same id which match the search
The following steps were performed on the current demo.
1. Open Product Data/Cars folder & search "fiat"
2. The selected items don't match the search but there are documents/assets with the same id which match the search
=> [Data objects Grid] Fix search

bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js, bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
Currently in the grid view the columns have fixed width which can get overridden by setting the width in the field definitions. But this fixed width is not optimal in most situations and leads to a lot of the columns being cropped - in this simple case ID and path are truncated:
This PR changes this behaviour by automatically adjusting the column width depending on the contents which are currently shown. Of course the widths can still be overridden in the field definitions. Without any other changes the grid from above screenshot now looks like this:
Of course this might lead to very big columns for text fields but imho it is still a better default setting than to truncate nearly all columns and nevertheless waste much space to the right.
=> [Grid] Auto-adjust column width depending on currently shown content

lib/Translation/Translator.php
Steps to reproduce the bug:
1. Setup two languages, one the fallback of the other (i.e. de and de_at, de is fallback for de_AT)
2. Now create a translation for de_AT with a placeholder i.e. cart.incl-vat --> "Taxrate is %percent%%", where %percent% is the placeholder which should be replaced.
3. The output will be "Taxrate is %percent%%" and thus the parameters won't be replaced.
4. On second call the translation will be right, the output is i.e. "Taxrate is 20%"
With this PR this behaviour gets fixed and the parameters are already replaced at the very first call.
=> Consider parameters in fallback translations

bundles/AdminBundle/Controller/Admin/TagsController.php
When tags are uppercase, when i search on tags filter section, i don't find nothing.
=> Tags filter not works if tags are uppercase

bundles/AdminBundle/Controller/Admin/TagsController.php
This is a fixup for #7610 
Like I said in that branch, I would not rely on the input and call `strtolower` nonetheless.
=> Fixup: tags filter not works if tags are uppercase

bundles/AdminBundle/Controller/Admin/Document/PageController.php
If you open a document, switch to the "settings" tab and then try to publish or unpublish the document, the new status is not applied.
If you switch to the tab "settings", all settings - including the current published/unpublished status - are transferred to the controller, which overwrites the new desired status.
Set the new status after all other settings are set.
=> Fix: Change the published state, regardless of the previous settings.

.travis.yml, composer.json
Active support for PHP 7.3 will end in 4 days: https://www.php.net/supported-versions.php
=> Removed PHP 7.3 support

lib/Document/Editable/EditableHandler.php
After upgrade from 6.7.* to 6.8.* all areabrick names are not translated anymore.
We use translation keys as names. so this is a blocker :(
=> Areabrick names are not translated

composer.json, doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md, lib/Mail.php
=> Replace html2text/html2text with soundasleep/html2text and removed deprecated methods from Mail

bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php, bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php, bundles/EcommerceFrameworkBundle/Model/AbstractOrderItem.php, bundles/EcommerceFrameworkBundle/Model/AbstractProduct.php, bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php, bundles/EcommerceFrameworkBundle/OfferTool/AbstractOfferToolProduct.php, bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php, bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php, bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php, bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php, phpstan-baseline.neon
Add following methods:
- AbstractOrder::getCartHash()
- AbstractOrderItem::getComment()
- AbstractOrderItem::setComment()
Removed unused methods:
- AbstractOrder::getDeliveryEMail()
- AbstractOrder::setDeliveryEMail()
- AbstractOrder::getCartModificationTimestamp()
=> Make AbstractOrder/AbstractOrderItem methods abstract and add missing methods

bundles/EcommerceFrameworkBundle/FilterService/FilterService.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectCategory.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectClassificationStoreAttributes.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/MultiSelect.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/MultiSelectRelation.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRange.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRangeSelection.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/SelectCategory.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/SelectRelation.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Input.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelect.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectCategory.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectFromMultiSelect.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectRelation.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRange.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRangeSelection.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/Select.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectCategory.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectFromMultiSelect.php, bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectRelation.php, doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/02_Filter_Nested_Documents.md, doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, phpstan-baseline.neon
This PR splits filter value generation and rendering into two methods.
This removes code duplication (the rendering calls are always the same) and improves extensibility, because when creating a REST API you need the raw filter values to send them as e.g. JSON to the frontend where they can be rendered by some JavaScript framework.
This is a breaking change, because it introduces a new abstract method: `Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\AbstractFilterType::getFilterValues()`
---
@m0nken you may like this
=> [Ecommerce][FilterService] Improve extensibility of filter types

doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
This is a followup to #4372
In the regex for static file serving in the nginx config the `(?!/admin/asset/webdav/)(?!/admin)` part is redundant, because when the path may not start with `/admin`, it may not start with `/admin/asset/webdav/` either, no need to specify this explicitly again.
=> Simplify regex for static files in nginx config

lib/Navigation/Builder.php
This code was improved by #7487 a bit, but we can do a little better.
Actually, if `$activeDocument` isn't an instance of `Document`, we don't even need to try building the trail, because `$activeTrail` would always be false anyways.
=> [Navigation] Improve active trail fallback code

bin/pimcore-install
This PR enables adding logic to the startup process also on fresh installation, which it should do according to the  documentation:
[Getting Started/Configuration](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Configuration.html): 
> If you need to execute code to influence Pimcore's startup process, you can do so by adding a file in `/app/startup.php` which will be automatically included as part of the bootstrap process.  Specifically, it will be loaded after all other bootstrapping (loading the autoloader, parsing constants, ...) is done, but before the kernel is loaded and booted. 
I encountered this issue when I was trying to implement [the documented Amazon S3 setup](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_an …
=> Add startup logic to installer

lib/Document/Adapter/Ghostscript.php
Removes possible line breaks around Ghostscript's console output of `--version`.
Fixes #7683
=> Fix Ghostscript::getVersion()

composer.json
This is a followup of #7541
Apparently the bug in PHPStan has been fixed in `0.12.56`, so only the broken version `0.12.55` should be listed in composers `conflict` section.
=> Conflict only with PHPStan 0.12.55

doc/Development_Documentation/18_Tools_and_Features/02_Custom_Icons.md
I removed the link to the demo site of the "Custom Icon for the Car DataObject" example for now, because it's broken and redirects to the homepage of [elements.at](https://www.elements.at/de) and I'm not sure where to link to instead.
Also, I moved setting the `elementQtipConfig` out of the condition in the "Custom Style for Assets" example, so that it matches the description.
=> Fix docs for "Custom Icons & Tooltips for Documents/Assets & Data Objects"

models/DataObject/ClassDefinition/Data/RgbaColor.php, models/DataObject/Classificationstore/Dao.php
Regression of #6102
`RgbaColor::Unmarshal()` now returns object instead of array
=> [DataObject] Fix Cannot save object with RGBA color field inside classification-store

README.md
By the way https://talk.pimcore.org doesn't exist any more either, will that be restored or migrated?
=> Removed API link, updated docs, & https usage

models/Asset/MetaData/EmbeddedMetaDataTrait.php
upload of images disrupted if metadata has an error
This Log an Error Message and continue the Upload of the Image
=> Log metadata Error for getXMPData

lib/Translation/ImporterService/Importer/DataObjectImporter.php
The translation import of localized fields in bricks currently does not work anymore. The reason is that a PHPStan level 2 fix added a check for a wrong parent class. 
Generally it would be a good idea to test each single line if we do such fixes/changes. I appreciate it really much if we improve the PHPStan level, but in this case I've got really serious problems and needed to fix missing data via scripts...
=> Localized fields in bricks translation import bugfix

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
see #7706 which is targeted for 6.9
=>  [DOCS] Preparation for Deep copy in Version::marshalData() corrupts in-memory Document object

bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
In System settings > Localization & Internationalization (i18n/l10n) there is a combo box for adding new locales. Currently this only supports searching for prefixes. I just had the pleasure to find `en_gb` in this list - took me nearly a minute ;-)
With this PR the typeahead feature does full text search on all available locales instead of only prefix search.
=> [Settings] Fulltext search in locale dropdown

bundles/AdminBundle/Resources/public/js/pimcore/settings/user/editorSettings.js, models/DataObject/AbstractObject.php, models/DataObject/Localizedfield/Dao.php, models/DataObject/Localizedfield/LanguageTableDoesNotExistException.php
Steps to reproduce bug:
* Create data object class `Test` with localized text field `test`
* Add new locale in system settings > localization / i18n
* Create new object of class `Test`
* An exception occurs `missing table created, start next run ... ;-)`
As https://github.com/pimcore/pimcore/blob/eb493066f5c3bafc68f1a9540886bd42161758d9/models/DataObject/Localizedfield/Dao.php#L260-L261 says this exception should cause the saving transaction to be retried - but currently this is not done because https://github.com/pimcore/pimcore/blob/eb493066f5c3bafc68f1a9540886bd42161758d9/models/DataObject/AbstractObject.php#L665-L695 does not handle this type of exception separately.
This PR fixes this by introducing a new exception class `LanguageTableDoesNotExistException` (which inherits DBAL's …
=> [Data Objects] Retry transaction when tables for newly added locale do not exist yet

lib/Cache/Core/CoreCacheHandler.php
Symfony Cache does not consider the key a tag, add key as tag in CoreCacheHandler
=> Symfony Cache Tags

bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessUpdateIndexQueueCommand.php
The `ecommerce:indexservice:process-update-queue` does not work corretly if used with multiple tenants (which do not contain the same products). The `commitBatchToIndex()` will only be executed for the tenants of the first combined product row. Therefore it's needed to call the command multiple times to get all items processed.
This PR collects all relevant workers of all rows and therefore the `commitBatchToIndex()` will be executed for all of them. Now a single call of the command is enough to process all items in the queue!
=> [Ecommerce][Productindex][Elasticsearch] fix execution of process update index queue command with multiple tenants

models/DataObject/Concrete.php
Issue:
- open https://demo.pimcore.fun/admin/login/deeplink?object_773_object
- change the title from " A un Angleso..." to something else
- change the text in the first field collection item (NewsText) from "Lorem ipsum dol..." to something else
- switch to the preview tab without saving
Observation:
- title is up to date (from session)
- news text is the one from the database
=> [Data Objects] Version preview from session

bundles/AdminBundle/Controller/Admin/AssetController.php
Fix an error, which occurs when using "Download selected items as ZIP" function at a folder view in assets.
It occurs when selecting large files. In our case there where 3 Videos ~200M. PHP Memory Limit was at 256M or 512M.
The function "file_get_contents" reads the whole file into memory before inserting it into the ZIP archive. With "addFile" of the class "ZipArchive" this limitation is bypassed.
=> [Assets] Fix "allowed memory size exhausted" error

bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
The docs say that the JS for custom editables should be created in the `pimcore.document.editables` namespace (since `pimcore.document.tags` was deprecated). But this is currently not possible. This PR fixes that. Also, an improved error message is thrown when an editable class does not exist.
<br>
Note: this PR is best looked at [without whitespace changes](https://github.com/pimcore/pimcore/pull/7776/files?w=1) ;)
=> Allow to create editables in new `pimcore.document.editables` namespace

lib/Templating/Helper/HelperCharsetTrait.php, lib/Twig/Extension/Templating/Action.php, lib/Twig/Extension/Templating/Inc.php, lib/Twig/Extension/Templating/Navigation.php, lib/Twig/Extension/Templating/PimcoreUrl.php, lib/Twig/Extension/Templating/Placeholder/AbstractExtension.php
In #7463 Templating helpers are deprecated and changed to extend from respective twig extensions, which causes problem when phpEngine call setCharset() on helpers. This PR adds a trait to support the charset calls and the same will be removed with PhpEngine on Pimcore 10.
- Also fixes AbstractHelper alias.
=> [Templating] Fix setCharset error on helpers

bundles/InstallBundle/Resources/install.sql
=> Drop migration_versions table on install

models/DataObject/ClassDefinition/Data/BooleanSelect.php, models/DataObject/Concrete.php
Fixed version preview of Boolean Select fields. Currently, false and empty values are indistinguishable and appear as empty strings.
The reason for the change in `DataObject\Concrete` is that its method is called in `bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.php:207` which makes it impossible to later distinguish a field that's unset/empty from a field with value false.
=> Boolean select preview

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php, bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
The reindex locking currently does not work correctly due some limitations of Symfony lock.
This PR changes the behaviour to a lock mechanism based on a tmp store entry. Additionally write operations to the old index are disabled to avoid race conditions. This write disable mechanism is currently disabled for Elasticsearch 5 as I was not able to test it. In theory it should work for 5 too.
=> [Ecommerce][Productindex][Elasticsearch] fix reindex mode locking

bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
Since Pimcore 6.8 the minimal supported browser versions for the admin backend changed through the use of the "nullish coalescing operator" (`??`).
The browsers that support this operator natively can be seen on [caniuse.com](https://caniuse.com/mdn-javascript_operators_nullish_coalescing). 
I updated the versions accordingly.
The PR that introduced that operator is #6923 (see [here](https://github.com/pimcore/pimcore/commit/8454a72a679a77198a722d4472461be0eda953af#diff-d986a526693963b97de953733d579ff291655b6e02b08d0485cddfeda2cc957fR69) and [here](https://github.com/pimcore/pimcore/commit/8454a72a679a77198a722d4472461be0eda953af#diff-550243b2690103c1c4129a6d7627b0b75e2067d9623b27d50871ae72944e82adR1041)).
Another commit that uses this operator is [this …
=> Update minimal supported browser versions for admin backend

bundles/CoreBundle/Resources/config/pimcore/default.yml, bundles/InstallBundle/Resources/install.sql
reverts 12c936dc6695dd9ac40ec6acc84b194194bd33b3
The problem with hard-coding the `server_version` is that schema/table comparisons are platform specific. This causes problems when for example running `./bin/console doctrine:migrations:version --all --add -n -q`. 
```text
In MetadataStorageError.php line 13:
The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
doctrine:migrations:version [--add] [--delete] [--all] [--range-from [RANGE-FROM]] [--range-to [RANGE-TO]] [--configuration CONFIGURATION] [--db-configuration DB-CONFIGURATION] [--prefix [PREFIX]] [--] [<version>]
```
=> Incompatibilities due to fixed Doctrine server_version

bundles/AdminBundle/Controller/Admin/AssetController.php
Given that you don't have the "create" permission for an asset folder, then the frontend will automatically hide many of the options for uploading files to that folder, but there's still some options left, where it will be up to the backend to reject the upload. I've found two:
1. when you drag-n-drop a file onto any folder
2. when you upload a file to a media component on a data object.
In those cases, AssetController returns a 200 response with `{status: false}`, which results in a rather sparse error message:
This PR uses `createAccessDeniedHttpException()` method to create a proper exception, resulting in a 403 response and an error message like this:
I chose to use the word "create" over "upload", since it's the name of the permission you need.
=> Improve error message when missing permission to create assets

.github/ci/files/config/packages/test/config.yaml, bundles/CoreBundle/Resources/config/pimcore/default.yml, bundles/InstallBundle/Installer.php
Causes issues when building the container without having a DB connection configured (e.g. before running the installer -> 
Composer install)
See also: #7847 , 12c936dc6695dd9ac40ec6acc84b194194bd33b3 and pimcore/demo#202
=> DB mapping types should be written by installer and not set in defaults

lib/Composer.php
The fix for `\Pimcore\Video\Adapter\Ffmpeg` is included in #6603
=> Fix: new Process() only accepts array as first constructor argument

lib/Event/Model/NotificationEvent.php, lib/Event/Model/TranslationEvent.php
=> Remove deprecated getElement() method on NotificationEvent and TranslationEvent

models/User/UserRole.php
All the setters in `AbstractUser` and many in `UserRole` were already chainable, so this is just to make the remaining setters in `UserRole` chainable too.
Not sure if this should go to master or 6.9. I'm fine with both, let me know if I should rebase.
=> Make all UserRole setters chainable

lib/Image/Adapter/Imagick.php
Resolves an issue where imagemagick couldn't find images with a colon ( : ) in the path.
The removed workaround prefixes a path that contains a colon with another colon and therefore imagemagick can't find the image and throws an error (the error is from a Windows system, but was reproducible with Ubuntu):
`
pimcore.ERROR: ImagickException: UnableToOpenBlob ':C:\folder\structure/public/var/assets/logo/logo-3x.png[0]': Invalid argument @ error/blob.c/OpenBlob/3315
`
The workaround was introduced in #2829 but the underlying issue was fixed later that year by imagemagick itself ImageMagick/ImageMagick#1402.
This only affects ImageMagick v7
=> Removed colon-in-path-workaround for imagemagick

bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js, bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
Currently calculated value fields support display types "input field" and "textbox". This PR adds support for HTML output allowing to fully flexibilize calculated field output. In the end this seems to be the same as dynamic text layout element but this for example lacks multi-language support and a getter method. So to support dynamically generated HTML in the "Edit" panel of the object which is also possible to be reused via its getter method I added the "HTML" display type to calculated value fields.
=> [Calculated value fields] Support display type HTML

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Controller/Admin/IndexController.php, bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js, doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/20_Custom_Views.md, lib/Config.php, lib/Tool.php
With this extension, you can define to which depth in a custom view object tree a specific object is available.
It's also backward compatible, both markups can be used:
- 'classes' => 'PRODUCT,3,CONFIGITEM'
- 'classes' => [
"PRODUCT" => 1,  
"3" => 3,
"CONFIGITEM" => 4
],
This extension, in combination with a very limited custom view, is very helpful when working with automated hierarchy trees that depend heavily on inheritance and order levels. 
Plus an additional PR:
If an object, for example, has been locked by code, the unlock button in the context menu can be hidden as well.
=> Extends the configurability of custom views

doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
Simply fixes a formatting issue in the classification store documentation.
=> fix. bad formatting in classification store documentation

doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
Coming from a non-Symfony background, I was accustomed with `.env` files, but not with the way Symfony 4 recommends using them. Which is a bit different from most (all?) other approaches I've seen, in that it recommends keeping the actual values (which you don't want to commit) in `.env.local`, not `.env`, so I think that's worth pointing out. 
Also updated the link to go a more updated documentation page.
=> Update docs: Section on .env files

bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
The first condition should not have an operator (currently it is AND)
Resolves #4056
Due to uncomfortable merge conflicts in https://github.com/pimcore/pimcore/pull/7902, I created a new branch/PR
=> Remove operator from first condition

bundles/CoreBundle/Command/ThumbnailsImageCommand.php
Generating system thumbnails using `bin/console pimcore:thumbnails:image --system` only outputs non-HDPI versions. When these thumbnails are then requested by calling `/admin/asset/get-image-thumbnail?hdpi=1`, the HDPI thumbnails are not available and have to generated on the fly which can cause high load (when e.g. the files are Photoshop files).
This PR generates the HDPI versions as well, provided `--skip-high-res` is not set. To make the code more explicit, the existing calls to `Asset\Image\Thumbnail\Config::getPreviewConfig()` now set the first argument to `false` when generating the non-HDPI version.
The presence of the bug in version 6.8.6 and the absence of the bug with the patch have been verified.
(`6.9` version of #7925)
=> Explicitly generate non-HDPI and HDPI system thumbnails

lib/Maintenance/Tasks/VersionsCleanupTask.php
We updated a pimcore application from v5 to v6 and between updating the application and running the migration scripts the cronjob deleted some version because it couldn't find the system.yml configs.
The Versioncleanup job deleted all versions because the default step value is set to zero. 
I propose to change the default value to 10, because thats the value that is set when i'm installing pimcore.
=> Maintainance Task VersionCleanup: set default steps to 10

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
When we drop asset image in wysiwyg block thumbnail is always generated. Reason: additional property "pimcore_disable_thumbnail" disappears.
We need to add "pimcore_disable_thumbnail" in extraAllowedContent as this functionality doesn't work: https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js#L300
=> wysiwyg.js and pimcore_disable_thumbnail

models/Asset.php, models/Asset/Service.php, models/Asset/WebDAV/File.php, models/Asset/WebDAV/Folder.php
In https://github.com/pimcore/pimcore/blob/de3119d12fd5a003db20dc896e757c7d7342664d/models/Asset/Service.php#L217
the file name contains an additional slash between `PIMCORE_ASSET_DIRECTORY` and the asset's full path. While this is no problem with local storage it becomes a problem with stream wrappers. Additionally there is no need to build the path here as `Asset::getFileSystemPath()` does it correctly anyway:
https://github.com/pimcore/pimcore/blob/de3119d12fd5a003db20dc896e757c7d7342664d/models/Asset.php#L466-L469
This is for Pimcore backend (sorry for mixing this in this WebDAV PR):
Before:
After:
The other important change in this PR is that in Pimcore backend you also see assets whose files do not exist anymore. To have the same behavior in WebDAV we need to suppress errors in …
=> [Assets] Show asset filesizes in UI when using stream wrappers + [WebDAV] Bugfix uploading new files + show assets without files

models/DataObject/Localizedfield.php
Resolves #7967
The only way i could find to fix the supportInheritance error is to set the correct context in `\Pimcore\Model\DataObject\Localizedfield::getLocalizedValue`.
=> Add context when getting localized parentContainer

bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js, bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js, bundles/CoreBundle/Resources/translations/en.json
When a data object is unpublished there currently is no way to recognize which version in the versions tab currently is saved in the database. This PR changes this with a new icon in the `Published` column:
Before:
After:
If the object is published, everything stays the same.
=> [Versions] Show current database version for unpublished elements

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
AWS hosted Elasticsearch version 6.x does not support the index close operation therefore index creation currently fails.
Therefore this PR directly adds the synonyms to the create index call. This way everything works correctly and the only drawback is that you can't use the `bin/console ecommerce:indexservice:elasticsearch-sync update-synonyms` command which isn't a real problem as you can still use the `bin/console ecommerce:indexservice:elasticsearch-sync reindex` command which is the better choice on live environments anyways.
=> [Ecommerce][Productindex][Elasticsearch] do not close index on index creation

bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
Resolves errors:
- Argument 1 passed to Symfony\Component\HttpKernel\Bundle\Bundle::setContainer() must implement interface Symfony\Component\DependencyInjection\ContainerInterface or be null, instance of Symfony\Component\DependencyInjection\Argument\ServiceLocator given..
- Object of class Symfony\Component\Console\Output\BufferedOutput could not be converted to string
=> Fix ExtensionManager load issues

models/Asset/Image/Thumbnail/Processor.php
Added Locking to prevent wasting of CPU resources on generating same Image Thumbnail in parallel by my multiple independent requests
=> Added Locking to prevent generating same thumbnail in concurent requests

bundles/CoreBundle/Controller/PublicServicesController.php
=> [Image Thumbnail] Do not generate error image in vendor folder when requested file extension is different

bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
- don't start change detector if panel is already dirty
- don't call `detectedChange` (and update title) if panel is already dirty (especially necessary when `getSaveData` delivers a string, because then this is executed for every character)
=> change detector improvements

bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/website.js
After hitting the `pimcore.globalmanager.get('translationwebsitemanager').activate` method,  the request will raise a json exception since the wrong parameter `filter` gets passed. I just adapted the logic from the admin translation class: 
https://github.com/solverat/pimcore/blob/2f700bd6beb4ce4c3c7844369e20a8a0dd272ddc/bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/admin.js#L32
=> Use searchSring instead of filter in website translation activation

lib/Document/Adapter/Ghostscript.php
=> Fix: No thumbnail for PDF documents with ) sign

models/Document/Editable/Areablock.php
There was an JSON parse error, when I clicked on the edit button of a brick with the following code:
```php
public function getEditableDialogBoxConfiguration(Document\Editable $area, ?Info $info): EditableDialogBoxConfiguration
{
$config = new EditableDialogBoxConfiguration();
$config->setItems([
[
'type' => 'select',
'name' => 'test',
'config' => [
'store' => [
["image 1", '<img src="/bundles/pimcoreadmin/img/flat-color-icons/idea.svg">'],
],
],
]
]);
return $config;
}
```
This pull request fixes the error.
=> Fix JSON parse error, when clicking on edit button of a brick

bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
On my environment Pimcore 6.8.7 (PHP 7.4) I have this error when  I run Symfony command lint:container 
````bash
/www/current $ php bin/console lint:container
In CheckTypeDeclarationsPass.php line 302:
Invalid definition for service "Pimcore\Targeting\DataProvider\GeoIp": argument 1 of "GeoIp2\Database\Reader::__construct()" accepts "string", "NULL" passed.  
````
This  PR fixes this error, setting an empty string instead of null value.
=> [CoreBundle] Invalid definition for service GeoIp : lint:container

doc/Development_Documentation/18_Tools_and_Features/29_Custom_Reports.md
Changes:
* There is no need that report adapter class needs to be in namespace `Pimcore\Model\Tool\CustomReport\Adapter`
* Description of PHP Adapter class was duplicated resulting in the impression that one needs to implement 2 classes
* the list items about the adapter factory were a bit misleading because the step `Add your Adapter Factory to the configuration` seemed to be only necessary for "complex adapter classes" but in fact it is for all adapters, regardless if they use an own factory or `DefaultCustomReportAdapterFactory`
=> [Docs] Clearer instrucutions how to set up custom report adapters

models/Element/Service.php
In https://github.com/pimcore/pimcore/blob/195588073f72e797da83ec4b850252d18f4b7c46/models/Element/Service.php#L783-L802
path and key of elements get restored. This happens for example when you unserialize a version. But while https://github.com/pimcore/pimcore/blob/195588073f72e797da83ec4b850252d18f4b7c46/models/Element/Service.php#L798-L800 
respects `AbstractObject::$doNotRestoreKeyAndPath` setting, the above lines where the key gets restored do not. This PR fixes this.
Script to reproduce:
```php
<?php
$object = \Pimcore\Model\DataObject\Concrete::getById(123);
var_dump('Original Key: '.$object->getKey());
$object->setKey('a');
var_dump('New Key: '.$object->getKey());
\Pimcore\Model\DataObject\AbstractObject::$doNotRestoreKeyAndPath = true;
$objectLatestVersion = …
```
=> [Versions] renewReferences() restores current key even if $doNotRestoreKeyAndPath is true

bundles/AdminBundle/Controller/Admin/NotificationController.php, bundles/AdminBundle/Resources/public/js/pimcore/notification/helper.js, models/Notification/Service/NotificationService.php
When a user receives a notification he can open the notification with one of the icons in the appearing modal in the bottom-right corner. If the notification got deleted in the meantime an exception gots thrown. This PR fixes this so that he gets the usual message "Element not found" (as when trying top open an object which got deleted in the meantime).
=> [Notifications] Prevent exception when trying to open deleted notification

models/Document/Editable/Link.php
Consider additional parameters in object linkgenerators.
The link generator produces a link with querystring zB www.example.com?test1=123
In the Pimcore backend additional parameters get configured zB test2=123
The currently resulting link is www.example.com?test1=123?test2=123
This PR changes the behaviour to the following result: www.example.com?test1=123&test2=123
=> Consider existing parameters in DataObject Linkgenerators

bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
(Fix is based on master as it doesn't occur in current 6.9).
This fixes adding and editing new units by checking for an undefined index 'baseunit'. There seems to be a changed behavior (no property 'baseunit' in payload) how newly persisted entries are updated.
1) Click "new unit" and enter ID "g" into modal.
2) Edit abbreviation to "g".
3) Lose focus, so entry is saved.
4) Exception is shown instead of update.
=> [DataObjects] Quantity Value: Fix adding new units

bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Add better layout possibilities for editable dialog box of a brick.
So you can use table layout or vbox layout.
Example:
```php
public function getEditableDialogBoxConfiguration(Document\Editable $area, ?Info $info): EditableDialogBoxConfiguration
{
$config = new EditableDialogBoxConfiguration();
$config->setItems([
[
'type' => 'panel',
'layout' => 'column',
'defaults' => [
'columnWidth' => '0.5',
],
'items' => [
[
'type' => 'panel',
'title' => 'Column 1',
'items' => [
[
'type' => 'input',
'name' => 'input1'
]
],
],
[
'type' => 'panel',
'title' => 'Column 2',
'items' => [
[
'type' => 'input',
'name' => 'input2'
]
],
]
]
]
]);
return $config;
}
=> Add better layout possibilities for editable dialog box of a brick

bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php, tests/Ecommerce/PricingManager/CombinedRuleTest.php, tests/Ecommerce/PricingManager/Rule/AbstractRuleTest.php
Fixes Pricing Rule issues:
- First condition is always ignored. Resolves #8142
- first condition(without brackets) shouldn't have an operator. #7902
- Previous state is ignored when AND condition results to true
=> [Ecommerce][PricingRules] Fix first condition is always ignored

models/Document/Editable.php, models/Document/Editable/Area.php, models/Document/Editable/Block/AbstractBlockItem.php
=> Document\Editable: renamed buildChildElementTagName() to buildChildEditableName()

lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
$targetDocument->getEditable() can return null and function call on null is not good.
=> DocumentDataExtractor editable check

lib/Image/Adapter/Imagick.php
- `setcolorspace` -> `setColorspace` method name
- Fewer checks for `!$this->isPreserveColor()`
=> Proper method name and fewer if-checks in Imagick adapter

bundles/CoreBundle/Resources/config/services.yml, lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
resolves #5387
Usage see: https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading
`memory_limit` should be set to at least `200M` when using preloading with Pimcore. 
Most of the classes used by Pimcore and not used as Symfony services should be covered.
=> Opcache Preloading Integration

models/Element/Recyclebin/Item.php
=> Fix recycle-bin restore for objects with non-existent parent

bundles/AdminBundle/Resources/public/js/pimcore/helpers/generic-grid.js
I suggest to increase the default timeout of proxy stores created via `pimcore.helpers.grid.buildDefaultStore` from 30s to 120s.
This is espcially useful for `/chart` or `/data` requests of custom report, which may take longer depending on the implementation.
=> [UI] Increase timeout of buildDefaultStore

bundles/AdminBundle/Controller/Admin/LogController.php
When the log file object is very big memory problems can arise with `file_get_contents()`. With this PR the log file gets streamed to prevent this.
=> [Application Logger] Stream log file object

lib/Templating/Renderer/IncludeRenderer.php
=> [Templating] Fix IncludeRenderer to avoid writing output-cache from editmode 

bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
Clicking the save button inside a pricing rule's tab always showed a success notification, not considering the actual response. With this PR the returned result is taken into account and the response message is shown to the user.
=> [Ecommerce] Fix pricing rule save misleading result message

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
Resolves #7974
Fieldcollections and Blocks always send their data without checking if content isDirty, but a LocalizedFields element itself checks again the isDirty() function of its children.
Therefore, a small check of the context container allows to ignore the isDirty() function of LocalizedFields in Fieldcollections and Blocks.
=> [Data Objects] Fieldcollection with Localized Fields deletes and overwrites content after unpublished save

bundles/AdminBundle/Resources/views/Admin/Misc/iconList.html.twig
The icon library could not be opened and threw an exception in the Twig template.
```
Too few arguments to function Pimcore\Model\Site::getById(), 0 passed in /var/www/pimcore-master/var/cache/dev/twig/.....php on line 48 and exactly 1 expected
```
=> [AdminBundle] Fix icon library

bundles/AdminBundle/Resources/public/js/pimcore/log/admin.js
Ext JS KeyNav constructor doesn't support multiple arguments anymore and
thus threw an exception. The functionality "search on key ENTER" was
already fixed/implemented in #2539, so this code seems obsolete.
=> [AdminBundle] Fix opening application logger

bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
I think this hunk was missed during the refactoring by #8148
An AND  condition always has to consider the existing state if available no matter if AND or AND NOT.
Not sure if this is somehow related to #7855 - unlikely due to timeline but sound somewhat familiar.
=> AND NOT condition needs to consider existing state

bundles/InstallBundle/Installer.php
Follow up to #7847
Having `server-version` not set results into other issues, like when using Doctrine entities.
=> Installer: write server version into database.yml

bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php, doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, lib/Tool/Console.php, lib/Web2Print/Processor.php, models/Asset/Video/Thumbnail/Processor.php
Symfony Process background processes are terminated as soon as parent process exists. So this is a change in behavior. 
For now, reverted execInBackground, will switch to queue implementations in Pimcore X.x versions. 
fixes #8355
=> Revert execInBackground

lib/Helper/TemporaryFileHelperTrait.php, models/Asset.php, models/Asset/MetaData/EmbeddedMetaDataTrait.php
follow up to #8335
- `TemporaryFileHelperTrait`:  added support for streams
- removed temporary file handling from Asset
=> TemporaryFileHelperTrait follow-up

models/Element/ElementInterface.php
which will be required in Pimcore 10. 
In preparation for #7905
=> ElementInterface: added upgrade note for getParent()

models/Translation/Listing/Dao.php, tests/Unit/Translation/TranslatorTest.php
doing something like fails: 
```
$translations = new Translation\Listing();
$translations->setDomain('messages');
$translations = $translations->getTranslations(); 
```
tests fail because of https://github.com/pimcore/pimcore/issues/8369
=> Fix missing parameters for translation listings

lib/Model/AbstractModel.php
=> Calling AbstractModel::create(['id' => 123]) throws exception on certain entities

bundles/CoreBundle/Resources/config/templating_twig.yml, lib/Twig/Extension/AssetHelperExtensions.php, lib/Twig/Extension/DataObjectHelperExtensions.php, lib/Twig/Extension/DocumentHelperExtensions.php, lib/Twig/Extension/ImageThumbnailExtension.php
These are quite some handy twig extensions that should be part of the Core.
@brusch there are many more things in coreshop/pimcore that might make sense, if you mgiht take a look at it what you think might help here as well: https://github.com/coreshop/CoreShop/tree/master/src/CoreShop/Component/Pimcore
=> Move Twig Helpers from coreshop/pimcore to pimcore/pimcore

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php, bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.twig, bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.twig
In some use-cases it is good to add a description or some meta data to data object versions. There is a field `note` in the `versions` table. Currently this can only be filled by manually calling the `Version::setNote()` method as far as I know. But currently this field is not displayed anywhere in the Pimcore backend. With this PR the version note gets shown in the data object preview / comparison - only if it is filled. So for projects which do not use version notes everything will look the same as before but for those which do the version note is displayed.
=> [Data object versions] Show version note

bundles/CoreBundle/Command/ThumbnailsClearCommand.php, doc/Development_Documentation/07_Workflow_Management/09_Working_with_PHP_API.md, models/Asset/Image/Thumbnail/Config.php, models/Asset/Image/Thumbnail/Config/Dao.php, models/Asset/Thumbnail/ClearTempFilesTrait.php, tests/_support/Util/TestHelper.php
This PR merges the 2 regular expressions and uses `SplFileInfo::getFilename()` for the check. I also moved the `isDir()` call after the regular expression check because file system calls can be quite slow - especially when using stream wrappers (we currently have > 100000 files in Google Cloud Storage).
And the cleanup of temporary files is delegated to `pimcore:thumbnails:clear` command in the background.
PS: I actually tried to enhance performance even more but as https://github.com/googleapis/google-cloud-php-storage does currently not support `glob` operations we really have to loop through every asset. It is especially bad that the iterator also returns files but I did not find a way to change this (tried RecursiveCallbackFilterIterator but this has to return `true` for all …
=> [Thumbnails] Performance improvements for cleaning thumbnails

lib/Document/Editable/EditmodeEditableDefinitionCollector.php
Since this was added to `master` in #8420 and #8435 we should use PHP >= 7.3 features.
=> Use `JSON_THROW_ON_ERROR` instead of custom JSON error handling

models/WebsiteSetting.php
If a setting is first deleted:
```php
$settingObject->delete();
```
It was then still available to the process and returned via 
```php
WebsiteSetting::getByName()
```
Which should not have happened. This overrides the Dao to to resolve the issue.
=> Fixes deleting a Website Setting not clearing it from cache

models/Dependency/Dao.php
The dependency query that is used in the search & replace functionality is fixed by adding the correct condition for the sourceType. If an id exists in more than one of the tables objects, documents or assets, the outcome of the query is not correct at the moment.
Resolves
https://github.com/pimcore/pimcore/issues/6973
=> Fix search and replace functionality

lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
related to #8361
If a target document has translated value in settings "title" & "description" then it should be added as target tag.
=> [XLIFF Export] Export translated target document settings

bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
fixes #8419
Obviously caused by the tooltips - extending the timeout and disabling mouse tracking solves the issue and is imho better experience anyway.
=> [Document] Fixed editmode flickering

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
The DataObjectController::saveAction() will now throw errors when unpublishing/publishing is not allowed. Otherwise the DataObject will get crossed out while no publishing/unpublishing is actually done.
If a customer wants to publish/unpublish an object via context menu, where he/she doesn't has any permissions, the saveAction() will end up in the final elseif-Condition `elseif ($object->isAllowed('save'))`. 
Therefor even if the user has no permissions, a new (per default) unpublished version is stored and the response treeData contains `published: false`.
This fix is an adaption of https://github.com/pimcore/pimcore/pull/7101/files
=> [Data Object] unpublish publish permission fix

models/DataObject/ClassDefinition/Data/Localizedfields.php, models/DataObject/LazyLoadedFieldsInterface.php, models/DataObject/Localizedfield.php, models/DataObject/Traits/LazyLoadedRelationTrait.php
Please review the fix for the lazy loading issue inside localized fields. 
After lazy loaded fields are removed on serialization for cache, the lazy loaded fields are now also unmarked as loaded.
There is an issue with lazy loading when using localized fields.
1. On a class, add "one-to-many" relation type under localized fields.
2. When the relation field is requested for the first time, the value gets lazy loaded.
3. When it is called the second time in a row, it returns null.
What happens is that after the object is loaded from the database and its lazy loaded values are retrieved, the object gets serialized for cache.
In Pimcore\Model\DataObject\Localizedfield.php, inside __sleep() method, all lazy loaded fields are unset before writing to cache.
However, there is …
=> lazy load fix when using localized field

lib/Model/Listing/Dao/QueryBuilderHelperTrait.php, models/DataObject/Listing/Dao.php
Doing $list->getQuery()->execute() where $list is DataObject\Listing would fail because conditionVariables weren't set in QueryBuilder
=> Query builder missing condition variables

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
The path property wasn't updated when the relation field was changed via the search popup. This causes PathFormatters based on the path value to return a string based on the old value.
1. Create a path formatter implementation displaying only the key instead of full path:
```
public function formatPath(array $result, ElementInterface $source, array $targets, array $params): array
{
foreach ($targets as $key => $item) {
if (!array_key_exists('path', $item) || $item['path'] === null) {
continue;
}
$pathParts = explode('/', $item['path']);
$result[$key] = array_pop($pathParts);
}
return $result;
}
```
2. Create a ManyToOne relation field with that path formatter
3. Update relation via drag-and-drop: working fine
4. Update relation via search popup: old value is still …
=> Fix: update path when changing relation via search popup

bundles/CoreBundle/Command/ClassesRebuildCommand.php, models/DataObject/Objectbrick/Definition.php
If you have a new class definition with an object brick and execute follow command (without this class definition in the db), you get an exception:
```
php bin/console pimcore:deployment:classes-rebuild -n
```
=> Fix undefined getFieldDefinition in ClassRebuildCommand

lib/Tool/Console.php
I want set the executables via .env and .env.local files.
Now it is possible to set it via symfony parameters:
```
parameters:
pimcore_executable_php: '%env(PIMCORE_EXECUTABLE_PHP)%'
```
But if the env doesn't exists, Pimcore now deactivate the executeable and do not check with `whereis`.
I think it would be good if Pimcore itself looks for these env variables.
=> Possibility to overwrite executables with env variables

lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
Clearing the cache where Pimcore thinks it is installed (by only checking if a connection can be done) still depends on the database. what if the database is empty or does not yet exist? that will still throw an error.
=> Cache warming should not depend on database

bundles/AdminBundle/Controller/Reports/CustomReportController.php
Currently reports with more than 5000 items cannot be exported. In the resulting file are maximum of 5000 rows. Reason is that in https://github.com/pimcore/pimcore/blob/ef8ad357b3de0c56b30b4a77e67e3d1ffc69ee25/bundles/AdminBundle/Controller/Reports/CustomReportController.php#L437 only the basename gets transfered to the client but in the next batch `$exportFile` was not prepended with `PIMCORE_SYSTEM_TEMP_DIRECTORY`:
https://github.com/pimcore/pimcore/blob/ef8ad357b3de0c56b30b4a77e67e3d1ffc69ee25/bundles/AdminBundle/Controller/Reports/CustomReportController.php#L416-L421
This bug was introduced in 1786bdd4962ee51544fad537352c2b4223309442
=> [Reports] Exporting reports with > 5000 items did not work

models/DataObject/ClassDefinition/Data/Classificationstore.php
- `array_keys($array, true, true)` returns all keys which matches the second argument (`true`)
- `$groupList` got a proper Order Key, a listing without it had no effect as we could see.
- general QoL things like removing unnecessary assignment on `$relation = $relation->load();` and phpdoc cleanup.
- Tooltip fallback with description only if description contains any text, would often end with ugly " - " otherwise.
- Don't call `recursiveGetActiveGroupCollectionMapping()` until required.
=> Cleanup of conditions in Classificationstore's classdefinition

bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
With the current settings one can only drop tags to an element if it already has children. Setting to _false_ will allow to set it as children as well.
=> Allow tags to be dropped to other tags, that don't have children yet

bundles/AdminBundle/Resources/public/css/editmode.css, bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
- no more stuttering (vertical movement of blocks) when starting to drag from toolbar & for moving blocks, everything stays at the same position
- outline of editables is not shown on hover when dragging area-bricks (add & move) 
- better coloring
=> [Document] optimized area-block drag & drop experience

models/DataObject/ClassDefinition/Data/Classificationstore.php
Turns out my cleanup prior to committing my [previous changes](https://github.com/pimcore/pimcore/pull/8598) were too hasty and introduced a bug.
`$activeGroups` should keep the format `[id => bool]` in  `recursiveGetActiveGroupsIds()` previous change incorrectly changed it to `[int => id]`, see:
Might actually need a new 6.8.x release as previous incorrect change makes editing Classification Stores hard in the admin UI as not all groups were properly returned.
=> Follow-up on PR #8598 (Classificationstore changes)

lib/Storage/Redis/ConnectionFactory.php
Fixes PHP Warning: `Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/pimcore/vendor/pimcore/pimcore/lib/Storage/Redis/ConnectionFactory.php on line 112`
=> Remove `final` keyword in ConnectionFactory.php

bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
After adding the first block (without reload) the entire block stayed semi-transparent.
=> [Document] block editable styling fix for initial controls

lib/Image/HtmlToImage.php
WIthout this PR you get the error `Warning: array_merge(): Expected parameter 1 to be an array, string given` when trying to display a document version.
=> [Document version preview] Prevent error when xvfb-run is not available

bundles/AdminBundle/Controller/Admin/TranslationController.php
**Filename before:**
`export_ website_translations.csv`
**Filename after:**
`export_website_translations.csv`
=> style: remove unnecessary space in export filename

composer.json
PHP 7 support was [added in version 3.4.0](https://github.com/Imagick/imagick/blob/master/ChangeLog#L187..L189), any earlier version requirement should be moot
=> Increase imagick minimum suggested version

models/DataObject/Concrete/Dao.php
Return directly after SELECT statement (if no result is found) to prevent unnecessary calls on empty $data (especially the $data[$key] in former line 179 which will lead to exceptions)
=> [Data Objects] - DAO - Prevent (array) access on empty $data

bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Currently the assigned object of a many-to-one relation is displayed in a text field. This PR changes it to a [`DisplayField`](https://docs.sencha.com/extjs/6.2.0/classic/Ext.form.field.Display.html). This has the advantage that you can use a path formatter which returns HTML:
As far as I know the capabilities of a text field are not used anyway (e.g. direct typing is disabled).
=> [Data Objects] Allow HTML-returning path formatter for many to one relation

lib/Model/Listing/AbstractListing.php
There is currently no way to reset a listing offset to 0.
Allows resetting offset to 0 in Listing classes.
If using KnpPaginator, you can set it to fix the pagination if the paginator runs out of bounds. The paginator resets the offset to the last available page. If there is only 1 page, the offset is reset to 0, but `Listing` class only allows numbers greater than 0
.
https://github.com/pimcore/pimcore/blob/055d64a90e8cd145795ed1e28f16c24fc7629c10/lib/Model/Listing/AbstractListing.php#L169-L178
=> Allow resetting offset to 0 in Listings

bundles/AdminBundle/Controller/Admin/AssetController.php
Assume you have created a thumbnail definition and enabled it to be listed as a download option for assets. When you download an asset from the asset detail page in the Pimcore backend, then the thumbnail file gets deleted afterwards. Actually it could be reused if the same thumbnail definition from this asset gets accessed again. But even worse: It gets even deleted if it existed before (e.g. when it got created by a frontend application or whatever called `$image->getThumbnail('name-of-thumbnail-config')`). So this breaks the whole create-once-always-reuse-lifecycle of asset thumbnails.
=> [Image thumbnails] Do not delete downloaded thumbnails when permanent thumbnail definition is used

lib/Tool.php
Noticed by #8684 
?pimcore_outputfilters_disabled=true not work. 
$requestKeys has the param names as values
=> Fix pimcore_outputfilters_disabled param

lib/Composer.php
If a bundle throws an exception in a migration, it shows only: "Notice: Array to string conversion"
=> Fix Array to string conversion

models/DataObject/ClassDefinition.php
The attribute is set initially to false. But if you use the setter it will be set to null. It's very confused
=> ClassDefinition::allowVariants should be a boolean

bundles/CoreBundle/Resources/config/pimcore/default.yml
Pimcore should use PHP default settings for mail delivery.
=> Defaults for Symfony Mailer transports used by Pimcore

lib/Tool/ClassUtils.php, tests/Unit/Tool/ClassUtilsTest.php
In Skeleton is no Bundle in the ExtensionManager. It should be at least PimcoreEcommerceFrameworkBundle.
PHP 8 has a new tokenizer constant T_NAME_QUALIFIED.
=> Fix: Empty Bundle List

bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Let's say we have double type in ES, and some getter on a product returns e.g.: 5.0, but without this flag `JSON_PRESERVE_ZERO_FRACTION`, we'll end up with integer instead after json_encode, and this leads to an error during indexing new products.
This is only the case for numbers like 1.0, 2.0, 3.0, and so on.
Every other fraction number works ok.
=> Ecommerce index service problem with fraction numbers in elastic search

lib/Web2Print/Processor/PdfReactor.php
It is only in WkHtmlToPdf and in the buildPdfFromString (which is only used in the test page)
=> Placeholder/Twig functionality is missing with PdfReactor

bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php, bundles/CoreBundle/Resources/config/services_symfony_workflow.yml
error message when building the container 
```
Argument 5 of service "state_machine.abstract" is abstract: events to dispatch
```
when other bundles also define workflows...
=> fix missing argument when defining workflows

models/Element/Service.php
Allow adding extra where conditions in customviews. (It broke in 6.9, works in 6.8)
DoctrineQueryBuilder `where` function overrides the complete where condition, thus in customviews you cannot add a simple where condition to the existing one.
Previously in 6.8, in customviews you could add a simple extra filter to the query like `o_published = 1`, so only the published elements would show up in the tree. In 6.9 (using Doctrine Query Builder) currently the whole `where` condition would be only `o_published = 1` and the original where conditions built in the `DataObjectController::treeGetChildsByIdAction` method are lost.
=> Fix overwriting where condition in customviews

models/DataObject/Service.php
Currently when you use grid operators you have to manually enable inheritance, otherwise values do not get inherited by parent elements. But for normal fields (without operators) inherited values do get shown by default. 
To reproduce this:
1. Create class Product, enable inheritance, add many-to-many object relation `test`
2. Create an object `/related`
2. Create an object `/parent` and assign `/related` in the relation field `test`
3. Create an object `/parent/child`.
4. Create a PHP class in `src/AppBundle/Operator/Attributes.php` with the follwoing code:
```php
<?php
namespace AppBundle\Operator;
use Pimcore\DataObject\GridColumnConfig\Operator\AbstractOperator;
use Pimcore\DataObject\GridColumnConfig\ResultContainer;
use Pimcore\Model\DataObject;
class Attributes extends …
```
=> [Grid] Enable inheritance for grid operators

bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php, bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridConfigDialog.js, bundles/CoreBundle/Resources/translations/en.json
Currently only the owner of a shared grid configuration (aka the person who created the grid config) can change and delete it. With this PR also admin users are allowed to change and delete shared grid configurations.
Additionally this PR adds 2 readonly fields in the grid config `Save & Share` panel for the owner and the modification timestamp. This way users can find out the owner of a shared grid config if they want to suggest changes.
=> [Grid Config] Admins should be able to change + delete shared grid configurations

bundles/AdminBundle/Resources/views/Admin/Login/login.html.twig
Older browsers are not allowed to access the admin backend. Instead,
a set of links to more up-to-date browsers is presented. These utilize
<a> with target="_blank" to open a new window upon clicking a link,
however they are vulnerable to `window.opener`.
Adding noopener and noreferrer prevents this in the first place and clears the CVSS score.
While an extremely unlikely case to cause a security issue, this is still a vulnerablity marked with a CVSS score of 4.8 for Deep Scans, e.g. detectify.com.
Reference: https://dev.to/ben/the-targetblank-vulnerability-by-example
=> Add noopener and noreferrer to admin login

lib/Config.php
=> Config::setSystemConfig sets it to the runtime but getSystemConfig never gets it from there

bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js, bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
As long as there are only the grid exports for CSV and Excel which are included in Pimcore, the result with and without this PR are the same. But if a bundle adds another grid export type, the result is wrong because 
https://github.com/pimcore/pimcore/blob/f1b0ccb8b3d5c7028416a73df9ea4bab508b165b/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js#L330
always uses the last added export type for the main button. This means currently the last added export type will get on the main export button, all others go into the button dropdown. With this PR the `CSV Export` will always stay on the main button while XLSX and other custom export types go into the button dropdown.
=> [Grid exports] Correct order of grid export types

lib/Navigation/Builder.php
Resolves a bug which would happen in only specific instances.
Consider the following scenario:
```twig
{% set menuOptions = { active: document, maxDepth: 5, expandSiblingNodesOfActiveBranch: true, onlyActiveBranch: true } %}
{{ pimcore_render_nav(pageNavigation, 'menu', 'renderMenu', menuOptions) }}
```
With a document structure that is at least 2 levels deeper than `maxDepth`, example where _Produkter_ is the root document for this menu.
This issue seems to be sensitive to cache:ing, so to reproduce it, first click around in the rendered menu to make sure it has been cached. Also good to do this in a clean browser session for some reason.
Then, *Unpublish* the page at the same level as the configured `maxDepth` by right-clicking and using the context menu option. In the screenshot above …
=> Bugfix for incorrect maxDepth comparison

doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md, models/DataObject/ClassDefinition/Dao.php, models/DataObject/ClassDefinition/Helper/Dao.php
Follow-up of #8409
Currently when you tick `indexed` and `unique` checkboxes for a field 2 indexes get created in the `object_store_*` table slowing down write performance. With this PR `object_store_*` tables only get unique indexes (if `unique` is ticked) and `object_query_*` tables only get non-unique indexes (when `indexed` is ticked).
=> [Data objects] Do not create non-unique index in object_store table

models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php, models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
1. Create class `Product`, add advanced many-to-many relation field `test`, allow assets
2. Create object of class `Product`, assign an asset, click `Only save new version`
3. Add meta column `abc` to field `test` in class `Product`
4. Reload object -> Uncaught exception
The reason is that the serialized `ElementMetadata` object does not have the newly added column but in https://github.com/pimcore/pimcore/blob/881f8a4448f23bddcafb8c01ccc5954cc00dc40f/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php#L342-L345
the current columns of the relational field get used. Thus there is an exception thrown in https://github.com/pimcore/pimcore/blob/881f8a4448f23bddcafb8c01ccc5954cc00dc40f/models/DataObject/Data/ElementMetadata.php#L101
=> [Data objects] Prevent fatal error when an unpublished version object gets opened after new meta field got added

lib/Tool/ClassUtils.php, tests/Unit/Tool/ClassUtilsTest.php, tests/_support/Resources/dummyfiles/ClassX.php, tests/_support/Resources/dummyfiles/ClassY.php
namespaces like `Test\TestClass` were not detected correctly.
=> fix ClassUtils.php with single-level namespaces

bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
Here should be a relative not absolute URL. It makes problems if Pimcore is behind a proxy.
Original output of the view:
`<form method="post" action="http://xyx.cz/admin/login/2fa-verify">`
After the change
`<form method="post" action="/admin/login/2fa-verify">`
=> 2FA login form should use relative url

bundles/CoreBundle/DependencyInjection/Configuration.php
When a bundle adds the following configuration:
```yaml
pimcore:
context:
context_name:
routes: ~
```
the contexts are not merged correctly. `bin/console debug:config pimcore context` results in:
```
profiler:
routes:
-
path: '^/_(profiler|wdt)(/.*)?$'
route: false
host: false
methods: {  }
admin:
routes:
-
path: '^/admin(/.*)?$'
route: false
host: false
methods: {  }
-
route: ^pimcore_admin_
path: false
host: false
methods: {  }
webservice:
routes:
-
path: '^/webservice(/.*)?$'
route: false
host: false
methods: {  }
-
route: ^pimcore_webservice
path: false
host: false
methods: {  }
plugin:
routes:
-
path: '^/plugin(/.*)?$'
route: false
host: false
methods: {  }
0:
routes: {  }
```
So the context name does not get used but numeric indexing. The reason is documented in …
=> [Contexts] Allow to extend pimcore.context list and use array keys

bundles/CoreBundle/Resources/config/cache.yml
Until now it used `FilesystemAdapter` because of DI, no idea why (actually it should be null and use the same as for `$itemsPool`). Probably because it's somewhere bound to `Symfony\Component\Cache\Adapter\AdapterInterface` by a bundle or Symfony itself.
=> [Cache] Default PDO cache should also use PDO for storing the tag information

bundles/AdminBundle/Helper/GridHelperService.php, models/DataObject/ClassDefinition/Data.php, models/DataObject/ClassDefinition/Data/Multiselect.php, models/DataObject/ClassDefinition/Data/Select.php
Steps to reproduce problem:
1. Create class `Product`. Add a `select` field `test` and option `A`and `B`. Add an object brick field named `bricks`.
2. Create an object brick `Brick`. Add a `select` field `test` and option `A`and `B`. Assign `Product.bricks` as allowed brick field.
3. Create an object `/A` of class `Product`, assign object brick `Brick`, select `A` in `Brick.test`.
4. Click `Home` in data object tree, click `Grid options` add field `test` from object brick `Brick`
5. Sort by field `test` -> first ambiguous column error appears
6. Filter by field `test=A` -> second ambiguous column error appears
This PR prefixes the sort / filter field names with the brick table alias.
=> [Data object grid] Prevent ambiguous columns when filtering / sorting by object brick field

bundles/AdminBundle/Controller/Searchadmin/SearchController.php
when path contains utf8 characters like umlauts quicksearch sometimes looked like
=> [QuickSearch] fix mb-issue in quick-search

bundles/CoreBundle/Migrations/Version20210428145320.php, bundles/InstallBundle/Resources/install.sql
If the UI field already allows 255 characters, so should the database. Keeping it short is an editorial issue.
https://github.com/pimcore/pimcore/blob/c4f055340935b9028b358f459267fe9ae42137f3/bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js#L213-L217
=> Migration to increase prettyUrl field size to 255

bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php, bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.php
Currently the brick name does not get displayed for localized object brick fields. This can lead to confusion because it looks like the field was actually a class field:
The field "Test" is actually in the object brick "Bodywork".
With this PR it looks like this:
=> [Data object version preview] Show brick name for localized brick fields

bundles/CoreBundle/Migrations/Version20210324152822.php
Migration failed for a different reason, but didn't told me. so it should fail and not further proceed. Otherwise you'll end up with following error when trying to access pimcore:
```
InvalidFieldNameException
An exception occurred while executing 'INSERT INTO `translations_admin` (`key`, `type`, `language`, `text`, `modificationDate`, `creationDate`) VALUES (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `key` = ?, `type` = ?, `language` = ?, `text` = ?, `modificationDate` = ?, `creationDate` = ?;' with params ["login", null, "en", "", 1619684040, 1619684040, "login", null, "en", "", 1619684040, 1619684040]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'
```
=> [PimcoreX] Translations Table migration is allowed to fail

bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php, doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/01_Configuration_Details.md
Resolves #7803 by adding default timeout parameters and the possibility to overwrite them via ecommerce index settings.
=> Add timeout option to elastic search client

bundles/AdminBundle/Resources/public/css/editmode.css, models/Document/Editable/Area.php
Resolves #8890
- Additionally fixes edit button overlapping css when multiple areas are used on a page
=> [Documents] Editable Dialog Box - Fix dialogbox editable naming when used in area

bundles/AdminBundle/Controller/Admin/TranslationController.php
Fixed issue where fetching admin translations was returning a query error if sorting/order key was previously set in a language which wasn't available anymore. 
**CASE:** Admin translations were sorted by orderKey "_uk" (Ukrainian), when changing config to limit languages to en (English) and de (German) in admin translations `if (in_array(trim($orderKey, '_'), $validLanguages))` would return false since the sorting language doesn't exist anymore in `$validLanguages` and the order key would be set `$list->setOrderKey($tableName . '.key' . $sortingSettings['orderKey'], false);` which would cause an error since it would search for a column in admin_translations table with the name of e.g. "_uk" which doesn't exist. Also by default if the language does not exist in `$validLanguages` the …
=> Fixed admin translations order key

bundles/AdminBundle/Controller/Admin/UserController.php, bundles/InstallBundle/Installer.php
By scanning the net for fresh installations or enumerating new accounts on existing sites an attacker could potentially get an idea of the default password. E.g. catching the when the new account appeared, or the creationDate of the root document or the basic Pimcore assets given by visiting the site could clue the attacker in. To prevent this (small) security hole we remove the dependency on `microtime()`.
For the controller, `uniqid()` is also based on microtime and `md5()`:ing it is actually ever so slightly decreasing the strength of the string given by `uniqid()`.
If nothing else this will prevent naive code analysis tools from warning us that *OMG the words "md5" and "password" appears on the same line in the code: must be insecure* ;)
=> random_bytes for default passwords

lib/Model/Listing/AbstractListing.php
This way it must not be annotated via `@var` each time (also for external users).
=> Add `@method` annotation for `getDao()` to `AbstractListing`

bundles/AdminBundle/Resources/public/js/pimcore/asset/gridexport/csv.js, bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
There is no validation currently for grid exports. For example when you request a CSV export without a column separator you will get something like 
`"id""fullpath""published""creationDate""modificationDate""name""shortDescription"`
This PR adds validation and also makes the column separator a required field.
The validation also makes sense for custom exports which perhaps also might need some validation.
=> [Data object grid] Validate grid export form on submit

models/Document/Editable/Snippet.php
regression of #8684
Causes saving documents to fail, because of `Service::cloneMe()` that creates a deep copy of the object and replaces references to documents with `ElementDescriptor`. 
See: 
https://github.com/pimcore/pimcore/blob/c2b5b40217a6d3fcfe7bbf18ba65745d28ebc213/models/Document/PageSnippet.php#L636
=> Fixed property type definition

lib/Navigation/Builder.php
Follow up to #8910 for `6.9` branch. 
Reverts  #8863
=> Revert "Bugfix for incorrect maxDepth comparison"

models/Notification/Service/NotificationService.php
If I send a notification to a role with ID 2, I will also send notifications to role 20 and others.
Maybe it would be better if there was a leading and a trailing comma in this type of column.
=> Fix: NotificationService::sendToGroup() has unsafe role condition

lib/Web2Print/Processor/HeadlessChrome.php
The $event should be the first argument in Symfony 5
=> HeadlessChrome Processor: Fix EventDispatcher call

composer.json, phpstan-baseline.neon
The new phpstan-symfony version ignores empty array parameters now.
See https://github.com/phpstan/phpstan-symfony/releases/tag/0.12.32
=> Update phpstan-symfony (Non-empty parameter array might be empty in different environment)

bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
=> Fix: Assets Paths not working for Login Sreen Image after update to 6.9

bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
=> Fix: Assets Paths not working for Login Sreen Image after update to Pimcore X

doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
`web/var/tmp` does not exist anymore after the step `Rename web/ to public/` is done.
After moving `app/AppKernel.php` you have to put it to namespace `App` and rename the class to `Kernel`, otherwise you get `Defined Kernel Class \App\Kernel not found`
=> [Docs] Fix upgrade instructions

bundles/CoreBundle/Migrations/Version20210408153226.php, bundles/CoreBundle/Migrations/Version20210412112812.php
Steps to reproduce problem:
1. Install Pimcore 10 with `composer create-project --prefer-dist pimcore/skeleton:dev-master` and `./vendor/bin/pimcore-install`
2. Directly after run `composer update`
Without this PR a migration will fail with 
```
An exception occurred while executing 'ALTER TABLE `versions` ADD `autoSave` TINYINT(4) NOT NULL DEFAULT 0':                                                                                                                                                                                                       
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'autoSave' 
```
The actual reason is that this operation is already done in https://github.com/pimcore/pimcore/blob/7fbbbf9413885e0b97fe64f2d52871021a7da0da/bundles/InstallBundle/ …
=> [X installation] Make migrations idempotent

bundles/AdminBundle/EventListener/AdminAuthenticationDoubleCheckListener.php
That ensures that `^/admin` is protected no matter if controllers implement `DoubleAuthenticationControllerInterface` or if the right Symfony Security config is in place. 
This adds an additional layer of security to the admin interface. 
If you don't want that behavior for certain routes, you can exclude them individually using: 
```yml
pimcore: 
admin: 
unauthenticated_routes: 
- { route: YOUR_ROUTE_NAME}
```
=> Make AdminAuthenticationDoubleCheckListener additionally use the Pimcore context

models/DataObject/ClassDefinition/Data/ImageGallery.php
when adding a lot of hotspots with additional data (objects, e.g.) the database datatype text is not sufficient.
the hotspots text is then cut off and the hotspots won't load anymore in the pimcore backend. 
Therefore I propose to update to database type longtext instead to make sure all hotspots are stored correctly
=> Update pimcore image gallery hotspots from database type text to longtext

lib/Document/Adapter/Ghostscript.php
When you have only installed the gs command without the pdftotext command, the getText method write an error in the maintenance cronjob and the method return no text.
=> Fix: getText not work with ghostscript only

lib/Document/Adapter/Ghostscript.php, lib/Document/Adapter/LibreOffice.php
Now I get following warnings/errors in the maintenance cronjob, when a user add new PDFs:
```
php bin/console maintenance
17:02:26 WARNING   [pimcore] Exception: No 'soffice' executable found, please install the application or add it to the PATH (in system settings or to your PATH environment variable in /var/www/html/vendor/pimcore/pimcore/lib/Tool/Console.php:132
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/lib/Document/Adapter/LibreOffice.php(71): Pimcore\Tool\Console::getExecutable('soffice', true)
#1 /var/www/html/vendor/pimcore/pimcore/lib/Document/Adapter/LibreOffice.php(37): Pimcore\Document\Adapter\LibreOffice::getLibreOfficeCli()
#2 /var/www/html/vendor/pimcore/pimcore/lib/Document.php(98): Pimcore\Document\Adapter\LibreOffice->isAvailable()
#3 …
```
=> Show not found executables only in verbose and without complete stack trace

doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md, lib/Workflow/Manager.php
Resolves #7586
[Fix] Call element `saveVersion()` when workflow option `save_version` is set, otherwise call element `save()`. This allows element to unpublish when `force_unpublished` option is set.
=> [Workflows] Fix object not unpublished with force_unpublished option

bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
Correct way to check for array key existence to prevent errors / warnings
Correct check for array key existence
=> [EDITABLES] Fix wrong array key check
