- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
- doc/Development_Documentation/26_Best_Practice/20_Working_With_Runtime_Cache.md
- models/DataObject/AbstractObject.php
- models/Document.php
> [DataObjects/Documents] Clear children cache on child delete

- .github/ISSUE_TEMPLATE.md
Previous no longer works with no redirect
Resolves #
> Updated issue template with new demo link

- models/Asset.php
- models/DataObject/AbstractObject.php
- models/Document.php
- models/Element/AbstractElement.php
- models/Element/Service.php
> [Elements] Cache keys should be generated in a central place for consistency

- models/DataObject/ClassDefinition.php
Allows to compare with the existing one while saving the new one.
Needed for #5782
> ClassDefinition: add force option

- lib/Model/Listing/AbstractListing.php
> [Listings] Prevent infinite loop

- doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md
- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/02_HeadMeta.md
- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/04_HeadStyle.md
- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/05_HeadTitle.md
- doc/Development_Documentation/02_MVC/02_Template/04_Thumbnails.md
> Added twig templates for MVC part of documentation

- models/Element/Recyclebin/Item.php
see https://github.com/pimcore/pimcore/pull/5981#issuecomment-595669615
> [Recyclebin] null out class definition

- lib/Maintenance/Tasks/AssetDocumentConversionTask.php
- models/Asset/Document.php
- models/Search/Backend/Data.php
> [Asset] getText() on documents should process the asset synchronously called from CLI

- bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/Product.php
- bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/ProductType.php
> [Ecommerce] Filters - fix array params for Product & ProductType

- bundles/CoreBundle/Resources/migrations/Version20200310122412.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
> Add in_preparation_queue index to store table

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
> [Assets] Exception handling - trigger error message in admin UI - #5912

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
> Localized field translate labels in tabs

- bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
- bundles/CoreBundle/EventListener/Frontend/ElementListener.php
Fixes #5893
Fixes #2704
Related #2826
> [Core] Fixed route collisions caused by same path prefixes of assets and documents in combination with unpublished documents

- models/DataObject/ClassDefinition/Data/Date.php
- models/DataObject/ClassDefinition/Data/Datetime.php
> [DataObjects] Date/Datetime - save current default date to db - #5594

- bundles/EcommerceFrameworkBundle/Controller/IndexController.php
Event parameters do have the wrong order
> Correct incorrect parameter order of Event

- bundles/CoreBundle/Command/ThumbnailsImageCommand.php
> [THUMBNAILS] add option for single asset-image thumbnail generator

- models/Asset/Image/Thumbnail.php
Reported here: https://github.com/pimcore/pimcore/pull/5443#issuecomment-600033385
Regression of #5443
> [Asset] config webp_auto_support is not respected anymore

- composer.json
- doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Mail.php
> [Mail] Use html2text\html2text library for html to text generation

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
> [Admin] Tree search case insensitive for Assets & Documents

- bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
> [Redirects] Allow target assets drag-n-drop on UI

- bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/xliff.js
> [Translations] XLIFF Export - Fix to export elements with same id

- .travis.yml
- .travis/run-stan.sh
With #6076 I ignored the tests without baseline. With this it should work again
> [PHPStan] Fix tests without baseline

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> Dynamic select in grouped objectbricks

- bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
> Classification Store only works in Grid Options with "Classes" Permissions

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
> [Data Objects] Grid Configurator - Fix preview for dynamic select types

- bundles/AdminBundle/Controller/Admin/UserController.php
> Cloning user does not clone "shared translation" rights

- bundles/AdminBundle/Controller/Rest/Helper.php
- doc/Development_Documentation/24_Web_Services/01_Query_Filters.md
> [Webservices] $or filter not working

- models/DataObject/ClassDefinition/Data/Hotspotimage.php
> HotspotImage: fixed notice

- models/DataObject/ClassDefinition/Data/RgbaColor.php
> Cannot save object with RGBA color field inside block

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
> [Admin] DataObjects Grid - fix grid cell editing regression of #6087

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/EmailController.php
- bundles/AdminBundle/Controller/Admin/Document/FolderController.php
- bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
- bundles/AdminBundle/Controller/Admin/Document/LinkController.php
- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
- lib/Db/ConnectionInterface.php
- lib/Extension/Document/Areabrick/AreabrickManagerInterface.php
- phpstan-baseline.neon
Before
```
[ERROR] Found 488 errors
```
After
```
[ERROR] Found 480 errors
```
> [PHPStan] Fixes

- bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
- bundles/CoreBundle/Resources/translations/en.extended.json
- models/Asset/Image/Thumbnail.php
- models/Asset/Image/Thumbnail/Config.php
- models/Asset/Image/Thumbnail/Processor.php
- models/Asset/Thumbnail/ImageThumbnailTrait.php
> [Asset] Thumbnails: add configuration for 1x1 image placeholder, where no image is wanted

- bundles/AdminBundle/Resources/public/css/editmode.css
> [Admin] Document editmode - Add fixed height for Areablock toolbar

- bundles/AdminBundle/Resources/public/css/icons.css
> Removes odd (incorrect?) selector

- bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
> [Admin] Token generated links should bypass 2FA

- doc/User_Documentation/05_DataObjects/02_CSV_Import/README.md
Added paragraphs for CSV configuration import and export
Related to this [Pull Request](https://github.com/pimcore/pimcore/pull/6092)
> Update 02_CSV_Import Readme.md

- bundles/CoreBundle/Migrations/Version20191114123638.php
> [Core] Fix Migration 20191114123638

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
> [Admin] Fix saving object should update modification date

- bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
Resolves #6126
Instead of two arrays for job, we reuse one - now we have a chain of `add, delete, add, delete` jobs.
> Delete job will be executed right after its add to recycle bin job.

- models/Asset/Image/Thumbnail.php
- models/Asset/Thumbnail/ImageThumbnailTrait.php
> [Asset] Image thumbnail: <picture> tag for SVGs shouldn't have a srcset and had wrong mime-type

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/12_Adding_Object_ Layout_types.md
Resolve #6148 
Created in private, so actually with @skoch98 ;-)
> Added support for additional layout types

- bundles/CoreBundle/Controller/PublicServicesController.php
- models/Asset/Image/Thumbnail/Config.php
Regression of #6085
Fixes #6177
> [Asset] Thumbnail media query bug fix, regression of #6085

- models/DataObject/Concrete/Dao/InheritanceHelper.php
```
ErrorException: Notice: Undefined index: id in vendor/pimcore/pimcore/models/DataObject/Concrete/Dao/InheritanceHelper.php:401
Stack trace:
#0 vendor/pimcore/pimcore/models/DataObject/Concrete/Dao/InheritanceHelper.php(530): Pimcore\Model\DataObject\Concrete\Dao\InheritanceHelper->filterResultByLanguage(Array, 'de', 'position')
#1 vendor/pimcore/pimcore/models/DataObject/Concrete/Dao/InheritanceHelper.php(620): Pimcore\Model\DataObject\Concrete\Dao\InheritanceHelper->getRelationsForNode(Array, Array)
#2 vendor/pimcore/pimcore/models/DataObject/Concrete/Dao/InheritanceHelper.php(253): Pimcore\Model\DataObject\Concrete\Dao\InheritanceHelper->getIdsToUpdateForRelationfields(Array, 'files', Array)
#3 vendor/pimcore/pimcore/models/DataObject/Localizedfield/Dao.php(390): …
```
> [InheritanceHelper] Fix Notice: Undefined index

- bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
> Batch edit with Grid Locking

- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
> Language selector in Grid options don't change language in view

- bundles/CoreBundle/EventListener/Frontend/ElementListener.php
- lib/Localization/LocaleService.php
> [Routing] Locale not set consistently (Translator, ...) when fallback document is used

- bundles/AdminBundle/Helper/GridHelperService.php
- models/DataObject/ClassDefinition/Data/Checkbox.php
- models/DataObject/ClassDefinition/Data/Consent.php
- models/DataObject/ClassDefinition/Data/Datetime.php
> [DataObjects Grid] Fix Objectbricks filter query

- bundles/CoreBundle/Migrations/Version20200407120641.php
- models/DataObject/Classificationstore/Dao.php
> Check classificationstore_data and groups tables for improvements

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
> [Assets] Upload from zip error handling

- bundles/CoreBundle/Migrations/Version20200407132737.php
- bundles/InstallBundle/Resources/install.sql
> Check uuid table for improvements

- bundles/CoreBundle/Migrations/Version20200407145422.php
- bundles/InstallBundle/Resources/install.sql
- models/Element/Note/Listing/Dao.php
contributes to #6133 
cid and ctype will always be used together as only the combination identifies a specific element
> Check notes table for improvements

- bundles/CoreBundle/Migrations/Version20200410112354.php
- bundles/InstallBundle/Resources/install.sql
- models/Property/Dao.php
> Check properties table for improvements

- bundles/AdminBundle/Controller/Admin/SettingsController.php
- bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
- bundles/CoreBundle/Resources/translations/en.extended.json
> [Asset] Thumbnails: Possibility to change order of media queries

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- models/DataObject/ClassDefinition/Data/Classificationstore.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
fixes a couple of undefined index notices as well as #6139
> Classificationstore: fix undefined index notices + default value

- bundles/AdminBundle/Resources/public/css/editmode.css
> [Admin] Document Editmode - Fix Areablock vertical toolbar

- models/DataObject/Localizedfield/Dao.php
> [DataObjects] Fix default value for localized fields

- models/DataObject/ClassDefinition/Data/QuantityValue.php
Data from the database is a string. Should be casted to float.
> [QuantityValue] Value should be a float

- models/DataObject/ClassDefinition/Data.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
> [LocalizedFields] - Exclude from Backend Full Text Search not working

- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
> [DataObject] Advanced Relations - Fix object cannot be saved with boolean column

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/block.js
> Classdefinition - Block datatype - disable "visible in grid" option

- bundles/AdminBundle/Resources/public/js/pimcore/startup.js
See https://xhr.spec.whatwg.org/#the-open()-method for more info on why
> Prevents synchrounous XHttpRequest for update check

- bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
- bundles/CoreBundle/EventListener/Frontend/ElementListener.php
- bundles/CoreBundle/EventListener/Frontend/LocaleListener.php
- lib/Localization/LocaleService.php
> [Routing] Locale not set consistently (Translator, ...) follow up to #6203

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
- bundles/CoreBundle/Resources/translations/en.json
> [DataObject] [Slider] Improve display of the slider component

- bundles/AdminBundle/Resources/public/js/pimcore/object/class.js
- bundles/CoreBundle/Resources/translations/en.json
> [Improvement] Add name of the class when about to be deleted

- models/Document/Tag/Snippet.php
Resolves https://github.com/pimcore/pimcore/issues/6199
> [Full-Page-Cache] Fix: Wrong links in multi site system

- models/User/AbstractUser.php
Fixes #6247
More generic approach than #6247
> [Users] Remove all children recursively on delete

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
- models/DataObject/ClassDefinition/Data/UrlSlug.php
- models/DataObject/Localizedfield/Dao.php
- models/DataObject/Objectbrick/Data/Dao.php
> [Data objects] Default value generator service for URL Slugs

- bundles/AdminBundle/Controller/Admin/SettingsController.php
> [Admin UI] Website Settings - Add checks for update/delete requests

- lib/Document/Renderer/DocumentRenderer.php
- lib/Http/RequestHelper.php
> Fix: New Request() in DocumentRenderer clears RequestContext Data

- models/Document/TargetingDocument.php
> [Documents] Targeting - Fix endless loop in Targeting Document

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
- models/DataObject/ClassDefinition/Data.php
- models/DataObject/Concrete.php
> [DataObject] Fix getBy filter for relation fields

- bundles/CoreBundle/Migrations/Version20200421142950.php
- models/DataObject/ClassDefinition.php
> [DataObjects] Complete getBy method annotations

- bundles/AdminBundle/Resources/public/js/pimcore/settings/recyclebin.js
different approach for https://github.com/pimcore/pimcore/pull/6198
> [Receyclebin] Refresh of custom-view trees on restore

- bundles/CoreBundle/Migrations/Version20200422090352.php
- bundles/InstallBundle/Resources/install.sql
Resolves partially #6133
cpath & userId combination used for isAllowed calls https://github.com/pimcore/pimcore/blob/ae677a1de09d1c488cce9cea3ba95a3e44954ae0/models/DataObject/AbstractObject/Dao.php#L471
> Check user_workspaces_* table permissions

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/Data/BlockElement.php
- models/Element/ElementDescriptor.php
- models/Element/Recyclebin/Item.php
- models/Version.php
- models/Version/ElementDescriptor.php
- models/Version/UnmarshalMatcher.php
> Move ElementDescriptor to Pimcore\Model\Element namespace

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
> Fixed bug with tabs in read-only fieldcollection

- bundles/AdminBundle/Controller/Admin/TranslationController.php
- bundles/AdminBundle/Resources/public/js/pimcore/functions.js
- models/Translation/AbstractTranslation.php
> Added translation support for longer texts

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/04_V4_to_V6.md
> [DOCS] Clearify upgrade process

- bundles/AdminBundle/Controller/Admin/ElementController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/replace_assignments.js
- bundles/CoreBundle/Resources/translations/en.json
- bundles/CoreBundle/Resources/translations/pl.json
- models/Dependency.php
- models/Dependency/Dao.php
Results grid in File -> Search and Replace Assignments now supports pagination.
> Search and replace pagination

- lib/Routing/Element/Router.php
Follow up to #6281
Resolves issues with the data-hub
> [Routing] Element Router must implement RouterInterface

- lib/Google/Cse.php
> [Google CSE] fix params as per new definition

- bundles/CoreBundle/Migrations/Version20200428082346.php
- bundles/InstallBundle/Resources/install.sql
> Support for UTF8 URLs in HTTP error log

- bundles/AdminBundle/Controller/Admin/AssetController.php
> [Asset] Fix content type for SVG rasterized images

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
- models/DataObject/ClassDefinition/Data/UrlSlug.php
> [Admin] DataObjects - URL Slugs readonly layout fix

- models/DataObject/ClassDefinition/Data/Localizedfields.php
> Problem saving objects with inherited mandatory attributes

- bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
- bundles/AdminBundle/Resources/public/js/pimcore/helpers/generic-grid.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/columnConfigDialog.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/keySelectionWindow.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/relationSelectionWindow.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
- models/DataObject/ClassDefinition/Data/Classificationstore.php
> Added classification-store translation support

- lib/Sitemap/Document/Filter/DocumentTypeFilter.php
Resolves #6053
please see https://github.com/pimcore/pimcore/issues/6053#issuecomment-603162070
> [Sitemap] Ignore hardlinks

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- models/DataObject/Traits/DefaultValueTrait.php
> [Data Objects] [Inheritance] Values at child not getting inherited from parent.

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
> [Admin] DataObjects - Disable reordering for not editable Advanced Relations

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data/Fieldcollections.php
- models/DataObject/ClassDefinition/Data/Objectbricks.php
> [DataObject] ObjectBrick/FieldCollection - Add Maximum limit validation in API

- bundles/EcommerceFrameworkBundle/Command/CleanupPendingOrdersCommand.php
- bundles/EcommerceFrameworkBundle/Command/Voucher/CleanupReservationsCommand.php
- bundles/EcommerceFrameworkBundle/Command/Voucher/CleanupStatisticsCommand.php
- bundles/EcommerceFrameworkBundle/PricingManager/Condition/AbstractOrder.php
- bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
- bundles/GeneratorBundle/Command/GenerateBundleCommand.php
- models/Asset/WebDAV/File.php
- models/Asset/WebDAV/Folder.php
- models/DataObject/Objectbrick/Dao.php
- models/Document/Hardlink/Wrapper.php
- models/Document/Tag.php
- models/Document/Tag/Area.php
- models/Document/Tag/Areablock.php
- models/Document/Tag/Block.php
- models/Document/Tag/TagInterface.php
- phpstan-baseline.neon
After Update > 0.12.24 PHPStan merge inherited PHPDocs
See https://github.com/phpstan/phpstan/releases/tag/0.12.24
So some new errors appears.
> [PHPStan] Fix current errors after phpstan update

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
Updates the API URLs for Datatrans according to their documentation: 
https://docs.datatrans.ch/docs/api-usage
> Change API URL for Datatrans

- bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js
> [Workflow] Translation label is not translated in notification

- bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
> [Admin] Documents - Fix "save, publish & close" option

- bundles/EcommerceFrameworkBundle/CartManager/MultiCartManager.php
Typo fixed and new function getAllCartsForCurrentUser to make it extendable
Makes it more easy to extend initSavedCarts method by overwriting the new getAllCartsForCurrentUser method. Otherwise you have to copy the whole method to change the the current user functionality.
We need this in our current project where not the logged in user is related to the cart but another entity called accountUser which is also held in environment.
> Typo fixed and new function getAllCartsForCurrentUser

- lib/Workflow/MarkingStore/StateTableMarkingStore.php
> [Workflow] Fix saving document workflow state

- doc/Development_Documentation/18_Tools_and_Features/01_Versioning.md
"$previousVersion = $versions[count($versions)-2]" this way we can get previousVersion.
Resolves #
> [DOCS] Update 01_Versioning.md

- models/Element/Service.php
That solves issues with DataObjects Linked to Doctrine Entities, also it optimizes the save-size of relations, not the full element is serialized, only its type and id.
> use ElementDescriptor for Session saving

- bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
- bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionField.php
- models/DataObject/ClassDefinition/Data.php
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/Extension/Text.php
- models/DataObject/ClassDefinition/Data/ExternalImage.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/StructuredTable.php
- models/DataObject/ClassDefinition/Data/Time.php
- models/DataObject/ClassDefinition/Data/UrlSlug.php
- models/DataObject/Fieldcollection.php
Fix wrong PHP docs of isEmpty methods and optimize some code inside.
> Fix: Data::isEmpty() methods have wrong PHP docs

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/MiscController.php
- bundles/AdminBundle/Controller/Admin/SettingsController.php
- bundles/AdminBundle/Controller/Admin/TranslationController.php
- bundles/CoreBundle/Command/InternalUnicodeCldrLanguageTerritoryGeneratorCommand.php
- bundles/CoreBundle/Command/Targeting/MigrateElementNamesCommand.php
- bundles/CoreBundle/Resources/config/aliases.yml
- bundles/CoreBundle/Resources/config/commands.yml
- bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
- phpstan-baseline.neon
`Pimcore::getContainer()` should be avoided if possible
> Avoid Pimcore::getContainer() in Controller/Commands

- doc/Development_Documentation/26_Best_Practice/10_Advanced_Pricing_System.md
'@pimcore_ecommerce.pricing_manager' should be: '@pimcore_ecommerce.locator.pricing_manager'
> Dokumentation change pricing_manager locator

- bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectFromMultiSelect.php
Hello,
This PR fix a notice error because undefined index when using select to SelectFromMultiselect filter (seems it has been forgotten for this one as the MultiselectFromMultiselect filter check well if set/empty already).
Thanks.
> Ecommerce fix notice filter

- bundles/AdminBundle/Controller/Admin/InstallController.php
- bundles/CoreBundle/Command/RequirementsCheckCommand.php
- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
- lib/Tool/Requirements.php
For CD/CI purposes, this PR is intented to provide a new console command to check if all the system requirements are satisfied. This is the same process as the one in the dedicated page in the UI.
There is also a special option to report only warning and/or errors.
This also provide a new static method to perform all the checks in one line (ready for some more future checks if necessary).
> [Console command] System requirements check

- bundles/CoreBundle/Command/SearchBackendReindexCommand.php
- lib/Document/Adapter/Ghostscript.php
- lib/Document/Adapter/LibreOffice.php
Related to #6289  (partly resolves)
> [Search Backend] consider Pdf content generation for search backend reindex

- bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/glossary.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/website.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/videothumbnail/item.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
> [Admin] XSS Protection for grids

- bundles/AdminBundle/Controller/Admin/ElementController.php
- bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js
- models/Element/Service.php
> Sometimes Objects cannot be found when click "Show In Tree"

- bundles/CoreBundle/Migrations/Version20200529121630.php
- models/DataObject/ClassDefinition/Data.php
- tests/_support/Helper/Model.php
- tests/model/LazyLoading/ManyToManyRelationTest.php
> [Data Object] Incorrect/inconsistent behavior with unpublished relations

- bundles/AdminBundle/Resources/public/css/admin.css
- bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
- lib/Tool/Admin.php
Some things we missed with the JS Routing PR
> further usage of routing

- models/Asset/Video/Thumbnail/Processor.php
Resolves broken video preview generation by remove unnecessary chmod()
> [Video Thumbnails] Fix video preview generation

- models/Element/Service.php
Basically the same Problem we have with copy and had with versions now fixed for Session saving as well.
I will provide a proper PR for all DeepCopy related parts for 7.0.
> fix session save for objects with complex linked entities as well

- models/Document/Tag/Video.php
CSS classes are ignored otherwise. Class should be working as described in the docs: https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Video.html
> Add class to html output of video editable

- lib/Routing/Staticroute/Router.php
seems that part from this PR https://github.com/pimcore/pimcore/pull/5946 got removed with this PR https://github.com/pimcore/pimcore/pull/6096 by accident
> fix staticroute router

- bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
fixes enhanced ecommerce tracking when there is no price available
> Fix Tracking when there is no price available

- doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md
- models/Document/Tag/Snippet.php
> [Documents] Snippet - Add Cache option

- lib/Routing/Element/Router.php
> [ElementRouter] Support query parameter and reference type

- .travis/setup-db-server.sh
… because getting the keys from gnupg.net sometimes fails
> [Travis] DB install with --allow-unauthenticated

- models/User/Folder.php
- models/User/UserRole/Folder.php
> [Users/Roles] Add getChildren() method for user/role folders

- lib/Config.php
Just happened to notice this while writing #6522
> Cleanup of commented try and nested if

- bundles/CoreBundle/Migrations/Version20200604110336.php
- models/DataObject/Localizedfield.php
- models/DataObject/Objectbrick/Definition.php
- tests/_support/Helper/Model.php
- tests/_support/Resources/objects/brick-import.json
- tests/_support/Resources/objects/inheritance.json
- tests/model/Inheritance/ObjectbrickTest.php
> [Data Objects] fields in bricks are not set on object creation

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
If I'm not mistaken, it works like this.
> Fix example code in the docs

- bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
> fix brick route

- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
> [Admin] Editmode - Fix "pimcore_admin_asset_getimagethumbnail" does not exist

- bundles/AdminBundle/Controller/Reports/CustomReportController.php
- bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Resolves #6408
The creation of the file gets split in several chunks to prevent a timeout. The progress is returned after each chunk and the client keeps resuming until the server says that it's finished with the creation of the file.
A progress bar to show the current progress was also added.
> CustomReport | CSV Download with progress bar #6408

- bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
> [Bug] Download as ZIP causes redirect to JSON file

- models/Element/Service.php
> [Document|Asset] + sign shouldn't be allowed in keys

- models/DataObject/Concrete.php
> Mandatory Fields Error is not User Friendly

- bundles/AdminBundle/Resources/public/css/icons.css
Resolves  #6098
Missed those lines in previous PR
> Resolve semiotic alignment of external/internal vs export/import

- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
> [Documents] Fix moving multiple documents for auto redirects

- .travis.yml
> [Travis] Builds for tags shouldn't be excluded

- bundles/AdminBundle/Controller/Searchadmin/SearchController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
With this PR it gets possible to sort data object search results by class name.
> [Object search] Sort by class name

- bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
> Unable to add/edit classification store

- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
> Unable to upload asset through ManyToOne(Many)Relation

- bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
> [Assets] Fix route for upload zip archive

- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
fixes #6592
regression of #6437
> Fix put mapping during reindex for elasticsearch5

- models/Asset/Video.php
Regression of #6388
Fix video upload error
> [Assets] Fix uploading new videos error

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
> "Paste as Child" not working since Backend Routing rework

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/70_Relation_Types.md
> ManyToManyRelations do now need type

- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- Element CSS class should be applied on tree
- Apply admin style for document publish/unpublish
> AdminStyle Improvements

- bundles/AdminBundle/Helper/GridHelperService.php
> [DataObjects] Grid - Fix sorting & filter for grid fields

- models/Element/AdminStyle.php
Resolves #6470 
Dependency on #6617
> [Admin] Documents tree - Update visibility based on exclude_from_navigation

- bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- lib/Pimcore.php
> Fix issues with shutdown when running cache warming / building the container 

- bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
> Pagination gets lost

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- lib/DataObject/Import/ColumnConfig/Value/DefaultValue.php
- lib/DataObject/Import/Resolver/Filename.php
- lib/DataObject/Import/Resolver/Fullpath.php
- lib/DataObject/Import/Resolver/GetBy.php
> [CSV Import] Fix undefined properties

- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
Fixes error 500 in version preview / diff of objects with Advanced Many-to-many Object Relation.
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getRealFullPath() on null" at /var/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php line 346 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getRealFullPath() on null at /var/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php:346)"} []
```
> Bugfix: Version preview/diff error (Advanced Many-to-many Object Relation)

- bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridCellEditor.js
> [Data Objects] grid cell editor for quantity value broken

- bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/tags/abstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridCellEditor.js
> [Asset] Listfolder grid celleditor window broken

- models/DataObject/ClassDefinition/Data/QuantityValue.php
> [QuantityValue] Fix notice: Undefined offset: 1

- models/DataObject/ClassDefinition/Data/UrlSlug.php
> [DataObjects][UrlSlug] isEmpty implementation is wrong

- models/DataObject/ClassDefinition/Data/UrlSlug.php
> Slug inheritance

- models/DataObject/ClassDefinition/Data/QuantityValue.php
See comment in https://github.com/pimcore/pimcore/pull/6647
> [QuantityValue] CSV Export/Import with abbreviation instead of unit ID

- bundles/AdminBundle/Resources/public/css/admin.css
see https://github.com/pimcore/pimcore/issues/6501
> [UI] Disabled toolbar buttons are hard to see

- bundles/AdminBundle/Resources/public/js/pimcore/object/folder.js
> [DataObject] Fix route generation for folders save

- models/DataObject/ClassDefinition/Data/Objectbricks.php
> [DataObject] Objectbricks - Fix saving inherited bricks with OmitMandatoryCheck

- models/DataObject.php
- models/DataObject/AbstractObject.php
> [DataObject] Fix DataObject alias for AbstractObject

- bundles/CoreBundle/Resources/config/routing.yml
- bundles/CoreBundle/Resources/config/services_routing.yml
- lib/Routing/Loader/FOSJsRoutingLoader.php
> Fix: FOSJsRouting for symfony 3.4

- bundles/AdminBundle/Resources/public/js/pimcore/helpers/quantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
> [Admin] UI Improvement - Set allowed units to empty array when saving a quantityvalue attribute.

- bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/MultiSelect.php
- bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/NumberRange.php
- bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/Select.php
- bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/SelectCategory.php
- bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultFactFinder.php
- bundles/EcommerceFrameworkBundle/IndexService/Config/FactFinderConfigInterface.php
- bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/07_Product_List.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Ecommerce] Deprecate FactFinder integration

- lib/Mail.php
- lib/Mail/Plugins/RedirectingPlugin.php
Hello,
This fix some sending email notice errors (we try to use Pimcore with E_ALL for front-end development, and we were hitting those ones).
Thanks.
> Fix notice errors with send mail

- bundles/AdminBundle/Helper/GridHelperService.php
1. Open Asset Folder
2. Filter file name with no input
3. Get error:
> [GridHelperService] Fix Notice: Undefined index: value

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js
Resolves #6710 
Regression from #6515
> Fix JS error in areablock when no limits are set

- models/DataObject/ClassDefinition/Data/QuantityValue.php
> Objectbrick data is not loaded

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
> Implement saveToSession for assets

- bundles/EcommerceFrameworkBundle/FilterService/Helper.php
Hello,
It replace https://github.com/pimcore/pimcore/pull/6724
This new one PR is based on 6.6 branch and for 6.6 branch so.
Thanks
> Fix ecommerce filter to keep order

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
> [DataObjects/Documents] Fix modification date updated from last published version

- models/DataObject/ClassDefinition.php
- models/DataObject/Concrete/Dao.php
> [Console Commands] Fix classes:rebuild -d fails when trying to delete a class

- bundles/AdminBundle/Controller/Admin/WorkflowController.php
> [Workflows - Data Objects / Documents ] Update modification date during workflow transition publish

- models/DataObject/Data/BlockElement.php
- models/DataObject/Fieldcollection/Dao.php
- models/DataObject/Fieldcollection/Data/Dao.php
> [DataObject] Block in Fieldcollection not working anymore #6726

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/13_Amazon_AWS_Setup/03_Amazon_AWS_S3_Setup.md
path location is wrong for assets in mirgration command
Resolves #
> [Docs] Update 03_Amazon_AWS_S3_Setup.md

- bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/email/blacklist.js
> [Admin] XSS Protection

- doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
> [Docs] Update 03_Working_with_PHP_API.md

- lib/DataObject/Import/Resolver/Filename.php
> [Data Objects] CSV Import - New Objects Based On Key

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
> CSV Export: no carriage return every 20 lines

- models/DataObject/ClassDefinition/Data/Block.php
The data could be saved, but if you want load it you get an SQL error.
> Fix: Pimcore can't load object bricks with localized block fields

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/fieldcontainer.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/layout.js
> An Ext.form.Fieldcontainer does not have a title

- models/Element/PermissionChecker.php
> [Admin] Users - Fix permissions analyzer result

- doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/15_Custom_Layouts.md
> Added note about sensitive data usage

- tests/_support/Helper/DataType/TestDataHelper.php
- tests/_support/Helper/Model.php
- tests/_support/Resources/objects/class-import.json
- tests/_support/Test/DataType/AbstractDataTypeTestCase.php
- tests/_support/Util/TestHelper.php
> [Tests] Model - Add test for Boolean Select field

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
> Image in image-editable breaks if too many Hotspots

- lib/Translation/ImportDataExtractor/Xliff12DataExtractor.php
> Cope with missing target tags in xliff import file

- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
> [Documents] Newsletter - Fix no preview button available in toolbar

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/DataObject/GridColumnConfig/Operator/ObjectBrickGetter.php
> Deprecate objectbrickgetter

- docs/Development_Documentation/13_Installation_and_Upgrade/09_Upgrade_Notes/01_Witin_V4.md
> [DOCS] Add info about MySQL charset changes to Pimcore 4 upgrade notes

- bundles/AdminBundle/Controller/Reports/AnalyticsController.php
> Notice: Undefined index: ga:uniquePageviews #6796

- doc/Development_Documentation/02_MVC/02_Template/02_Templating_Helpers/README.md
there is no add function available on $this->view
> [DOCS] no add function on $this->view

- lib/Model/Listing/AbstractListing.php
Only the setter can have a string as parameter. But the attribute and the getter is always an array.
> AbstractListing order attribute is always an array

- .travis/phpstan.s4.travis.neon
- .travis/phpstan.travis.neon
- composer.json
- phpstan.neon
> [PHPStan] Fix Ignored error

- lib/Translation/Escaper/Xliff12Escaper.php
This depending on the read string, it's not always the case.
Resolves #6786
@weisswurstkanone would you mind to share your opinion?
> asXml adds a version declaration, remove it when extracting content

- models/DataObject/ClassDefinition/Data/CustomDataCopyInterface.php
- models/Element/Service.php
similar to VersionMarshal and RecycleBinMarshal just for copy
> implement custom copy function for class-definition types

- bundles/CoreBundle/EventListener/PimcoreContextListener.php
- bundles/CoreBundle/EventListener/ResponseExceptionListener.php
> Force context resolving for error page 

- bundles/CoreBundle/Migrations/Version20200721123847.php
- bundles/InstallBundle/Resources/install.sql
Same column definition as e.g. objects.o_published
> [Database] Convert search_backend_data.published to tinyint

- models/Document/Hardlink.php
- models/Document/Page.php
[`Pimcore\Model\Document\Page::delete()`](https://github.com/pimcore/pimcore/blob/34f953311a296113636803b48880d87e2675bb1d/models/Document.php) and [`Pimcore\Model\Document\Hardlink::delete()`](https://github.com/pimcore/pimcore/blob/34f953311a296113636803b48880d87e2675bb1d/models/Document/Hardlink.php#L240-L252) delete items from the database but don't wrap this into a transaction. 
Their parent classes/methods [`Pimcore\Model\Document\PageSnippet::delete()`](https://github.com/pimcore/pimcore/blob/34f953311a296113636803b48880d87e2675bb1d/models/Document/PageSnippet.php#L184-L206) and [`Pimcore\Model\Document::delete()`](https://github.com/pimcore/pimcore/blob/34f953311a296113636803b48880d87e2675bb1d/models/Document.php#L789-L852) are wrapped into a transaction which is why I think these …
> Wrap page/hardlink deletion into transaction

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Controller/Admin/RecyclebinController.php
- bundles/AdminBundle/Controller/Admin/TagsController.php
- bundles/AdminBundle/Controller/Admin/TranslationController.php
- bundles/AdminBundle/Controller/Searchadmin/SearchController.php
- bundles/AdminBundle/Helper/GridHelperService.php
- bundles/CoreBundle/Command/LowQualityImagePreviewCommand.php
- bundles/CoreBundle/Command/ThumbnailsImageCommand.php
- bundles/CoreBundle/Command/ThumbnailsVideoCommand.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
- doc/Development_Documentation/26_Best_Practice/85_Using_Tags_for_Filtering.md
- lib/Db/ConnectionInterface.php
- lib/Db/PimcoreExtensionsTrait.php
- lib/Model/Listing/AbstractListing.php
- models/Asset/Dao.php
- models/DataObject/AbstractObject/Dao.php
- models/DataObject/Concrete/Dao/InheritanceHelper.php
- models/Document/Dao.php
- models/Document/Printcontainer/Dao.php
- models/Document/Service/Dao.php
- models/Element/PermissionChecker.php
- models/Element/Tag/Dao.php
> [Data objects] Objects of wrong folder displayed

- composer.json
Resolves temporarily #6825
Temporary fix needs to be reverted
> [Composer] Add conflicts for Symfony 3.4.43 & 4.4.11 due to regressions

- bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
> [Admin] Fix opening new assets

- bundles/AdminBundle/Controller/Admin/LoginController.php
- bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
- bundles/CoreBundle/Resources/config/pimcore/security.yml
Fixes issue described here: https://github.com/pimcore/pimcore/issues/6840#issuecomment-665491716
> Login page: CSRF token refresh on tab activate and before the PHP session expires

- models/DataObject/ClassDefinition/Data/Video.php
> [Data Object] Fixed Video CSV Import

- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
- doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
- doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md
- doc/Development_Documentation/03_Documents/01_Editables/34_Table.md
I have updated the documentation for current Editables:
- Area
- Select
- Snippet
- Table
> [Pimcore Docs] Update the documentation

- bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
fixes https://github.com/pimcore/pimcore/issues/6850
> Add getCategories for default Mockup

- bundles/AdminBundle/Controller/Admin/UserController.php
- bundles/CoreBundle/Controller/PublicServicesController.php
> [User] Invitation link - consider custom admin entry point for invitation links

- models/DataObject/AbstractObject.php
- models/DataObject/Concrete.php
- models/Document.php
- models/Document/Hardlink.php
- models/Document/Page.php
- models/Document/PageSnippet.php
Resolves #6821
Reason for master base #6821 (comment)
> [DataObject/Document] - Refactor delete() method to fix multiple event triggers

- models/DataObject/ClassDefinition/Data/Select.php
> [Admin] DataObject Grid - Fix filter condition for Select Types

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
> Object UI breaks if checkbox or Calculated field is added under field container

- bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
Resolves #6841  
Simple fix to javascript to pull in video preview thumbnails
> asset search shows video preview

- bundles/AdminBundle/Controller/Admin/UserController.php
> [User] Temporary link - consider custom admin entry point

- bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/EmailController.php
- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
- doc/Development_Documentation/03_Documents/03_Navigation.md
- doc/Development_Documentation/03_Documents/09_Working_with_PHP_API.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Targeting/Document/DocumentTargetingConfigurator.php
- lib/Templating/Renderer/TagRenderer.php
- lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
- lib/Translation/ImporterService/Importer/DocumentImporter.php
- models/Document/PageSnippet.php
- models/Document/PageSnippet/Dao.php
- models/Document/Service.php
- models/Document/Tag.php
- models/Document/Tag/Area.php
- models/Document/Tag/Area/Info.php
- models/Document/Tag/Block/AbstractBlockItem.php
- models/Document/Targeting/TargetingDocumentDaoInterface.php
- models/Document/Targeting/TargetingDocumentDaoTrait.php
- models/Document/Targeting/TargetingDocumentInterface.php
- models/Document/TargetingDocument.php
- models/Search/Backend/Data.php
- models/Webservice/Data/Document/PageSnippet.php
- tests/_support/Util/TestHelper.php
> [Document] Refactoring to unify document editable methods

- bundles/AdminBundle/Controller/Admin/DataObject/VariantsController.php
resolves #6898 
follow-up task #6906, this needs to be aligned
> Grid editing of quantity values in variants tab is broken

- models/Asset/Dao.php
- models/DataObject/AbstractObject/Dao.php
- models/Document/Dao.php
Currently you get a PHP notice `Trying to access array offset on value of type bool` when no element with the given fullpath can be found.
> [Element Dao] Prevent notice when no element gets found by getByPath()

- bundles/InstallBundle/Command/InstallCommand.php
- doc/Development_Documentation/01_Getting_Started/00_Installation.md
Log dir was changed here: https://github.com/pimcore/pimcore/commit/daba49f34e064cf72fca3cf0047981670a245759
> InstallCommand: Correct info to log file path

- doc/Development_Documentation/18_Tools_and_Features/02_Custom_Icons.md
> [Documentation] Improve AdminStyle Listener example

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
> Object grid: save query + sql condition

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
> [Documentation] Improve Plugin Backend UI example

- bundles/AdminBundle/Resources/public/js/pimcore/element/note_details.js
replaced non existent iconCls with white checkmark svg url
Removed non existent iconCls and replaced it with svg url
> Replace non existent icon

- lib/Image/Adapter/Imagick.php
regression from https://github.com/pimcore/pimcore/issues/5505
fixes:
see here: 
https://github.com/Imagick/imagick/blob/060c34ac7e7600ca8443059cc6104f80e8c7ef13/imagick_helpers.c#L1741
and here:
https://github.com/ImageMagick/ImageMagick/blob/fab704b6fc4ca4736278601e3790ce54ae684db4/MagickCore/image.h#L41
> fix [Imagick]: add compatibility fix for Imagick 3.4.4 and ImageMagick 7

- models/DataObject/AbstractObject.php
> [DataObject] Fix deleting folders

- models/Document/Tag/Relations.php
> [Documents] Fix saving relations editable

- bundles/CoreBundle/Controller/PublicServicesController.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Tool/HybridAuth.php
> Deprecate HybridAuth integration 

- bundles/EcommerceFrameworkBundle/Controller/ConfigController.php
- bundles/EcommerceFrameworkBundle/Controller/IndexController.php
- bundles/EcommerceFrameworkBundle/Controller/PricingController.php
- bundles/EcommerceFrameworkBundle/Controller/Reports/PiwikController.php
- bundles/EcommerceFrameworkBundle/Resources/config/pimcore/routing.yml
- bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/indexfieldselectionfield/data/indexFieldSelection.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/indexfieldselectionfield/tags/indexFieldSelection.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/indexfieldselectionfield/tags/indexFieldSelectionCombo.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/indexfieldselectionfield/tags/indexFieldSelectionField.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/order/OrderTab.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/panel.js
- bundles/EcommerceFrameworkBundle/Resources/public/js/voucherservice/VoucherSeriesTab.js
Not sure whether you want this in 6.6 or dev-master
> implement js-routing for commerce

- bundles/CoreBundle/DependencyInjection/Configuration.php
- bundles/CoreBundle/Resources/config/maintenance.yml
- lib/Maintenance/Tasks/VersionsCleanupStackTraceDbTask.php
- models/Asset.php
- models/DataObject/Concrete.php
- models/Document/PageSnippet.php
- models/Element/AbstractElement.php
- models/Version.php
> [Versions] Stack Trace - Add config option to disable trace & maintenance task for cleanup

- models/DataObject/ClassDefinition/Data/BooleanSelect.php
- models/DataObject/ClassDefinition/Data/CalculatedValue.php
- models/DataObject/ClassDefinition/Data/Checkbox.php
- models/DataObject/ClassDefinition/Data/Consent.php
- models/DataObject/ClassDefinition/Data/Date.php
- models/DataObject/ClassDefinition/Data/Datetime.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/ExternalImage.php
- models/DataObject/ClassDefinition/Data/Fieldcollections.php
- models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
- models/DataObject/ClassDefinition/Data/Hotspotimage.php
- models/DataObject/ClassDefinition/Data/Image.php
- models/DataObject/ClassDefinition/Data/Input.php
- models/DataObject/ClassDefinition/Data/Link.php
- models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
- models/DataObject/ClassDefinition/Data/Multiselect.php
- models/DataObject/ClassDefinition/Data/Numeric.php
- models/DataObject/ClassDefinition/Data/Password.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/Select.php
- models/DataObject/ClassDefinition/Data/Slider.php
- models/DataObject/ClassDefinition/Data/Textarea.php
- models/DataObject/ClassDefinition/Data/Video.php
- models/DataObject/ClassDefinition/Data/Wysiwyg.php
- models/DataObject/ClassDefinition/NullablePhpdocReturnTypeTrait.php
> More correct return value types

- models/Element/Tag.php
- models/Element/Tag/Dao.php
Similar to objects, assets and documents this PR adds the methods `Tag::getByPath()` and `Tag::__toString()`
> [Tags] Add Tag::getByPath() and Tag::__toString()

- lib/Translation/Escaper/Xliff12Escaper.php
> XLIFF Import deleting HTML special chars in 6.7.0

- models/Document/Tag/Video.php
Added the dnt parameter for cookieless embed.
> "Do not track" embed of Vimeo videos

- tests/Model/Element/DependenciesTest.php
> [Tests] Dependencies - Add tests for element dependencies

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
> [Admin] DataObjects - Disable bool meta column for non-editable relations

- lib/DataObject/Import/ColumnConfig/AbstractConfigElement.php
- lib/DataObject/Import/ColumnConfig/Operator/ObjectBrickSetter.php
> CSV import. ObjectBrick setter - Default mode is not set

- models/DataObject/Service.php
> Failing to load class definition for column config without admin permission or object instance

- bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
Closed  #7021 in favor of this one since rebasing duplicated commits
> correct image.js

- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/Concrete.php
> [DataObject] Fix validation exception shows stack trace when inheritance enabled

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
This pull request primarily aims at providing a proper https configuration for nginx. This is related to recent changes to the apache configuration, which adapts LetsEncrypt.
A few comments were added that might refer to external links. These have been added to better reflect certain behavior.
I have been running this (a bit similar) configuration myself.
> Provide https example for nginx configuration

- models/DataObject/ClassDefinition/Data/BooleanSelect.php
> boolean select csv import and export not working

- bundles/CoreBundle/Migrations/Version20200817133132.php
- models/DataObject/ClassDefinition/Dao.php
related to https://github.com/pimcore/pimcore/issues/6960
Resolves: #6960
> add primary key for relations table

- doc/Development_Documentation/03_Documents/03_Navigation.md
Given example is PHP only, adding working Twig one
Resolves #
> Adding Home page to navigation in Twig

- models/Element/Tag/Dao.php
Corrected the way the brackets are set in the sql query generation method
none - easy fix
> fix wrong brackets for dao sql query generation

- doc/Development_Documentation/22_Administration_of_Pimcore/07_Users_and_Roles.md
- **Backup**, **Bounce Mail Inbox** doesn't exist anymore
- **Plugins** renamed in **Extensions**
- **Website Translations** renamed in **Translations**
> [DOC] Cleanup permissions

- bundles/AdminBundle/Controller/Admin/TagsController.php
- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
- bundles/CoreBundle/Migrations/Version20200820151104.php
- bundles/InstallBundle/Resources/install.sql
> [Tags] Tag names should be unique in the same hierarchy level

- models/Document/PageSnippet.php
- models/Document/PageSnippet/Dao.php
> PageSippet: set/remove editable loses existing elements on save

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/EmailController.php
- bundles/AdminBundle/Controller/Admin/Document/FolderController.php
- bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
- bundles/AdminBundle/Controller/Admin/Document/LinkController.php
- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Controller/Admin/Document/PageController.php
- bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
- bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
- bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php
- models/Element/AdminStyle.php
Resolves #7047
AdminStyle should be updated for tree node on all document type save
> [Admin] Documents Tree - Fix AdminStyle on save

- models/Element/Service.php
> Fix deepcopy service method signature

- models/DataObject/Service.php
> Fix Pimcore 6.7 BC Break in Layout\Text rendering class

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
- models/DataObject/ClassDefinition/Data/Block.php
Resolves #7059
Similar fix like fieldcollections https://github.com/pimcore/pimcore/issues/1764
> [Admin] DataObject - Fix only save last filled localizedfields in Objectbricks/Blocks

- doc/Development_Documentation/18_Tools_and_Features/25_System_Settings.md
Add new recommended way to read system config in controllers to docs
> Add note about system config in php

- doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
- lib/Event/Model/TagEvent.php
- lib/Event/TagEvents.php
- models/Element/Tag.php
- models/Element/Tag/Dao.php
> [Tags] Add Events for add/delete/update, addTagToElement, removeTagFromElement

- doc/Development_Documentation/18_Tools_and_Features/03_Scheduling.md
I tried to improve the scheduling docs a bit.
> [Docs] Some scheduling improvements

- models/DataObject/ClassDefinition/NullablePhpdocReturnTypeTrait.php
> [DataObject] Classes - Fix generated docBlock for setters - append null

- bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollection.js
This fix was extracted from #7087
> Fix forbidden name check for fieldcollection

- lib/Document/Editable/DelegatingEditableHandler.php
- lib/Document/Editable/EditableHandlerInterface.php
> [Document] Deprecate DelegatingEditableHandler and EditableHandlerInterface 

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Docs] Add note about PR 7084 to upgrade notes

- bundles/AdminBundle/Controller/Admin/UserController.php
- models/User/AbstractUser.php
> [Users] Cleanup user-role relation when deleting a UserRole

- .travis.yml
> [Travis] Add PHP 8 Job

- bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
- bundles/CoreBundle/Migrations/Version20200807105448.php
- bundles/InstallBundle/Resources/install.sql
- models/DataObject/Data/QuantityValue.php
- models/DataObject/QuantityValue/Unit.php
- models/DataObject/QuantityValue/Unit/Dao.php
resolves #1023 
see comment https://github.com/pimcore/pimcore/issues/1023#issuecomment-662382202
> [Objects] Quantity Value: Do not store Unit IDs in class definitions

- models/Version.php
> Fix DeepCopy for Versions

- models/Tool/Lock.php
```
$lock = Lock::get('test'); //not existing lock
$lock->getId() //null
$lock->getDate() //null
```
> Set correct return types for Pimcore\Model\Tool\Lock

- bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.php
> Fix quicksearch translation

- bundles/EcommerceFrameworkBundle/Controller/PricingController.php
- bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/panel.js
Credits go to @AndreasKoettl95  (original PR #6827) 
- implemented JS Routing
> [Ecommerce] Added copy & rename functionality to pricing rules panel

- doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
> [DOCS] Add twig version for manual mode for areablocks

- bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
> [Document] Editables: Renamed `options` property to `config`

- doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md
- doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/01_Application_Testing.md
> [Docs] Annotate some code examples for proper highlighting

- doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md
Extra menu doesn't exist any more and is called settings now
> Extra menu doesn't exist any more

- bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php
* Highlight modified classification store fields in object version comparison
> [Data Objects] Classification store version comparison

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/slider.js
> Slider mandatory

- models/DataObject/Concrete/Dao/InheritanceHelper.php
The error occurred after i removed an object brick
> Fix "Undefined index: id" error after save

- models/DataObject/ClassDefinition/Layout/DynamicTextLabelInterface.php
- models/DataObject/ClassDefinition/Layout/Text.php
- models/DataObject/Service.php
> [Object Grid] Missing field name and values when edit related fields from/in grid view table popup

- doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
- models/DataObject/ClassDefinition/Layout.php
- models/DataObject/ClassDefinition/Layout/Iframe.php
- models/DataObject/ClassDefinition/Layout/Text.php
> Object param of Layout::enrichLayoutDefinition can be null now

- bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- lib/DependencyInjection/ConfigMerger.php
- lib/Tool/ArrayUtils.php
- tests/Unit/Tool/ConfigMergerTest.php
> Deprecate security config merger

- bundles/AdminBundle/Resources/public/js/pimcore/document/link.js
> [Admin] Documents - Fix editable settings for links when not allowed to publish

- models/DataObject/ClassDefinition/Service.php
Can we export the modificationDate? It would be helpful to check whether a class needs to be imported.
The import set the modificationDate to `time()`, so it would not a problem there.
> [Class Export] Export modificationDate

- composer.json
Many thanks for using the opcache-gui - I really appreciate it!  I've recently released a new major version which added some additional functionality and wondered if you'd be interested in updating the version your include?  Here are the release details, if you're interested: https://github.com/amnuts/opcache-gui/releases/tag/3.0.0
Thanks!
> Updated to latest opcache-gui

- models/Document/Email.php
- models/Document/Newsletter.php
- models/Document/PageSnippet.php
- models/Document/Service.php
> [Documents] Fix content for Email/Newsletter is not copied

- bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php
> [Ecommerce][Tracking] Avoid autostart session by accessing the FlashBag

- bundles/CoreBundle/Migrations/Version20180904201947.php
- bundles/CoreBundle/Migrations/Version20180924111736.php
- bundles/CoreBundle/Migrations/Version20181214145532.php
- bundles/CoreBundle/Migrations/Version20190108131401.php
Resolves https://github.com/pimcore/pimcore/issues/6979#issuecomment-700559532
Regression of #4781
> [Migrations] Fix migrations for table users_permission_definitions

- models/DataObject/Localizedfield/Dao.php
- tests/Model/LazyLoading/ManyToManyRelationTest.php
- tests/_support/Helper/Model.php
> Modifing an object having a fieldcollection with inside a localized fields delete the localized values

- models/DataObject/ClassDefinition/Data/Localizedfields.php
> Object with gallery inside localized field inside block throws an error when saving

- doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
These should point to the demo repo, right?
> [Docs] Fix dead links

- doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
- doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
- lib/Mail.php
- lib/Web2Print/Processor.php
Resolves #3692
Replaces Placeholder support in v7.
> Support for Twig in Emails and Web2Print Documents

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/Tool/Tracking/Event.php
- models/Tool/Tracking/Event/Dao.php
> Deprecated Tool\Tracking\Event

- models/DataObject/Localizedfield/Dao.php
- tests/Model/LazyLoading/ManyToManyObjectRelationTest.php
- tests/Model/LazyLoading/ManyToManyRelationTest.php
- tests/Model/LazyLoading/ManyToOneRelationTest.php
- tests/_support/Helper/Model.php
- tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingLocalizedTest_export.json
> [Data Object] Modifing an object having a fieldcollection with inside a localized fields delete the localized values 

- bundles/AdminBundle/Controller/Admin/IndexController.php
- bundles/CoreBundle/EventListener/ControllerViewModelListener.php
- bundles/CoreBundle/EventListener/TemplateControllerListener.php
- bundles/EcommerceFrameworkBundle/FilterService/Helper.php
- bundles/EcommerceFrameworkBundle/FilterService/ListHelper.php
- bundles/EcommerceFrameworkBundle/Resources/config/filter_service.yml
- doc/Development_Documentation/02_MVC/00_Controller.md
- doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Analytics/Piwik/EventListener/IndexSettingsListener.php
- lib/Controller/ArgumentValueResolver/ViewModelValueResolver.php
- lib/Controller/FrontendController.php
- lib/Controller/TemplateControllerInterface.php
- lib/Controller/Traits/TemplateControllerTrait.php
- lib/Event/Admin/IndexActionSettingsEvent.php
- lib/Event/AdminEvents.php
- lib/Http/Request/Resolver/ViewModelResolver.php
- lib/Templating/Model/ViewModel.php
- lib/Templating/Model/ViewModelInterface.php
- lib/Templating/PhpEngine.php
- models/Document/Editable.php
- models/Document/Editable/Area/AbstractArea.php
- models/Document/Editable/Area/Info.php
> Deprecate auto view rendering

- bundles/CoreBundle/DependencyInjection/Compiler/LockStoragePass.php
- bundles/CoreBundle/Migrations/Version20201001133558.php
- bundles/CoreBundle/PimcoreCoreBundle.php
- bundles/CoreBundle/Resources/config/services.yml
- bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
- bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
- bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- bundles/EcommerceFrameworkBundle/Resources/config/checkout_manager.yml
- bundles/InstallBundle/Resources/install.sql
- doc/Development_Documentation/19_Development_Tools_and_Details/17_Static_Helpers.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Document/Adapter/LibreOffice.php
- lib/Maintenance/Executor.php
- lib/Maintenance/Tasks/CacheCleanupTask.php
- lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
- lib/Routing/RedirectHandler.php
- lib/Web2Print/Processor.php
- models/Asset/Document/ImageThumbnail.php
- models/Asset/Video/ImageThumbnail.php
- models/Asset/Video/Thumbnail/Processor.php
- models/Tool/Lock.php
- models/Tool/Lock/Dao.php
> Deprecated Tool\Lock, created Symfony Lock factory service

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> Deprecate payment providers

- bundles/AdminBundle/Controller/Reports/QrcodeController.php
- bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/item.js
- bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/panel.js
- bundles/CoreBundle/Controller/PublicServicesController.php
- doc/Development_Documentation/18_Tools_and_Features/23_QR_Codes.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/Tool/Qrcode/Config.php
- models/Tool/Qrcode/Config/Dao.php
- models/Tool/Qrcode/Config/Listing.php
- models/Tool/Qrcode/Config/Listing/Dao.php
> Deprecated QRCodes

- bundles/CoreBundle/Migrations/Version20201008101817.php
- bundles/InstallBundle/Resources/install.sql
- doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
- models/Document/Editable/Dao.php
- models/Document/PageSnippet/Dao.php
- models/Document/Targeting/TargetingDocumentDaoTrait.php
> Renamed DB Table documents_elements to documents_editables

- bundles/AdminBundle/Resources/public/css/editmode.css
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
- bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig
- doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
- doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
- doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
- lib/Document/Editable/EditableHandler.php
- lib/Extension/Document/Areabrick/AbstractAreabrick.php
- lib/Extension/Document/Areabrick/AbstractTemplateAreabrick.php
- lib/Extension/Document/Areabrick/AreabrickInterface.php
- lib/Extension/Document/Areabrick/TemplateAreabrickInterface.php
> [Document] Remove support for edit.php on Area-Bricks

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Add a null check to gridTabAbstract. It crashes if filters isn't defined in this.grid yet.
> Grid filters null check

- models/DataObject/ClassDefinition/Data/Consent.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/ExternalImage.php
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Hotspotimage.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/StructuredTable.php
- models/DataObject/ClassDefinition/Data/Video.php
> [DataObject] Undefined notice warning for $params['language']

- bundles/AdminBundle/Resources/public/js/pimcore/settings/glossary.js
- bundles/CoreBundle/Migrations/Version20201012154224.php
- bundles/CoreBundle/Resources/translations/en.json
- bundles/InstallBundle/Resources/install.sql
- doc/Development_Documentation/18_Tools_and_Features/21_Glossary.md
- lib/Tool/Glossary/Processor.php
- models/Glossary.php
> [Glossary] Removed support for acronyms

- models/Asset.php
- models/DataObject/AbstractObject.php
- models/Document.php
- models/Element/AbstractElement.php
- models/Element/ElementInterface.php
> [Element] Added setProperties() and setProperty() to ElementInterface

- bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
- bundles/CoreBundle/EventListener/Frontend/ElementListener.php
- bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php
Timing issue ... regression of #7247
> [Document] Document in session is not used in templates

- models/Document/Editable/Areablock.php
- models/Document/Editable/Block.php
- models/Document/Editable/Checkbox.php
- models/Document/Editable/Date.php
- models/Document/Editable/Embed.php
- models/Document/Editable/Image.php
- models/Document/Editable/Input.php
- models/Document/Editable/Link.php
- models/Document/Editable/Multiselect.php
- models/Document/Editable/Numeric.php
- models/Document/Editable/Pdf.php
- models/Document/Editable/Relation.php
- models/Document/Editable/Relations.php
- models/Document/Editable/Renderlet.php
- models/Document/Editable/Select.php
- models/Document/Editable/Snippet.php
- models/Document/Editable/Table.php
- models/Document/Editable/Textarea.php
- models/Document/Editable/Video.php
- models/Document/Editable/Wysiwyg.php
> [Document] Make editable properties protected

- bundles/EcommerceFrameworkBundle/IndexService/Getter/TagsGetter.php
> [Ecommerce] [IndexService] Fix the Pimcore TagsGetter

- bundles/AdminBundle/Controller/Admin/TranslationController.php
- bundles/CoreBundle/Resources/config/event_listeners.yml
- bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
- models/Element/AdminStyle.php
> [Core] Use TranslatorInterface for DI - #7276

- lib/Templating/Renderer/EditableRenderer.php
- lib/Translation/ImporterService/Importer/DocumentImporter.php
- models/Document/PageSnippet.php
- models/Document/TargetingDocument.php
> [Document] PageSnippet::setEditable() remove name from signature (redundant)

- bundles/AdminBundle/Helper/GridHelperService.php
> [DataObject] GridOptions ... DB error when adding objectbrick fields

- lib/Routing/Redirect/Csv.php
> [Redirects] Fix CSV import error

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
> [Admin] Fix multiselect inside not rendered tabs in Fieldcollections lose data

- composer.json
- lib/Tool/Text.php
Resolves #7288
Encoding detection bugfix
Using third-party library 
https://github.com/onnov/detect-encoding
> Fixed encoding detection

- models/Document/Editable/Block/AbstractBlockItem.php
- models/Document/Editable/Block/Item.php
> [Document] AbstractBlockItem - Deprecate getElement()

- models/Asset.php
- models/Asset/Service.php
> [Asset] Fix Stream error when saving an asset to an S3 bucket

- doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
Resolves #
Was hard to read otherwise
> [Docs] jsonmus -> json for example

- doc/Development_Documentation/24_Web_Services/README.md
> Added link to reasons why REST API was deprecated

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
> Change Alignment of input data type label from right to left

- models/DataObject/ClassDefinition/Data/Link.php
> [Data Objects] Links in Blocks will not be cleaned up when Target Document is deleted

- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/Localizedfield.php
> "owner missing" error after upgrading from 6.0.x/6.6.9 to current 6.7.2

- lib/Maintenance/Tasks/VersionsCleanupStackTraceDbTask.php
Newly introduced VersionsCleanupStackTraceDbTask is collecting all table entries which have stackTrace != NULL
On big environments (e.g. we have multiple customers with about 4 million versions) the current implementation will eat up all RAM resources already on collecting all versions at once from database.
As well if you have customers which generate a high number of versions per week this can be a problem.
Just collect the data in smaller packages to avoid this.
Regression from https://github.com/pimcore/pimcore/commit/9da5a11bfb62592a1e4976114bb45e47513f1576
> [Maintenance] Fix versions cleanup stacktrace db task

- bundles/CoreBundle/Command/ThumbnailsImageCommand.php
- lib/Tool/Frontend.php
- models/Asset/Image/Thumbnail.php
> Fixes missing usage of webp_auto_support for console command

- doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md
Clarify that you can use 'auto' as height to have the renderlet dynamically change height depending on content, just like a snippet.
> [Docs] Renderlet can accept 'auto' as height as well

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
- models/Document/Editable/Link.php
> [Document] Link editable can generate invalid type="" attribute

- models/Document/Editable.php
- models/Document/PageSnippet.php
Resolves #7366
Regression of #6900
> [Documents] Fix content of unpublished documents lost

- lib/Translation/Translator.php
> [Translations] Fix %count% parameter translations

- bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
> Admin login is not recognizing Edge correctly anymore and hides the login form

- lib/Maintenance/Tasks/LogArchiveTask.php
Follow-up of https://github.com/pimcore/pimcore/pull/7066#issuecomment-689345674
> [Application logs] Cleanup referenced FileObjects

- bundles/EcommerceFrameworkBundle/PricingManager/Action/CartDiscount.php
> fixed  Ecommerce: Incorrect calculation of order sum with voucher (rounding error)

- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- lib/Maintenance/Tasks/CacheCleanupTask.php
- lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
- models/Asset/Document/ImageThumbnail.php
> Fixed locking - follow up to #7386

- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
- lib/Tool/Admin.php
> [Pimcore7] admin-helper: remove deprecation

- models/DataObject/QuantityValue/Unit.php
Make it possible to chain setters
Not sure if its a "bugfix" or "feature"
Resolves #
> [QuantityValueUnit] make setters chainable

- lib/Extension/Document/Areabrick/AbstractAreabrick.php
- lib/Templating/Renderer/EditableRenderer.php
- models/Document/Editable.php
- models/Document/Editable/Area.php
- models/Document/Editable/Date.php
- models/Document/Editable/Renderlet.php
- models/Document/Editable/Snippet.php
- models/Document/Editable/Table.php
- models/Document/Editable/Video.php
follow up to #7278 + some fixes
> [Document] Removed Editables BC Layers

- models/DataObject/ClassDefinition/Helper/CalculatorClassResolver.php
- models/DataObject/Service.php
> Remove CalculatorClassInterface BC Layer

- bundles/AdminBundle/Controller/Admin/ElementController.php
> Remove deprecated static PathFormatter layer

- models/DataObject/Data/Hotspotimage.php
> [DataObject] Preview with Image Advanced and Thumbnails failing, wrongly ElementDescriptor returned

- models/DataObject/Classificationstore.php
Fixes swapped parameter in php doc
> fix: swapped parameters

- models/DataObject/ClassDefinition/Data/Table.php
Resolves #7365 
Fix an issue with table access when columns config is enabled
> Fix null data on table with columns config enabled

- doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
- lib/Controller/Config/ConfigNormalizer.php
- lib/Extension/Document/Areabrick/AbstractTemplateAreabrick.php
- lib/Extension/Document/Areabrick/TemplateAreabrickInterface.php
- phpstan-baseline.neon
- phpstan.neon
> Removed PHP Templating engine leftovers

- .travis.yml
- bundles/AdminBundle/Controller/Admin/External/AdminerController.php
- bundles/AdminBundle/Controller/Admin/LogController.php
- bundles/CoreBundle/Migrations/Version20200828091305.php
- composer.json
- doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
- lib/Db/ConnectionInterface.php
- lib/Db/PimcoreExtensionsTrait.php
- lib/Db/ZendCompatibility/QueryBuilder.php
- lib/Migrations/Configuration/Configuration.php
- lib/Migrations/SqlFileWriter.php
- lib/Model/Listing/AbstractListing.php
- lib/Targeting/Storage/DbStorage.php
- lib/Targeting/VisitorInfoResolver.php
- models/Notification/Listing/Dao.php
- models/Notification/Service/NotificationService.php
- tests/Model/Inheritance/GeneralTest.php
The PR https://github.com/pimcore/pimcore/pull/7327 use \Doctrine\DBAL\Exception which is first created in doctrine/dbal 2.11.0.
doctrine/dbal 2.11.0 requires php ^7.3
> Pimcore requires doctrine/dbal ^2.11.0 and php ^7.3

- models/DataObject/ClassDefinition/Data/QuantityValue.php
> Fix quantity value comparator

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/checkbox.js
> Fix EditableDialog not showing labels of checkboxes

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/select.js
- doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
> [Documents] Select Editable defaultValue empty fix and docs update 

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
File path in last step does not match the paths specified above
> Fixes wrong file path in docs

- lib/Workflow/MarkingStore/DataObjectMultipleStateMarkingStore.php
> Fixed Workflow Deprecations

- .travis.yml
- .travis/setup-db-server.sh
- doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
- MariaDB >= 10.2
- MySQL >= 5.7
- AWS Aurora (supported versions see MySQL)
- Percona Server (supported versions see MySQL)
> New RDBMS minimum requirements

- bundles/EcommerceFrameworkBundle/Tracking/Tracker.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Ecommerce] Deprecate Ecommerce Tracking Php templates

- models/DataObject/Localizedfield.php
> Fatal with caching on localized fields caused by ElementDescriptor

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
* Fix null pointer error
Object ID is stored in `this.data`, as indicated on line 471 `if (this.data.id)`
Causes a console error during batch edit
> Fix batch edit null error

- composer.json
See https://github.com/phpstan/phpstan/issues/4067
> composer.json conflict with "phpstan/phpstan": "^0.12.55"

- lib/Controller/Controller.php
- lib/Templating/TwigDefaultDelegatingEngine.php
> [Core] Add Rendering support for Templating Engine

- composer.json
- lib/Kernel.php
PHP version check is done already by Composer anyway.
> Added PHP 8.0 to composer.json and removed manual PHP version check

- models/DataObject/Data/BlockElement.php
> Blocks with many entries causes fatal error / probably infinite loop

- lib/Workflow/Notification/NotificationEmailService.php
Resubmitting to proper branch (6.8) for bugfix
Resolves #
I am getting object links when I am editing pages.
For instance here is the deeplink to the page: https://www.site.com/admin/login/deeplink?document_1824_page
Here is the link that came in the email when i edited the page and submitted the workflow: https://www.site.com/admin/login/deeplink?object_1824_object
The ID is correct but the link is wrong.
> [Workflows] Fix deeplink for workflow notifications

- bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
- bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
Is used here:
https://github.com/pimcore/pimcore/blob/b926dc320b5ccda17e20665303ca239404a3d821/bundles/EcommerceFrameworkBundle/CartManager/SessionCartItem.php#L42
> Add setItems method to CartInterface

- bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
- bundles/EcommerceFrameworkBundle/PriceSystem/ModificatedPriceInterface.php
Is used here:
https://github.com/pimcore/pimcore/blob/b926dc320b5ccda17e20665303ca239404a3d821/bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php#L349
https://github.com/pimcore/pimcore/blob/b926dc320b5ccda17e20665303ca239404a3d821/bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php#L136
> Add getRule method to ModificatedPriceInterface

- models/DataObject/ClassDefinition/Data/Relations/AllowAssetRelationTrait.php
- models/DataObject/ClassDefinition/Data/Relations/AllowDocumentRelationTrait.php
- models/DataObject/ClassDefinition/Data/Relations/AllowObjectRelationTrait.php
> [Data Objects] Relation Data-Types: Validation error if object without an ID was assigned

- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstractRelations.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
> [Admin] Fix open action for folder relations

- models/DataObject/ClassDefinition/Data/Table.php
> [Data Object] Table Data-Type should always return an array

- models/Asset.php
- models/Asset/Dao.php
- models/DataObject/AbstractObject.php
- models/DataObject/AbstractObject/Dao.php
- models/Document.php
- models/Document/Dao.php
- models/Element/Exception/ElementNotFoundException.php
- models/Exception/NotFoundException.php
> Model::getById() ::getByPath() ... shouldn't catch any exceptions

- lib/Event/Model/ElementEventInterface.php
Is used very often. 
For example here:
https://github.com/pimcore/pimcore/blob/b926dc320b5ccda17e20665303ca239404a3d821/bundles/CoreBundle/EventListener/ElementTagsListener.php#L50
> Add getArgument method to ElementEventInterface

- composer.json
> Pimcore X Alias

- lib/Translation/Translator.php
Resolves #7184
Might fix also #7584
Fixes:
- parameters usage
- fallback translations
- translated text as keys
> [Translations] Fix shared translations

- bundles/AdminBundle/Resources/public/js/pimcore/element/notes.js
- bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
> Prevent multiple open panels (sent email, notes)

- bundles/AdminBundle/Translation/AdminUserTranslator.php
> Removed AdminUserTranslator::transChoice()

- bundles/AdminBundle/Controller/Admin/RedirectsController.php
- bundles/AdminBundle/Controller/Admin/SettingsController.php
> fix permission checks

- models/Dependency.php
getRequiredBy returns always an array and generate sql queries.
> Optimize Dependency::isRequired()

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- bundles/AdminBundle/Controller/Admin/IndexController.php
- bundles/AdminBundle/Controller/Admin/LoginController.php
- bundles/AdminBundle/Controller/AdminController.php
- bundles/AdminBundle/EventListener/CsrfProtectionListener.php
- bundles/AdminBundle/Resources/config/event_listeners.yml
- bundles/AdminBundle/Resources/config/security_services.yml
- bundles/AdminBundle/Security/CsrfProtectionHandler.php
- bundles/CoreBundle/Resources/config/pimcore/default.yml
- bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
> Add a service CSRF protection and deprecate event listener methods

- bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
ClassMapLoader should have higher priority than PrefixLoader, since it works with static mapping.
> [Core] Implementation Loaders - Classmap loader takes priority over Prefix loader

- models/Asset/Image/Thumbnail/Config.php
- models/Asset/Image/Thumbnail/Config/Dao.php
- models/Asset/Video/Thumbnail/Config.php
- models/Asset/Video/Thumbnail/Config/Dao.php
- models/DataObject/ClassDefinition.php
- models/DataObject/ClassDefinition/CustomLayout.php
- models/DataObject/ClassDefinition/Dao.php
- models/DataObject/Classificationstore/CollectionConfig.php
- models/DataObject/Classificationstore/CollectionConfig/Dao.php
- models/DataObject/Classificationstore/GroupConfig.php
- models/DataObject/Classificationstore/GroupConfig/Dao.php
- models/DataObject/Classificationstore/KeyConfig.php
- models/DataObject/Classificationstore/KeyConfig/Dao.php
- models/DataObject/Classificationstore/StoreConfig.php
- models/DataObject/Classificationstore/StoreConfig/Dao.php
- models/Metadata/Predefined.php
- models/Metadata/Predefined/Dao.php
- models/Staticroute.php
- models/Staticroute/Dao.php
- models/Tool/CustomReport/Config.php
- models/Tool/CustomReport/Config/Dao.php
- models/Tool/Targeting/Rule.php
- models/Tool/Targeting/Rule/Dao.php
- models/Tool/Targeting/TargetGroup.php
- models/Tool/Targeting/TargetGroup/Dao.php
- models/User/AbstractUser.php
- models/User/AbstractUser/Dao.php
- models/WebsiteSetting.php
- models/WebsiteSetting/Dao.php
resolves #7591 
resolves #7322
> Model::getByName shouldn't catch any exceptions

- lib/Tool/DeviceDetector.php
check if HTTP_USER_AGENT isset
> DeviceDetector check if HTTP_USER_AGENT isset

- models/DataObject/ClassDefinition/Data.php
> Fixed wrong annotation

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/booleanSelect.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/consent.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/externalImage.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/link.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/rgbaColor.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/structuredTable.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/time.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js
> Cannot read property 'syncContent' of null

- models/Asset.php
follow up for https://github.com/pimcore/pimcore/pull/6385
> Fix asset metadata conversion

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
> Fixed object relation select values

- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Consent.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/ExternalImage.php
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Hotspotimage.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/Link.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/StructuredTable.php
- models/DataObject/ClassDefinition/Data/Video.php
- models/DataObject/Data/BlockElement.php
- models/DataObject/Localizedfield/Dao.php
- models/DataObject/OwnerAwareFieldInterface.php
- models/DataObject/Traits/OwnerAwareFieldTrait.php
> OwnerAwareFieldInterface: add setters and getters

- tests/Cache/Core/AbstractCoreHandlerTest.php
> Upgrade PHPUnit and codeception/phpunit-wrapper to latest version 

- bundles/CoreBundle/DependencyInjection/Configuration.php
- doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> Deprecate pimcore.translations.case_insensitive

- doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
Here's the screenshot for the reference: https://pimcore.com/docs/pimcore/current/Development_Documentation/img/dynamic_textlabel_1.png
> Update description & code example to match the screenshot

- bundles/CoreBundle/Migrations/Version20201207132025.php
- models/Asset/Dao.php
> Asset Metadata not being displayed

- bundles/AdminBundle/Controller/Reports/CustomReportController.php
- bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Resolves #7651
Fixed CSV export of filtered custom reports
> Fix custom reports export

- bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
- lib/Twig/Extension/AdminExtension.php
Currently the admin UI is broken when debug mode is disabled
> [Admin UI] Fixed issue when running not in debug mode

- models/DataObject/ClassDefinition/Data/RgbaColor.php
> [DataObject] Fix Cannot save object with RGBA color field inside classification-store

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
> Localized field in Objectbrick breaks the context for all the following non-localized fields

- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/imagecropper.js
- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/imagehotspotmarkereditor.js
> [DataObject] Fix HotspotImage modal window background issue with white transparent image

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Reverts pimcore/pimcore#7519
Causes other problems see @skochTC  comment here: https://github.com/pimcore/pimcore/commit/9c4b38a463519e850936f22dc5475fc1ad2d9c2b#commitcomment-45129223
> Revert "Fix batch edit null error"

- bundles/CoreBundle/Resources/config/cache.yml
- bundles/InstallBundle/Installer.php
- bundles/InstallBundle/Resources/config/services.yml
Install cache tables, otherwise it creates unneeded and confusing logs.
> install cache on installation

- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/Data/AbstractQuantityValue.php
- models/DataObject/Data/InputQuantityValue.php
- models/DataObject/Data/QuantityValue.php
- phpstan-baseline.neon
- getUnitId(), getUnit(), getValue() can return null
- Cunstructor should use string instead of int as unit
> Fix wrong QuantityValue PHPDocs

- bundles/CoreBundle/Resources/config/cache.yml
- bundles/InstallBundle/Installer.php
- bundles/InstallBundle/Resources/config/services.yml
> Revert "install cache on installation"

- bundles/InstallBundle/Installer.php
> Create cache table on install

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
- bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/Config/HobexConfig.php
- doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/11_Hobex.md
> PaymentProvider Hobex : webhook support 

- models/Asset/Image/Thumbnail/Processor.php
> Fix Wrong High-Res Images when using specific Image Area

- lib/Tool/Newsletter.php
> [Newsletter] Fix to avoid updating creationDate for existing e-mail in subscribe

- bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/FieldCollectionGetter.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ObjectBrickGetter.js
> [Admin] Data Object - Validate required attributes for ObjectBrickGetter & FieldCollectionGetter

- bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
- bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
- bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch7.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch7.php
- bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
- composer.json
- doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/01_PimcoreEcommerceFrameworkBundle_Configuration_Reference.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/05_Data_Architecture_and_Indexing_Process.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/01_Configuration_Details.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/02_Synonyms.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/README.md
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/README.md
- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/01_Filter_Classification_Store.md
- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/02_Filter_Nested_Documents.md
- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/README.md
- doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
> Add ES7 Support

- bundles/InstallBundle/Installer.php
- lib/Cache/Symfony/CacheClearer.php
- lib/Process/PartsBuilder.php
- lib/Tool/AssetsInstaller.php
- tests/Unit/Process/PartsBuilderTest.php
> Deprecated PartsBuilder

- models/Tool/CustomReport/Adapter/Sql.php
Resolves a bug when mixed grid and drilldown filters are used in SQL adapter inside a custom report.
https://user-images.githubusercontent.com/43776120/102893558-15e8e380-4462-11eb-8a38-9044a47be5f5.mp4
> [CustomReport] Fix mixed grid/drilldown filters in SQL Adapter

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/layout.js
> [DataObject][Custom Layouts] Missing layout components

- lib/Bootstrap.php
> Remove deprecated Bootstrap::boostrap method

- lib/Image/Optimizer.php
> Remove deprecated Pimcore\Image\Optimizer::optimize method

- composer.json
> ocramius/package-versions: ^2.0

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
- bundles/AdminBundle/Resources/public/js/pimcore/functions.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToOneRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
- bundles/CoreBundle/Resources/translations/aliases.json
> Remove data type BC layer ('multihrefMetadata','objectsMetadata','objects','multihref','href','nonownerobjects')

- doc/Development_Documentation/01_Getting_Started/01_Advanced_Installation_Topics.md
> Fix cronjob randomness example in the docs

- composer.json
PHP 8 compatibility - see also #7844
> webmozarts/console-parallelization: ^1.2.0

- bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/objects.js
> Fixed parent class

- bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
1. Set env `PIMCORE_PHP_ERROR_REPORTING=E_ALL`
2. Try to set focial point on new image asset
3. Get following error:
> Fix Notice: Undefined index: data

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_V5_to_V6.md
The app.php doesn't exist anymore, thus the link was broken. I put in a link that points directly to a commit before that change.
> Update link to app.php in the upgrade docs

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
- models/DataObject/Classificationstore.php
- models/DataObject/Classificationstore/Group.php
- models/DataObject/Classificationstore/Key.php
Allowing easier access to active group and key data.
> [ClassificationStore] Provide group and key models

- bundles/AdminBundle/Controller/Admin/IndexController.php
- lib/Config.php
- lib/Tool.php
> Fix Notice: Undefined index: classes

- models/DataObject/ClassDefinition/Data/Select.php
This PR is based on Pimcore V6.8 in favor of #7922 .
> Pimcore Backend | Grid View | Value "0" is not shown | V6.8

- models/DataObject/Objectbrick.php
Alternative approach for #7891
> [Object bricks] Brick container class might contain removed brick types after unserializing

- models/DataObject/ClassDefinition/Data/RgbaColor.php
> [DataObjects] RgbaColor::checkValidity should validate color components against valid value range

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/Asset/Listing/Dao.php
- models/DataObject/Listing/Dao.php
- models/Document/Listing/Dao.php
- models/Translation/Listing/Dao.php
Follow up to #7817
- added compatibility layer for document listings
- added compatibility layer for translation listings
- trigger deprecation notice when using getQuery() or onCreateQuery()
> Follow up to #7817 - Doctrine Query Builder 

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Geopolygon.php
- models/DataObject/ClassDefinition/Data/Geopolyline.php
> [DataObjects] Implement checkValidity for geo datatypes

- models/DataObject/ClassDefinition/Data/Hotspotimage.php
> [Data Objects] Image Gallery - Undefined Index in HotspotImage getDataFromEditmode

- bundles/AdminBundle/Controller/Admin/TranslationController.php
- bundles/AdminBundle/Helper/GridHelperService.php
- lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
- models/Asset/Listing.php
- models/DataObject/Listing.php
- models/Document/Listing.php
- models/Element/Service.php
- models/Translation/Listing.php
Follow up to #7817
- Added onCreateQueryBuilder callback for Doctrine Query Builder
> Follow up to #7817 - Use onCreateQueryBuilder for Doctrine QB

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
> Many-To-Many Relation: Could not add Folder

- bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
- lib/Model/Listing/AbstractListing.php
- lib/Model/Listing/Dao/AbstractDao.php
- models/DataObject/Listing/Concrete/Dao.php
- models/DataObject/Listing/Dao.php
- models/Document/Listing/Dao.php
> Follow up: deprecated Zend Query Builder

- bundles/CoreBundle/Resources/config/templating_twig.yml
- lib/Twig/Extension/CacheExtension.php
- lib/Twig/Extension/HeaderExtension.php
- lib/Twig/Extension/HelpersExtension.php
- lib/Twig/Extension/PimcoreToolExtension.php
- lib/Twig/Extension/TemplatingHelperExtension.php
> Deprecate TemplatingHelperExtension

- models/Document.php
> get correct path of documents from multiple sites in pimcore

- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/Data/AbstractQuantityValue.php
> InputQuantityValue does not persist any data anymore

- bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
resolves #8002 
regression of https://github.com/pimcore/pimcore/pull/7583
> Typehint wrong for IndexFieldSelection data type

- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/Data/AbstractQuantityValue.php
> Fix InputQuantityValue issues

- models/DataObject/Concrete.php
> Fixes #8049 Add subitems to ValidationException rethrow

- models/DataObject/QuantityValue/Unit/Listing/Dao.php
Fixes issue where Unit listing did not receive condition variables.
> Unit listing missing condition variables fix

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/relation.js
> [Document - Editable Dialog Box] Fix Relation editable buttons

- lib/Helper/Mail.php
> Fix resend email for old log entries e.g. example@demain.com (example)

- lib/Image/Adapter/Imagick.php
> Imagick adapter: support s3:// URL

- bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
> Fix CSRF Attack warning when using wrong custom login screen

- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
follow up to #7232 and related to #7995
> Rectify payment provider deprecations

- bundles/AdminBundle/Resources/public/js/pimcore/startup.js
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/DataObject/GridColumnConfig/Operator/AnyGetter.php
> [CSV Export] restrict AnyGetter to Pimcore Elements (Asset/Document/Object) and check user permission 

- lib/Web2Print/Processor/PdfReactor8.php
> Fix: Class 'ColorSpace' not found

- bundles/InstallBundle/Installer.php
> Catch cache clear exception on installation

- lib/Translation/Translator.php
- models/Translation.php
- models/Translation/Dao.php
- models/Translation/Listing.php
Resolves #7999
Fix translator to check for valid domains & throw exception when wrong domain is used to list translations
> Fix Translations Error

- bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
> [Ecommerce] remove unnecessary instanceof checks in OrderManager

- composer.json
> Guzzle 7 - Drop Guzzle 6

- bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
- bundles/EcommerceFrameworkBundle/CartManager/Cart.php
- bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- tests/Ecommerce/CartManager/SessionCartTest.php
> [Ecommerce] Unify Cart Item Counting

- lib/Routing/Staticroute/Router.php
- models/Staticroute.php
> [Static Routes] Do not merge request params on static-route generate

- bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
- bundles/EcommerceFrameworkBundle/CartManager/SessionCart.php
> [Ecommerce] Fixed cleanup of cart amount cache-variables

- bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
- bundles/EcommerceFrameworkBundle/CartManager/Cart.php
- bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- tests/Ecommerce/CartManager/SessionCartTest.php
> [Ecommerce] Remove BC Layer for Cart Counting

- bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
- bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerInterface.php
- bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
- bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
- bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
- bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerInterface.php
- bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PaymentInterface.php
> [Ecommerce] Add deprecation commands to old checkout manager architecture

- tests/Model/Asset/PropertiesTest.php
- tests/Model/DataType/PropertiesTest.php
- tests/Model/Document/PropertiesTest.php
- tests/_support/Helper/Element/PropertiesTestHelper.php
- tests/_support/Test/AbstractPropertiesTest.php
> [Tests] Properties

- tests/Model/Asset/AssetTest.php
- tests/_support/Util/TestHelper.php
> [Tests] Assets: CRUD, Thumbnails, ... 

- doc/User_Documentation/08_Targeting_and_Personalization/README.md
> Docs - small fixes (Targeting & Personalization)

- models/DataObject/Listing/Concrete/Dao.php
> Fix Doctrine QueryBuilder applyjoins

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
> [DataObject Grid] inputQuantityValue - Fix grid view renderer - 

- models/Document/Editable/Block.php
> [Documents][Blocks] Possible undefined notice in manual mode

- models/Staticroute.php
Resolves https://github.com/pimcore/pimcore/pull/8076#issuecomment-773982030
> [Static Routes] Merge router.request_context params e.g._locale

- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
Markdown to HTML rendering at the bottom of the page was broken: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Classification_Store.html#page_Adding-new-items-to-Classification-Store-through-code
> Code block fix in 15_Classification_Store.md

- doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/03_HeadScript.md
- lib/Twig/Extension/Templating/HeadScript.php
Adds additional option to use "async" in headscript
> added async option to headscript

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
> [Admin] Fix Can't open object in AdvManyToManyRelation

- bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
> Custom Login screen - Fix and support external image URL

- bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
- lib/Twig/Extension/HelpersExtension.php
Follow up to https://github.com/pimcore/pimcore/commit/417e3a42b6035371663d397ce29a63f4fdc63e7b
Related fix for #8129
> Custom Login screen - Fix and support external image URL for Pimcore 10

- lib/Config.php
Found this small improvement when I was trying to understand Views & Perspectives.
> Simplification & microoptimisation of TreeConfig sorting

- lib/Mail.php
> Fixed sending newsletters

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
- bundles/CoreBundle/Migrations/Version20210211152319.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
> [DataObject] Classificationstore + QuantityValue not properly restored

- bundles/AdminBundle/Controller/Reports/CustomReportController.php
- models/Tool/CustomReport/Adapter/Sql.php
> [Custom Reports] Adding custom SQL statements to SELECT field does not work anymore

- lib/Templating/Renderer/EditableRenderer.php
- lib/Translation/ImporterService/Importer/DocumentImporter.php
- models/Document/PageSnippet.php
- models/Document/TargetingDocument.php
- models/Webservice/Data/Document/PageSnippet.php
- phpstan-baseline.neon
> [Documents] Page::setEditable remove params in method signature

- models/Document/Editable.php
> [Documents] Backport Editable::buildChildEditableName() to v6.9

- bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_1.css
> Added missing @font-face for Open Sans

- bundles/CoreBundle/Resources/config/templating_twig.yml
- bundles/CoreBundle/Resources/views/Targeting/toolbar/toolbar.html.twig
- composer.json
See https://packagist.org/packages/twig/extensions
> composer.json: Removed abandoned twig/extensions

- models/DataObject/ClassDefinition/Data/QuantityValue.php
> Fix Cannot save QuantityValues in ClassificationStore

- models/DataObject/ClassDefinition.php
- models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
> [Data Object] Generate Type Declarations should be on by default

- bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch6.php
- bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
- doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> deprecated Elasticsearch 6 support

- doc/Development_Documentation/18_Tools_and_Features/13_Perspectives.md
> fix link to perspective sample file

- lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
see https://github.com/pimcore/pimcore/commit/0c5613cd6ea946f133503a05ebe66a0f2c68c9ef#r47455126
> Fixed cache warmer if Pimcore isn't set up yet

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Targeting/Storage/Cookie/JWT/Decoder.php
> Deprecate JWT Decoder

- bundles/AdminBundle/Controller/BruteforceProtectedControllerInterface.php
- bundles/AdminBundle/EventListener/BruteforceProtectionListener.php
- bundles/AdminBundle/Security/BruteforceProtectionHandler.php
- bundles/AdminBundle/Security/Exception/BruteforceProtectionException.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Core] Security - mark BruteforceProtectionHandler internal

- lib/Event/AdminEvents.php
- lib/Event/AssetEvents.php
- lib/Event/CoreCacheEvents.php
- lib/Event/DataObjectImportEvents.php
- lib/Event/DocumentEvents.php
- lib/Event/FrontendEvents.php
- lib/Event/SystemEvents.php
- lib/Event/TargetingEvents.php
- lib/Event/TestEvents.php
- lib/Event/UserRoleEvents.php
> Fix Events PhpDoc

- lib/Helper/Mail.php
Added file scheme uri in Mail helper for resolving absolute paths. This is useful when i.e. generating PDF's with wkhtml and we pass sources to assets with file scheme. Currently it appends host to the file scheme URI.
> added file uri scheme in mail helper for absolute paths

- bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
> Fix Maximum call stack size exceeded on filter button click

- models/Asset/MetaData/ClassDefinition/Data/Asset.php
- models/Asset/MetaData/ClassDefinition/Data/DataObject.php
- models/Asset/MetaData/ClassDefinition/Data/Document.php
> [Asset] Fix saving dependencies of Element type metadata

- models/DataObject/Classificationstore/Dao.php
- tests/Model/DataType/ClassificationStore/AbstractClassificationStoreTest.php
- tests/Model/DataType/ClassificationStore/GeneralTest.php
> Fix Classification Store doesn't allow null

- bundles/AdminBundle/Resources/public/css/editmode.css
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
- models/Document/Editable/Area.php
Resolves #8240
for better comparison view https://github.com/pimcore/pimcore/pull/8266/files?diff=split&w=1
> [Document] Editable Dialog Box - Add Area Support

- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
- bundles/CoreBundle/Resources/translations/en.json
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Data Object] Deprecate CSV Import

- models/Document.php
documents inside hardlinks from different sites used the wrong domain
> bugfix fullpath of hardlinks

- models/DataObject/ClassDefinition/Data/Geopoint.php
> Geopoint latitude/longitude constructor #7840

- bundles/AdminBundle/Controller/Admin/AssetController.php
- bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
- bundles/AdminBundle/Controller/Admin/WorkflowController.php
- lib/Document/Adapter/Ghostscript.php
- lib/Document/Adapter/LibreOffice.php
- lib/Image/HtmlToImage.php
- lib/Image/Optimizer/AbstractCommandOptimizer.php
- lib/Image/Optimizer/AdvancedPngOptimizer.php
- lib/Image/Optimizer/CjpegOptimizer.php
- lib/Image/Optimizer/JpegoptimOptimizer.php
- lib/Image/Optimizer/PngCrushOptimizer.php
- lib/Image/Optimizer/PngOutOptimizer.php
- lib/Image/Optimizer/ZopflipngOptimizer.php
- lib/Tool/Console.php
- lib/Video/Adapter/Ffmpeg.php
- lib/Web2Print/Processor.php
- models/Asset/Image.php
- models/Asset/MetaData/EmbeddedMetaDataTrait.php
- models/Asset/Video/Thumbnail/Processor.php
> Tool\Console Deprecations

- bundles/AdminBundle/Controller/Admin/WorkflowController.php
- lib/Document/Adapter/Ghostscript.php
- lib/Document/Adapter/LibreOffice.php
- lib/Image/HtmlToImage.php
- lib/Image/Optimizer/AbstractCommandOptimizer.php
- lib/Tool/Console.php
- lib/Video/Adapter/Ffmpeg.php
- lib/Web2Print/Processor.php
- models/Asset/Image.php
> Set low process priority for certain processes 

- bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js
- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
> JS helper to format durations

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Geopolygon.php
- models/DataObject/ClassDefinition/Data/Geopolyline.php
- models/DataObject/Data/GeoCoordinates.php
- tests/_support/Helper/DataType/TestDataHelper.php
- tests/_support/Test/DataType/AbstractDataTypeTestCase.php
- tests/_support/Util/TestHelper.php
> Remove BC layer for Geopoint latitude/longitude constructor

- bundles/AdminBundle/EventListener/AdminExceptionListener.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
> Brick validation exception

- bundles/CoreBundle/Migrations/Version20210303165115.php
- bundles/InstallBundle/Resources/install.sql
- doc/Development_Documentation/19_Development_Tools_and_Details/42_Settings_Store.md
- models/Tool/SettingsStore.php
- models/Tool/SettingsStore/Dao.php
- tests/Model/Tool/SettingsStoreTest.php
Adds a settings store to Pimcore, that persists simple key-value data to Pimcore database.
> SettingsStore

- bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
> [Admin] Grids - Fix dblclick event columns to open element

- bundles/CoreBundle/Migrations/Version20210303165115.php
- bundles/InstallBundle/Resources/install.sql
- doc/Development_Documentation/19_Development_Tools_and_Details/42_Settings_Store.md
- models/Tool/SettingsStore.php
- models/Tool/SettingsStore/Dao.php
- tests/Model/Tool/SettingsStoreTest.php
See https://github.com/pimcore/pimcore/pull/8332#issuecomment-791243369
> Settings-store follow up from #8332

- bundles/AdminBundle/GDPR/DataProvider/Assets.php
- bundles/AdminBundle/GDPR/DataProvider/DataObjects.php
- bundles/AdminBundle/GDPR/DataProvider/Exporter.php
- models/Property.php
> Make GDPR Exporters independent from REST Webservices

- bundles/CoreBundle/Resources/config/templating_twig.yml
- bundles/CoreBundle/Resources/views/Targeting/toolbar/toolbar.html.twig
- bundles/CoreBundle/Resources/views/Targeting/toolbar/toolbar_js.html.twig
- composer.json
> Fixed targeting toolbar regression

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
- lib/Extension/Bundle/Installer/SettingsStoreAwareInstaller.php
- lib/Migrations/BundleAwareMigration.php
adds a installer for bundles that stores installation state in new SettingsStore
> SettingsStoreAware Installer

- bundles/CoreBundle/Resources/config/migrations.yml
- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
- lib/Extension/Bundle/Installer/SettingsStoreAwareInstaller.php
> Migrated SettingsStoreAwareInstaller to symfony 5 and doctrine migrations

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
> Key default values not working/implemented in Classificationstore

- bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
hot fixes https://github.com/pimcore/pimcore/issues/8367
> [Ecommerce] apply custom rule class option

- .github/workflows/codeception.yml
- lib/Translation/Translator.php
- tests/Unit/Translation/TranslatorTest.php
> [Translation] Fix Using parameter %count% in simple translation values will create additional translation keys

- models/Element/ElementInterface.php
> ElementInterface: added getParent()

- lib/Kernel.php
> It should be possible to override a bundles config - follow up to #8186

- bundles/CoreBundle/Migrations/Version20210310115115.php
- bundles/InstallBundle/Resources/install.sql
> Added compatibility layer for table documents_elements

- bundles/CoreBundle/Migrations/Version20201008101817.php
> Migration: consider #8389 for Pimcore X

- bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
- lib/Event/AdminEvents.php
> [AdminBundle] Moved AssetController under Pimcore\Bundle\AdminBundle\Controller\Admin\Asset

- models/Document/PageSnippet.php
> Revert "Fix: "Call to undefined method getInherited" when saving a document a second time"

- tests/Model/Document/DocumentTest.php
> [Tests] Add test to check serialization of documents

- lib/Twig/Extension/ImageThumbnailExtension.php
- models/Asset/Image/Thumbnail.php
... doesn't exist anymore in v10
> [Twig] Removed argument $removeAttributes from pimcore_image_thumbnail_html 

- lib/Twig/Extension/NavigationExtension.php
> [Navigation] Add missing deprecation message for build navigation 

- doc/Development_Documentation/03_Documents/03_Navigation.md
- lib/Twig/Extension/Templating/Navigation.php
> [Navigation] Remove deprecated method buildNavigation

- models/DataObject/Classificationstore/KeyGroupRelation/Dao.php
> Fixed getById method in KeyGroupRelation Dao

- doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
- doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
> [Docs] Add Twig Extensions examples

- bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.twig
- bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.twig
Follow-up on #8403
see https://twig.symfony.com/doc/3.x/tests/odd.html
I was too slow to give feedback on the PR :)
> Shorter Twig syntax for odd rows

- bundles/EcommerceFrameworkBundle/CartManager/Cart/Dao.php
- models/Asset/Dao.php
- models/DataObject/AbstractObject.php
- models/DataObject/AbstractObject/Dao.php
- models/DataObject/ClassDefinition/CustomLayout/Dao.php
- models/DataObject/Classificationstore/CollectionConfig/Dao.php
- models/DataObject/Classificationstore/GroupConfig/Dao.php
- models/DataObject/Classificationstore/KeyConfig/Dao.php
- models/DataObject/Classificationstore/StoreConfig/Dao.php
- models/DataObject/Concrete/Dao.php
- models/Document/Dao.php
- models/Document/Email/Dao.php
- models/Document/Hardlink/Dao.php
- models/Document/Link/Dao.php
- models/Document/Newsletter/Dao.php
- models/Document/Page/Dao.php
- models/Document/PrintAbstract/Dao.php
- models/Document/Snippet/Dao.php
- models/Site/Dao.php
- models/Tool/Email/Blacklist/Dao.php
- models/Tool/Targeting/Rule/Dao.php
- models/Tool/Targeting/TargetGroup/Dao.php
- models/Tool/Tracking/Event/Dao.php
- models/User/AbstractUser/Dao.php
- models/WebsiteSetting/Dao.php
> [Models] Fixed notices "Trying to access array offset on value of type bool"

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- lib/Translation/ImporterService/Importer/AbstractElementImporter.php
- models/Document/Service.php
> Changes due to signature change of Document::setProperty()

- lib/Templating/Renderer/IncludeRenderer.php
- lib/Tool/DomCrawler.php
> [Glossary] fixed documents using pimcore glossary throw error

- bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/manager.js
- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
- bundles/CoreBundle/Resources/config/documents.yml
- lib/Document/Editable/EditmodeEditableDefinitionCollector.php
- lib/Templating/Renderer/EditableRenderer.php
- models/Document/Editable.php
- models/Document/Editable/Area.php
- models/Document/Editable/Areablock.php
- models/Document/Editable/Block.php
- models/Document/Editable/Scheduledblock.php
> Document Editables: refactored to allow dynamic add/remove of editables

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/manager.js
- bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
- lib/Document/Editable/EditmodeEditableDefinitionCollector.php
- lib/Templating/Renderer/EditableRenderer.php
- models/Document/Editable.php
> [Documents] Editable configuration was overwritten

- bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js
> [Documents] Reload does not save editable data to session

- bundles/AdminBundle/Resources/public/js/pimcore/document/edit/dnd.js
follow up of #7824
fixes #8431
> [Documents] Click in editmode causes error

- models/Translation/Listing/Dao.php
> [Translations] getAllTranslations must not cache with single cache-key

- lib/Translation/Escaper/Xliff12Escaper.php
- lib/Translation/ExportService/Exporter/Xliff12Exporter.php
> [XLIFF Export] Fix Exporter - follow up to #8361

- models/WebsiteSetting.php
> Fix wrong PhpDocs

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
- models/Version.php
> [DataObjects] Version - Fix preview for calculated localized fields

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geobounds.js
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopolygon.php
- models/DataObject/ClassDefinition/Data/Geopolyline.php
> [DataObject] Fix Geo data types marshalling

- models/DataObject/ClassDefinition/Data/ImageGallery.php
> [DataObject] Fix ImageGallery marshalling

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/geo/abstract.js
- models/DataObject/Data/EncryptedField.php
> [DataObjects] Fix Encrypted fields with Ownerawareinterface leads to recursion on save

- bundles/InstallBundle/Command/InstallCommand.php
- bundles/InstallBundle/DependencyInjection/Configuration.php
- bundles/InstallBundle/DependencyInjection/PimcoreInstallExtension.php
- bundles/InstallBundle/Event/InstallerStepEvent.php
- bundles/InstallBundle/Installer.php
- bundles/InstallBundle/InstallerKernel.php
- bundles/InstallBundle/PimcoreInstallBundle.php
- bundles/InstallBundle/SystemConfig/ConfigWriter.php
> [InstallBundle] Mark classes as final/internal

- bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php
> [Documents] cannot unset $site->rootDocument

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Helper/LongRunningHelper.php
- lib/Http/Request/Resolver/EditmodeResolver.php
- lib/Templating/Renderer/IncludeRenderer.php
> Removed Runtime::get('pimcore_editmode')

- models/Element/Service.php
> [Elements] getSafeVersionInfo broken

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
- bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
- bundles/AdminBundle/Controller/Admin/EmailController.php
- bundles/AdminBundle/Controller/Admin/RecyclebinController.php
- bundles/AdminBundle/Controller/Admin/RedirectsController.php
- bundles/AdminBundle/Controller/Admin/SettingsController.php
- bundles/AdminBundle/Controller/Admin/UserController.php
> [AdminBundle] Fix returning data in adminjson by using getObjectVars

- bundles/AdminBundle/Resources/public/js/pimcore/asset/audio.js
- bundles/AdminBundle/Resources/public/js/pimcore/asset/document.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/image.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/input.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/textarea.js
- bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
- bundles/AdminBundle/Resources/public/js/pimcore/startup.js
> Admin UI: Removed some IE specific code

- doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/10_Recurring_Payments.md
> [DOCS] Change PHP Template Examples to Twig

- bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
- bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Removed fixes that were introduced with the following issues and are obsolete as of now (ExtJS 7). 
#1542
#1804
> [Admin UI] Removed some obsolete ExtJS fixes/overrides

- bundles/AdminBundle/Resources/public/css/admin.css
- bundles/AdminBundle/Resources/public/css/ext-modifications.css
- bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_2.css
- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
- bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
- bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
> [Admin UI] Fixed ExtJS styling issues

- bundles/AdminBundle/Controller/Admin/SettingsController.php
- bundles/CoreBundle/Migrations/Version20210323082921.php
- bundles/InstallBundle/Resources/install.sql
- models/WebsiteSetting.php
- models/WebsiteSetting/Dao.php
- models/WebsiteSetting/Listing.php
- models/WebsiteSetting/Listing/Dao.php
> [Website Settings] Moved persistence to database

- bundles/AdminBundle/Controller/Admin/SettingsController.php
- bundles/CoreBundle/Migrations/Version20210323110055.php
- lib/Config.php
> Robots.txt: changed persistence to SettingsStore

- bundles/InstallBundle/SystemConfig/ConfigWriter.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Bootstrap.php
- lib/Config.php
- lib/Config/EnvironmentConfig.php
- lib/Config/EnvironmentConfigInterface.php
- lib/Pimcore.php
> Deprecation of legacy constants, classes and methods related to debug/dev mode

- bundles/CoreBundle/DependencyInjection/Configuration.php
- bundles/CoreBundle/Resources/config/pimcore/default.yml
> Config: do not allow extra keys in 'pimcore' path

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
> [Admin] Fix creating a site throws JS error

- doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
> Fixed typo in 01_Image_Thumbnails.md

- bundles/AdminBundle/Controller/Admin/UserController.php
> [Admin] Fix user workspaces load

- bundles/AdminBundle/Controller/Admin/ElementController.php
> [Admin] Fix predefined properties on documents

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
> [Document] Fix adding areabrick on empty content page

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- lib/Maintenance/Tasks/VersionsCompressTask.php
- models/Asset.php
- models/Asset/Image.php
- models/Asset/Thumbnail/ImageThumbnailTrait.php
- models/Version.php
- stubs/dynamic-constants.php
> Deprecated classes, constants and methods in preparation for Flysystem

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
- doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
> [DataObjects] Fix javascript to disable adding urlslug in classificationstore

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Data.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- models/DataObject/ClassDefinition/Data/Geobounds.php
- models/DataObject/ClassDefinition/Data/Geopoint.php
- models/DataObject/ClassDefinition/Data/Geopolygon.php
- models/DataObject/ClassDefinition/Data/Geopolyline.php
- models/DataObject/ClassDefinition/Data/Hotspotimage.php
- models/DataObject/ClassDefinition/Data/Image.php
- models/DataObject/ClassDefinition/Data/ImageGallery.php
- models/DataObject/ClassDefinition/Data/InputQuantityValue.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
- models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
- models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
- models/DataObject/ClassDefinition/Data/QuantityValue.php
- models/DataObject/ClassDefinition/Data/RgbaColor.php
- models/DataObject/ClassDefinition/Data/Video.php
resolves #8488
depends on https://github.com/pimcore/pimcore/pull/8573
> [DataObject] Deprecate marshal/unmarshal of field definitions

- lib/Templating/Renderer/ActionRenderer.php
> [Templating] Fix ActionRenderer to pass params document reference

- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> Fix link for CSV import

- bundles/AdminBundle/Helper/GridHelperService.php
> [Admin] DataObject Grid - fix Sorting by fullpath

- composer.json
> Conflict with doctrine/dbal ^2.13.0

- models/DataObject/ClassDefinition.php
> [DataObjects] Fix New class/field-collection results in error

- bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
> [Admin] Fix moving duplicate node breaks elements tree between parentchild folders

- bundles/CoreBundle/Resources/config/marshaller.yml
- lib/DataObject/ClassificationstoreDataMarshaller/BooleanSelect.php
- lib/DataObject/ClassificationstoreDataMarshaller/Multiselect.php
- lib/DataObject/ClassificationstoreDataMarshaller/QuantityValue.php
- lib/DataObject/ClassificationstoreDataMarshaller/RgbaColor.php
- lib/DataObject/ClassificationstoreDataMarshaller/Table.php
- lib/DataObject/FielddefinitionMarshaller/Traits/RgbaColorTrait.php
- models/DataObject/Classificationstore/Dao.php
resolves #8491 
TODO: create unit tests on 6.8
> [Data Object] ClassificationStore should utilize new normalize/denormalize methods of data-types

- models/DataObject/ClassDefinition.php
array_unique returns the filtered array and has no reference
https://www.php.net/manual/de/function.array-unique.php
> Fix wrong usage of array_unique

- .github/ci/files/app/config/config_test.yml
- models/DataObject/ClassDefinition/Data/EncryptedField.php
- tests/Model/DataType/ClassificationStore/AbstractClassificationStoreTest.php
- tests/Model/DataType/ClassificationStore/GeneralTest.php
added classification store tests
> Classificationstore tests

- models/DataObject/ClassDefinition/Data/Block.php
- models/DataObject/ClassDefinition/Data/Classificationstore.php
- models/DataObject/ClassDefinition/Data/Fieldcollections.php
- models/DataObject/ClassDefinition/Data/Objectbricks.php
> [DataObject] Implement Normalizer Interface for structured data types

- lib/File.php
- lib/Helper/TemporaryFileHelperTrait.php
- models/Asset.php
- models/Asset/Image/Thumbnail.php
- `Image\Thumbnail::getStream()`
- `Image\Thumbnail::getFilesize()`
- `TemporaryFileHelperTrait`
> Pimcore X Backports

- models/Asset.php
> [Asset] Fix Renaming parent doesn't update child paths

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
> [AdminBundle] Fix grid configs passed in adminjson - follow up to #8527

- bundles/AdminBundle/Resources/public/css/icons.css
- bundles/AdminBundle/Resources/public/js/pimcore/report/panel.js
> Use material icon for report tab in elements

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/select.js
- lib/Templating/Renderer/EditableRenderer.php
> [Document] Select Editable - default value applied on initial build

- models/DataObject/ClassDefinition/CustomLayout.php
- models/DataObject/Service.php
> [DataObject] Fix Pimcore\Model\DataObject\Service::getValidLayouts()

- models/Asset/MetaData/EmbeddedMetaDataTrait.php
- models/Asset/Video.php
> [Assets] Video preview error if using remote storage for Assets

- bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
fixes part 2 of
https://github.com/pimcore/pimcore/pull/8671
> Fix classificationstore bugs (2)

- lib/Controller/Traits/ElementEditLockHelperTrait.php
> [Admin] Fix edit lock info

- bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
- bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
- models/DataObject/Listing/Dao.php
- models/Document/Listing/Dao.php
- models/Translation/AbstractTranslation/Listing/Dao.php
probably fixes https://github.com/pimcore/pimcore/issues/8681
> Cast querybuilder to string when fetching data

- composer.json
see #8694 and doctrine/DoctrineMigrationsBundle#414
Hopefully https://github.com/doctrine/DoctrineMigrationsBundle/issues/414 get's fixed in `3.1.1` , then this fix should be fine in future as well.
> Conflict with doctrine/doctrine-migrations-bundle: 3.1.0

- bundles/AdminBundle/Controller/Admin/TranslationController.php
> [Admin] Shared Translations - Fix sort by language column

- models/DataObject/Service.php
> [DataObject] Don't save fieldDefinitionsCache into class definitions file

- bundles/AdminBundle/EventListener/AdminExceptionListener.php
> [Admin] Fix Validation "message" is empty in error response

- models/DataObject/Objectbrick/Definition.php
Steps:
1. Create Object class "ClassA"
2. Add brick attribute in ClassA "BrickAttrA"
3. Create Object Brick "BrickA"
4. Assign "ClassA:BrickAttrA" on "BrickA"
5. Delete "ClassA"
6. Delete "BrickA" => thows exception:
> [Data Object] Fix brick deletion when related class does not exists

- models/Asset.php
- models/DataObject/AbstractObject.php
- models/Document.php
- models/Element/ElementInterface.php
Resolves #8689
follow up to https://github.com/pimcore/pimcore/pull/7299
> [Element] setProperties() param should be nullable

- models/Version.php
> Version.php -> class_alias GeoPoint?

- models/DataObject/ClassDefinition.php
Pimcore X throws me that error on PHP8 when creating a brick programmatic:
```
Behat\Testwork\Call\Exception\FatalThrowableError: Type error: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:318
Stack trace:
#0 vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(318): method_exists(Array, 'getChildren')
#1 vendor/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php(210): Pimcore\Model\DataObject\ClassDefinition::cleanupForExport(Array)
#2 vendor/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php(180): Pimcore\Model\DataObject\Objectbrick\Definition->generateClassFiles(true)
#3 src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php(178): …
```
> check if is object before checking if method_exists

- models/DataObject/ClassDefinition/Data/EncryptedField.php
> Encrypted fields: normalizer does not call not call delegate's normalizer

- bundles/CoreBundle/Resources/config/marshaller.yml
- lib/DataObject/ClassificationstoreDataMarshaller/EncryptedField.php
> Implement Classification Store Marshaller for EncryptedField

- bundles/InstallBundle/Command/InstallCommand.php
- bundles/InstallBundle/Installer.php
Resolves #3852
Follow-up of reverted #3858
> [Installer] Support --skip-database-... options

- bundles/CoreBundle/Resources/config/marshaller.yml
- lib/DataObject/BlockDataMarshaller/EncryptedField.php
> Implement marshaller for encrypted block fields

- bundles/AdminBundle/Controller/Admin/AssetController.php
> "Public URL" in Assets should include scheme and hostname

- lib/Tool/Admin.php
> Tool\Admin::getLanguages() returns language multiple times

- models/Translation.php
- models/Translation/Admin.php
- models/Translation/Website.php
> [Translations] Fix import translations from file BC layer

- bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
> Do not save assets in tree list calls

- bundles/CoreBundle/Migrations/Version20210412112812.php
- bundles/InstallBundle/Resources/install.sql
- lib/Tool/Requirements.php
> All tables should have a primary key

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> [Custom Layouts] Save fails on 2nd save

- bundles/AdminBundle/Resources/public/css/ext-modifications.css
> [DataObjects] RgbaColor fixed color preview

- bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
> Fix creating document translations using Document Language Overview

- bundles/CoreBundle/Command/Migration/ControllerReferenceMigrationCommand.php
Resolves #
Improvements:
- Consider unpublished documents
- Added option to process a particular document tree
> New Controller Reference migrations command improvements

- bundles/AdminBundle/Controller/Admin/SettingsController.php
> [Static Routes] Fixed regression of #8452

- models/DataObject/ClassDefinition/Layout/Traits/LabelTrait.php
> Fixed regression of #8452

- doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/03_Conditions.md
Link is not working
Resolves #
> [Docs] Update 03_Conditions.md

- doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/09_Targeting_Storage.md
Link is not working
Resolves #
> [Docs] Update 09_Targeting_Storage.md

- lib/Document/Adapter/Ghostscript.php
Fixes GS command, which could not be executed due to wrong parameter formatting
To reproduce upload any pdf or other document and try to create a thumbnail
> Fix Ghostscript parameter

- lib/Tool/Requirements.php
Alternative approach for / fixes  #8817
> Fixed installer, regression of #8817

- bundles/InstallBundle/Command/InstallCommand.php
- bundles/InstallBundle/Installer.php
Resolves https://github.com/pimcore/pimcore/commit/05071de32c38dbb4908bda4c1095055ed78ed22a#r49599458 https://github.com/pimcore/pimcore/issues/3852
> [Installer] Fix --skip-database-* options

- bundles/AdminBundle/Controller/Admin/UserController.php
> Cannot edit roles

- bundles/CoreBundle/Command/Document/MigrateElementsCommand.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> [Documents] Provide migration script for rename of elements to editables

- bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php
> [PimcoreX] Fix edit site

- bundles/AdminBundle/Controller/Admin/ElementController.php
- bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
- bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
> [Documents] Version preview saves resaves version when you click on show

- lib/Composer/PackageInfo.php
Add support for `composer2` `installed.json`.
[composer2](https://getcomposer.org/upgrade/UPGRADE-2.0.md) changed the `installed.json` format
**Important change**: packages are now wrapped into a `"packages"` top level key instead of the whole file being the package array
> Support composer2 installed.json format

- bundles/AdminBundle/Controller/Admin/SettingsController.php
> Fix Admin custom image - SVG mime guesser issue

- bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
- doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
- lib/File.php
- models/DataObject/ClassDefinition.php
- models/DataObject/ClassDefinition/CustomLayout.php
- models/DataObject/ClassDefinition/CustomLayout/Listing/Dao.php
- models/DataObject/Fieldcollection/Definition.php
- models/DataObject/Objectbrick/Definition.php
- models/DataObject/Traits/LocateFileTrait.php
> Save Pimcore Classes in /config/pimcore/classes

- bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Resolves #8844
Icon should have priority over iconCls
> [Data Object] Fix Saving an object causes the custom icon to disappear

- bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
> [Documents] Fix Template names are not filtered

- bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
> Remove Image-Service on Login-Screen

- models/DataObject/ClassDefinition/Data/Classificationstore.php
> Prepared statements for Classificationstore groups fix

- doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
> Pimcore X Upgrade Guide

- models/Document/PageSnippet.php
> [Pimcore X] Warning: Undefined array key "versions"

- .github/ci/files/config/system.yml
- bundles/CoreBundle/DependencyInjection/Configuration.php
- bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/Localizedfield/Dao.php
- tests/Model/Inheritance/LocalizedFieldTest.php
> Query Table + Fallback languages

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
> [Data Objects] Cannot add Selection Options - 10.0.0-BETA3

- bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
> [Document] Fixed changing order of bricks

- doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/DataObject/ClassDefinition/Layout/DynamicTextLabelInterface.php
- models/DataObject/ClassDefinition/Layout/Text.php
Try to open a Event object in the Pimcore Demo:
Regression from https://github.com/pimcore/pimcore/pull/8859
> Fix Text Layout without renderer class

- lib/Twig/Extension/Templating/HeadLink.php
- lib/Twig/Extension/Templating/HeadScript.php
> Fixed pimcore_head_link().appendStylesheet()

- bundles/AdminBundle/Controller/Admin/UserController.php
> Admin - Roles - Workspaces - Rights not saved (10.0.0-Beta3)

- lib/Navigation/Builder.php
This reverts commit 851b2a40
Reverts #8863
> Revert "Bugfix for incorrect maxDepth comparison"

- bundles/CoreBundle/Resources/translations/en.json
regression of https://github.com/pimcore/pimcore/pull/8398
> Readded translation

- doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
replace app.php with index.php and fix path to thumbnails
> Update Nginx Setup Guide

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
- models/DataObject/ClassDefinition/Data/Classificationstore.php
- models/DataObject/ClassDefinition/Data/Localizedfields.php
- models/DataObject/Service.php
Fixes localized classification store not honoring workspace language settings for users
> fix classification store language permisions via workspace

- bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
> Object can not be saved in Pimcore 6.9

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
- models/DataObject/ClassDefinition/Data/UrlSlug.php
> [DataObjects] UrlSlug value does not update when we save it blank

- models/Tool/CustomReport/Adapter/Sql.php
> [Custom Reports] Fixed data service issue - only exported columns were delivered

- lib/Navigation/Builder.php
> Adds cachetags for elements in navigation menus

- bundles/CoreBundle/Migrations/Version20200817133132.php
> Don't remove primary key from new relation id columns

- models/Document/Editable/Block.php
fixes #8946 
regression of #8899
> Block::blockControls() should be public

- lib/Mail.php
> [Pimcore\Mail] Fix using email addressee from mail document causes error

- bundles/AdminBundle/Resources/public/js/pimcore/startup.js
> [Pimcore X] Fix Quicksearch highlight throws exceptions

- models/Document/Editable/Renderlet.php
> [Document] Renderlet: fixed frontend() method on CLI

- doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
> [DOCS] pimcore.error.ValidationCancelledException is not a constructor

- bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
> [Data Objects] Grid config dialog - add double click handler for operator trees

- bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
> [Pimcore X][ClassDefinition] quantityValue unit selection broken

- bundles/AdminBundle/Controller/Admin/SettingsController.php
> [UI] Custom logo needs to be stored in Flysystem storage

- bundles/CoreBundle/Migrations/Version20210430124911.php
- bundles/EcommerceFrameworkBundle/CartManager/AbstractCartItem.php
- bundles/EcommerceFrameworkBundle/Tools/Installer.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
fixed #6464
also merge https://github.com/pimcore/demo/pull/226  when this is merged
> Ecommerce | Cart | order is lost when more than one items are added within one second

- bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
Fix one new PHPStan error after merging branch 6.9
> Fix PHPStan error

- bundles/InstallBundle/Installer.php
> use .env Kernel if found

- models/Document/PageSnippet.php
> [Documents] Translations can cause errors on document creation

- bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
- doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
- models/Asset/Service.php
- models/DataObject/Service.php
- models/Document/Service.php
- models/Element/Service.php
- phpstan-baseline.neon
> Element\Service::getSafeCopyName() created deprecated alias and removed unnecessary argument

- lib/Console/AbstractCommand.php
> Make AbstractCommand public

- models/DataObject/ClassDefinition/Data/Date.php
- models/DataObject/ClassDefinition/Data/Datetime.php
> [DataObjects] Fix column type change for date fields

- models/Document/Editable/Renderlet.php
> [Documents] Assigning folder to Renderlet does not work anymore

- bundles/AdminBundle/Resources/public/css/admin.css
- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
> [DataObjects] Fix Display of ManyToOne relation broken

- lib/File.php
> Get exclusive lock when writing files 

- bundles/CoreBundle/Resources/config/services_workflow.yml
- lib/Workflow/ExpressionService.php
> [Workflows] Error when adding elements via CLI when workflow with supports strategy is active

- models/DataObject/Listing/Dao.php
- models/Element/Service.php
> [CustomViews] Do not load

- lib/Document/Adapter/Ghostscript.php
Was already fixed in https://github.com/pimcore/pimcore/pull/8054 but get lost
> Fix: No thumbnail for PDF documents with ) sign again

- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/multiselect.js
- bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
Related to https://github.com/coreshop/CoreShop/issues/1625
> [DataObjects] fix multiselect in dataobject - javascript error item.getId is not a function

- models/Document/Editable/Video.php
> Fix video editable undefined index warnings

- bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
> [DataObjects] Fix Advanced ManyToMany Relations field checkbox metadata column editor

- bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php
> [Document] Check if adding "document" and "editmode" as global Twig variables works
